package codegen

import (
	"fmt"
	"go/format"
	"go/token"
	"strings"

	mf "github.com/felixgeelhaar/glossa/messageformat"
)

// GoType is the Go type of an argument's value.
func GoType(a mf.Argument) string {
	switch a.Type {
	case mf.ArgInteger:
		return "int"
	case mf.ArgNumber, mf.ArgPercent, mf.ArgCurrency, mf.ArgUnit:
		return "float64"
	case mf.ArgDate, mf.ArgTime, mf.ArgDatetime:
		return "time.Time"
	}
	return "string"
}

// GoOptions configure Go.
type GoOptions struct {
	Package string
	// Runtime is the Go runtime's import path.
	Runtime string
	Source  string
}

// goParam makes an argument name a Go parameter name.
func goParam(name string, used map[string]bool) string {
	p := camel(name)
	p = strings.TrimPrefix(p, "_")
	if p == "" || token.IsKeyword(p) || p == "m" || p == "opts" || p == "glossa" || p == "time" || !token.IsIdentifier(p) {
		p += "Arg"
	}
	for used[p] {
		p += "_"
	}
	used[p] = true
	return p
}

// Go renders typed accessors: one method per message on Messages,
// bound to a *glossa.Localizer with For or to a request's context with
// FromContext. The output is gofmt'ed.
func Go(entries []Entry, opts GoOptions) ([]byte, []Warning, error) {
	entries = sortEntries(entries)
	keys := make([]string, len(entries))
	for i, e := range entries {
		keys[i] = e.Key
	}
	names, warnings := goNames(keys)
	usesTime := false
	var body strings.Builder
	for _, e := range entries {
		name, ok := names[e.Key]
		if !ok {
			continue
		}
		used := map[string]bool{}
		var params, args []string
		for _, a := range e.Arguments {
			p := goParam(a.Name, used)
			t := GoType(a)
			usesTime = usesTime || strings.HasPrefix(t, "time.")
			params = append(params, p+" "+t)
			args = append(args, fmt.Sprintf("%q: %s", a.Name, p))
		}
		params = append(params, "opts ...glossa.Option")
		fmt.Fprintf(&body, "\n// %s renders %s: %s\n", name, e.Key, comment(docText(e)))
		fmt.Fprintf(&body, "func (m Messages) %s(%s) string {\n", name, strings.Join(params, ", "))
		argMap := "nil"
		if len(args) > 0 {
			argMap = "glossa.Args{" + strings.Join(args, ", ") + "}"
		}
		fmt.Fprintf(&body, "\treturn m.l.T(%q, %s, opts...)\n}\n", e.Key, argMap)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by glossa generate from %s. DO NOT EDIT.\n\n", opts.Source)
	fmt.Fprintf(&b, "// Package %s has typed accessors for the project's messages.\n", opts.Package)
	fmt.Fprintf(&b, "package %s\n\nimport (\n\t\"context\"\n", opts.Package)
	if usesTime {
		b.WriteString("\t\"time\"\n")
	}
	fmt.Fprintf(&b, "\n\tglossa %q\n)\n", opts.Runtime)
	b.WriteString(goPrelude)
	b.WriteString(body.String())
	b.WriteString("\n// IDs are the message IDs, for dynamic use (glossa.Localizer.T).\nconst (\n")
	for _, e := range entries {
		if name, ok := names[e.Key]; ok {
			fmt.Fprintf(&b, "\tID%s = %q\n", name, e.Key)
		}
	}
	b.WriteString(")\n")
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, warnings, fmt.Errorf("codegen: generated Go doesn't parse (a bug): %w", err)
	}
	return src, warnings, nil
}

const goPrelude = `
// Localizer renders a message by ID; *glossa.Localizer implements it.
type Localizer interface {
	T(id string, args glossa.Args, opts ...glossa.Option) string
}

// Contextual finds the locale on a request's context; *glossa.Client
// implements it.
type Contextual interface {
	Localizer(ctx context.Context) *glossa.Localizer
}

// Messages are the project's messages with typed arguments:
//
//	m := For(client.For(user.Locale))
//	subject := m.CheckoutPay(order.Total)
type Messages struct{ l Localizer }

// For binds the accessors to a localizer.
func For(l Localizer) Messages { return Messages{l: l} }

// FromContext binds the accessors to the locale on ctx (set by
// glossa's middleware).
func FromContext(ctx context.Context, c Contextual) Messages { return For(c.Localizer(ctx)) }
`
