package codegen

import (
	"fmt"
	"path"
	"sort"
	"strings"

	mf "github.com/felixgeelhaar/glossa/messageformat"
)

// TSType is the TypeScript type of an argument's value.
func TSType(a mf.Argument) string {
	switch a.Type {
	case mf.ArgNumber, mf.ArgInteger, mf.ArgPercent, mf.ArgCurrency, mf.ArgUnit:
		return "number"
	case mf.ArgDate, mf.ArgTime, mf.ArgDatetime:
		return "Date | number | string"
	case mf.ArgSelect:
		if a.Selector == nil || len(a.Selector.Keys) == 0 {
			return "string"
		}
		var cases []string
		for _, k := range a.Selector.Keys {
			cases = append(cases, quote(k))
		}
		// The catch-all variant takes any other string; the literal cases
		// are there for autocomplete.
		return strings.Join(cases, " | ") + " | (string & {})"
	}
	return "string"
}

// tsValues is the values type of a message.
func tsValues(args []mf.Argument) string {
	if len(args) == 0 {
		return "Record<string, never>"
	}
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = fmt.Sprintf("%s: %s", tsKey(a.Name), TSType(a))
	}
	return "{ " + strings.Join(parts, "; ") + " }"
}

// TSOptions configure TypeScript.
type TSOptions struct {
	// Source names the catalog the module was generated from.
	Source string
}

// TypeScript renders the typed module: the Messages map (message ID →
// values), MessageId, and createMessages(t) with one accessor per
// message.
func TypeScript(entries []Entry, opts TSOptions) ([]byte, []Warning) {
	entries = sortEntries(entries)
	keys := make([]string, len(entries))
	for i, e := range entries {
		keys[i] = e.Key
	}
	paths, warnings := tsPaths(keys)
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by glossa generate from %s. DO NOT EDIT.\n", opts.Source)
	b.WriteString("/* eslint-disable */\n\n")
	b.WriteString("/** Message ID → the values it takes (the shape @glossa/vue's useMessages<M>() and GlossaRegister expect). */\n")
	b.WriteString("export interface Messages {\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "  /** %s */\n", docText(e))
		fmt.Fprintf(&b, "  %s: %s;\n", quote(e.Key), tsValues(e.Arguments))
	}
	b.WriteString("}\n\n")
	b.WriteString("export type MessageId = keyof Messages;\n\n")
	b.WriteString("/** Renders a message by ID, e.g. a runtime's t(); values are already typed by the accessors. */\n")
	b.WriteString("export type Translate = (id: MessageId, values: Record<string, unknown>) => string;\n\n")
	b.WriteString("/** Typed accessors: `const messages = createMessages(t); messages.checkout.pay({ amount })`. */\n")
	b.WriteString("export function createMessages(t: Translate) {\n  return ")
	writeTSTree(&b, buildTree(entries, paths), 1)
	b.WriteString(" as const;\n}\n")
	return []byte(b.String()), warnings
}

func docText(e Entry) string {
	s := comment(e.Text)
	if e.Description != "" {
		s = comment(e.Description) + " — " + s
	}
	return s
}

// tree is the nested accessor object.
type tree struct {
	children map[string]*tree
	entry    *Entry
}

func buildTree(entries []Entry, paths map[string][]string) *tree {
	root := &tree{children: map[string]*tree{}}
	for i := range entries {
		segs, ok := paths[entries[i].Key]
		if !ok {
			continue
		}
		node := root
		for _, s := range segs {
			child, ok := node.children[s]
			if !ok {
				child = &tree{children: map[string]*tree{}}
				node.children[s] = child
			}
			node = child
		}
		node.entry = &entries[i]
	}
	return root
}

func writeTSTree(b *strings.Builder, t *tree, depth int) {
	indent := strings.Repeat("  ", depth+1)
	names := make([]string, 0, len(t.children))
	for n := range t.children {
		names = append(names, n)
	}
	sort.Strings(names)
	b.WriteString("{\n")
	for _, n := range names {
		c := t.children[n]
		if c.entry != nil {
			e := c.entry
			fmt.Fprintf(b, "%s/** %s */\n", indent, docText(*e))
			if len(e.Arguments) == 0 {
				fmt.Fprintf(b, "%s%s: (): string => t(%s, {}),\n", indent, tsKey(n), quote(e.Key))
			} else {
				fmt.Fprintf(b, "%s%s: (values: Messages[%s]): string => t(%s, values),\n", indent, tsKey(n), quote(e.Key), quote(e.Key))
			}
			continue
		}
		fmt.Fprintf(b, "%s%s: ", indent, tsKey(n))
		writeTSTree(b, c, depth+1)
		b.WriteString(",\n")
	}
	b.WriteString(strings.Repeat("  ", depth) + "}")
}

// moduleImport is the import specifier of the typed module at
// modulePath (relative to the importing file): relative, with .js.
func moduleImport(modulePath string) string {
	imp := strings.TrimSuffix(modulePath, path.Ext(modulePath)) + ".js"
	if !strings.HasPrefix(imp, ".") {
		imp = "./" + imp
	}
	return imp
}

// Vue renders the @glossa/vue registration next to the typed module:
// every useGlossa().t / $t call is typed by Messages, and
// useTypedMessages() returns the accessors on the app's runtime.
// modulePath is the typed module relative to the Vue file.
func Vue(modulePath string) []byte {
	return []byte(fmt.Sprintf(`// Code generated by glossa generate. DO NOT EDIT.
/* eslint-disable */
import { useMessages } from "@glossa/vue";
import { createMessages } from %[1]q;
import type { Messages } from %[1]q;

declare module "@glossa/vue" {
  interface GlossaRegister {
    messages: Messages;
  }
}

/**
 * Typed accessors on the app's Glossa runtime, reactive like t(). Call it
 * in setup(): const m = useTypedMessages(); m.checkout.pay({ amount }).
 */
export function useTypedMessages() {
  const { t } = useMessages<Messages>();
  const render = t as unknown as (id: string, values: Record<string, unknown>) => string;
  return createMessages((id, values) => render(id, values));
}
`, moduleImport(modulePath)))
}

// React renders the @glossa/react registration next to the typed
// module: every useGlossa().t call and <T id> is typed by Messages, and
// the useTypedMessages() hook returns the accessors on the provider's
// runtime. modulePath is the typed module relative to the React file.
func React(modulePath string) []byte {
	return []byte(fmt.Sprintf(`// Code generated by glossa generate. DO NOT EDIT.
/* eslint-disable */
import { useMemo } from "react";
import { useMessages } from "@glossa/react";
import { createMessages } from %[1]q;
import type { Messages } from %[1]q;

declare module "@glossa/react" {
  interface GlossaRegister {
    messages: Messages;
  }
}

/**
 * Typed accessors on the provider's Glossa runtime. A hook: it re-renders
 * like useGlossa(). const m = useTypedMessages(); m.checkout.pay({ amount }).
 */
export function useTypedMessages() {
  const { t } = useMessages<Messages>();
  return useMemo(() => {
    const render = t as unknown as (id: string, values: Record<string, unknown>) => string;
    return createMessages((id, values) => render(id, values));
  }, [t]);
}
`, moduleImport(modulePath)))
}
