// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package schedulersql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLease = `-- name: AcquireLease :execrows

INSERT INTO system_leases (name, holder, acquired_at, expires_at, last_run_at)
VALUES ($1, $2, $3, $4, NULL)
ON CONFLICT (name) DO UPDATE
SET holder = EXCLUDED.holder, acquired_at = EXCLUDED.acquired_at, expires_at = EXCLUDED.expires_at
WHERE (system_leases.expires_at IS NULL OR system_leases.expires_at <= $3)
  AND (system_leases.last_run_at IS NULL OR system_leases.last_run_at <= $5)
`

type AcquireLeaseParams struct {
	Name      string
	Holder    string
	Now       pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	DueBefore pgtype.Timestamptz
}

// System scope scheduler.lease (db.SystemTx as glossa_system):
// migration 0017 opens system_leases to it and to nothing else. A lease
// is tenantless: it belongs to the deployment.
// Takes the lease when no live one is held and the job is due — its
// last completed run was at or before due_before. Both conditions are
// checked in the row's own update, so two replicas racing can't both
// win.
func (q *Queries) AcquireLease(ctx context.Context, arg AcquireLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, acquireLease,
		arg.Name,
		arg.Holder,
		arg.Now,
		arg.ExpiresAt,
		arg.DueBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLease = `-- name: GetLease :one
SELECT name, holder, acquired_at, expires_at, last_run_at FROM system_leases WHERE name = $1
`

func (q *Queries) GetLease(ctx context.Context, name string) (SystemLease, error) {
	row := q.db.QueryRow(ctx, getLease, name)
	var i SystemLease
	err := row.Scan(
		&i.Name,
		&i.Holder,
		&i.AcquiredAt,
		&i.ExpiresAt,
		&i.LastRunAt,
	)
	return i, err
}

const releaseLease = `-- name: ReleaseLease :exec
UPDATE system_leases
SET holder = '', expires_at = NULL, last_run_at = $1
WHERE name = $2 AND holder = $3
`

type ReleaseLeaseParams struct {
	RanAt  pgtype.Timestamptz
	Name   string
	Holder string
}

// Ends the lease and records the run, so the interval is measured from
// when the work finished.
func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseLease, arg.RanAt, arg.Name, arg.Holder)
	return err
}
