// Package m3 is Glossa's M3 exit test (RFC 0004 §12): the platform is
// shown to know where every message of a fixture application appears, to
// answer a pull request with a Glossa check and a branch environment, to
// keep the in-product editor out of production builds, and to render
// documents in five locales.
//
// The four parts, in the order the test runs them:
//
//  1. Context. A Vite + Vue shop with one React island, a Go receipt
//     renderer and its template — about 150 messages, source de, targets
//     en, es, fr and ja — is pushed, its build's usages and its
//     extractor's usages are uploaded, and `glossa capture` screenshots
//     eight routes in de and ja at two viewports against a headless
//     Chrome the test starts. Every active message must end up with a
//     usage that names a file, a line and a component, and with a
//     visible region.
//  2. Pull request. A fake GitHub delivers signed webhooks and serves the
//     App endpoints while the real server opens the branch and the pr-7
//     environment, fails the check over an invalid message and missing
//     translations, accepts the repair — written through an in-context
//     grant, the way the overlay does — and, on merge, activates the
//     proposed messages and destroys the environment.
//  3. Overlay guards. The production build of the app holds no loader,
//     and the loader refuses to activate against a production manifest.
//  4. Documents. The Go runtime's document goldens and the fpdf example
//     still render de, en, es, fr and ja.
//
// The test is behind the `system` build tag and needs Docker and a
// Chrome:
//
//	go test -tags=system -timeout=900s ./internal/systemtest/m3/...   (or: make system-m3)
//
// It writes REPORT.md. The fixture application lives in testdata/app and
// is generated by package fixture; its two builds and the two usages
// documents beside them are written by
// `pnpm --filter @glossa/unplugin build:m3` from real Vite builds.
package m3

//go:generate go run ./fixturegen -out testdata
