// @vitest-environment node
/**
 * The scripts embedded in the glossa binary (platform/internal/cli/capture)
 * are exactly what this package builds: a stale capture agent can't ship.
 */
import { describe, expect, it } from "vitest";

import { bundle, bundles, checkedIn } from "../scripts/cli-bundles.mjs";

describe("glossa capture's embedded scripts", () => {
  for (const b of bundles) {
    it(`${b.path.split("platform/")[1]} matches a fresh build`, async () => {
      const fresh = await bundle(b);
      expect(fresh.startsWith("// Code generated by")).toBe(true);
      const stale = (await checkedIn(b)) !== fresh;
      expect(
        stale,
        "out of date: run `pnpm -r --filter @glossa/capture... build && pnpm --filter @glossa/capture build:cli`",
      ).toBe(false);
    });
  }

  it("the agent carries no fixture code, and the fixture no agent", async () => {
    const [agent, app] = await Promise.all(bundles.map((b) => bundle(b)));
    expect(agent).toContain("glossa.runtimes");
    expect(agent).toContain("data-glossa-redact");
    expect(agent).not.toContain("prj_fixture");
    expect(app).toContain("prj_fixture");
    expect(app).not.toContain("__glossaCapture");
  });
});
