// Package fixture is the M3 exit test's application (RFC 0004 §12.1):
// Brotwerk's shop, about 150 messages in German with complete English,
// Spanish, French and Japanese, spread over eight routes of a Vite + Vue
// app with one React island, plus a Go receipt renderer and its template
// that reuse the invoice copy.
//
// Everything is generated by Generate from a seed (DefaultSeed) and
// committed under ../testdata/app: the catalogs the CLI pushes, the app's
// sources, its capture plan, and fixture.json — what the test expects the
// platform to know once the build, the extractor and the capture have
// uploaded. Regenerate with
//
//	go generate ./internal/systemtest/m3/...
//
// and rebuild the app afterwards (`pnpm --filter @glossa/unplugin build:m3`).
// TestFixtureIsCurrent fails when the committed files differ from what the
// generator writes.
package fixture

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// DefaultSeed is the seed the committed fixture was generated with. It
// only picks vocabulary; the shape of the app is fixed.
const DefaultSeed = 20260920

// Application is the slug of the fixture's application in the project.
const Application = "shop"

// Files of the fixture, relative to its directory.
const (
	FileFixture = "fixture.json"
	// FileUsages is where @glossa/unplugin writes the build's usages.
	FileUsages = "usages.json"
	// DirPreview and DirProduction hold the two committed builds: the
	// preview one the capture drives, and the production one the bundle
	// scan reads (RFC 0004 §12.3).
	DirPreview    = "built/preview"
	DirProduction = "built/production"
)

// Commit is the commit the committed build was made at: the generator
// writes it into the app's build info, so the usages document and the
// captures agree without a git checkout.
const Commit = "3c1a5f70b28d4e96a1f0c7b4d8e2a95630fb47c1"

// BranchCommit is the head commit of the pull request's CI push.
const BranchCommit = "7d0e4b19af6c2538e1b7d940c6a2f85413ce0d7b"

// DefaultBranch is the project's default branch.
const DefaultBranch = "main"

// PRBranch and PRNumber are the pull request of §12.2.
const (
	PRBranch = "feature/pickup-copy"
	PRNumber = 7
)

// PREnvironment is the branch environment the pull request opens.
const PREnvironment = "pr-7"

// Kinds of usage the fixture places.
const (
	KindT         = "t"
	KindComponent = "component"
	KindElement   = "element"
	KindTemplate  = "template"
)

// Surface is where a message is used: one place in one file.
type Surface struct {
	File      string `json:"file"`
	Component string `json:"component"`
	Route     string `json:"route,omitempty"`
	Kind      string `json:"kind"`
}

// Message is one message of the shop.
type Message struct {
	Key       string `json:"key"`
	Namespace string `json:"namespace"`
	// Pattern names the shape of the source text: plain, plural, values,
	// markup or attribute. It decides how the app renders it.
	Pattern string `json:"pattern"`
	// Source is the German source, in MessageFormat 2.
	Source string `json:"source"`
	// Translations are the four targets, by locale.
	Translations map[string]string `json:"translations"`
	// Web is where the Vue app (or the React island) uses it.
	Web Surface `json:"web"`
	// Go is where the receipt renderer or its template uses it, for the
	// messages the server side reuses. Empty for the rest.
	Go []Surface `json:"go,omitempty"`
	// Line is where the message is used, for the pull request's new
	// keys: what the check's annotation has to name.
	Line int `json:"line,omitempty"`
}

// Page is one route of the app.
type Page struct {
	Route     string `json:"route"`
	URL       string `json:"url"`
	File      string `json:"file"`
	Component string `json:"component"`
	Title     string `json:"title"`
}

// Fixture is the generated application and everything the test expects
// the platform to hold once it has been pushed, built and captured.
type Fixture struct {
	Seed         int64    `json:"seed"`
	SourceLocale string   `json:"source_locale"`
	Locales      []string `json:"locales"`
	Application  string   `json:"application"`
	Commit       string   `json:"commit"`
	Branch       string   `json:"branch"`

	Pages    []Page    `json:"pages"`
	Messages []Message `json:"messages"`

	// Viewports and CaptureLocales are the capture plan's, so the report
	// can name them without reading the YAML back.
	Viewports      [][2]int `json:"viewports"`
	CaptureLocales []string `json:"capture_locales"`

	// Branch is what the pull request's CI push adds (§12.2): five new
	// keys, one of them a message the structural check refuses.
	NewKeys []Message `json:"new_keys"`
	// InvalidKey is the key of the new message whose first push is
	// invalid, with the text that is refused and the text that fixes it.
	InvalidKey     string `json:"invalid_key"`
	InvalidSource  string `json:"invalid_source"`
	InvalidFile    string `json:"invalid_file"`
	InvalidLine    int    `json:"invalid_line"`
	RepairedSource string `json:"repaired_source"`
}

// Message returns the message with a key.
func (f *Fixture) Message(key string) (*Message, bool) {
	for i := range f.Messages {
		if f.Messages[i].Key == key {
			return &f.Messages[i], true
		}
	}
	for i := range f.NewKeys {
		if f.NewKeys[i].Key == key {
			return &f.NewKeys[i], true
		}
	}
	return nil, false
}

// Keys are every active message's key, sorted.
func (f *Fixture) Keys() []string {
	keys := make([]string, 0, len(f.Messages))
	for _, m := range f.Messages {
		keys = append(keys, m.Key)
	}
	slices.Sort(keys)
	return keys
}

// Catalog is the locale's catalog, key → text, as the CLI pushes it.
func (f *Fixture) Catalog(locale string, messages []Message) map[string]string {
	out := map[string]string{}
	for _, m := range messages {
		if locale == f.SourceLocale {
			out[m.Key] = m.Source
			continue
		}
		if t, ok := m.Translations[locale]; ok && t != "" {
			out[m.Key] = t
		}
	}
	return out
}

// Routes are the app's route patterns in page order.
func (f *Fixture) Routes() []string {
	out := make([]string, 0, len(f.Pages))
	for _, p := range f.Pages {
		out = append(out, p.Route)
	}
	return out
}

// GoUsages counts the usages the Go extractor is expected to find.
func (f *Fixture) GoUsages() int {
	n := 0
	for _, m := range f.Messages {
		n += len(m.Go)
	}
	return n
}

// Load reads a generated fixture from a directory.
func Load(dir string) (*Fixture, error) {
	raw, err := os.ReadFile(filepath.Join(dir, FileFixture))
	if err != nil {
		return nil, err
	}
	var f Fixture
	if err := json.Unmarshal(raw, &f); err != nil {
		return nil, fmt.Errorf("%s: %w", FileFixture, err)
	}
	return &f, nil
}

// Write writes the fixture's files into dir, removing the generated
// files that are no longer produced.
func Write(f *Fixture, dir string) error {
	files, err := Files(f)
	if err != nil {
		return err
	}
	for name, body := range files {
		p := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(p, body, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// Files renders every generated file of the fixture, by path relative to
// the fixture's directory (forward slashes).
func Files(f *Fixture) (map[string][]byte, error) {
	out := map[string][]byte{}
	doc, err := marshal(f)
	if err != nil {
		return nil, err
	}
	out[FileFixture] = doc
	app, err := AppFiles(f)
	if err != nil {
		return nil, err
	}
	for name, body := range app {
		out["app/"+name] = body
	}
	return out, nil
}

// marshal writes a document the way the committed files hold it.
func marshal(v any) ([]byte, error) {
	var b strings.Builder
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}
