// Package m2 is Glossa's M2 exit test (RFC 0003 §1): a ~600-message
// catalog with partial Spanish, French and Japanese is imported into a
// real glossa-server (Postgres, MinIO), filled through the public API
// with a deterministic fake provider that makes labelled mistakes, and
// handed to reviewers as a short, risk-ordered queue; the approved
// result is published and rendered by the Go runtime through glossa-edge.
//
// The test is behind the `system` build tag and needs Docker:
//
//	go test -tags=system -timeout=600s ./internal/systemtest/...   (or: make system-m2)
//
// It writes REPORT.md, the per-locale launch summary of intent §69.
// The fixture lives in testdata and is generated by package fixture.
package m2

//go:generate go run ./fixturegen -out testdata
