import { describe, expect, it } from "vitest";

import { compileRoutes, componentOf, globRegExp, isGenerated, normalizeUsages, projectPath, routeOf } from "./usage.js";

describe("routes", () => {
  it("derives Astro page routes: index dropped, [param] kept", () => {
    const none = compileRoutes(undefined);
    expect(routeOf("src/pages/index.astro", none)).toBe("/");
    expect(routeOf("src/pages/checkout/payment.astro", none)).toBe("/checkout/payment");
    expect(routeOf("src/pages/blog/[slug].astro", none)).toBe("/blog/[slug]");
    expect(routeOf("src/pages/blog/index.astro", none)).toBe("/blog");
    expect(routeOf("src/components/Footer.astro", none)).toBeUndefined();
  });

  it("takes the first routes entry with a matching glob", () => {
    const routes = compileRoutes({ "/checkout": ["src/checkout/*.tsx"], "/any": ["src/**"] });
    expect(routeOf("src/checkout/Pay.tsx", routes)).toBe("/checkout");
    expect(routeOf("src/checkout/deep/Pay.tsx", routes)).toBe("/any");
    expect(routeOf("lib/x.ts", routes)).toBeUndefined();
  });

  it("globs: ** crosses directories, * doesn't, the rest is literal", () => {
    expect(globRegExp("src/**").test("src/a/b.ts")).toBe(true);
    expect(globRegExp("src/*.ts").test("src/a/b.ts")).toBe(false);
    expect(globRegExp("src/a.ts").test("src/abts")).toBe(false);
  });
});

describe("files", () => {
  it("names components after Vue and Astro files, and only JSX files get the AST's", () => {
    const jsx = () => "Header";
    expect(componentOf("src/checkout/PaymentFooter.vue", jsx)).toBe("PaymentFooter");
    expect(componentOf("src/pages/blog/[slug].astro", jsx)).toBe("[slug]");
    expect(componentOf("src/Header.tsx", jsx)).toBe("Header");
    expect(componentOf("src/header.ts", jsx)).toBeUndefined();
    expect(componentOf("index.html", jsx)).toBeUndefined();
  });

  it("keeps project paths relative, POSIX and NFC, and drops files outside the root", () => {
    expect(projectPath("/app", "/app/src/grösse.ts")).toBe("src/grösse.ts");
    expect(projectPath("/app", "/elsewhere/x.ts")).toBeUndefined();
    expect(projectPath("/app", "/app/node_modules/x/index.js")).toBeUndefined();
    expect(projectPath("/app", "/app")).toBeUndefined();
  });

  it("recognizes generated files by their first line", () => {
    expect(isGenerated("// Code generated by glossa generate from locales/en.json. DO NOT EDIT.\nexport {}")).toBe(true);
    expect(isGenerated("// Code generated by glossa generate. DO NOT EDIT.")).toBe(true);
    expect(isGenerated("\n// Code generated by x. DO NOT EDIT.")).toBe(false);
    expect(isGenerated("// Code generated by x.\n")).toBe(false);
  });
});

describe("normalizeUsages", () => {
  it("sorts by key, file (code points), line and column, keeps one usage per position and orders fields", () => {
    const out = normalizeUsages([
      { kind: "t", key: "b", file: "a.ts", line: 1, column: 1 },
      { kind: "element", key: "a", file: "src/negatives.html", line: 1, column: 1 },
      { kind: "t", route: "/x", component: "Negatives", key: "a", file: "src/Negatives.vue", line: 2, column: 5 },
      { kind: "t", key: "a", file: "src/Negatives.vue", line: 2, column: 3 },
      { kind: "t", key: "a", file: "src/Negatives.vue", line: 2, column: 3 },
    ]);
    expect(out.map((u) => `${u.key} ${u.file}:${u.line}:${u.column}`)).toEqual([
      "a src/Negatives.vue:2:3",
      "a src/Negatives.vue:2:5",
      "a src/negatives.html:1:1",
      "b a.ts:1:1",
    ]);
    expect(Object.keys(out[1]!)).toEqual(["key", "file", "line", "column", "component", "route", "kind"]);
  });
});
