// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locales.sql

package localizationsql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const allLocales = `-- name: AllLocales :many
SELECT tenant_id, project_id, code, is_source, created_by, created_at FROM localization_locales WHERE project_id = $1 ORDER BY code
`

func (q *Queries) AllLocales(ctx context.Context, projectID uuid.UUID) ([]LocalizationLocale, error) {
	rows, err := q.db.Query(ctx, allLocales, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalizationLocale
	for rows.Next() {
		var i LocalizationLocale
		if err := rows.Scan(
			&i.TenantID,
			&i.ProjectID,
			&i.Code,
			&i.IsSource,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLocale = `-- name: DeleteLocale :execrows
DELETE FROM localization_locales
WHERE project_id = $1 AND code = $2 AND NOT is_source
`

type DeleteLocaleParams struct {
	ProjectID uuid.UUID
	Code      string
}

func (q *Queries) DeleteLocale(ctx context.Context, arg DeleteLocaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocale, arg.ProjectID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectFallbackGraph = `-- name: DeleteProjectFallbackGraph :exec
DELETE FROM localization_fallback_graphs WHERE project_id = $1
`

func (q *Queries) DeleteProjectFallbackGraph(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectFallbackGraph, projectID)
	return err
}

const deleteProjectLocales = `-- name: DeleteProjectLocales :exec
DELETE FROM localization_locales WHERE project_id = $1
`

func (q *Queries) DeleteProjectLocales(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectLocales, projectID)
	return err
}

const getFallbackGraph = `-- name: GetFallbackGraph :one
SELECT tenant_id, project_id, edges, version, updated_by, updated_at FROM localization_fallback_graphs WHERE project_id = $1
`

func (q *Queries) GetFallbackGraph(ctx context.Context, projectID uuid.UUID) (LocalizationFallbackGraph, error) {
	row := q.db.QueryRow(ctx, getFallbackGraph, projectID)
	var i LocalizationFallbackGraph
	err := row.Scan(
		&i.TenantID,
		&i.ProjectID,
		&i.Edges,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocale = `-- name: GetLocale :one
SELECT tenant_id, project_id, code, is_source, created_by, created_at FROM localization_locales WHERE project_id = $1 AND code = $2
`

type GetLocaleParams struct {
	ProjectID uuid.UUID
	Code      string
}

func (q *Queries) GetLocale(ctx context.Context, arg GetLocaleParams) (LocalizationLocale, error) {
	row := q.db.QueryRow(ctx, getLocale, arg.ProjectID, arg.Code)
	var i LocalizationLocale
	err := row.Scan(
		&i.TenantID,
		&i.ProjectID,
		&i.Code,
		&i.IsSource,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertFallbackGraph = `-- name: InsertFallbackGraph :execrows
INSERT INTO localization_fallback_graphs (tenant_id, project_id, edges, version, updated_by, updated_at)
VALUES (app_current_tenant(), $1, $2, $3,
        $4, $5)
ON CONFLICT (project_id) DO NOTHING
`

type InsertFallbackGraphParams struct {
	ProjectID uuid.UUID
	Edges     json.RawMessage
	Version   int32
	UpdatedBy string
	UpdatedAt time.Time
}

func (q *Queries) InsertFallbackGraph(ctx context.Context, arg InsertFallbackGraphParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFallbackGraph,
		arg.ProjectID,
		arg.Edges,
		arg.Version,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLocale = `-- name: InsertLocale :execrows

INSERT INTO localization_locales (tenant_id, project_id, code, is_source, created_by, created_at)
VALUES (app_current_tenant(), $1, $2, $3,
        $4, $5)
ON CONFLICT (project_id, code) DO NOTHING
`

type InsertLocaleParams struct {
	ProjectID uuid.UUID
	Code      string
	IsSource  bool
	CreatedBy string
	CreatedAt time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
// A locale's identity is its code within the project, so adding one
// twice is a no-op.
func (q *Queries) InsertLocale(ctx context.Context, arg InsertLocaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLocale,
		arg.ProjectID,
		arg.Code,
		arg.IsSource,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLocales = `-- name: ListLocales :many
SELECT tenant_id, project_id, code, is_source, created_by, created_at FROM localization_locales
WHERE project_id = $1 AND code > $2
ORDER BY code
LIMIT $3
`

type ListLocalesParams struct {
	ProjectID uuid.UUID
	After     string
	MaxRows   int32
}

func (q *Queries) ListLocales(ctx context.Context, arg ListLocalesParams) ([]LocalizationLocale, error) {
	rows, err := q.db.Query(ctx, listLocales, arg.ProjectID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalizationLocale
	for rows.Next() {
		var i LocalizationLocale
		if err := rows.Scan(
			&i.TenantID,
			&i.ProjectID,
			&i.Code,
			&i.IsSource,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFallbackGraph = `-- name: LockFallbackGraph :one
SELECT tenant_id, project_id, edges, version, updated_by, updated_at FROM localization_fallback_graphs WHERE project_id = $1 FOR UPDATE
`

func (q *Queries) LockFallbackGraph(ctx context.Context, projectID uuid.UUID) (LocalizationFallbackGraph, error) {
	row := q.db.QueryRow(ctx, lockFallbackGraph, projectID)
	var i LocalizationFallbackGraph
	err := row.Scan(
		&i.TenantID,
		&i.ProjectID,
		&i.Edges,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFallbackGraph = `-- name: UpdateFallbackGraph :execrows
UPDATE localization_fallback_graphs
SET edges = $1, version = $2, updated_by = $3,
    updated_at = $4
WHERE project_id = $5 AND version = $6
`

type UpdateFallbackGraphParams struct {
	Edges           json.RawMessage
	Version         int32
	UpdatedBy       string
	UpdatedAt       time.Time
	ProjectID       uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateFallbackGraph(ctx context.Context, arg UpdateFallbackGraphParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFallbackGraph,
		arg.Edges,
		arg.Version,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
