// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package localizationsql

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type LocalizationFallbackGraph struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	Edges     json.RawMessage
	Version   int32
	UpdatedBy string
	UpdatedAt time.Time
}

type LocalizationLocale struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	Code      string
	IsSource  bool
	CreatedBy string
	CreatedAt time.Time
}

type LocalizationMessage struct {
	TenantID       uuid.UUID
	MessageID      uuid.UUID
	ProjectID      uuid.UUID
	Key            string
	Namespace      string
	State          string
	SourceRevision int32
	Version        int32
	UpdatedAt      time.Time
}

type LocalizationTranslation struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ProjectID      uuid.UUID
	MessageID      uuid.UUID
	Locale         string
	Syntax         string
	Text           string
	Model          json.RawMessage
	State          string
	Origin         string
	Author         string
	SourceRevision int32
	Warnings       json.RawMessage
	Revision       int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type LocalizationTranslationRevision struct {
	TenantID       uuid.UUID
	TranslationID  uuid.UUID
	Revision       int32
	Kind           string
	Syntax         string
	Text           string
	Model          json.RawMessage
	State          string
	Origin         string
	OriginDetail   json.RawMessage
	Author         string
	SourceRevision int32
	Findings       json.RawMessage
	CreatedAt      time.Time
}
