// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: translations.sql

package localizationsql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectMessages = `-- name: DeleteProjectMessages :exec
DELETE FROM localization_messages WHERE project_id = $1
`

func (q *Queries) DeleteProjectMessages(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectMessages, projectID)
	return err
}

const deleteProjectTranslations = `-- name: DeleteProjectTranslations :exec
DELETE FROM localization_translations WHERE project_id = $1
`

func (q *Queries) DeleteProjectTranslations(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectTranslations, projectID)
	return err
}

const getTranslation = `-- name: GetTranslation :one
SELECT t.id, t.tenant_id, t.project_id, t.message_id, t.locale, t.syntax, t.text, t.model, t.state, t.origin, t.author, t.source_revision, t.warnings, t.revision, t.created_at, t.updated_at, coalesce(m.source_revision, 0)::integer AS current_source_revision
FROM localization_translations t
LEFT JOIN localization_messages m ON m.message_id = t.message_id
WHERE t.message_id = $1 AND t.locale = $2
`

type GetTranslationParams struct {
	MessageID uuid.UUID
	Locale    string
}

type GetTranslationRow struct {
	ID                    uuid.UUID
	TenantID              uuid.UUID
	ProjectID             uuid.UUID
	MessageID             uuid.UUID
	Locale                string
	Syntax                string
	Text                  string
	Model                 json.RawMessage
	State                 string
	Origin                string
	Author                string
	SourceRevision        int32
	Warnings              json.RawMessage
	Revision              int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
	CurrentSourceRevision int32
}

// With the message's current source revision, from which "outdated" is
// derived (0 while Localization hasn't seen the message).
func (q *Queries) GetTranslation(ctx context.Context, arg GetTranslationParams) (GetTranslationRow, error) {
	row := q.db.QueryRow(ctx, getTranslation, arg.MessageID, arg.Locale)
	var i GetTranslationRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.MessageID,
		&i.Locale,
		&i.Syntax,
		&i.Text,
		&i.Model,
		&i.State,
		&i.Origin,
		&i.Author,
		&i.SourceRevision,
		&i.Warnings,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentSourceRevision,
	)
	return i, err
}

const insertTranslation = `-- name: InsertTranslation :exec

INSERT INTO localization_translations (id, tenant_id, project_id, message_id, locale, syntax, text, model,
                                       state, origin, author, source_revision, warnings, revision,
                                       created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14,
        $15)
`

type InsertTranslationParams struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	MessageID      uuid.UUID
	Locale         string
	Syntax         string
	Text           string
	Model          json.RawMessage
	State          string
	Origin         string
	Author         string
	SourceRevision int32
	Warnings       json.RawMessage
	Revision       int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// ── translations ───────────────────────────────────────────────────
func (q *Queries) InsertTranslation(ctx context.Context, arg InsertTranslationParams) error {
	_, err := q.db.Exec(ctx, insertTranslation,
		arg.ID,
		arg.ProjectID,
		arg.MessageID,
		arg.Locale,
		arg.Syntax,
		arg.Text,
		arg.Model,
		arg.State,
		arg.Origin,
		arg.Author,
		arg.SourceRevision,
		arg.Warnings,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTranslationRevision = `-- name: InsertTranslationRevision :exec
INSERT INTO localization_translation_revisions (tenant_id, translation_id, revision, kind, syntax, text, model,
                                                state, origin, origin_detail, author, source_revision,
                                                findings, created_at)
VALUES (app_current_tenant(), $1, $2, $3, $4,
        $5, $6, $7, $8, $9,
        $10, $11, $12, $13)
`

type InsertTranslationRevisionParams struct {
	TranslationID  uuid.UUID
	Revision       int32
	Kind           string
	Syntax         string
	Text           string
	Model          json.RawMessage
	State          string
	Origin         string
	OriginDetail   json.RawMessage
	Author         string
	SourceRevision int32
	Findings       json.RawMessage
	CreatedAt      time.Time
}

func (q *Queries) InsertTranslationRevision(ctx context.Context, arg InsertTranslationRevisionParams) error {
	_, err := q.db.Exec(ctx, insertTranslationRevision,
		arg.TranslationID,
		arg.Revision,
		arg.Kind,
		arg.Syntax,
		arg.Text,
		arg.Model,
		arg.State,
		arg.Origin,
		arg.OriginDetail,
		arg.Author,
		arg.SourceRevision,
		arg.Findings,
		arg.CreatedAt,
	)
	return err
}

const listTranslationRevisions = `-- name: ListTranslationRevisions :many
SELECT tenant_id, translation_id, revision, kind, syntax, text, model, state, origin, origin_detail, author, source_revision, findings, created_at FROM localization_translation_revisions
WHERE translation_id = $1 AND revision < $2
ORDER BY revision DESC
LIMIT $3
`

type ListTranslationRevisionsParams struct {
	TranslationID uuid.UUID
	Before        int32
	MaxRows       int32
}

// Newest first; before is exclusive.
func (q *Queries) ListTranslationRevisions(ctx context.Context, arg ListTranslationRevisionsParams) ([]LocalizationTranslationRevision, error) {
	rows, err := q.db.Query(ctx, listTranslationRevisions, arg.TranslationID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalizationTranslationRevision
	for rows.Next() {
		var i LocalizationTranslationRevision
		if err := rows.Scan(
			&i.TenantID,
			&i.TranslationID,
			&i.Revision,
			&i.Kind,
			&i.Syntax,
			&i.Text,
			&i.Model,
			&i.State,
			&i.Origin,
			&i.OriginDetail,
			&i.Author,
			&i.SourceRevision,
			&i.Findings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsOfMessage = `-- name: ListTranslationsOfMessage :many
SELECT t.id, t.tenant_id, t.project_id, t.message_id, t.locale, t.syntax, t.text, t.model, t.state, t.origin, t.author, t.source_revision, t.warnings, t.revision, t.created_at, t.updated_at, coalesce(m.source_revision, 0)::integer AS current_source_revision
FROM localization_translations t
LEFT JOIN localization_messages m ON m.message_id = t.message_id
WHERE t.message_id = $1 AND t.locale > $2
ORDER BY t.locale
LIMIT $3
`

type ListTranslationsOfMessageParams struct {
	MessageID uuid.UUID
	After     string
	MaxRows   int32
}

type ListTranslationsOfMessageRow struct {
	ID                    uuid.UUID
	TenantID              uuid.UUID
	ProjectID             uuid.UUID
	MessageID             uuid.UUID
	Locale                string
	Syntax                string
	Text                  string
	Model                 json.RawMessage
	State                 string
	Origin                string
	Author                string
	SourceRevision        int32
	Warnings              json.RawMessage
	Revision              int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
	CurrentSourceRevision int32
}

func (q *Queries) ListTranslationsOfMessage(ctx context.Context, arg ListTranslationsOfMessageParams) ([]ListTranslationsOfMessageRow, error) {
	rows, err := q.db.Query(ctx, listTranslationsOfMessage, arg.MessageID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTranslationsOfMessageRow
	for rows.Next() {
		var i ListTranslationsOfMessageRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.MessageID,
			&i.Locale,
			&i.Syntax,
			&i.Text,
			&i.Model,
			&i.State,
			&i.Origin,
			&i.Author,
			&i.SourceRevision,
			&i.Warnings,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentSourceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMessageState = `-- name: LockMessageState :one


SELECT tenant_id, message_id, project_id, key, namespace, state, source_revision, version, updated_at FROM localization_messages WHERE message_id = $1 FOR UPDATE
`

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
// ── message projection ─────────────────────────────────────────────
func (q *Queries) LockMessageState(ctx context.Context, messageID uuid.UUID) (LocalizationMessage, error) {
	row := q.db.QueryRow(ctx, lockMessageState, messageID)
	var i LocalizationMessage
	err := row.Scan(
		&i.TenantID,
		&i.MessageID,
		&i.ProjectID,
		&i.Key,
		&i.Namespace,
		&i.State,
		&i.SourceRevision,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const lockTranslation = `-- name: LockTranslation :one
SELECT id, tenant_id, project_id, message_id, locale, syntax, text, model, state, origin, author, source_revision, warnings, revision, created_at, updated_at FROM localization_translations
WHERE message_id = $1 AND locale = $2
FOR UPDATE
`

type LockTranslationParams struct {
	MessageID uuid.UUID
	Locale    string
}

func (q *Queries) LockTranslation(ctx context.Context, arg LockTranslationParams) (LocalizationTranslation, error) {
	row := q.db.QueryRow(ctx, lockTranslation, arg.MessageID, arg.Locale)
	var i LocalizationTranslation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.MessageID,
		&i.Locale,
		&i.Syntax,
		&i.Text,
		&i.Model,
		&i.State,
		&i.Origin,
		&i.Author,
		&i.SourceRevision,
		&i.Warnings,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const messagesMissingIn = `-- name: MessagesMissingIn :many
SELECT m.message_id, m.key FROM localization_messages m
WHERE m.project_id = $1
  AND m.key > $2
  AND ($3::text IS NULL OR m.namespace = $3)
  AND ($4::text IS NULL OR m.state = $4)
  AND ($5::text IS NULL OR m.key LIKE $5)
  AND NOT EXISTS (SELECT FROM localization_translations t
                  WHERE t.message_id = m.message_id AND t.locale = $6)
ORDER BY m.key
LIMIT $7
`

type MessagesMissingInParams struct {
	ProjectID uuid.UUID
	After     string
	Namespace pgtype.Text
	State     pgtype.Text
	KeyLike   pgtype.Text
	Locale    string
	MaxRows   int32
}

type MessagesMissingInRow struct {
	MessageID uuid.UUID
	Key       string
}

// Messages with no translation in a locale, in key order.
func (q *Queries) MessagesMissingIn(ctx context.Context, arg MessagesMissingInParams) ([]MessagesMissingInRow, error) {
	rows, err := q.db.Query(ctx, messagesMissingIn,
		arg.ProjectID,
		arg.After,
		arg.Namespace,
		arg.State,
		arg.KeyLike,
		arg.Locale,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesMissingInRow
	for rows.Next() {
		var i MessagesMissingInRow
		if err := rows.Scan(&i.MessageID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesOutdatedIn = `-- name: MessagesOutdatedIn :many
SELECT m.message_id, m.key FROM localization_messages m
WHERE m.project_id = $1
  AND m.key > $2
  AND ($3::text IS NULL OR m.namespace = $3)
  AND ($4::text IS NULL OR m.state = $4)
  AND ($5::text IS NULL OR m.key LIKE $5)
  AND EXISTS (SELECT FROM localization_translations t
              WHERE t.message_id = m.message_id AND t.locale = $6
                AND t.source_revision < m.source_revision)
ORDER BY m.key
LIMIT $7
`

type MessagesOutdatedInParams struct {
	ProjectID uuid.UUID
	After     string
	Namespace pgtype.Text
	State     pgtype.Text
	KeyLike   pgtype.Text
	Locale    string
	MaxRows   int32
}

type MessagesOutdatedInRow struct {
	MessageID uuid.UUID
	Key       string
}

// Messages whose translation in a locale was made against an older
// source revision, in key order.
func (q *Queries) MessagesOutdatedIn(ctx context.Context, arg MessagesOutdatedInParams) ([]MessagesOutdatedInRow, error) {
	rows, err := q.db.Query(ctx, messagesOutdatedIn,
		arg.ProjectID,
		arg.After,
		arg.Namespace,
		arg.State,
		arg.KeyLike,
		arg.Locale,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagesOutdatedInRow
	for rows.Next() {
		var i MessagesOutdatedInRow
		if err := rows.Scan(&i.MessageID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newlyOutdatedTranslations = `-- name: NewlyOutdatedTranslations :many
SELECT id, tenant_id, project_id, message_id, locale, syntax, text, model, state, origin, author, source_revision, warnings, revision, created_at, updated_at FROM localization_translations
WHERE message_id = $1
  AND source_revision >= $2 AND source_revision < $3
ORDER BY locale
`

type NewlyOutdatedTranslationsParams struct {
	MessageID   uuid.UUID
	OldRevision int32
	NewRevision int32
}

// Translations that were current at old_revision and are behind
// new_revision.
func (q *Queries) NewlyOutdatedTranslations(ctx context.Context, arg NewlyOutdatedTranslationsParams) ([]LocalizationTranslation, error) {
	rows, err := q.db.Query(ctx, newlyOutdatedTranslations, arg.MessageID, arg.OldRevision, arg.NewRevision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalizationTranslation
	for rows.Next() {
		var i LocalizationTranslation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.MessageID,
			&i.Locale,
			&i.Syntax,
			&i.Text,
			&i.Model,
			&i.State,
			&i.Origin,
			&i.Author,
			&i.SourceRevision,
			&i.Warnings,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotTranslations = `-- name: SnapshotTranslations :many
SELECT t.id, t.tenant_id, t.project_id, t.message_id, t.locale, t.syntax, t.text, t.model, t.state, t.origin, t.author, t.source_revision, t.warnings, t.revision, t.created_at, t.updated_at, coalesce(m.source_revision, 0)::integer AS current_source_revision
FROM localization_translations t
LEFT JOIN localization_messages m ON m.message_id = t.message_id
WHERE t.project_id = $1 AND t.state = ANY ($2::text[])
ORDER BY t.locale, t.message_id
`

type SnapshotTranslationsParams struct {
	ProjectID uuid.UUID
	States    []string
}

type SnapshotTranslationsRow struct {
	ID                    uuid.UUID
	TenantID              uuid.UUID
	ProjectID             uuid.UUID
	MessageID             uuid.UUID
	Locale                string
	Syntax                string
	Text                  string
	Model                 json.RawMessage
	State                 string
	Origin                string
	Author                string
	SourceRevision        int32
	Warnings              json.RawMessage
	Revision              int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
	CurrentSourceRevision int32
}

// A project's translations in the given review states, for a release.
func (q *Queries) SnapshotTranslations(ctx context.Context, arg SnapshotTranslationsParams) ([]SnapshotTranslationsRow, error) {
	rows, err := q.db.Query(ctx, snapshotTranslations, arg.ProjectID, arg.States)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotTranslationsRow
	for rows.Next() {
		var i SnapshotTranslationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.MessageID,
			&i.Locale,
			&i.Syntax,
			&i.Text,
			&i.Model,
			&i.State,
			&i.Origin,
			&i.Author,
			&i.SourceRevision,
			&i.Warnings,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentSourceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTranslation = `-- name: UpdateTranslation :execrows
UPDATE localization_translations
SET syntax = $1, text = $2, model = $3, state = $4,
    origin = $5, author = $6, source_revision = $7,
    warnings = $8, revision = $9, updated_at = $10
WHERE id = $11 AND revision = $12
`

type UpdateTranslationParams struct {
	Syntax           string
	Text             string
	Model            json.RawMessage
	State            string
	Origin           string
	Author           string
	SourceRevision   int32
	Warnings         json.RawMessage
	Revision         int32
	UpdatedAt        time.Time
	ID               uuid.UUID
	ExpectedRevision int32
}

func (q *Queries) UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTranslation,
		arg.Syntax,
		arg.Text,
		arg.Model,
		arg.State,
		arg.Origin,
		arg.Author,
		arg.SourceRevision,
		arg.Warnings,
		arg.Revision,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertMessageState = `-- name: UpsertMessageState :execrows
INSERT INTO localization_messages (tenant_id, message_id, project_id, key, namespace, state,
                                   source_revision, version, updated_at)
VALUES (app_current_tenant(), $1, $2, $3, $4,
        $5, $6, $7, $8)
ON CONFLICT (message_id) DO UPDATE
SET key = EXCLUDED.key, namespace = EXCLUDED.namespace, state = EXCLUDED.state,
    source_revision = GREATEST(localization_messages.source_revision, EXCLUDED.source_revision),
    version = EXCLUDED.version, updated_at = EXCLUDED.updated_at
WHERE localization_messages.version < EXCLUDED.version
`

type UpsertMessageStateParams struct {
	MessageID      uuid.UUID
	ProjectID      uuid.UUID
	Key            string
	Namespace      string
	State          string
	SourceRevision int32
	Version        int32
	UpdatedAt      time.Time
}

// Keeps the snapshot with the highest version; an older or repeated
// event changes nothing.
func (q *Queries) UpsertMessageState(ctx context.Context, arg UpsertMessageStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertMessageState,
		arg.MessageID,
		arg.ProjectID,
		arg.Key,
		arg.Namespace,
		arg.State,
		arg.SourceRevision,
		arg.Version,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
