// Generates `lib/src/subtags.g.dart` from the IANA Language Subtag Registry.
//
// RFC 5646 §4.5 canonicalization needs the registry's `Preferred-Value`
// mappings (deprecated languages, extlangs, regions, variants and
// grandfathered tags) and its `Suppress-Script` entries. Dart has no CLDR
// or registry data of its own — `package:intl` carries formatting data
// only — so the tables are generated here rather than hand-written, and
// the generated file records the registry's File-Date.
//
// Usage:
//
//   curl -fsSLo /tmp/registry.txt \
//     https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
//   dart run tool/gen_subtags.dart /tmp/registry.txt
//
// Re-run it when the registry moves, and commit the result.
library;

import 'dart:io';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln('usage: dart run tool/gen_subtags.dart <registry file>');
    exitCode = 64;
    return;
  }
  final records = File(args.single).readAsStringSync().split('\n%%\n');
  final fileDate = _fields(records.first)['File-Date'] ?? 'unknown';

  final language = <String, String>{};
  final extlang = <String, String>{};
  final region = <String, String>{};
  final variant = <String, String>{};
  final grandfathered = <String, String?>{};
  final redundant = <String, String>{};
  final suppressScript = <String, String>{};

  for (final record in records.skip(1)) {
    final f = _fields(record);
    final subtag = (f['Subtag'] ?? f['Tag'])?.toLowerCase();
    if (subtag == null) continue;
    final preferred = f['Preferred-Value']?.toLowerCase();
    switch (f['Type']) {
      case 'language':
        if (preferred != null) language[subtag] = preferred;
        final suppress = f['Suppress-Script'];
        if (suppress != null) suppressScript[subtag] = suppress.toLowerCase();
      case 'extlang':
        if (preferred != null) extlang[subtag] = preferred;
      case 'region':
        if (preferred != null) region[subtag] = preferred;
      case 'variant':
        if (preferred != null) variant[subtag] = preferred;
      case 'grandfathered':
        grandfathered[subtag] = preferred;
      case 'redundant':
        if (preferred != null) redundant[subtag] = preferred;
    }
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_subtags.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Source: IANA Language Subtag Registry, File-Date $fileDate.')
    ..writeln('// Regenerate with the command in tool/gen_subtags.dart.')
    ..writeln()
    ..writeln('/// The registry file date these tables were generated from.')
    ..writeln("const String subtagRegistryDate = '$fileDate';")
    ..writeln();
  _writeMap(out, 'languagePreferred',
      'Deprecated primary language subtags and their replacements.', language);
  _writeMap(out, 'extlangPreferred',
      'Extended language subtags and the tags that replace `prefix-extlang`.',
      extlang);
  _writeMap(out, 'regionPreferred',
      'Deprecated region subtags and their replacements.', region);
  _writeMap(out, 'variantPreferred',
      'Deprecated variant subtags and their replacements.', variant);
  _writeMap(
      out,
      'redundantPreferred',
      'Whole tags the registry marks redundant, and their replacements.',
      redundant);
  _writeMap(
      out,
      'suppressScript',
      'Scripts a language implies, which a canonical tag leaves out.',
      suppressScript);
  _writeNullableMap(
      out,
      'grandfathered',
      'Grandfathered tags; the value is the replacement, or null when the '
          'registry names none.',
      grandfathered);

  File('lib/src/subtags.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('lib/src/subtags.g.dart written from registry $fileDate: '
      '${language.length} language, ${extlang.length} extlang, '
      '${region.length} region, ${variant.length} variant, '
      '${redundant.length} redundant, ${suppressScript.length} suppress-script, '
      '${grandfathered.length} grandfathered');
}

/// Parse one registry record, unfolding its continuation lines.
Map<String, String> _fields(String record) {
  final lines = <String>[];
  for (final line in record.split('\n')) {
    if (line.startsWith('  ') && lines.isNotEmpty) {
      lines[lines.length - 1] += line.substring(1);
    } else {
      lines.add(line);
    }
  }
  final out = <String, String>{};
  for (final line in lines) {
    final i = line.indexOf(': ');
    if (i < 0) continue;
    // The first value wins: a record may repeat Description or Prefix.
    out.putIfAbsent(line.substring(0, i), () => line.substring(i + 2));
  }
  return out;
}

void _writeMap(
    StringBuffer out, String name, String doc, Map<String, String> m) {
  out
    ..writeln('/// $doc')
    ..writeln('const Map<String, String> $name = {');
  for (final key in m.keys.toList()..sort()) {
    out.writeln("  '$key': '${m[key]}',");
  }
  out
    ..writeln('};')
    ..writeln();
}

void _writeNullableMap(
    StringBuffer out, String name, String doc, Map<String, String?> m) {
  out
    ..writeln('/// $doc')
    ..writeln('const Map<String, String?> $name = {');
  for (final key in m.keys.toList()..sort()) {
    final v = m[key];
    out.writeln("  '$key': ${v == null ? 'null' : "'$v'"},");
  }
  out
    ..writeln('};')
    ..writeln();
}
