// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package integrationsql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDelivery = `-- name: ClaimDelivery :one
WITH due AS (
    SELECT d.delivery_id
    FROM integration_github_deliveries d
    WHERE d.state = 'pending' AND d.available_at <= now()
    ORDER BY d.available_at, d.delivery_id
    LIMIT 1
    FOR UPDATE OF d SKIP LOCKED
)
UPDATE integration_github_deliveries e
SET attempts     = e.attempts + 1,
    available_at = now() + make_interval(secs => $1::float8),
    claim_token  = gen_random_uuid()
FROM due
WHERE e.delivery_id = due.delivery_id
RETURNING e.delivery_id, e.event, e.action, e.installation_id, e.tenant_id, e.payload, e.attempts, e.claim_token
`

type ClaimDeliveryRow struct {
	DeliveryID     string
	Event          string
	Action         string
	InstallationID int64
	TenantID       uuid.NullUUID
	Payload        []byte
	Attempts       int32
	ClaimToken     uuid.NullUUID
}

// ClaimDelivery leases the oldest due delivery. System scope.
func (q *Queries) ClaimDelivery(ctx context.Context, leaseSeconds float64) (ClaimDeliveryRow, error) {
	row := q.db.QueryRow(ctx, claimDelivery, leaseSeconds)
	var i ClaimDeliveryRow
	err := row.Scan(
		&i.DeliveryID,
		&i.Event,
		&i.Action,
		&i.InstallationID,
		&i.TenantID,
		&i.Payload,
		&i.Attempts,
		&i.ClaimToken,
	)
	return i, err
}

const connectionsForRepository = `-- name: ConnectionsForRepository :many
SELECT id, tenant_id, installation_id, repository_id, repository_name, project_id, application_id, default_branch, path, created_by, created_at, updated_at FROM integration_git_connections WHERE repository_id = $1 ORDER BY path, id
`

// ConnectionsForRepository is how a pull-request event finds the
// projects a repository feeds, one per monorepo path.
func (q *Queries) ConnectionsForRepository(ctx context.Context, repositoryID int64) ([]IntegrationGitConnection, error) {
	rows, err := q.db.Query(ctx, connectionsForRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationGitConnection
	for rows.Next() {
		var i IntegrationGitConnection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InstallationID,
			&i.RepositoryID,
			&i.RepositoryName,
			&i.ProjectID,
			&i.ApplicationID,
			&i.DefaultBranch,
			&i.Path,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDeliveriesBefore = `-- name: DeleteDeliveriesBefore :execrows
DELETE FROM integration_github_deliveries
WHERE received_at < $1 AND state <> 'pending'
`

// DeleteDeliveriesBefore is the replay-window sweep: a delivery ID is
// kept for seven days, then it is gone. System scope.
func (q *Queries) DeleteDeliveriesBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeliveriesBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredInstallIntents = `-- name: DeleteExpiredInstallIntents :execrows
DELETE FROM integration_github_install_intents WHERE expires_at < $1
`

// System scope: the sweep drops intents whose window closed.
func (q *Queries) DeleteExpiredInstallIntents(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredInstallIntents, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGitConnection = `-- name: DeleteGitConnection :execrows
DELETE FROM integration_git_connections WHERE id = $1
`

func (q *Queries) DeleteGitConnection(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInstallation = `-- name: DeleteInstallation :execrows
DELETE FROM integration_github_installations WHERE id = $1
`

func (q *Queries) DeleteInstallation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstallation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deliveryDepth = `-- name: DeliveryDepth :many
SELECT event, count(*)::bigint AS pending
FROM integration_github_deliveries WHERE state = 'pending' GROUP BY event ORDER BY event
`

type DeliveryDepthRow struct {
	Event   string
	Pending int64
}

// DeliveryDepth is the §11 inbox-depth metric: pending rows per event.
// System scope.
func (q *Queries) DeliveryDepth(ctx context.Context) ([]DeliveryDepthRow, error) {
	rows, err := q.db.Query(ctx, deliveryDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryDepthRow
	for rows.Next() {
		var i DeliveryDepthRow
		if err := rows.Scan(&i.Event, &i.Pending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGitConnection = `-- name: GetGitConnection :one
SELECT id, tenant_id, installation_id, repository_id, repository_name, project_id, application_id, default_branch, path, created_by, created_at, updated_at FROM integration_git_connections WHERE id = $1
`

func (q *Queries) GetGitConnection(ctx context.Context, id uuid.UUID) (IntegrationGitConnection, error) {
	row := q.db.QueryRow(ctx, getGitConnection, id)
	var i IntegrationGitConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InstallationID,
		&i.RepositoryID,
		&i.RepositoryName,
		&i.ProjectID,
		&i.ApplicationID,
		&i.DefaultBranch,
		&i.Path,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallation = `-- name: GetInstallation :one
SELECT id, tenant_id, installation_id, account_id, account_login, account_type, state, connected_by, connected_at, updated_at FROM integration_github_installations WHERE id = $1
`

func (q *Queries) GetInstallation(ctx context.Context, id uuid.UUID) (IntegrationGithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallation, id)
	var i IntegrationGithubInstallation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InstallationID,
		&i.AccountID,
		&i.AccountLogin,
		&i.AccountType,
		&i.State,
		&i.ConnectedBy,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationByGitHubID = `-- name: GetInstallationByGitHubID :one
SELECT id, tenant_id, installation_id, account_id, account_login, account_type, state, connected_by, connected_at, updated_at FROM integration_github_installations WHERE installation_id = $1
`

func (q *Queries) GetInstallationByGitHubID(ctx context.Context, installationID int64) (IntegrationGithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationByGitHubID, installationID)
	var i IntegrationGithubInstallation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InstallationID,
		&i.AccountID,
		&i.AccountLogin,
		&i.AccountType,
		&i.State,
		&i.ConnectedBy,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGitConnection = `-- name: InsertGitConnection :execrows

INSERT INTO integration_git_connections (id, tenant_id, installation_id, repository_id, repository_name,
                                         project_id, application_id, default_branch, path,
                                         created_by, created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3,
        $4, $5, $6, $7,
        $8, $9, $10, $11)
ON CONFLICT (repository_id, path) DO NOTHING
`

type InsertGitConnectionParams struct {
	ID             uuid.UUID
	InstallationID uuid.UUID
	RepositoryID   int64
	RepositoryName string
	ProjectID      uuid.UUID
	ApplicationID  uuid.UUID
	DefaultBranch  string
	Path           string
	CreatedBy      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// ── Git connections ────────────────────────────────────────────────
func (q *Queries) InsertGitConnection(ctx context.Context, arg InsertGitConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertGitConnection,
		arg.ID,
		arg.InstallationID,
		arg.RepositoryID,
		arg.RepositoryName,
		arg.ProjectID,
		arg.ApplicationID,
		arg.DefaultBranch,
		arg.Path,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertInstallIntent = `-- name: InsertInstallIntent :execrows


INSERT INTO integration_github_install_intents (id, tenant_id, person, state_hash, created_at, expires_at)
VALUES ($1, app_current_tenant(), $2, $3,
        $4, $5)
ON CONFLICT (id) DO NOTHING
`

type InsertInstallIntentParams struct {
	ID        uuid.UUID
	Person    string
	StateHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

// The GitHub integration (RFC 0004 §6), migration 0019.
//
// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant, except the queries marked system scope, which run as
// glossa_system ("integration.github") across tenants — the webhook
// endpoint (no tenant on the request), the inbox worker and the sweep.
// ── install intents ────────────────────────────────────────────────
func (q *Queries) InsertInstallIntent(ctx context.Context, arg InsertInstallIntentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInstallIntent,
		arg.ID,
		arg.Person,
		arg.StateHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertInstallation = `-- name: InsertInstallation :execrows

INSERT INTO integration_github_installations (id, tenant_id, installation_id, account_id, account_login,
                                              account_type, state, connected_by, connected_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3,
        $4, $5, $6, $7,
        $8, $9)
ON CONFLICT (installation_id) DO NOTHING
`

type InsertInstallationParams struct {
	ID             uuid.UUID
	InstallationID int64
	AccountID      int64
	AccountLogin   string
	AccountType    string
	State          string
	ConnectedBy    string
	ConnectedAt    time.Time
	UpdatedAt      time.Time
}

// ── installations ──────────────────────────────────────────────────
// InsertInstallation claims an installation for the current tenant. The
// unique index on installation_id is global, so a second tenant's insert
// raises a unique violation rather than returning zero rows; the store
// turns that into installation_already_claimed.
func (q *Queries) InsertInstallation(ctx context.Context, arg InsertInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInstallation,
		arg.ID,
		arg.InstallationID,
		arg.AccountID,
		arg.AccountLogin,
		arg.AccountType,
		arg.State,
		arg.ConnectedBy,
		arg.ConnectedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listGitConnections = `-- name: ListGitConnections :many
SELECT id, tenant_id, installation_id, repository_id, repository_name, project_id, application_id, default_branch, path, created_by, created_at, updated_at FROM integration_git_connections
WHERE ($1::uuid IS NULL OR installation_id = $1::uuid)
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
ORDER BY repository_name, path, id
`

type ListGitConnectionsParams struct {
	InstallationID uuid.NullUUID
	ProjectID      uuid.NullUUID
}

func (q *Queries) ListGitConnections(ctx context.Context, arg ListGitConnectionsParams) ([]IntegrationGitConnection, error) {
	rows, err := q.db.Query(ctx, listGitConnections, arg.InstallationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationGitConnection
	for rows.Next() {
		var i IntegrationGitConnection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InstallationID,
			&i.RepositoryID,
			&i.RepositoryName,
			&i.ProjectID,
			&i.ApplicationID,
			&i.DefaultBranch,
			&i.Path,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallations = `-- name: ListInstallations :many
SELECT id, tenant_id, installation_id, account_id, account_login, account_type, state, connected_by, connected_at, updated_at FROM integration_github_installations ORDER BY connected_at, id
`

func (q *Queries) ListInstallations(ctx context.Context) ([]IntegrationGithubInstallation, error) {
	rows, err := q.db.Query(ctx, listInstallations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationGithubInstallation
	for rows.Next() {
		var i IntegrationGithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InstallationID,
			&i.AccountID,
			&i.AccountLogin,
			&i.AccountType,
			&i.State,
			&i.ConnectedBy,
			&i.ConnectedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInstallIntent = `-- name: RedeemInstallIntent :one
UPDATE integration_github_install_intents
SET redeemed_at = $1
WHERE state_hash = $2 AND redeemed_at IS NULL AND expires_at > $1
RETURNING id, tenant_id, person, created_at, expires_at
`

type RedeemInstallIntentParams struct {
	Now       pgtype.Timestamptz
	StateHash []byte
}

type RedeemInstallIntentRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Person    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

// RedeemInstallIntent takes an unexpired, unredeemed intent by its
// state's hash and marks it used in the same statement, so two callbacks
// racing on one state leave exactly one winner.
func (q *Queries) RedeemInstallIntent(ctx context.Context, arg RedeemInstallIntentParams) (RedeemInstallIntentRow, error) {
	row := q.db.QueryRow(ctx, redeemInstallIntent, arg.Now, arg.StateHash)
	var i RedeemInstallIntentRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Person,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const resolveInstallationTenant = `-- name: ResolveInstallationTenant :one
SELECT tenant_id, state FROM integration_github_installations
WHERE installation_id = $1
`

type ResolveInstallationTenantRow struct {
	TenantID uuid.UUID
	State    string
}

// ResolveInstallationTenant maps GitHub's installation ID to the tenant
// that claimed it. System scope: the inbox worker runs before a tenant
// is known, and the grant covers these three columns only.
func (q *Queries) ResolveInstallationTenant(ctx context.Context, installationID int64) (ResolveInstallationTenantRow, error) {
	row := q.db.QueryRow(ctx, resolveInstallationTenant, installationID)
	var i ResolveInstallationTenantRow
	err := row.Scan(&i.TenantID, &i.State)
	return i, err
}

const retryDelivery = `-- name: RetryDelivery :execrows
UPDATE integration_github_deliveries
SET available_at = now() + make_interval(secs => $1::float8),
    failure      = $2,
    claim_token  = NULL
WHERE delivery_id = $3 AND claim_token = $4::uuid
`

type RetryDeliveryParams struct {
	DelaySeconds float64
	Failure      string
	DeliveryID   string
	ClaimToken   uuid.UUID
}

// RetryDelivery hands a claimed delivery back for another attempt after
// a delay, keeping its payload. System scope.
func (q *Queries) RetryDelivery(ctx context.Context, arg RetryDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryDelivery,
		arg.DelaySeconds,
		arg.Failure,
		arg.DeliveryID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleDelivery = `-- name: SettleDelivery :execrows
UPDATE integration_github_deliveries
SET state        = $1,
    tenant_id    = $2,
    failure      = $3,
    payload      = NULL,
    claim_token  = NULL,
    processed_at = $4
WHERE delivery_id = $5 AND claim_token = $6::uuid
`

type SettleDeliveryParams struct {
	State       string
	TenantID    uuid.NullUUID
	Failure     string
	ProcessedAt pgtype.Timestamptz
	DeliveryID  string
	ClaimToken  uuid.UUID
}

// SettleDelivery ends a claimed delivery: it records the tenant it
// resolved to, drops the payload and keeps the ID for the replay window.
// The claim token fences it, so a worker whose lease expired changes
// nothing. System scope.
func (q *Queries) SettleDelivery(ctx context.Context, arg SettleDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleDelivery,
		arg.State,
		arg.TenantID,
		arg.Failure,
		arg.ProcessedAt,
		arg.DeliveryID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storeDelivery = `-- name: StoreDelivery :execrows

INSERT INTO integration_github_deliveries (delivery_id, event, action, installation_id, state, payload,
                                           received_at, available_at)
VALUES ($1, $2, $3, $4, 'pending',
        $5, $6, $6)
ON CONFLICT (delivery_id) DO NOTHING
`

type StoreDeliveryParams struct {
	DeliveryID     string
	Event          string
	Action         string
	InstallationID int64
	Payload        []byte
	ReceivedAt     time.Time
}

// ── the webhook inbox ──────────────────────────────────────────────
// StoreDelivery is the endpoint's whole write: system scope, no tenant.
// A delivery ID we have already seen changes nothing, which is what
// makes a duplicate a no-op inside the replay window.
func (q *Queries) StoreDelivery(ctx context.Context, arg StoreDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, storeDelivery,
		arg.DeliveryID,
		arg.Event,
		arg.Action,
		arg.InstallationID,
		arg.Payload,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGitConnection = `-- name: UpdateGitConnection :execrows
UPDATE integration_git_connections
SET project_id     = $1,
    application_id = $2,
    default_branch = $3,
    path           = $4,
    updated_at     = $5
WHERE id = $6
`

type UpdateGitConnectionParams struct {
	ProjectID     uuid.UUID
	ApplicationID uuid.UUID
	DefaultBranch string
	Path          string
	UpdatedAt     time.Time
	ID            uuid.UUID
}

func (q *Queries) UpdateGitConnection(ctx context.Context, arg UpdateGitConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGitConnection,
		arg.ProjectID,
		arg.ApplicationID,
		arg.DefaultBranch,
		arg.Path,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInstallationState = `-- name: UpdateInstallationState :execrows
UPDATE integration_github_installations
SET state = $1, account_login = $2, updated_at = $3
WHERE installation_id = $4
`

type UpdateInstallationStateParams struct {
	State          string
	AccountLogin   string
	UpdatedAt      time.Time
	InstallationID int64
}

func (q *Queries) UpdateInstallationState(ctx context.Context, arg UpdateInstallationStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInstallationState,
		arg.State,
		arg.AccountLogin,
		arg.UpdatedAt,
		arg.InstallationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
