// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package integrationsql

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IntegrationGitConnection struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	InstallationID uuid.UUID
	RepositoryID   int64
	RepositoryName string
	ProjectID      uuid.UUID
	ApplicationID  uuid.UUID
	DefaultBranch  string
	Path           string
	CreatedBy      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type IntegrationGithubCheck struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	InstallationID int64
	RepositoryID   int64
	PullRequest    int32
	Branch         string
	HeadSha        string
	CommentID      int64
	Runs           json.RawMessage
	State          string
	Conclusion     string
	Attempts       int32
	Failure        string
	ClaimToken     uuid.NullUUID
	RequestedAt    time.Time
	AvailableAt    time.Time
	CompletedAt    pgtype.Timestamptz
	UpdatedAt      time.Time
}

type IntegrationGithubInstallation struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	InstallationID int64
	AccountID      int64
	AccountLogin   string
	AccountType    string
	State          string
	ConnectedBy    string
	ConnectedAt    time.Time
	UpdatedAt      time.Time
}

type IntegrationJob struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	Direction       string
	ProjectID       uuid.NullUUID
	Kind            string
	Format          string
	Mode            pgtype.Text
	Options         json.RawMessage
	Access          json.RawMessage
	State           string
	FileName        string
	FileKey         pgtype.Text
	FileSize        pgtype.Int8
	FileSha256      pgtype.Text
	ContentType     pgtype.Text
	Fingerprint     pgtype.Text
	ReusedJobID     uuid.NullUUID
	Summary         json.RawMessage
	TotalItems      int32
	ProcessedItems  int32
	FailureCode     pgtype.Text
	FailureMessage  pgtype.Text
	CancelRequested bool
	Attempts        int32
	MaxAttempts     int32
	AvailableAt     time.Time
	ClaimToken      uuid.NullUUID
	CreatedBy       string
	CreatedAt       time.Time
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       time.Time
	ExpiresAt       time.Time
	FilesDeletedAt  pgtype.Timestamptz
}

type IntegrationJobItem struct {
	JobID    uuid.UUID
	TenantID uuid.UUID
	Seq      int32
	Kind     string
	ItemKey  string
	Locale   string
	Status   string
	Code     pgtype.Text
	Detail   pgtype.Text
	Line     pgtype.Int4
	Col      pgtype.Int4
	Ref      pgtype.Text
}
