// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package integrationsql

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IntegrationJob struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	Direction       string
	ProjectID       uuid.NullUUID
	Kind            string
	Format          string
	Mode            pgtype.Text
	Options         json.RawMessage
	Access          json.RawMessage
	State           string
	FileName        string
	FileKey         pgtype.Text
	FileSize        pgtype.Int8
	FileSha256      pgtype.Text
	ContentType     pgtype.Text
	Fingerprint     pgtype.Text
	ReusedJobID     uuid.NullUUID
	Summary         json.RawMessage
	TotalItems      int32
	ProcessedItems  int32
	FailureCode     pgtype.Text
	FailureMessage  pgtype.Text
	CancelRequested bool
	Attempts        int32
	MaxAttempts     int32
	AvailableAt     time.Time
	ClaimToken      uuid.NullUUID
	CreatedBy       string
	CreatedAt       time.Time
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       time.Time
	ExpiresAt       time.Time
	FilesDeletedAt  pgtype.Timestamptz
}

type IntegrationJobItem struct {
	JobID    uuid.UUID
	TenantID uuid.UUID
	Seq      int32
	Kind     string
	ItemKey  string
	Locale   string
	Status   string
	Code     pgtype.Text
	Detail   pgtype.Text
	Line     pgtype.Int4
	Col      pgtype.Int4
}
