// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device.sql

package identitysql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertDeviceAuthorization = `-- name: InsertDeviceAuthorization :exec

INSERT INTO identity_device_authorizations (id, device_code_hash, user_code_hash, client_name, status,
                                            interval_seconds, requested_at, expires_at)
VALUES ($1, $2, $3, $4, 'pending',
        $5, $6, $7)
`

type InsertDeviceAuthorizationParams struct {
	ID              uuid.UUID
	DeviceCodeHash  string
	UserCodeHash    string
	ClientName      string
	IntervalSeconds int32
	RequestedAt     time.Time
	ExpiresAt       time.Time
}

// Device sign-in (RFC 0006 §7.2, migration 0054). System scope only:
// a device authorization belongs to a person, not to a tenant.
func (q *Queries) InsertDeviceAuthorization(ctx context.Context, arg InsertDeviceAuthorizationParams) error {
	_, err := q.db.Exec(ctx, insertDeviceAuthorization,
		arg.ID,
		arg.DeviceCodeHash,
		arg.UserCodeHash,
		arg.ClientName,
		arg.IntervalSeconds,
		arg.RequestedAt,
		arg.ExpiresAt,
	)
	return err
}

const lockDeviceAuthorizationByDeviceCode = `-- name: LockDeviceAuthorizationByDeviceCode :one
SELECT id, device_code_hash, user_code_hash, client_name, status, person_id, interval_seconds, requested_at, expires_at, last_polled_at, decided_at, redeemed_at FROM identity_device_authorizations
WHERE device_code_hash = $1
FOR UPDATE
`

func (q *Queries) LockDeviceAuthorizationByDeviceCode(ctx context.Context, deviceCodeHash string) (IdentityDeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, lockDeviceAuthorizationByDeviceCode, deviceCodeHash)
	var i IdentityDeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientName,
		&i.Status,
		&i.PersonID,
		&i.IntervalSeconds,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.DecidedAt,
		&i.RedeemedAt,
	)
	return i, err
}

const lockPendingDeviceAuthorizationByUserCode = `-- name: LockPendingDeviceAuthorizationByUserCode :one
SELECT id, device_code_hash, user_code_hash, client_name, status, person_id, interval_seconds, requested_at, expires_at, last_polled_at, decided_at, redeemed_at FROM identity_device_authorizations
WHERE user_code_hash = $1 AND status = 'pending' AND expires_at > $2
FOR UPDATE
`

type LockPendingDeviceAuthorizationByUserCodeParams struct {
	UserCodeHash string
	Now          time.Time
}

func (q *Queries) LockPendingDeviceAuthorizationByUserCode(ctx context.Context, arg LockPendingDeviceAuthorizationByUserCodeParams) (IdentityDeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, lockPendingDeviceAuthorizationByUserCode, arg.UserCodeHash, arg.Now)
	var i IdentityDeviceAuthorization
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientName,
		&i.Status,
		&i.PersonID,
		&i.IntervalSeconds,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.DecidedAt,
		&i.RedeemedAt,
	)
	return i, err
}

const purgeDeviceAuthorizations = `-- name: PurgeDeviceAuthorizations :execrows
DELETE FROM identity_device_authorizations WHERE expires_at < $1
`

// Expired authorizations have nothing left to say; the audit trail
// holds what was decided.
func (q *Queries) PurgeDeviceAuthorizations(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeviceAuthorizations, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDeviceAuthorization = `-- name: UpdateDeviceAuthorization :exec
UPDATE identity_device_authorizations
SET status = $1, person_id = $2, interval_seconds = $3,
    last_polled_at = $4, decided_at = $5,
    redeemed_at = $6
WHERE id = $7
`

type UpdateDeviceAuthorizationParams struct {
	Status          string
	PersonID        uuid.NullUUID
	IntervalSeconds int32
	LastPolledAt    pgtype.Timestamptz
	DecidedAt       pgtype.Timestamptz
	RedeemedAt      pgtype.Timestamptz
	ID              uuid.UUID
}

func (q *Queries) UpdateDeviceAuthorization(ctx context.Context, arg UpdateDeviceAuthorizationParams) error {
	_, err := q.db.Exec(ctx, updateDeviceAuthorization,
		arg.Status,
		arg.PersonID,
		arg.IntervalSeconds,
		arg.LastPolledAt,
		arg.DecidedAt,
		arg.RedeemedAt,
		arg.ID,
	)
	return err
}

const withdrawDeviceApprovals = `-- name: WithdrawDeviceApprovals :exec
UPDATE identity_device_authorizations SET status = 'denied'
WHERE person_id = $1 AND status = 'approved'
`

// Signing out everywhere: an approved device that has not taken its
// session yet never gets one.
func (q *Queries) WithdrawDeviceApprovals(ctx context.Context, personID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, withdrawDeviceApprovals, personID)
	return err
}
