// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package identitysql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM identity_groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGroupMember = `-- name: DeleteGroupMember :execrows
DELETE FROM identity_group_members WHERE group_id = $1 AND member_id = $2
`

type DeleteGroupMemberParams struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroupMember, arg.GroupID, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVendor = `-- name: DeleteVendor :execrows
DELETE FROM identity_vendors WHERE id = $1
`

func (q *Queries) DeleteVendor(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVendor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroup = `-- name: GetGroup :one
SELECT id, tenant_id, name, version, created_by, created_at, updated_at FROM identity_groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (IdentityGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i IdentityGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendor = `-- name: GetVendor :one
SELECT id, tenant_id, name, contact, locales, version, created_by, created_at, updated_at FROM identity_vendors WHERE id = $1
`

func (q *Queries) GetVendor(ctx context.Context, id uuid.UUID) (IdentityVendor, error) {
	row := q.db.QueryRow(ctx, getVendor, id)
	var i IdentityVendor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Contact,
		&i.Locales,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const groupMemberIDs = `-- name: GroupMemberIDs :many
SELECT member_id FROM identity_group_members
WHERE group_id = $1
ORDER BY member_id
`

func (q *Queries) GroupMemberIDs(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, groupMemberIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var member_id uuid.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGroup = `-- name: InsertGroup :execrows
INSERT INTO identity_groups (id, tenant_id, name, version, created_by, created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $5)
ON CONFLICT (id) DO NOTHING
`

type InsertGroupParams struct {
	ID        uuid.UUID
	Name      string
	Version   int32
	CreatedBy string
	CreatedAt time.Time
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertGroup,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGroupMember = `-- name: InsertGroupMember :exec
INSERT INTO identity_group_members (tenant_id, group_id, member_id, added_by, added_at)
VALUES (app_current_tenant(), $1, $2, $3, $4)
`

type InsertGroupMemberParams struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
	AddedBy  string
	AddedAt  time.Time
}

func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error {
	_, err := q.db.Exec(ctx, insertGroupMember,
		arg.GroupID,
		arg.MemberID,
		arg.AddedBy,
		arg.AddedAt,
	)
	return err
}

const insertVendor = `-- name: InsertVendor :execrows

INSERT INTO identity_vendors (id, tenant_id, name, contact, locales, version, created_by, created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $7)
ON CONFLICT (id) DO NOTHING
`

type InsertVendorParams struct {
	ID        uuid.UUID
	Name      string
	Contact   string
	Locales   []string
	Version   int32
	CreatedBy string
	CreatedAt time.Time
}

// Groups and vendors (RFC 0006 §3.3, §4.3). Tenant scope (db.TenantTx):
// RLS limits every statement to the current tenant.
func (q *Queries) InsertVendor(ctx context.Context, arg InsertVendorParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVendor,
		arg.ID,
		arg.Name,
		arg.Contact,
		arg.Locales,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, tenant_id, name, version, created_by, created_at, updated_at FROM identity_groups
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListGroupsParams struct {
	After   uuid.UUID
	MaxRows int32
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]IdentityGroup, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityGroup
	for rows.Next() {
		var i IdentityGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendors = `-- name: ListVendors :many
SELECT id, tenant_id, name, contact, locales, version, created_by, created_at, updated_at FROM identity_vendors
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListVendorsParams struct {
	After   uuid.UUID
	MaxRows int32
}

func (q *Queries) ListVendors(ctx context.Context, arg ListVendorsParams) ([]IdentityVendor, error) {
	rows, err := q.db.Query(ctx, listVendors, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityVendor
	for rows.Next() {
		var i IdentityVendor
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Contact,
			&i.Locales,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGroup = `-- name: LockGroup :one
SELECT id, tenant_id, name, version, created_by, created_at, updated_at FROM identity_groups WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockGroup(ctx context.Context, id uuid.UUID) (IdentityGroup, error) {
	row := q.db.QueryRow(ctx, lockGroup, id)
	var i IdentityGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockVendor = `-- name: LockVendor :one
SELECT id, tenant_id, name, contact, locales, version, created_by, created_at, updated_at FROM identity_vendors WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockVendor(ctx context.Context, id uuid.UUID) (IdentityVendor, error) {
	row := q.db.QueryRow(ctx, lockVendor, id)
	var i IdentityVendor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Contact,
		&i.Locales,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :execrows
UPDATE identity_groups
SET name = $1, version = $2, updated_at = $3
WHERE id = $4 AND version = $2 - 1
`

type UpdateGroupParams struct {
	Name      string
	Version   int32
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGroup,
		arg.Name,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVendor = `-- name: UpdateVendor :execrows
UPDATE identity_vendors
SET name = $1, contact = $2, locales = $3,
    version = $4, updated_at = $5
WHERE id = $6 AND version = $4 - 1
`

type UpdateVendorParams struct {
	Name      string
	Contact   string
	Locales   []string
	Version   int32
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVendor,
		arg.Name,
		arg.Contact,
		arg.Locales,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
