// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incontext.sql

package identitysql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPreviewOrigins = `-- name: CountPreviewOrigins :one
SELECT count(*) FROM identity_preview_origins WHERE project_id = $1
`

func (q *Queries) CountPreviewOrigins(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPreviewOrigins, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGrantsForOrigin = `-- name: DeleteGrantsForOrigin :execrows
DELETE FROM identity_in_context_grants
WHERE project_id = $1 AND origin = $2
`

type DeleteGrantsForOriginParams struct {
	ProjectID uuid.UUID
	Origin    string
}

// Unregistering an origin ends the editor sessions minted for it, so
// access stops now rather than when the last 15-minute grant expires.
func (q *Queries) DeleteGrantsForOrigin(ctx context.Context, arg DeleteGrantsForOriginParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrantsForOrigin, arg.ProjectID, arg.Origin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePreviewOrigin = `-- name: DeletePreviewOrigin :execrows
DELETE FROM identity_preview_origins WHERE id = $1
`

func (q *Queries) DeletePreviewOrigin(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePreviewOrigin, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPreviewOrigin = `-- name: GetPreviewOrigin :one
SELECT id, tenant_id, project_id, origin, label, created_by, created_at FROM identity_preview_origins WHERE id = $1
`

func (q *Queries) GetPreviewOrigin(ctx context.Context, id uuid.UUID) (IdentityPreviewOrigin, error) {
	row := q.db.QueryRow(ctx, getPreviewOrigin, id)
	var i IdentityPreviewOrigin
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Origin,
		&i.Label,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPreviewOriginFor = `-- name: GetPreviewOriginFor :one
SELECT id, tenant_id, project_id, origin, label, created_by, created_at FROM identity_preview_origins
WHERE project_id = $1 AND origin = $2
`

type GetPreviewOriginForParams struct {
	ProjectID uuid.UUID
	Origin    string
}

func (q *Queries) GetPreviewOriginFor(ctx context.Context, arg GetPreviewOriginForParams) (IdentityPreviewOrigin, error) {
	row := q.db.QueryRow(ctx, getPreviewOriginFor, arg.ProjectID, arg.Origin)
	var i IdentityPreviewOrigin
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Origin,
		&i.Label,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO identity_in_context_grants (id, tenant_id, project_id, person_id, token_hash, origin,
                                        permissions, created_at, expires_at)
VALUES ($1, app_current_tenant(), $2, $3,
        $4, $5, $6, $7,
        $8)
`

type InsertGrantParams struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	PersonID    uuid.UUID
	TokenHash   string
	Origin      string
	Permissions json.RawMessage
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.Exec(ctx, insertGrant,
		arg.ID,
		arg.ProjectID,
		arg.PersonID,
		arg.TokenHash,
		arg.Origin,
		arg.Permissions,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertPreviewOrigin = `-- name: InsertPreviewOrigin :execrows

INSERT INTO identity_preview_origins (id, tenant_id, project_id, origin, label, created_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6)
ON CONFLICT (project_id, origin) DO NOTHING
`

type InsertPreviewOriginParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Origin    string
	Label     string
	CreatedBy string
	CreatedAt time.Time
}

// Preview origins and in-context grants (RFC 0004 §5.2).
// Tenant scope (db.TenantTx) unless the name starts with System.
func (q *Queries) InsertPreviewOrigin(ctx context.Context, arg InsertPreviewOriginParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPreviewOrigin,
		arg.ID,
		arg.ProjectID,
		arg.Origin,
		arg.Label,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPreviewOrigins = `-- name: ListPreviewOrigins :many
SELECT id, tenant_id, project_id, origin, label, created_by, created_at FROM identity_preview_origins
WHERE project_id = $1
ORDER BY origin
`

func (q *Queries) ListPreviewOrigins(ctx context.Context, projectID uuid.UUID) ([]IdentityPreviewOrigin, error) {
	rows, err := q.db.Query(ctx, listPreviewOrigins, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityPreviewOrigin
	for rows.Next() {
		var i IdentityPreviewOrigin
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Origin,
			&i.Label,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const systemGetGrantByHash = `-- name: SystemGetGrantByHash :one
SELECT id, tenant_id, project_id, person_id, origin, permissions, expires_at
FROM identity_in_context_grants
WHERE token_hash = $1
`

type SystemGetGrantByHashRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ProjectID   uuid.UUID
	PersonID    uuid.UUID
	Origin      string
	Permissions json.RawMessage
	ExpiresAt   time.Time
}

func (q *Queries) SystemGetGrantByHash(ctx context.Context, tokenHash string) (SystemGetGrantByHashRow, error) {
	row := q.db.QueryRow(ctx, systemGetGrantByHash, tokenHash)
	var i SystemGetGrantByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.PersonID,
		&i.Origin,
		&i.Permissions,
		&i.ExpiresAt,
	)
	return i, err
}

const systemOriginRegistered = `-- name: SystemOriginRegistered :one
SELECT EXISTS (SELECT FROM identity_preview_origins WHERE origin = $1)
`

// A CORS preflight carries no credentials, so the origin is checked
// against every project's registrations before any tenant is known.
func (q *Queries) SystemOriginRegistered(ctx context.Context, origin string) (bool, error) {
	row := q.db.QueryRow(ctx, systemOriginRegistered, origin)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const systemPurgeExpiredGrants = `-- name: SystemPurgeExpiredGrants :execrows
DELETE FROM identity_in_context_grants WHERE expires_at < $1
`

func (q *Queries) SystemPurgeExpiredGrants(ctx context.Context, at time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, systemPurgeExpiredGrants, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const systemTouchGrant = `-- name: SystemTouchGrant :exec
UPDATE identity_in_context_grants SET last_used_at = $1
WHERE id = $2
  AND (last_used_at IS NULL OR last_used_at < $1::timestamptz - interval '1 minute')
`

type SystemTouchGrantParams struct {
	At pgtype.Timestamptz
	ID uuid.UUID
}

// At most one write a minute per grant, however hot it is.
func (q *Queries) SystemTouchGrant(ctx context.Context, arg SystemTouchGrantParams) error {
	_, err := q.db.Exec(ctx, systemTouchGrant, arg.At, arg.ID)
	return err
}
