// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package identitysql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activateMember = `-- name: ActivateMember :execrows
UPDATE identity_members
SET person_id = $1, status = 'active', version = version + 1,
    updated_at = $2
WHERE id = $3 AND status = 'invited'
`

type ActivateMemberParams struct {
	PersonID  uuid.NullUUID
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) ActivateMember(ctx context.Context, arg ActivateMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateMember, arg.PersonID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM identity_members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMember = `-- name: GetMember :one
SELECT m.id, m.tenant_id, m.person_id, m.email, m.roles, m.locales, m.status, m.version, m.created_by, m.created_at, m.updated_at, coalesce(p.display_name, '')::text AS display_name
FROM identity_members m
LEFT JOIN identity_people p ON p.id = m.person_id
WHERE m.id = $1
`

type GetMemberRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	PersonID    uuid.NullUUID
	Email       string
	Roles       []string
	Locales     []string
	Status      string
	Version     int32
	CreatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DisplayName string
}

func (q *Queries) GetMember(ctx context.Context, id uuid.UUID) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PersonID,
		&i.Email,
		&i.Roles,
		&i.Locales,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :execrows

INSERT INTO identity_members (id, tenant_id, person_id, email, roles, locales, status, version,
                              created_by, created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8,
        $9, $9)
ON CONFLICT (id) DO NOTHING
`

type InsertMemberParams struct {
	ID        uuid.UUID
	PersonID  uuid.NullUUID
	Email     string
	Roles     []string
	Locales   []string
	Status    string
	Version   int32
	CreatedBy string
	CreatedAt time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant, so none of these take a tenant_id to filter on.
// ON CONFLICT (id) DO NOTHING makes a retried idempotent create a no-op;
// the caller then loads the existing row.
func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMember,
		arg.ID,
		arg.PersonID,
		arg.Email,
		arg.Roles,
		arg.Locales,
		arg.Status,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.tenant_id, m.person_id, m.email, m.roles, m.locales, m.status, m.version, m.created_by, m.created_at, m.updated_at, coalesce(p.display_name, '')::text AS display_name
FROM identity_members m
LEFT JOIN identity_people p ON p.id = m.person_id
WHERE m.id > $1
ORDER BY m.id
LIMIT $2
`

type ListMembersParams struct {
	After   uuid.UUID
	MaxRows int32
}

type ListMembersRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	PersonID    uuid.NullUUID
	Email       string
	Roles       []string
	Locales     []string
	Status      string
	Version     int32
	CreatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DisplayName string
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PersonID,
			&i.Email,
			&i.Roles,
			&i.Locales,
			&i.Status,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveOwners = `-- name: LockActiveOwners :many
SELECT id FROM identity_members
WHERE status = 'active' AND 'owner' = ANY (roles)
ORDER BY id
FOR UPDATE
`

// Locks the owner rows, so two concurrent demotions can't both see a
// second owner and leave none.
func (q *Queries) LockActiveOwners(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockActiveOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMember = `-- name: LockMember :one
SELECT id, tenant_id, person_id, email, roles, locales, status, version, created_by, created_at, updated_at FROM identity_members WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockMember(ctx context.Context, id uuid.UUID) (IdentityMember, error) {
	row := q.db.QueryRow(ctx, lockMember, id)
	var i IdentityMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PersonID,
		&i.Email,
		&i.Roles,
		&i.Locales,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const systemGetActiveMembership = `-- name: SystemGetActiveMembership :one

SELECT id, roles, locales FROM identity_members
WHERE person_id = $1 AND tenant_id = $2 AND status = 'active'
`

type SystemGetActiveMembershipParams struct {
	PersonID uuid.NullUUID
	TenantID uuid.UUID
}

type SystemGetActiveMembershipRow struct {
	ID      uuid.UUID
	Roles   []string
	Locales []string
}

// System scope (db.SystemTx), before a tenant is chosen.
func (q *Queries) SystemGetActiveMembership(ctx context.Context, arg SystemGetActiveMembershipParams) (SystemGetActiveMembershipRow, error) {
	row := q.db.QueryRow(ctx, systemGetActiveMembership, arg.PersonID, arg.TenantID)
	var i SystemGetActiveMembershipRow
	err := row.Scan(&i.ID, &i.Roles, &i.Locales)
	return i, err
}

const systemGetTenant = `-- name: SystemGetTenant :one
SELECT id, kind, slug, name, created_at FROM tenants WHERE id = $1
`

func (q *Queries) SystemGetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, systemGetTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const systemListMembershipsOfPerson = `-- name: SystemListMembershipsOfPerson :many
SELECT m.id AS member_id, m.roles, m.locales, t.id AS tenant_id, t.kind, t.slug, t.name, t.created_at
FROM identity_members m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.person_id = $1 AND m.status = 'active' AND t.id > $2
ORDER BY t.id
LIMIT $3
`

type SystemListMembershipsOfPersonParams struct {
	PersonID uuid.NullUUID
	After    uuid.UUID
	MaxRows  int32
}

type SystemListMembershipsOfPersonRow struct {
	MemberID  uuid.UUID
	Roles     []string
	Locales   []string
	TenantID  uuid.UUID
	Kind      string
	Slug      string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) SystemListMembershipsOfPerson(ctx context.Context, arg SystemListMembershipsOfPersonParams) ([]SystemListMembershipsOfPersonRow, error) {
	rows, err := q.db.Query(ctx, systemListMembershipsOfPerson, arg.PersonID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemListMembershipsOfPersonRow
	for rows.Next() {
		var i SystemListMembershipsOfPersonRow
		if err := rows.Scan(
			&i.MemberID,
			&i.Roles,
			&i.Locales,
			&i.TenantID,
			&i.Kind,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const systemListOpenInvitations = `-- name: SystemListOpenInvitations :many
SELECT id, tenant_id FROM identity_members
WHERE email = $1 AND status = 'invited'
ORDER BY id
`

type SystemListOpenInvitationsRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) SystemListOpenInvitations(ctx context.Context, email string) ([]SystemListOpenInvitationsRow, error) {
	rows, err := q.db.Query(ctx, systemListOpenInvitations, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemListOpenInvitationsRow
	for rows.Next() {
		var i SystemListOpenInvitationsRow
		if err := rows.Scan(&i.ID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberAccess = `-- name: UpdateMemberAccess :execrows
UPDATE identity_members
SET roles = $1, locales = $2, version = $3,
    updated_at = $4
WHERE id = $5 AND version = $3 - 1
`

type UpdateMemberAccessParams struct {
	Roles     []string
	Locales   []string
	Version   int32
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateMemberAccess(ctx context.Context, arg UpdateMemberAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMemberAccess,
		arg.Roles,
		arg.Locales,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
