// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitysql

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityApiToken struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	TokenHash  string
	Hint       string
	Scopes     []string
	CreatedBy  string
	CreatedAt  time.Time
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	RevokedBy  pgtype.Text
	Projects   []uuid.UUID
}

type IdentityDeviceAuthorization struct {
	ID              uuid.UUID
	DeviceCodeHash  string
	UserCodeHash    string
	ClientName      string
	Status          string
	PersonID        uuid.NullUUID
	IntervalSeconds int32
	RequestedAt     time.Time
	ExpiresAt       time.Time
	LastPolledAt    pgtype.Timestamptz
	DecidedAt       pgtype.Timestamptz
	RedeemedAt      pgtype.Timestamptz
}

type IdentityEmailLink struct {
	Hash      string
	Purpose   string
	Email     string
	ExpiresAt time.Time
	Consumed  bool
	CreatedAt time.Time
}

type IdentityGroup struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Version   int32
	CreatedBy string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type IdentityLoginAttempt struct {
	Key          string
	FailureCount int32
	LockedUntil  pgtype.Timestamptz
	UpdatedAt    time.Time
}

type IdentityMember struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	PersonID   uuid.NullUUID
	Email      string
	Roles      []string
	Locales    []string
	Status     string
	Version    int32
	CreatedBy  string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Projects   []uuid.UUID
	VendorID   uuid.NullUUID
	Visibility string
}

type IdentityPasskey struct {
	CredentialID []byte
	PersonID     uuid.UUID
	PublicKey    []byte
	SignCount    int64
	Name         string
	CreatedAt    time.Time
	LastUsedAt   pgtype.Timestamptz
}

type IdentityPreviewOrigin struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	Origin    string
	Label     string
	CreatedBy string
	CreatedAt time.Time
}

type IdentityTotp struct {
	PersonID         uuid.UUID
	SecretCiphertext string
	ConfirmedAt      pgtype.Timestamptz
	LastStep         pgtype.Int8
	UpdatedAt        time.Time
}

type IdentityVendor struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Contact   string
	Locales   []string
	Version   int32
	CreatedBy string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Kind      string
	Slug      string
	Name      string
	CreatedAt time.Time
}
