// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package identitysql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmTOTP = `-- name: ConfirmTOTP :execrows
UPDATE identity_totp SET confirmed_at = $1, updated_at = $1
WHERE person_id = $2 AND confirmed_at IS NULL
`

type ConfirmTOTPParams struct {
	At       pgtype.Timestamptz
	PersonID uuid.UUID
}

func (q *Queries) ConfirmTOTP(ctx context.Context, arg ConfirmTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmTOTP, arg.At, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeEmailLink = `-- name: ConsumeEmailLink :execrows
UPDATE identity_email_links SET consumed = true
WHERE hash = $1 AND purpose = $2 AND NOT consumed
`

type ConsumeEmailLinkParams struct {
	Hash    string
	Purpose string
}

func (q *Queries) ConsumeEmailLink(ctx context.Context, arg ConsumeEmailLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeEmailLink, arg.Hash, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeTOTPStep = `-- name: ConsumeTOTPStep :execrows
UPDATE identity_totp SET last_step = $1
WHERE person_id = $2 AND (last_step IS NULL OR last_step < $1)
`

type ConsumeTOTPStepParams struct {
	Step     pgtype.Int8
	PersonID uuid.UUID
}

func (q *Queries) ConsumeTOTPStep(ctx context.Context, arg ConsumeTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeTOTPStep, arg.Step, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLoginAttempt = `-- name: DeleteLoginAttempt :exec
DELETE FROM identity_login_attempts WHERE key = $1
`

func (q *Queries) DeleteLoginAttempt(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteLoginAttempt, key)
	return err
}

const deletePasskey = `-- name: DeletePasskey :execrows
DELETE FROM identity_passkeys WHERE credential_id = $1
`

func (q *Queries) DeletePasskey(ctx context.Context, credentialID []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskey, credentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePasskeyOfPerson = `-- name: DeletePasskeyOfPerson :execrows
DELETE FROM identity_passkeys
WHERE credential_id = $1 AND person_id = $2
`

type DeletePasskeyOfPersonParams struct {
	CredentialID []byte
	PersonID     uuid.UUID
}

func (q *Queries) DeletePasskeyOfPerson(ctx context.Context, arg DeletePasskeyOfPersonParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskeyOfPerson, arg.CredentialID, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM identity_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsOfPerson = `-- name: DeleteSessionsOfPerson :exec
DELETE FROM identity_sessions WHERE person_id = $1
`

func (q *Queries) DeleteSessionsOfPerson(ctx context.Context, personID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsOfPerson, personID)
	return err
}

const deleteTOTP = `-- name: DeleteTOTP :execrows
DELETE FROM identity_totp WHERE person_id = $1
`

func (q *Queries) DeleteTOTP(ctx context.Context, personID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTOTP, personID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailLink = `-- name: GetEmailLink :one
SELECT hash, purpose, email, expires_at, consumed, created_at FROM identity_email_links WHERE hash = $1 AND purpose = $2
`

type GetEmailLinkParams struct {
	Hash    string
	Purpose string
}

func (q *Queries) GetEmailLink(ctx context.Context, arg GetEmailLinkParams) (IdentityEmailLink, error) {
	row := q.db.QueryRow(ctx, getEmailLink, arg.Hash, arg.Purpose)
	var i IdentityEmailLink
	err := row.Scan(
		&i.Hash,
		&i.Purpose,
		&i.Email,
		&i.ExpiresAt,
		&i.Consumed,
		&i.CreatedAt,
	)
	return i, err
}

const getLoginAttempt = `-- name: GetLoginAttempt :one
SELECT key, failure_count, locked_until, updated_at FROM identity_login_attempts WHERE key = $1
`

func (q *Queries) GetLoginAttempt(ctx context.Context, key string) (IdentityLoginAttempt, error) {
	row := q.db.QueryRow(ctx, getLoginAttempt, key)
	var i IdentityLoginAttempt
	err := row.Scan(
		&i.Key,
		&i.FailureCount,
		&i.LockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasskey = `-- name: GetPasskey :one
SELECT credential_id, person_id, public_key, sign_count, name, created_at, last_used_at FROM identity_passkeys WHERE credential_id = $1
`

func (q *Queries) GetPasskey(ctx context.Context, credentialID []byte) (IdentityPasskey, error) {
	row := q.db.QueryRow(ctx, getPasskey, credentialID)
	var i IdentityPasskey
	err := row.Scan(
		&i.CredentialID,
		&i.PersonID,
		&i.PublicKey,
		&i.SignCount,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPersonByEmail = `-- name: GetPersonByEmail :one
SELECT p.id, p.email, p.display_name, p.individual_tenant_id, p.password_hash, p.email_verified_at, p.created_at, p.updated_at, (t.confirmed_at IS NOT NULL)::boolean AS totp_enabled
FROM identity_people p
LEFT JOIN identity_totp t ON t.person_id = p.id
WHERE p.email = $1
`

type GetPersonByEmailRow struct {
	ID                 uuid.UUID
	Email              string
	DisplayName        string
	IndividualTenantID uuid.UUID
	PasswordHash       pgtype.Text
	EmailVerifiedAt    pgtype.Timestamptz
	CreatedAt          time.Time
	UpdatedAt          time.Time
	TotpEnabled        bool
}

func (q *Queries) GetPersonByEmail(ctx context.Context, email string) (GetPersonByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPersonByEmail, email)
	var i GetPersonByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IndividualTenantID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpEnabled,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT p.id, p.email, p.display_name, p.individual_tenant_id, p.password_hash, p.email_verified_at, p.created_at, p.updated_at, (t.confirmed_at IS NOT NULL)::boolean AS totp_enabled
FROM identity_people p
LEFT JOIN identity_totp t ON t.person_id = p.id
WHERE p.id = $1
`

type GetPersonByIDRow struct {
	ID                 uuid.UUID
	Email              string
	DisplayName        string
	IndividualTenantID uuid.UUID
	PasswordHash       pgtype.Text
	EmailVerifiedAt    pgtype.Timestamptz
	CreatedAt          time.Time
	UpdatedAt          time.Time
	TotpEnabled        bool
}

func (q *Queries) GetPersonByID(ctx context.Context, id uuid.UUID) (GetPersonByIDRow, error) {
	row := q.db.QueryRow(ctx, getPersonByID, id)
	var i GetPersonByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IndividualTenantID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpEnabled,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, person_id, created_at, expires_at FROM identity_sessions WHERE token_hash = $1
`

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (IdentitySession, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i IdentitySession
	err := row.Scan(
		&i.TokenHash,
		&i.PersonID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTOTP = `-- name: GetTOTP :one
SELECT person_id, secret_ciphertext, confirmed_at, last_step, updated_at FROM identity_totp WHERE person_id = $1
`

func (q *Queries) GetTOTP(ctx context.Context, personID uuid.UUID) (IdentityTotp, error) {
	row := q.db.QueryRow(ctx, getTOTP, personID)
	var i IdentityTotp
	err := row.Scan(
		&i.PersonID,
		&i.SecretCiphertext,
		&i.ConfirmedAt,
		&i.LastStep,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCeremony = `-- name: InsertCeremony :exec
INSERT INTO identity_webauthn_ceremonies (key_hash, purpose, person_id, state, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCeremonyParams struct {
	KeyHash   string
	Purpose   string
	PersonID  uuid.NullUUID
	State     []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertCeremony(ctx context.Context, arg InsertCeremonyParams) error {
	_, err := q.db.Exec(ctx, insertCeremony,
		arg.KeyHash,
		arg.Purpose,
		arg.PersonID,
		arg.State,
		arg.ExpiresAt,
	)
	return err
}

const insertEmailLink = `-- name: InsertEmailLink :exec
INSERT INTO identity_email_links (hash, purpose, email, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertEmailLinkParams struct {
	Hash      string
	Purpose   string
	Email     string
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailLink(ctx context.Context, arg InsertEmailLinkParams) error {
	_, err := q.db.Exec(ctx, insertEmailLink,
		arg.Hash,
		arg.Purpose,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}

const insertPasskey = `-- name: InsertPasskey :exec
INSERT INTO identity_passkeys (credential_id, person_id, public_key, sign_count, name, created_at)
VALUES ($1, $2, $3, $4,
        $5, $6)
`

type InsertPasskeyParams struct {
	CredentialID []byte
	PersonID     uuid.UUID
	PublicKey    []byte
	SignCount    int64
	Name         string
	CreatedAt    time.Time
}

func (q *Queries) InsertPasskey(ctx context.Context, arg InsertPasskeyParams) error {
	_, err := q.db.Exec(ctx, insertPasskey,
		arg.CredentialID,
		arg.PersonID,
		arg.PublicKey,
		arg.SignCount,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const insertPerson = `-- name: InsertPerson :exec

INSERT INTO identity_people (id, email, display_name, individual_tenant_id, password_hash,
                             email_verified_at, created_at, updated_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $7)
`

type InsertPersonParams struct {
	ID                 uuid.UUID
	Email              string
	DisplayName        string
	IndividualTenantID uuid.UUID
	PasswordHash       pgtype.Text
	EmailVerifiedAt    pgtype.Timestamptz
	CreatedAt          time.Time
}

// People and their credentials are global: these queries run in system
// scope (db.SystemTx), except where noted.
func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) error {
	_, err := q.db.Exec(ctx, insertPerson,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.IndividualTenantID,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.CreatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO identity_sessions (token_hash, person_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	TokenHash string
	PersonID  uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.TokenHash,
		arg.PersonID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const invalidateEmailLinks = `-- name: InvalidateEmailLinks :exec
UPDATE identity_email_links SET consumed = true
WHERE email = $1 AND purpose = $2 AND NOT consumed
`

type InvalidateEmailLinksParams struct {
	Email   string
	Purpose string
}

func (q *Queries) InvalidateEmailLinks(ctx context.Context, arg InvalidateEmailLinksParams) error {
	_, err := q.db.Exec(ctx, invalidateEmailLinks, arg.Email, arg.Purpose)
	return err
}

const listPasskeysOfPerson = `-- name: ListPasskeysOfPerson :many
SELECT credential_id, person_id, public_key, sign_count, name, created_at, last_used_at FROM identity_passkeys WHERE person_id = $1 ORDER BY created_at
`

func (q *Queries) ListPasskeysOfPerson(ctx context.Context, personID uuid.UUID) ([]IdentityPasskey, error) {
	rows, err := q.db.Query(ctx, listPasskeysOfPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityPasskey
	for rows.Next() {
		var i IdentityPasskey
		if err := rows.Scan(
			&i.CredentialID,
			&i.PersonID,
			&i.PublicKey,
			&i.SignCount,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE identity_people
SET email_verified_at = coalesce(email_verified_at, $1), updated_at = $1
WHERE id = $2
`

type MarkEmailVerifiedParams struct {
	At time.Time
	ID uuid.UUID
}

func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, markEmailVerified, arg.At, arg.ID)
	return err
}

const pagePasskeysOfPerson = `-- name: PagePasskeysOfPerson :many
SELECT credential_id, name, created_at, last_used_at FROM identity_passkeys
WHERE person_id = $1
  AND (created_at, credential_id) > ($2::timestamptz, $3::bytea)
ORDER BY created_at, credential_id
LIMIT $4
`

type PagePasskeysOfPersonParams struct {
	PersonID       uuid.UUID
	AfterCreatedAt time.Time
	AfterID        []byte
	MaxRows        int32
}

type PagePasskeysOfPersonRow struct {
	CredentialID []byte
	Name         string
	CreatedAt    time.Time
	LastUsedAt   pgtype.Timestamptz
}

// Oldest first; keyset on (created_at, credential_id).
func (q *Queries) PagePasskeysOfPerson(ctx context.Context, arg PagePasskeysOfPersonParams) ([]PagePasskeysOfPersonRow, error) {
	rows, err := q.db.Query(ctx, pagePasskeysOfPerson,
		arg.PersonID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PagePasskeysOfPersonRow
	for rows.Next() {
		var i PagePasskeysOfPersonRow
		if err := rows.Scan(
			&i.CredentialID,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
INSERT INTO identity_login_attempts AS a (key, failure_count, locked_until, updated_at)
VALUES ($1, 1,
        CASE WHEN 1 >= $2::integer
             THEN $3::timestamptz + make_interval(secs => $4::double precision) END,
        $3::timestamptz)
ON CONFLICT (key) DO UPDATE
SET failure_count = CASE WHEN a.locked_until IS NOT NULL AND a.locked_until <= $3::timestamptz
                         THEN 1 ELSE a.failure_count + 1 END,
    locked_until = CASE
        WHEN (CASE WHEN a.locked_until IS NOT NULL AND a.locked_until <= $3::timestamptz
                   THEN 1 ELSE a.failure_count + 1 END) >= $2::integer
        THEN $3::timestamptz + make_interval(secs => $4::double precision)
        WHEN a.locked_until IS NOT NULL AND a.locked_until <= $3::timestamptz THEN NULL
        ELSE a.locked_until END,
    updated_at = $3::timestamptz
RETURNING failure_count, locked_until
`

type RecordLoginFailureParams struct {
	Key         string
	MaxFailures int32
	Now         time.Time
	LockSeconds float64
}

type RecordLoginFailureRow struct {
	FailureCount int32
	LockedUntil  pgtype.Timestamptz
}

// One statement, so concurrent failures can't lose increments: an expired
// lock restarts the count, and reaching max_failures sets the lock.
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure,
		arg.Key,
		arg.MaxFailures,
		arg.Now,
		arg.LockSeconds,
	)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailureCount, &i.LockedUntil)
	return i, err
}

const saveLoginAttempt = `-- name: SaveLoginAttempt :exec
INSERT INTO identity_login_attempts (key, failure_count, locked_until, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE
SET failure_count = EXCLUDED.failure_count, locked_until = EXCLUDED.locked_until, updated_at = now()
`

type SaveLoginAttemptParams struct {
	Key          string
	FailureCount int32
	LockedUntil  pgtype.Timestamptz
}

func (q *Queries) SaveLoginAttempt(ctx context.Context, arg SaveLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, saveLoginAttempt, arg.Key, arg.FailureCount, arg.LockedUntil)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE identity_people
SET password_hash = $1, updated_at = $2
WHERE id = $3
`

type SetPasswordHashParams struct {
	PasswordHash pgtype.Text
	At           time.Time
	ID           uuid.UUID
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.PasswordHash, arg.At, arg.ID)
	return err
}

const takeCeremony = `-- name: TakeCeremony :one
DELETE FROM identity_webauthn_ceremonies
WHERE key_hash = $1 AND purpose = $2
RETURNING person_id, state, expires_at
`

type TakeCeremonyParams struct {
	KeyHash string
	Purpose string
}

type TakeCeremonyRow struct {
	PersonID  uuid.NullUUID
	State     []byte
	ExpiresAt time.Time
}

// Single use: the row is gone whether or not the ceremony then succeeds.
func (q *Queries) TakeCeremony(ctx context.Context, arg TakeCeremonyParams) (TakeCeremonyRow, error) {
	row := q.db.QueryRow(ctx, takeCeremony, arg.KeyHash, arg.Purpose)
	var i TakeCeremonyRow
	err := row.Scan(&i.PersonID, &i.State, &i.ExpiresAt)
	return i, err
}

const updatePasskeySignCount = `-- name: UpdatePasskeySignCount :execrows
UPDATE identity_passkeys SET sign_count = $1, last_used_at = $2
WHERE credential_id = $3
`

type UpdatePasskeySignCountParams struct {
	SignCount    int64
	At           pgtype.Timestamptz
	CredentialID []byte
}

func (q *Queries) UpdatePasskeySignCount(ctx context.Context, arg UpdatePasskeySignCountParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasskeySignCount, arg.SignCount, arg.At, arg.CredentialID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPendingTOTP = `-- name: UpsertPendingTOTP :execrows
INSERT INTO identity_totp (person_id, secret_ciphertext, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (person_id) DO UPDATE
SET secret_ciphertext = EXCLUDED.secret_ciphertext, last_step = NULL, updated_at = EXCLUDED.updated_at
WHERE identity_totp.confirmed_at IS NULL
`

type UpsertPendingTOTPParams struct {
	PersonID         uuid.UUID
	SecretCiphertext string
	At               time.Time
}

// Replaces a pending secret; never a confirmed one.
func (q *Queries) UpsertPendingTOTP(ctx context.Context, arg UpsertPendingTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPendingTOTP, arg.PersonID, arg.SecretCiphertext, arg.At)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
