// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package identitysql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getToken = `-- name: GetToken :one
SELECT id, tenant_id, name, token_hash, hint, scopes, created_by, created_at, expires_at, last_used_at, revoked_at, revoked_by FROM identity_api_tokens WHERE id = $1
`

func (q *Queries) GetToken(ctx context.Context, id uuid.UUID) (IdentityApiToken, error) {
	row := q.db.QueryRow(ctx, getToken, id)
	var i IdentityApiToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TokenHash,
		&i.Hint,
		&i.Scopes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const insertToken = `-- name: InsertToken :execrows

INSERT INTO identity_api_tokens (id, tenant_id, name, token_hash, hint, scopes, created_by,
                                 created_at, expires_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8)
ON CONFLICT (id) DO NOTHING
`

type InsertTokenParams struct {
	ID        uuid.UUID
	Name      string
	TokenHash string
	Hint      string
	Scopes    []string
	CreatedBy string
	CreatedAt time.Time
	ExpiresAt pgtype.Timestamptz
}

// Tenant scope (db.TenantTx) unless the name starts with System.
func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.Hint,
		arg.Scopes,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTokens = `-- name: ListTokens :many
SELECT id, tenant_id, name, token_hash, hint, scopes, created_by, created_at, expires_at, last_used_at, revoked_at, revoked_by FROM identity_api_tokens
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListTokensParams struct {
	After   uuid.UUID
	MaxRows int32
}

func (q *Queries) ListTokens(ctx context.Context, arg ListTokensParams) ([]IdentityApiToken, error) {
	rows, err := q.db.Query(ctx, listTokens, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityApiToken
	for rows.Next() {
		var i IdentityApiToken
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TokenHash,
			&i.Hint,
			&i.Scopes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE identity_api_tokens
SET revoked_at = $1, revoked_by = $2
WHERE id = $3 AND revoked_at IS NULL
`

type RevokeTokenParams struct {
	RevokedAt pgtype.Timestamptz
	RevokedBy pgtype.Text
	ID        uuid.UUID
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeToken, arg.RevokedAt, arg.RevokedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const systemGetTokenByHash = `-- name: SystemGetTokenByHash :one
SELECT id, tenant_id, scopes, expires_at, revoked_at, last_used_at
FROM identity_api_tokens
WHERE token_hash = $1
`

type SystemGetTokenByHashRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Scopes     []string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) SystemGetTokenByHash(ctx context.Context, tokenHash string) (SystemGetTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, systemGetTokenByHash, tokenHash)
	var i SystemGetTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const systemTouchToken = `-- name: SystemTouchToken :exec
UPDATE identity_api_tokens SET last_used_at = $1
WHERE id = $2
  AND (last_used_at IS NULL OR last_used_at < $1::timestamptz - interval '1 minute')
`

type SystemTouchTokenParams struct {
	At pgtype.Timestamptz
	ID uuid.UUID
}

// At most one write a minute per token, however hot it is.
func (q *Queries) SystemTouchToken(ctx context.Context, arg SystemTouchTokenParams) error {
	_, err := q.db.Exec(ctx, systemTouchToken, arg.At, arg.ID)
	return err
}
