DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS translations;
DROP TABLE IF EXISTS keys;
DROP TABLE IF EXISTS locales;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS tenants;
DROP EXTENSION IF EXISTS pgcrypto;
