// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bindings.sql

package workflowsql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBinding = `-- name: DeleteBinding :execrows
DELETE FROM workflow_bindings WHERE id = $1
`

func (q *Queries) DeleteBinding(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBinding, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBindingsOfDefinition = `-- name: DeleteBindingsOfDefinition :execrows
DELETE FROM workflow_bindings WHERE definition_id = $1
`

func (q *Queries) DeleteBindingsOfDefinition(ctx context.Context, definitionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBindingsOfDefinition, definitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBinding = `-- name: GetBinding :one
SELECT id, tenant_id, project_id, subject, locales, namespace, definition_id, position, created_by, created_at FROM workflow_bindings WHERE id = $1
`

func (q *Queries) GetBinding(ctx context.Context, id uuid.UUID) (WorkflowBinding, error) {
	row := q.db.QueryRow(ctx, getBinding, id)
	var i WorkflowBinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Subject,
		&i.Locales,
		&i.Namespace,
		&i.DefinitionID,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertBinding = `-- name: InsertBinding :one

INSERT INTO workflow_bindings (id, tenant_id, project_id, subject, locales, namespace, definition_id, created_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4::text[],
        $5, $6, $7, $8)
ON CONFLICT DO NOTHING
RETURNING position
`

type InsertBindingParams struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	Subject      string
	Locales      []string
	Namespace    pgtype.Text
	DefinitionID uuid.UUID
	CreatedBy    string
	CreatedAt    time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
//
// Bindings (RFC 0006 §2.3): which definition runs for a subject. The
// precedence between them is the domain's (workflow/domain.Resolve);
// these only store and list them, in creation order.
func (q *Queries) InsertBinding(ctx context.Context, arg InsertBindingParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, insertBinding,
		arg.ID,
		arg.ProjectID,
		arg.Subject,
		arg.Locales,
		arg.Namespace,
		arg.DefinitionID,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var position pgtype.Int8
	err := row.Scan(&position)
	return position, err
}

const listBindings = `-- name: ListBindings :many
SELECT id, tenant_id, project_id, subject, locales, namespace, definition_id, position, created_by, created_at FROM workflow_bindings
WHERE project_id = $1
  AND ($2::text IS NULL OR subject = $2::text)
ORDER BY position
`

type ListBindingsParams struct {
	ProjectID uuid.UUID
	Subject   pgtype.Text
}

// A project's bindings for one subject, or for every subject, in
// creation order: the order Resolve reads "later" from.
func (q *Queries) ListBindings(ctx context.Context, arg ListBindingsParams) ([]WorkflowBinding, error) {
	rows, err := q.db.Query(ctx, listBindings, arg.ProjectID, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowBinding
	for rows.Next() {
		var i WorkflowBinding
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Subject,
			&i.Locales,
			&i.Namespace,
			&i.DefinitionID,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
