// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package workflowsql

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type WorkflowBinding struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	ProjectID    uuid.UUID
	Subject      string
	Locales      []string
	Namespace    pgtype.Text
	DefinitionID uuid.UUID
	Position     pgtype.Int8
	CreatedBy    string
	CreatedAt    time.Time
}

type WorkflowDefinition struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ProjectID uuid.NullUUID
	Name      string
	Subject   string
	Latest    int32
	CreatedBy string
	CreatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type WorkflowDefinitionVersion struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	DefinitionID uuid.UUID
	Version      int32
	Schema       string
	Document     json.RawMessage
	CreatedBy    string
	CreatedAt    time.Time
}

type WorkflowInstance struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	ProjectID    uuid.UUID
	DefinitionID uuid.UUID
	Version      int32
	SubjectKind  string
	SubjectID    uuid.UUID
	Locale       string
	State        string
	Snapshot     []byte
	Status       string
	DueAt        pgtype.Timestamptz
	OverdueAt    pgtype.Timestamptz
	TimerState   pgtype.Text
	CreatedAt    time.Time
	UpdatedAt    time.Time
	FinishedAt   pgtype.Timestamptz
}

type WorkflowTransition struct {
	TenantID      uuid.UUID
	InstanceID    uuid.UUID
	Seq           int64
	FromState     string
	Event         string
	ToState       string
	Outcome       string
	Guards        json.RawMessage
	Actions       json.RawMessage
	Actor         string
	OutboxEventID uuid.UUID
	At            time.Time
}
