// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package worksql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approvalDecisions = `-- name: ApprovalDecisions :many
SELECT tenant_id, approval_id, seq, principal, verdict, reason, decided_at FROM workflow_approval_decisions WHERE approval_id = $1 ORDER BY seq
`

func (q *Queries) ApprovalDecisions(ctx context.Context, approvalID uuid.UUID) ([]WorkflowApprovalDecision, error) {
	rows, err := q.db.Query(ctx, approvalDecisions, approvalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowApprovalDecision
	for rows.Next() {
		var i WorkflowApprovalDecision
		if err := rows.Scan(
			&i.TenantID,
			&i.ApprovalID,
			&i.Seq,
			&i.Principal,
			&i.Verdict,
			&i.Reason,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assignmentUnits = `-- name: AssignmentUnits :many
SELECT assignment_id, message_id, locale FROM workflow_assignment_units
WHERE assignment_id = ANY($1::uuid[])
ORDER BY assignment_id, message_id, locale
`

type AssignmentUnitsRow struct {
	AssignmentID uuid.UUID
	MessageID    uuid.UUID
	Locale       string
}

func (q *Queries) AssignmentUnits(ctx context.Context, assignmentIds []uuid.UUID) ([]AssignmentUnitsRow, error) {
	rows, err := q.db.Query(ctx, assignmentUnits, assignmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssignmentUnitsRow
	for rows.Next() {
		var i AssignmentUnitsRow
		if err := rows.Scan(&i.AssignmentID, &i.MessageID, &i.Locale); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coveredUnits = `-- name: CoveredUnits :many
SELECT DISTINCT u.message_id, u.locale
FROM workflow_assignments a
JOIN workflow_assignment_units u ON u.tenant_id = a.tenant_id AND u.assignment_id = a.id
WHERE a.project_id = $1
  AND a.assignee = ANY($2::text[])
  AND (a.state IN ('open', 'accepted') OR (a.state = 'done' AND a.closed_at >= $3))
  AND (NOT $4::boolean OR (u.message_id = $5 AND u.locale = $6))
ORDER BY u.message_id, u.locale
`

type CoveredUnitsParams struct {
	ProjectID uuid.UUID
	Assignees []string
	DoneSince pgtype.Timestamptz
	OneUnit   bool
	MessageID uuid.UUID
	Locale    string
}

type CoveredUnitsRow struct {
	MessageID uuid.UUID
	Locale    string
}

// The units that assignments to any of the assignees cover in a
// project: live ones, and those completed since done_since (§3.3).
func (q *Queries) CoveredUnits(ctx context.Context, arg CoveredUnitsParams) ([]CoveredUnitsRow, error) {
	rows, err := q.db.Query(ctx, coveredUnits,
		arg.ProjectID,
		arg.Assignees,
		arg.DoneSince,
		arg.OneUnit,
		arg.MessageID,
		arg.Locale,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoveredUnitsRow
	for rows.Next() {
		var i CoveredUnitsRow
		if err := rows.Scan(&i.MessageID, &i.Locale); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApproval = `-- name: GetApproval :one
SELECT id, tenant_id, project_id, instance_id, subject_kind, subject_id, locale, required, eligible, distinct_from_author, due_at, state, version, created_by, created_at, closed_at FROM workflow_approvals WHERE id = $1
`

func (q *Queries) GetApproval(ctx context.Context, id uuid.UUID) (WorkflowApproval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i WorkflowApproval
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.InstanceID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Locale,
		&i.Required,
		&i.Eligible,
		&i.DistinctFromAuthor,
		&i.DueAt,
		&i.State,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, tenant_id, project_id, instance_id, assignee, permission, due_at, state, version, created_by, created_at, updated_at, closed_by, closed_at, reason FROM workflow_assignments WHERE id = $1
`

func (q *Queries) GetAssignment(ctx context.Context, id uuid.UUID) (WorkflowAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i WorkflowAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.InstanceID,
		&i.Assignee,
		&i.Permission,
		&i.DueAt,
		&i.State,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.Reason,
	)
	return i, err
}

const insertApproval = `-- name: InsertApproval :exec

INSERT INTO workflow_approvals (id, tenant_id, project_id, instance_id, subject_kind, subject_id, locale, required,
                                eligible, distinct_from_author, due_at, state, version, created_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12,
        $13, $14)
`

type InsertApprovalParams struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	InstanceID         uuid.NullUUID
	SubjectKind        string
	SubjectID          uuid.UUID
	Locale             string
	Required           int32
	Eligible           string
	DistinctFromAuthor bool
	DueAt              pgtype.Timestamptz
	State              string
	Version            int32
	CreatedBy          string
	CreatedAt          time.Time
}

// ── approvals ───────────────────────────────────────────────────────
func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) error {
	_, err := q.db.Exec(ctx, insertApproval,
		arg.ID,
		arg.ProjectID,
		arg.InstanceID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Locale,
		arg.Required,
		arg.Eligible,
		arg.DistinctFromAuthor,
		arg.DueAt,
		arg.State,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertAssignment = `-- name: InsertAssignment :exec


INSERT INTO workflow_assignments (id, tenant_id, project_id, instance_id, assignee, permission, due_at, state,
                                  version, created_by, created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $9,
        $10, $10)
`

type InsertAssignmentParams struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	InstanceID uuid.NullUUID
	Assignee   string
	Permission string
	DueAt      pgtype.Timestamptz
	State      string
	Version    int32
	CreatedBy  string
	CreatedAt  time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
//
// Assignments and approvals (RFC 0006 §3.1–3.2, migration 0044).
// ── assignments ─────────────────────────────────────────────────────
func (q *Queries) InsertAssignment(ctx context.Context, arg InsertAssignmentParams) error {
	_, err := q.db.Exec(ctx, insertAssignment,
		arg.ID,
		arg.ProjectID,
		arg.InstanceID,
		arg.Assignee,
		arg.Permission,
		arg.DueAt,
		arg.State,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertAssignmentUnits = `-- name: InsertAssignmentUnits :exec
INSERT INTO workflow_assignment_units (tenant_id, assignment_id, message_id, locale)
SELECT app_current_tenant(), $1, u.message_id, u.locale
FROM (SELECT unnest($2::uuid[]) AS message_id, unnest($3::text[]) AS locale) AS u
`

type InsertAssignmentUnitsParams struct {
	AssignmentID uuid.UUID
	MessageIds   []uuid.UUID
	Locales      []string
}

func (q *Queries) InsertAssignmentUnits(ctx context.Context, arg InsertAssignmentUnitsParams) error {
	_, err := q.db.Exec(ctx, insertAssignmentUnits, arg.AssignmentID, arg.MessageIds, arg.Locales)
	return err
}

const insertDecision = `-- name: InsertDecision :exec
INSERT INTO workflow_approval_decisions (tenant_id, approval_id, seq, principal, verdict, reason, decided_at)
VALUES (app_current_tenant(), $1, $2, $3, $4,
        $5, $6)
`

type InsertDecisionParams struct {
	ApprovalID uuid.UUID
	Seq        int32
	Principal  string
	Verdict    string
	Reason     string
	DecidedAt  time.Time
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) error {
	_, err := q.db.Exec(ctx, insertDecision,
		arg.ApprovalID,
		arg.Seq,
		arg.Principal,
		arg.Verdict,
		arg.Reason,
		arg.DecidedAt,
	)
	return err
}

const latestApproval = `-- name: LatestApproval :one
SELECT id, tenant_id, project_id, instance_id, subject_kind, subject_id, locale, required, eligible, distinct_from_author, due_at, state, version, created_by, created_at, closed_at FROM workflow_approvals
WHERE project_id = $1 AND subject_kind = $2
  AND subject_id = $3 AND locale = $4
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type LatestApprovalParams struct {
	ProjectID   uuid.UUID
	SubjectKind string
	SubjectID   uuid.UUID
	Locale      string
}

func (q *Queries) LatestApproval(ctx context.Context, arg LatestApprovalParams) (WorkflowApproval, error) {
	row := q.db.QueryRow(ctx, latestApproval,
		arg.ProjectID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Locale,
	)
	var i WorkflowApproval
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.InstanceID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Locale,
		&i.Required,
		&i.Eligible,
		&i.DistinctFromAuthor,
		&i.DueAt,
		&i.State,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listAssignments = `-- name: ListAssignments :many
SELECT id, tenant_id, project_id, instance_id, assignee, permission, due_at, state, version, created_by, created_at, updated_at, closed_by, closed_at, reason FROM workflow_assignments
WHERE id > $1
  AND ($2::uuid = '00000000-0000-0000-0000-000000000000' OR project_id = $2)
  AND (cardinality($3::text[]) = 0 OR state = ANY($3::text[]))
  AND (NOT $4::boolean OR assignee = ANY($5::text[]))
ORDER BY id
LIMIT $6
`

type ListAssignmentsParams struct {
	After      uuid.UUID
	ProjectID  uuid.UUID
	States     []string
	ByAssignee bool
	Assignees  []string
	MaxRows    int32
}

func (q *Queries) ListAssignments(ctx context.Context, arg ListAssignmentsParams) ([]WorkflowAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignments,
		arg.After,
		arg.ProjectID,
		arg.States,
		arg.ByAssignee,
		arg.Assignees,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowAssignment
	for rows.Next() {
		var i WorkflowAssignment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.InstanceID,
			&i.Assignee,
			&i.Permission,
			&i.DueAt,
			&i.State,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApproval = `-- name: LockApproval :one
SELECT id, tenant_id, project_id, instance_id, subject_kind, subject_id, locale, required, eligible, distinct_from_author, due_at, state, version, created_by, created_at, closed_at FROM workflow_approvals WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockApproval(ctx context.Context, id uuid.UUID) (WorkflowApproval, error) {
	row := q.db.QueryRow(ctx, lockApproval, id)
	var i WorkflowApproval
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.InstanceID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Locale,
		&i.Required,
		&i.Eligible,
		&i.DistinctFromAuthor,
		&i.DueAt,
		&i.State,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const lockAssignment = `-- name: LockAssignment :one
SELECT id, tenant_id, project_id, instance_id, assignee, permission, due_at, state, version, created_by, created_at, updated_at, closed_by, closed_at, reason FROM workflow_assignments WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAssignment(ctx context.Context, id uuid.UUID) (WorkflowAssignment, error) {
	row := q.db.QueryRow(ctx, lockAssignment, id)
	var i WorkflowAssignment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.InstanceID,
		&i.Assignee,
		&i.Permission,
		&i.DueAt,
		&i.State,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.Reason,
	)
	return i, err
}

const updateApproval = `-- name: UpdateApproval :execrows
UPDATE workflow_approvals
SET state = $1, version = $2, closed_at = $3
WHERE id = $4 AND version = $2 - 1
`

type UpdateApprovalParams struct {
	State    string
	Version  int32
	ClosedAt pgtype.Timestamptz
	ID       uuid.UUID
}

func (q *Queries) UpdateApproval(ctx context.Context, arg UpdateApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateApproval,
		arg.State,
		arg.Version,
		arg.ClosedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAssignment = `-- name: UpdateAssignment :execrows
UPDATE workflow_assignments
SET state = $1, version = $2, updated_at = $3,
    closed_by = $4, closed_at = $5, reason = $6
WHERE id = $7 AND version = $2 - 1
`

type UpdateAssignmentParams struct {
	State     string
	Version   int32
	UpdatedAt time.Time
	ClosedBy  pgtype.Text
	ClosedAt  pgtype.Timestamptz
	Reason    string
	ID        uuid.UUID
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAssignment,
		arg.State,
		arg.Version,
		arg.UpdatedAt,
		arg.ClosedBy,
		arg.ClosedAt,
		arg.Reason,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
