// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: check_runs.sql

package qualitysql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCheckRun = `-- name: GetCheckRun :one
SELECT id, tenant_id, project_id, ref, trigger, policy_version, layers, errors, warnings, waived, conclusion, created_by, started_at, completed_at, commit_sha FROM quality_check_runs WHERE project_id = $1 AND id = $2
`

type GetCheckRunParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetCheckRun(ctx context.Context, arg GetCheckRunParams) (QualityCheckRun, error) {
	row := q.db.QueryRow(ctx, getCheckRun, arg.ProjectID, arg.ID)
	var i QualityCheckRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Ref,
		&i.Trigger,
		&i.PolicyVersion,
		&i.Layers,
		&i.Errors,
		&i.Warnings,
		&i.Waived,
		&i.Conclusion,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CommitSha,
	)
	return i, err
}

const hasCheckRunOf = `-- name: HasCheckRunOf :one
SELECT EXISTS (
    SELECT 1 FROM quality_check_runs
    WHERE project_id = $1
      AND trigger = ANY ($2::text[])
) AS found
`

type HasCheckRunOfParams struct {
	ProjectID   uuid.UUID
	RunTriggers []string
}

// Whether the project has any run by one of these triggers: what the
// pull-request check asks to learn that a repository's CI runs `glossa
// check` (RFC 0005 §14 decision 11). EXISTS stops at the first matching
// row, and the project_id prefix of quality_check_runs_ref bounds the
// walk to this project's runs within retention.
func (q *Queries) HasCheckRunOf(ctx context.Context, arg HasCheckRunOfParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasCheckRunOf, arg.ProjectID, arg.RunTriggers)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const insertCheckRun = `-- name: InsertCheckRun :exec

INSERT INTO quality_check_runs (id, tenant_id, project_id, ref, commit_sha, trigger, policy_version, layers,
                                errors, warnings, waived, conclusion, created_by, started_at, completed_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7::text[], $8,
        $9, $10, $11, $12, $13,
        $14)
`

type InsertCheckRunParams struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	Ref           string
	CommitSha     string
	RunTrigger    string
	PolicyVersion int32
	Layers        []string
	Errors        int32
	Warnings      int32
	Waived        int32
	Conclusion    pgtype.Text
	CreatedBy     string
	StartedAt     time.Time
	CompletedAt   pgtype.Timestamptz
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
//
// A check run is one evaluation of one ref against one policy version
// (RFC 0005 §2.2 rule 3). Every surface reads the stored run rather than
// recomputing it, so these queries are the only place a run is written.
// A run and its verdict, written once. The counts are what the run
// concluded, with the waivers that were live while it graded; nothing
// rewrites them afterwards, because a verdict is history.
func (q *Queries) InsertCheckRun(ctx context.Context, arg InsertCheckRunParams) error {
	_, err := q.db.Exec(ctx, insertCheckRun,
		arg.ID,
		arg.ProjectID,
		arg.Ref,
		arg.CommitSha,
		arg.RunTrigger,
		arg.PolicyVersion,
		arg.Layers,
		arg.Errors,
		arg.Warnings,
		arg.Waived,
		arg.Conclusion,
		arg.CreatedBy,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const latestCheckRun = `-- name: LatestCheckRun :one
SELECT id, tenant_id, project_id, ref, trigger, policy_version, layers, errors, warnings, waived, conclusion, created_by, started_at, completed_at, commit_sha FROM quality_check_runs
WHERE project_id = $1
  AND ($2::text = '' OR ref = $2::text)
  AND ($3::text = '' OR commit_sha = $3::text)
  AND ($4::text = '' OR conclusion = $4::text)
  AND ($5::text = '' OR trigger = $5::text)
ORDER BY started_at DESC, id DESC
LIMIT 1
`

type LatestCheckRunParams struct {
	ProjectID  uuid.UUID
	Ref        string
	CommitSha  string
	Conclusion string
	RunTrigger string
}

// The newest run matching the same filters: what a findings list reads
// when the caller names a branch or a commit instead of a run.
func (q *Queries) LatestCheckRun(ctx context.Context, arg LatestCheckRunParams) (QualityCheckRun, error) {
	row := q.db.QueryRow(ctx, latestCheckRun,
		arg.ProjectID,
		arg.Ref,
		arg.CommitSha,
		arg.Conclusion,
		arg.RunTrigger,
	)
	var i QualityCheckRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Ref,
		&i.Trigger,
		&i.PolicyVersion,
		&i.Layers,
		&i.Errors,
		&i.Warnings,
		&i.Waived,
		&i.Conclusion,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CommitSha,
	)
	return i, err
}

const listCheckRuns = `-- name: ListCheckRuns :many
SELECT id, tenant_id, project_id, ref, trigger, policy_version, layers, errors, warnings, waived, conclusion, created_by, started_at, completed_at, commit_sha FROM quality_check_runs
WHERE project_id = $1
  AND ($2::text = '' OR ref = $2::text)
  AND ($3::text = '' OR commit_sha = $3::text)
  AND ($4::text = '' OR conclusion = $4::text)
  AND ($5::text = '' OR trigger = $5::text)
  AND ($6::timestamptz IS NULL
       OR (started_at, id) < ($6::timestamptz, $7::uuid))
ORDER BY started_at DESC, id DESC
LIMIT $8
`

type ListCheckRunsParams struct {
	ProjectID      uuid.UUID
	Ref            string
	CommitSha      string
	Conclusion     string
	RunTrigger     string
	AfterStartedAt pgtype.Timestamptz
	AfterID        uuid.NullUUID
	MaxRows        int32
}

// A page of a project's runs, newest first, narrowed by ref (a branch or
// an environment), commit and conclusion. An empty filter matches
// everything, so the three combine.
func (q *Queries) ListCheckRuns(ctx context.Context, arg ListCheckRunsParams) ([]QualityCheckRun, error) {
	rows, err := q.db.Query(ctx, listCheckRuns,
		arg.ProjectID,
		arg.Ref,
		arg.CommitSha,
		arg.Conclusion,
		arg.RunTrigger,
		arg.AfterStartedAt,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityCheckRun
	for rows.Next() {
		var i QualityCheckRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Ref,
			&i.Trigger,
			&i.PolicyVersion,
			&i.Layers,
			&i.Errors,
			&i.Warnings,
			&i.Waived,
			&i.Conclusion,
			&i.CreatedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
