// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package qualitysql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const latestRun = `-- name: LatestRun :one
SELECT id, ref, trigger, policy_version, layers, errors, warnings, waived,
       conclusion, created_by, started_at, completed_at
FROM quality_check_runs
WHERE project_id = $1
  AND ($2::text = '' OR ref = $2::text)
  AND (NOT $3::boolean OR completed_at IS NOT NULL)
ORDER BY started_at DESC, id DESC
LIMIT 1
`

type LatestRunParams struct {
	ProjectID     uuid.UUID
	Ref           string
	CompletedOnly bool
}

type LatestRunRow struct {
	ID            uuid.UUID
	Ref           string
	Trigger       string
	PolicyVersion int32
	Layers        []string
	Errors        int32
	Warnings      int32
	Waived        int32
	Conclusion    pgtype.Text
	CreatedBy     string
	StartedAt     time.Time
	CompletedAt   pgtype.Timestamptz
}

// The latest run of a ref, or of the project when ref is empty: what
// every surface reads (migration 0027, quality_check_runs_ref).
func (q *Queries) LatestRun(ctx context.Context, arg LatestRunParams) (LatestRunRow, error) {
	row := q.db.QueryRow(ctx, latestRun, arg.ProjectID, arg.Ref, arg.CompletedOnly)
	var i LatestRunRow
	err := row.Scan(
		&i.ID,
		&i.Ref,
		&i.Trigger,
		&i.PolicyVersion,
		&i.Layers,
		&i.Errors,
		&i.Warnings,
		&i.Waived,
		&i.Conclusion,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const runFindings = `-- name: RunFindings :many
SELECT id, fingerprint, layer, code, severity, message_id, message_key, locale,
       namespace, file, line, col, route, component, capture_id, region,
       span_side, span_start, span_end, explanation, subject, detail,
       source_revision, waiver_id
FROM quality_findings
WHERE run_id = $1
  AND ($2::text = '' OR layer = $2::text)
  AND ($3::text = '' OR locale = $3::text)
  AND ($4::text = '' OR severity = $4::text)
  AND ($5::text = '' OR message_key = $5::text)
  AND (NOT $6::boolean OR severity = 'waived')
  AND ($7::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR id > $7::uuid)
ORDER BY id
LIMIT $8::integer
`

type RunFindingsParams struct {
	RunID      uuid.UUID
	Layer      string
	Locale     string
	Severity   string
	MessageKey string
	WaivedOnly bool
	After      uuid.UUID
	RowLimit   int32
}

type RunFindingsRow struct {
	ID             uuid.UUID
	Fingerprint    string
	Layer          string
	Code           string
	Severity       string
	MessageID      uuid.NullUUID
	MessageKey     string
	Locale         string
	Namespace      string
	File           string
	Line           pgtype.Int4
	Col            pgtype.Int4
	Route          string
	Component      string
	CaptureID      uuid.NullUUID
	Region         string
	SpanSide       pgtype.Text
	SpanStart      pgtype.Int4
	SpanEnd        pgtype.Int4
	Explanation    string
	Subject        string
	Detail         string
	SourceRevision pgtype.Int4
	WaiverID       uuid.NullUUID
}

// One run's findings, filtered and keyset-paginated on the finding id.
func (q *Queries) RunFindings(ctx context.Context, arg RunFindingsParams) ([]RunFindingsRow, error) {
	rows, err := q.db.Query(ctx, runFindings,
		arg.RunID,
		arg.Layer,
		arg.Locale,
		arg.Severity,
		arg.MessageKey,
		arg.WaivedOnly,
		arg.After,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunFindingsRow
	for rows.Next() {
		var i RunFindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Layer,
			&i.Code,
			&i.Severity,
			&i.MessageID,
			&i.MessageKey,
			&i.Locale,
			&i.Namespace,
			&i.File,
			&i.Line,
			&i.Col,
			&i.Route,
			&i.Component,
			&i.CaptureID,
			&i.Region,
			&i.SpanSide,
			&i.SpanStart,
			&i.SpanEnd,
			&i.Explanation,
			&i.Subject,
			&i.Detail,
			&i.SourceRevision,
			&i.WaiverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
