// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: linguistic_jobs.sql

package qualitysql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLinguisticJob = `-- name: GetLinguisticJob :one
SELECT id, tenant_id, project_id, ref, scope, state, batch, check_run_id, findings, skipped_sensitive, reviewed, failure_code, last_error, created_by, created_at, updated_at, started_at, finished_at FROM quality_linguistic_jobs
WHERE project_id = $1 AND id = $2
`

type GetLinguisticJobParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetLinguisticJob(ctx context.Context, arg GetLinguisticJobParams) (QualityLinguisticJob, error) {
	row := q.db.QueryRow(ctx, getLinguisticJob, arg.ProjectID, arg.ID)
	var i QualityLinguisticJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Ref,
		&i.Scope,
		&i.State,
		&i.Batch,
		&i.CheckRunID,
		&i.Findings,
		&i.SkippedSensitive,
		&i.Reviewed,
		&i.FailureCode,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertLinguisticJob = `-- name: InsertLinguisticJob :exec

INSERT INTO quality_linguistic_jobs (id, tenant_id, project_id, ref, scope, state, batch, created_by,
                                     created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $8)
`

type InsertLinguisticJobParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Ref       string
	Scope     json.RawMessage
	State     string
	Batch     string
	CreatedBy string
	CreatedAt time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
//
// Linguistic-QA jobs (RFC 0005 §3.8, migration 0038). The linguistic
// layer is the one layer that needs a model, so it is a job and never a
// check; these rows are that job's life.
func (q *Queries) InsertLinguisticJob(ctx context.Context, arg InsertLinguisticJobParams) error {
	_, err := q.db.Exec(ctx, insertLinguisticJob,
		arg.ID,
		arg.ProjectID,
		arg.Ref,
		arg.Scope,
		arg.State,
		arg.Batch,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listLinguisticJobs = `-- name: ListLinguisticJobs :many
SELECT id, tenant_id, project_id, ref, scope, state, batch, check_run_id, findings, skipped_sensitive, reviewed, failure_code, last_error, created_by, created_at, updated_at, started_at, finished_at FROM quality_linguistic_jobs
WHERE project_id = $1
  AND ($2::text IS NULL OR state = $2::text)
  AND (
      $3::timestamptz IS NULL
      OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListLinguisticJobsParams struct {
	ProjectID uuid.UUID
	State     pgtype.Text
	AfterAt   pgtype.Timestamptz
	AfterID   uuid.NullUUID
	MaxRows   int32
}

// A page of a project's jobs, newest first. The cursor is (created_at,
// id), as every other newest-first page in the platform is.
func (q *Queries) ListLinguisticJobs(ctx context.Context, arg ListLinguisticJobsParams) ([]QualityLinguisticJob, error) {
	rows, err := q.db.Query(ctx, listLinguisticJobs,
		arg.ProjectID,
		arg.State,
		arg.AfterAt,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityLinguisticJob
	for rows.Next() {
		var i QualityLinguisticJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Ref,
			&i.Scope,
			&i.State,
			&i.Batch,
			&i.CheckRunID,
			&i.Findings,
			&i.SkippedSensitive,
			&i.Reviewed,
			&i.FailureCode,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLinguisticJob = `-- name: UpdateLinguisticJob :execrows
UPDATE quality_linguistic_jobs
SET state             = $1,
    batch             = $2,
    check_run_id      = $3,
    findings          = $4,
    skipped_sensitive = $5,
    reviewed          = $6,
    failure_code      = $7,
    last_error        = $8,
    updated_at        = $9,
    started_at        = $10,
    finished_at       = $11
WHERE project_id = $12 AND id = $13
  AND state IN ('queued', 'running')
`

type UpdateLinguisticJobParams struct {
	State            string
	Batch            string
	CheckRunID       uuid.NullUUID
	Findings         int32
	SkippedSensitive int32
	Reviewed         int32
	FailureCode      string
	LastError        string
	UpdatedAt        time.Time
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	ProjectID        uuid.UUID
	ID               uuid.UUID
}

// The job's progress. `state` is guarded: a job that has already
// finished is never moved again, so a late poll of a cancelled job
// cannot resurrect it, and two readers reconciling the same job settle
// it once.
func (q *Queries) UpdateLinguisticJob(ctx context.Context, arg UpdateLinguisticJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLinguisticJob,
		arg.State,
		arg.Batch,
		arg.CheckRunID,
		arg.Findings,
		arg.SkippedSensitive,
		arg.Reviewed,
		arg.FailureCode,
		arg.LastError,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
