// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy_versions.sql

package qualitysql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPolicyVersion = `-- name: GetPolicyVersion :one
SELECT id, tenant_id, project_id, version, document, created_by, created_at FROM quality_policy_versions
WHERE project_id = $1 AND version = $2
`

type GetPolicyVersionParams struct {
	ProjectID uuid.UUID
	Version   int32
}

func (q *Queries) GetPolicyVersion(ctx context.Context, arg GetPolicyVersionParams) (QualityPolicyVersion, error) {
	row := q.db.QueryRow(ctx, getPolicyVersion, arg.ProjectID, arg.Version)
	var i QualityPolicyVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Version,
		&i.Document,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertPolicyVersion = `-- name: InsertPolicyVersion :execrows

INSERT INTO quality_policy_versions (id, tenant_id, project_id, version, document, created_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6)
ON CONFLICT (project_id, version) DO NOTHING
`

type InsertPolicyVersionParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Version   int32
	Document  json.RawMessage
	CreatedBy string
	CreatedAt time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
//
// The check policy's version history (RFC 0005 §4.3). The live document
// is Catalog's (settings.check_policy); this is the record of how it got
// there — one append-only row per saved version, with who wrote it and
// when. Nothing updates a row: a version is history.
// One saved version. The unique index on (project_id, version) is what
// makes the version monotonic under concurrency: two saves racing for
// the same number cannot both land, and the loser is told to read the
// policy again rather than silently overwriting the winner.
func (q *Queries) InsertPolicyVersion(ctx context.Context, arg InsertPolicyVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolicyVersion,
		arg.ID,
		arg.ProjectID,
		arg.Version,
		arg.Document,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPolicyVersions = `-- name: ListPolicyVersions :many
SELECT id, tenant_id, project_id, version, document, created_by, created_at FROM quality_policy_versions
WHERE project_id = $1
  AND ($2::integer IS NULL OR version < $2::integer)
ORDER BY version DESC
LIMIT $3
`

type ListPolicyVersionsParams struct {
	ProjectID    uuid.UUID
	AfterVersion pgtype.Int4
	MaxRows      int32
}

// A page of a project's policy versions, newest first. The cursor is
// the version itself: it is monotonic and unique per project, so it
// needs no tiebreaker.
func (q *Queries) ListPolicyVersions(ctx context.Context, arg ListPolicyVersionsParams) ([]QualityPolicyVersion, error) {
	rows, err := q.db.Query(ctx, listPolicyVersions, arg.ProjectID, arg.AfterVersion, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityPolicyVersion
	for rows.Next() {
		var i QualityPolicyVersion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Version,
			&i.Document,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
