// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waivers.sql

package qualitysql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWaiver = `-- name: GetWaiver :one
SELECT id, tenant_id, project_id, fingerprint, reason, scope, ref, source_revision, created_by, created_at, expires_at, revoked_at FROM quality_waivers WHERE project_id = $1 AND id = $2
`

type GetWaiverParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetWaiver(ctx context.Context, arg GetWaiverParams) (QualityWaiver, error) {
	row := q.db.QueryRow(ctx, getWaiver, arg.ProjectID, arg.ID)
	var i QualityWaiver
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Fingerprint,
		&i.Reason,
		&i.Scope,
		&i.Ref,
		&i.SourceRevision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listLiveWaivers = `-- name: ListLiveWaivers :many
SELECT id, tenant_id, project_id, fingerprint, reason, scope, ref, source_revision, created_by, created_at, expires_at, revoked_at FROM quality_waivers
WHERE project_id = $1 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > $2::timestamptz)
`

type ListLiveWaiversParams struct {
	ProjectID uuid.UUID
	Now       time.Time
}

// Every waiver that stands now, for grading a run as it is recorded.
func (q *Queries) ListLiveWaivers(ctx context.Context, arg ListLiveWaiversParams) ([]QualityWaiver, error) {
	rows, err := q.db.Query(ctx, listLiveWaivers, arg.ProjectID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityWaiver
	for rows.Next() {
		var i QualityWaiver
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Fingerprint,
			&i.Reason,
			&i.Scope,
			&i.Ref,
			&i.SourceRevision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaivers = `-- name: ListWaivers :many
SELECT w.id, w.tenant_id, w.project_id, w.fingerprint, w.reason, w.scope, w.ref, w.source_revision, w.created_by, w.created_at, w.expires_at, w.revoked_at, coalesce(f.layer, '') AS finding_layer, coalesce(f.code, '') AS finding_code,
       coalesce(f.locale, '') AS finding_locale, coalesce(f.message_key, '') AS finding_message_key,
       coalesce(f.namespace, '') AS finding_namespace, coalesce(f.explanation, '') AS finding_explanation
FROM quality_waivers w
LEFT JOIN LATERAL (
    SELECT f.layer, f.code, f.locale, f.message_key, f.namespace, f.explanation
    FROM quality_findings f
    WHERE f.project_id = w.project_id AND f.fingerprint = w.fingerprint
    ORDER BY f.run_id DESC
    LIMIT 1
) f ON true
WHERE w.project_id = $1
  AND ($2::text = '' OR w.fingerprint = $2::text)
  AND ($3::text = '' OR f.layer = $3::text)
  AND ($4::text = '' OR f.code = $4::text)
  AND ($5::text = '' OR f.message_key = $5::text)
  AND ($6::boolean IS NULL
       OR (w.revoked_at IS NULL AND (w.expires_at IS NULL OR w.expires_at > $7::timestamptz))
          = $6::boolean)
  AND ($8::timestamptz IS NULL
       OR (w.created_at, w.id) < ($8::timestamptz, $9::uuid))
ORDER BY w.created_at DESC, w.id DESC
LIMIT $10
`

type ListWaiversParams struct {
	ProjectID      uuid.UUID
	Fingerprint    string
	Layer          string
	Code           string
	MessageKey     string
	Active         pgtype.Bool
	Now            time.Time
	AfterCreatedAt pgtype.Timestamptz
	AfterID        uuid.NullUUID
	MaxRows        int32
}

type ListWaiversRow struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	ProjectID          uuid.UUID
	Fingerprint        string
	Reason             string
	Scope              string
	Ref                string
	SourceRevision     int32
	CreatedBy          string
	CreatedAt          time.Time
	ExpiresAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
	FindingLayer       string
	FindingCode        string
	FindingLocale      string
	FindingMessageKey  string
	FindingNamespace   string
	FindingExplanation string
}

// A page of a project's waivers, newest first, each with what it
// accepts: the layer, code, locale and message of the most recent
// finding carrying its fingerprint (run ids are time-ordered UUIDv7).
// A waiver whose finding no longer occurs anywhere still lists, with
// those fields empty — it is exactly the unexamined waiver a dashboard
// should show.
func (q *Queries) ListWaivers(ctx context.Context, arg ListWaiversParams) ([]ListWaiversRow, error) {
	rows, err := q.db.Query(ctx, listWaivers,
		arg.ProjectID,
		arg.Fingerprint,
		arg.Layer,
		arg.Code,
		arg.MessageKey,
		arg.Active,
		arg.Now,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWaiversRow
	for rows.Next() {
		var i ListWaiversRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Fingerprint,
			&i.Reason,
			&i.Scope,
			&i.Ref,
			&i.SourceRevision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.FindingLayer,
			&i.FindingCode,
			&i.FindingLocale,
			&i.FindingMessageKey,
			&i.FindingNamespace,
			&i.FindingExplanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWaiver = `-- name: RevokeWaiver :execrows
UPDATE quality_waivers SET revoked_at = $1
WHERE project_id = $2 AND id = $3 AND revoked_at IS NULL
`

type RevokeWaiverParams struct {
	RevokedAt pgtype.Timestamptz
	ProjectID uuid.UUID
	ID        uuid.UUID
}

// Revoking is idempotent: a waiver already taken back matches nothing
// and the caller answers 204 all the same.
func (q *Queries) RevokeWaiver(ctx context.Context, arg RevokeWaiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeWaiver, arg.RevokedAt, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWaiver = `-- name: UpsertWaiver :one

INSERT INTO quality_waivers (id, tenant_id, project_id, fingerprint, reason, scope, ref, source_revision,
                             created_by, created_at, expires_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $9,
        $10)
ON CONFLICT (project_id, fingerprint, scope, ref) WHERE revoked_at IS NULL
DO UPDATE SET reason = EXCLUDED.reason, source_revision = EXCLUDED.source_revision,
              expires_at = EXCLUDED.expires_at, created_by = EXCLUDED.created_by
RETURNING id, tenant_id, project_id, fingerprint, reason, scope, ref, source_revision, created_by, created_at, expires_at, revoked_at, (xmax = 0) AS inserted
`

type UpsertWaiverParams struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Fingerprint    string
	Reason         string
	Scope          string
	Ref            string
	SourceRevision int32
	CreatedBy      string
	CreatedAt      time.Time
	ExpiresAt      pgtype.Timestamptz
}

type UpsertWaiverRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ProjectID      uuid.UUID
	Fingerprint    string
	Reason         string
	Scope          string
	Ref            string
	SourceRevision int32
	CreatedBy      string
	CreatedAt      time.Time
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	Inserted       bool
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
//
// A waiver accepts a finding by its fingerprint, with a reason that the
// column, the domain and the API all require (RFC 0005 §2.3). It never
// deletes anything: the finding it accepts is still computed, still
// listed and still counted, at severity `waived`.
// Waiving a finding a second time is not a second waiver: the partial
// unique index allows one live waiver per fingerprint and reach, so a
// repeat restates the reason, the expiry and the source revision it is
// made against. Revoking frees the slot, and the revoked row stays as
// history.
func (q *Queries) UpsertWaiver(ctx context.Context, arg UpsertWaiverParams) (UpsertWaiverRow, error) {
	row := q.db.QueryRow(ctx, upsertWaiver,
		arg.ID,
		arg.ProjectID,
		arg.Fingerprint,
		arg.Reason,
		arg.Scope,
		arg.Ref,
		arg.SourceRevision,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i UpsertWaiverRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Fingerprint,
		&i.Reason,
		&i.Scope,
		&i.Ref,
		&i.SourceRevision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Inserted,
	)
	return i, err
}
