// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogsql

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogApplication struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	Slug      string
	Name      string
	Platform  string
	Version   int32
	CreatedBy string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CatalogMessage struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ProjectID      uuid.UUID
	Key            string
	Namespace      string
	Description    string
	MaxLength      pgtype.Int4
	State          string
	SourceSyntax   string
	SourceText     string
	SourceModel    json.RawMessage
	Arguments      json.RawMessage
	Markup         json.RawMessage
	SourceRevision int32
	Version        int32
	CreatedBy      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CatalogProject struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Slug         string
	Name         string
	SourceLocale string
	Settings     json.RawMessage
	Version      int32
	CreatedBy    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CatalogSourceRevision struct {
	TenantID  uuid.UUID
	MessageID uuid.UUID
	Revision  int32
	Syntax    string
	Text      string
	Model     json.RawMessage
	Author    string
	CreatedAt time.Time
}
