// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package catalogsql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteApplication = `-- name: DeleteApplication :execrows
DELETE FROM catalog_applications WHERE project_id = $1 AND id = $2
`

type DeleteApplicationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplication, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM catalog_projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplication = `-- name: GetApplication :one
SELECT id, tenant_id, project_id, slug, name, platform, version, created_by, created_at, updated_at FROM catalog_applications WHERE project_id = $1 AND id = $2
`

type GetApplicationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetApplication(ctx context.Context, arg GetApplicationParams) (CatalogApplication, error) {
	row := q.db.QueryRow(ctx, getApplication, arg.ProjectID, arg.ID)
	var i CatalogApplication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Platform,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, slug, name, source_locale, settings, version, created_by, created_at, updated_at FROM catalog_projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (CatalogProject, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i CatalogProject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.SourceLocale,
		&i.Settings,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertApplication = `-- name: InsertApplication :execrows
INSERT INTO catalog_applications (id, tenant_id, project_id, slug, name, platform, version,
                                  created_by, created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $8)
ON CONFLICT (id) DO NOTHING
`

type InsertApplicationParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Slug      string
	Name      string
	Platform  string
	Version   int32
	CreatedBy string
	CreatedAt time.Time
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertApplication,
		arg.ID,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
		arg.Platform,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertProject = `-- name: InsertProject :execrows

INSERT INTO catalog_projects (id, tenant_id, slug, name, source_locale, settings, version,
                              created_by, created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $8)
ON CONFLICT (id) DO NOTHING
`

type InsertProjectParams struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	SourceLocale string
	Settings     json.RawMessage
	Version      int32
	CreatedBy    string
	CreatedAt    time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant, so none of these filter on tenant_id.
// ON CONFLICT (id) makes a retried idempotent create a no-op; a slug
// clash still fails on the (tenant_id, slug) constraint.
func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertProject,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.SourceLocale,
		arg.Settings,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listApplications = `-- name: ListApplications :many
SELECT id, tenant_id, project_id, slug, name, platform, version, created_by, created_at, updated_at FROM catalog_applications
WHERE project_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListApplicationsParams struct {
	ProjectID uuid.UUID
	After     uuid.UUID
	MaxRows   int32
}

func (q *Queries) ListApplications(ctx context.Context, arg ListApplicationsParams) ([]CatalogApplication, error) {
	rows, err := q.db.Query(ctx, listApplications, arg.ProjectID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogApplication
	for rows.Next() {
		var i CatalogApplication
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.Platform,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, tenant_id, slug, name, source_locale, settings, version, created_by, created_at, updated_at FROM catalog_projects
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListProjectsParams struct {
	After   uuid.UUID
	MaxRows int32
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]CatalogProject, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogProject
	for rows.Next() {
		var i CatalogProject
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.SourceLocale,
			&i.Settings,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApplication = `-- name: LockApplication :one
SELECT id, tenant_id, project_id, slug, name, platform, version, created_by, created_at, updated_at FROM catalog_applications
WHERE project_id = $1 AND id = $2
FOR UPDATE
`

type LockApplicationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) LockApplication(ctx context.Context, arg LockApplicationParams) (CatalogApplication, error) {
	row := q.db.QueryRow(ctx, lockApplication, arg.ProjectID, arg.ID)
	var i CatalogApplication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Platform,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockProject = `-- name: LockProject :one
SELECT id, tenant_id, slug, name, source_locale, settings, version, created_by, created_at, updated_at FROM catalog_projects WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockProject(ctx context.Context, id uuid.UUID) (CatalogProject, error) {
	row := q.db.QueryRow(ctx, lockProject, id)
	var i CatalogProject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.SourceLocale,
		&i.Settings,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :execrows
UPDATE catalog_applications
SET slug = $1, name = $2, platform = $3,
    version = $4, updated_at = $5
WHERE id = $6 AND version = $7
`

type UpdateApplicationParams struct {
	Slug            string
	Name            string
	Platform        string
	Version         int32
	UpdatedAt       time.Time
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateApplication,
		arg.Slug,
		arg.Name,
		arg.Platform,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE catalog_projects
SET slug = $1, name = $2, settings = $3,
    version = $4, updated_at = $5
WHERE id = $6 AND version = $7
`

type UpdateProjectParams struct {
	Slug            string
	Name            string
	Settings        json.RawMessage
	Version         int32
	UpdatedAt       time.Time
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProject,
		arg.Slug,
		arg.Name,
		arg.Settings,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
