// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package releasesql

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ReleaseDeliveryKey struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	ProjectID    uuid.UUID
	Key          string
	Name         string
	CreatedBy    string
	CreatedAt    time.Time
	RevokedAt    pgtype.Timestamptz
	RevokedBy    pgtype.Text
	Environments []string
	Branches     bool
	IndexVersion int16
}

type ReleaseDeployment struct {
	TenantID          uuid.UUID
	ProjectID         uuid.UUID
	Environment       string
	Number            int32
	ReleaseID         uuid.UUID
	PreviousReleaseID uuid.NullUUID
	Action            string
	CreatedBy         string
	CreatedAt         time.Time
}

type ReleaseEnvironment struct {
	TenantID         uuid.UUID
	ProjectID        uuid.UUID
	Name             string
	Policy           json.RawMessage
	CurrentReleaseID uuid.NullUUID
	Version          int32
	CreatedBy        string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Kind             string
	Branch           pgtype.Text
}

type ReleasePublishRequest struct {
	TenantID         uuid.UUID
	ProjectID        uuid.UUID
	Environment      string
	RequestID        uuid.UUID
	FirstRequestedAt time.Time
	NotBefore        time.Time
	RequestedBy      string
}

type ReleaseRelease struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ProjectID      uuid.UUID
	Version        int32
	ParentID       uuid.NullUUID
	Environment    string
	Policy         json.RawMessage
	Content        json.RawMessage
	ManifestDigest string
	Stats          json.RawMessage
	Note           string
	CreatedBy      string
	CreatedAt      time.Time
	Branch         pgtype.Text
}
