// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: release.sql

package releasesql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeDeliveryKeys = `-- name: ActiveDeliveryKeys :many
SELECT id, tenant_id, project_id, key, name, created_by, created_at, revoked_at, revoked_by, environments, branches, index_version FROM release_delivery_keys WHERE project_id = $1 AND revoked_at IS NULL ORDER BY id
`

func (q *Queries) ActiveDeliveryKeys(ctx context.Context, projectID uuid.UUID) ([]ReleaseDeliveryKey, error) {
	rows, err := q.db.Query(ctx, activeDeliveryKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseDeliveryKey
	for rows.Next() {
		var i ReleaseDeliveryKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.Environments,
			&i.Branches,
			&i.IndexVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBranchEnvironments = `-- name: CountBranchEnvironments :one
SELECT count(*)::integer FROM release_environments WHERE project_id = $1 AND kind = 'branch'
`

func (q *Queries) CountBranchEnvironments(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBranchEnvironments, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :execrows
DELETE FROM release_environments WHERE project_id = $1 AND name = $2
`

type DeleteEnvironmentParams struct {
	ProjectID uuid.UUID
	Name      string
}

// Its deployments stay: they are history, like the releases.
func (q *Queries) DeleteEnvironment(ctx context.Context, arg DeleteEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironment, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectEnvironments = `-- name: DeleteProjectEnvironments :many
DELETE FROM release_environments WHERE project_id = $1 RETURNING name
`

func (q *Queries) DeleteProjectEnvironments(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteProjectEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchEnvironment = `-- name: GetBranchEnvironment :one
SELECT tenant_id, project_id, name, policy, current_release_id, version, created_by, created_at, updated_at, kind, branch FROM release_environments WHERE project_id = $1 AND branch = $2
`

type GetBranchEnvironmentParams struct {
	ProjectID uuid.UUID
	Branch    pgtype.Text
}

func (q *Queries) GetBranchEnvironment(ctx context.Context, arg GetBranchEnvironmentParams) (ReleaseEnvironment, error) {
	row := q.db.QueryRow(ctx, getBranchEnvironment, arg.ProjectID, arg.Branch)
	var i ReleaseEnvironment
	err := row.Scan(
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Policy,
		&i.CurrentReleaseID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Branch,
	)
	return i, err
}

const getDeliveryKey = `-- name: GetDeliveryKey :one
SELECT id, tenant_id, project_id, key, name, created_by, created_at, revoked_at, revoked_by, environments, branches, index_version FROM release_delivery_keys WHERE project_id = $1 AND id = $2
`

type GetDeliveryKeyParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetDeliveryKey(ctx context.Context, arg GetDeliveryKeyParams) (ReleaseDeliveryKey, error) {
	row := q.db.QueryRow(ctx, getDeliveryKey, arg.ProjectID, arg.ID)
	var i ReleaseDeliveryKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.Environments,
		&i.Branches,
		&i.IndexVersion,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT tenant_id, project_id, name, policy, current_release_id, version, created_by, created_at, updated_at, kind, branch FROM release_environments WHERE project_id = $1 AND name = $2
`

type GetEnvironmentParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (ReleaseEnvironment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, arg.ProjectID, arg.Name)
	var i ReleaseEnvironment
	err := row.Scan(
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Policy,
		&i.CurrentReleaseID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Branch,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, tenant_id, project_id, version, parent_id, environment, policy, content, manifest_digest, stats, note, created_by, created_at, branch FROM release_releases WHERE project_id = $1 AND id = $2
`

type GetReleaseParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetRelease(ctx context.Context, arg GetReleaseParams) (ReleaseRelease, error) {
	row := q.db.QueryRow(ctx, getRelease, arg.ProjectID, arg.ID)
	var i ReleaseRelease
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Version,
		&i.ParentID,
		&i.Environment,
		&i.Policy,
		&i.Content,
		&i.ManifestDigest,
		&i.Stats,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Branch,
	)
	return i, err
}

const insertDeliveryKey = `-- name: InsertDeliveryKey :execrows

INSERT INTO release_delivery_keys (id, tenant_id, project_id, key, name, environments, branches, created_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5::text[], $6, $7, $8)
ON CONFLICT (id) DO NOTHING
`

type InsertDeliveryKeyParams struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	Key          string
	Name         string
	Environments []string
	Branches     bool
	CreatedBy    string
	CreatedAt    time.Time
}

// ── delivery keys ──────────────────────────────────────────────────
func (q *Queries) InsertDeliveryKey(ctx context.Context, arg InsertDeliveryKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDeliveryKey,
		arg.ID,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Environments,
		arg.Branches,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDeployment = `-- name: InsertDeployment :exec

INSERT INTO release_deployments (tenant_id, project_id, environment, number, release_id, previous_release_id,
                                 action, created_by, created_at)
VALUES (app_current_tenant(), $1, $2, $3, $4,
        $5, $6, $7, $8)
`

type InsertDeploymentParams struct {
	ProjectID         uuid.UUID
	Environment       string
	Number            int32
	ReleaseID         uuid.UUID
	PreviousReleaseID uuid.NullUUID
	Action            string
	CreatedBy         string
	CreatedAt         time.Time
}

// ── deployments ────────────────────────────────────────────────────
func (q *Queries) InsertDeployment(ctx context.Context, arg InsertDeploymentParams) error {
	_, err := q.db.Exec(ctx, insertDeployment,
		arg.ProjectID,
		arg.Environment,
		arg.Number,
		arg.ReleaseID,
		arg.PreviousReleaseID,
		arg.Action,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertEnvironment = `-- name: InsertEnvironment :execrows


INSERT INTO release_environments (tenant_id, project_id, name, kind, branch, policy, current_release_id, version,
                                  created_by, created_at, updated_at)
VALUES (app_current_tenant(), $1, $2, $3, $4, $5,
        NULL, $6, $7, $8, $9)
ON CONFLICT DO NOTHING
`

type InsertEnvironmentParams struct {
	ProjectID uuid.UUID
	Name      string
	Kind      string
	Branch    pgtype.Text
	Policy    json.RawMessage
	Version   int32
	CreatedBy string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
// ── environments ───────────────────────────────────────────────────
// An environment's identity is its name within the project, so creating
// one twice is a no-op (the default environments are ensured this way).
func (q *Queries) InsertEnvironment(ctx context.Context, arg InsertEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Branch,
		arg.Policy,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRelease = `-- name: InsertRelease :execrows

INSERT INTO release_releases (id, tenant_id, project_id, version, parent_id, environment, policy, branch, content,
                              manifest_digest, stats, note, created_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $9,
        $10, $11, $12, $13)
ON CONFLICT (id) DO NOTHING
`

type InsertReleaseParams struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Version        int32
	ParentID       uuid.NullUUID
	Environment    string
	Policy         json.RawMessage
	Branch         pgtype.Text
	Content        json.RawMessage
	ManifestDigest string
	Stats          json.RawMessage
	Note           string
	CreatedBy      string
	CreatedAt      time.Time
}

// ── releases ───────────────────────────────────────────────────────
// A retried publish (same Idempotency-Key, same ID) inserts nothing.
func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRelease,
		arg.ID,
		arg.ProjectID,
		arg.Version,
		arg.ParentID,
		arg.Environment,
		arg.Policy,
		arg.Branch,
		arg.Content,
		arg.ManifestDigest,
		arg.Stats,
		arg.Note,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lastDeploymentNumber = `-- name: LastDeploymentNumber :one
SELECT coalesce(max(number), 0)::integer FROM release_deployments
WHERE project_id = $1 AND environment = $2
`

type LastDeploymentNumberParams struct {
	ProjectID   uuid.UUID
	Environment string
}

func (q *Queries) LastDeploymentNumber(ctx context.Context, arg LastDeploymentNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, lastDeploymentNumber, arg.ProjectID, arg.Environment)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listDeliveryKeys = `-- name: ListDeliveryKeys :many
SELECT id, tenant_id, project_id, key, name, created_by, created_at, revoked_at, revoked_by, environments, branches, index_version FROM release_delivery_keys
WHERE project_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListDeliveryKeysParams struct {
	ProjectID uuid.UUID
	After     uuid.UUID
	MaxRows   int32
}

func (q *Queries) ListDeliveryKeys(ctx context.Context, arg ListDeliveryKeysParams) ([]ReleaseDeliveryKey, error) {
	rows, err := q.db.Query(ctx, listDeliveryKeys, arg.ProjectID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseDeliveryKey
	for rows.Next() {
		var i ReleaseDeliveryKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.Environments,
			&i.Branches,
			&i.IndexVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT tenant_id, project_id, environment, number, release_id, previous_release_id, action, created_by, created_at FROM release_deployments
WHERE project_id = $1 AND environment = $2 AND number < $3
ORDER BY number DESC
LIMIT $4
`

type ListDeploymentsParams struct {
	ProjectID    uuid.UUID
	Environment  string
	BeforeNumber int32
	MaxRows      int32
}

// Newest first.
func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]ReleaseDeployment, error) {
	rows, err := q.db.Query(ctx, listDeployments,
		arg.ProjectID,
		arg.Environment,
		arg.BeforeNumber,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseDeployment
	for rows.Next() {
		var i ReleaseDeployment
		if err := rows.Scan(
			&i.TenantID,
			&i.ProjectID,
			&i.Environment,
			&i.Number,
			&i.ReleaseID,
			&i.PreviousReleaseID,
			&i.Action,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT tenant_id, project_id, name, policy, current_release_id, version, created_by, created_at, updated_at, kind, branch FROM release_environments
WHERE project_id = $1 AND name > $2
ORDER BY name
LIMIT $3
`

type ListEnvironmentsParams struct {
	ProjectID uuid.UUID
	After     string
	MaxRows   int32
}

func (q *Queries) ListEnvironments(ctx context.Context, arg ListEnvironmentsParams) ([]ReleaseEnvironment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, arg.ProjectID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseEnvironment
	for rows.Next() {
		var i ReleaseEnvironment
		if err := rows.Scan(
			&i.TenantID,
			&i.ProjectID,
			&i.Name,
			&i.Policy,
			&i.CurrentReleaseID,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT id, tenant_id, project_id, version, parent_id, environment, policy, content, manifest_digest, stats, note, created_by, created_at, branch FROM release_releases
WHERE project_id = $1 AND version < $2
ORDER BY version DESC
LIMIT $3
`

type ListReleasesParams struct {
	ProjectID     uuid.UUID
	BeforeVersion int32
	MaxRows       int32
}

// Newest first.
func (q *Queries) ListReleases(ctx context.Context, arg ListReleasesParams) ([]ReleaseRelease, error) {
	rows, err := q.db.Query(ctx, listReleases, arg.ProjectID, arg.BeforeVersion, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseRelease
	for rows.Next() {
		var i ReleaseRelease
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Version,
			&i.ParentID,
			&i.Environment,
			&i.Policy,
			&i.Content,
			&i.ManifestDigest,
			&i.Stats,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBranchEnvironment = `-- name: LockBranchEnvironment :one
SELECT tenant_id, project_id, name, policy, current_release_id, version, created_by, created_at, updated_at, kind, branch FROM release_environments WHERE project_id = $1 AND branch = $2 FOR UPDATE
`

type LockBranchEnvironmentParams struct {
	ProjectID uuid.UUID
	Branch    pgtype.Text
}

func (q *Queries) LockBranchEnvironment(ctx context.Context, arg LockBranchEnvironmentParams) (ReleaseEnvironment, error) {
	row := q.db.QueryRow(ctx, lockBranchEnvironment, arg.ProjectID, arg.Branch)
	var i ReleaseEnvironment
	err := row.Scan(
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Policy,
		&i.CurrentReleaseID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Branch,
	)
	return i, err
}

const lockDeliveryKey = `-- name: LockDeliveryKey :one
SELECT id, tenant_id, project_id, key, name, created_by, created_at, revoked_at, revoked_by, environments, branches, index_version FROM release_delivery_keys WHERE project_id = $1 AND id = $2 FOR UPDATE
`

type LockDeliveryKeyParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) LockDeliveryKey(ctx context.Context, arg LockDeliveryKeyParams) (ReleaseDeliveryKey, error) {
	row := q.db.QueryRow(ctx, lockDeliveryKey, arg.ProjectID, arg.ID)
	var i ReleaseDeliveryKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.Environments,
		&i.Branches,
		&i.IndexVersion,
	)
	return i, err
}

const lockEnvironment = `-- name: LockEnvironment :one
SELECT tenant_id, project_id, name, policy, current_release_id, version, created_by, created_at, updated_at, kind, branch FROM release_environments WHERE project_id = $1 AND name = $2 FOR UPDATE
`

type LockEnvironmentParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) LockEnvironment(ctx context.Context, arg LockEnvironmentParams) (ReleaseEnvironment, error) {
	row := q.db.QueryRow(ctx, lockEnvironment, arg.ProjectID, arg.Name)
	var i ReleaseEnvironment
	err := row.Scan(
		&i.TenantID,
		&i.ProjectID,
		&i.Name,
		&i.Policy,
		&i.CurrentReleaseID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Branch,
	)
	return i, err
}

const lockProjectEnvironments = `-- name: LockProjectEnvironments :many
SELECT tenant_id, project_id, name, policy, current_release_id, version, created_by, created_at, updated_at, kind, branch FROM release_environments WHERE project_id = $1 ORDER BY name FOR UPDATE
`

// Serializes publishes of one project (release versions have no gaps).
func (q *Queries) LockProjectEnvironments(ctx context.Context, projectID uuid.UUID) ([]ReleaseEnvironment, error) {
	rows, err := q.db.Query(ctx, lockProjectEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseEnvironment
	for rows.Next() {
		var i ReleaseEnvironment
		if err := rows.Scan(
			&i.TenantID,
			&i.ProjectID,
			&i.Name,
			&i.Policy,
			&i.CurrentReleaseID,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markKeyIndexed = `-- name: MarkKeyIndexed :exec
UPDATE release_delivery_keys SET index_version = $1
WHERE id = $2 AND index_version <> $1
`

type MarkKeyIndexedParams struct {
	IndexVersion int16
	ID           uuid.UUID
}

// The key's index object was written in this format.
func (q *Queries) MarkKeyIndexed(ctx context.Context, arg MarkKeyIndexedParams) error {
	_, err := q.db.Exec(ctx, markKeyIndexed, arg.IndexVersion, arg.ID)
	return err
}

const maxReleaseVersion = `-- name: MaxReleaseVersion :one
SELECT coalesce(max(version), 0)::integer FROM release_releases WHERE project_id = $1
`

func (q *Queries) MaxReleaseVersion(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxReleaseVersion, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const revokeDeliveryKey = `-- name: RevokeDeliveryKey :execrows
UPDATE release_delivery_keys
SET revoked_at = $1, revoked_by = $2
WHERE project_id = $3 AND id = $4 AND revoked_at IS NULL
`

type RevokeDeliveryKeyParams struct {
	RevokedAt pgtype.Timestamptz
	RevokedBy pgtype.Text
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) RevokeDeliveryKey(ctx context.Context, arg RevokeDeliveryKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeliveryKey,
		arg.RevokedAt,
		arg.RevokedBy,
		arg.ProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rollbackTarget = `-- name: RollbackTarget :one
SELECT r.id, r.tenant_id, r.project_id, r.version, r.parent_id, r.environment, r.policy, r.content, r.manifest_digest, r.stats, r.note, r.created_by, r.created_at, r.branch FROM release_deployments d
JOIN release_releases r ON r.id = d.release_id
WHERE d.project_id = $1 AND d.environment = $2
  AND r.version < $3
ORDER BY r.version DESC
LIMIT 1
`

type RollbackTargetParams struct {
	ProjectID      uuid.UUID
	Environment    string
	CurrentVersion int32
}

// The newest release the environment served that is older than the one
// it serves now.
func (q *Queries) RollbackTarget(ctx context.Context, arg RollbackTargetParams) (ReleaseRelease, error) {
	row := q.db.QueryRow(ctx, rollbackTarget, arg.ProjectID, arg.Environment, arg.CurrentVersion)
	var i ReleaseRelease
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Version,
		&i.ParentID,
		&i.Environment,
		&i.Policy,
		&i.Content,
		&i.ManifestDigest,
		&i.Stats,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Branch,
	)
	return i, err
}

const servedInEnvironment = `-- name: ServedInEnvironment :one
SELECT EXISTS (
    SELECT 1 FROM release_deployments
    WHERE project_id = $1 AND environment = $2 AND release_id = $3
)
`

type ServedInEnvironmentParams struct {
	ProjectID   uuid.UUID
	Environment string
	ReleaseID   uuid.UUID
}

func (q *Queries) ServedInEnvironment(ctx context.Context, arg ServedInEnvironmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, servedInEnvironment, arg.ProjectID, arg.Environment, arg.ReleaseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setDeliveryKeyScope = `-- name: SetDeliveryKeyScope :execrows
UPDATE release_delivery_keys
SET environments = $1::text[], branches = $2, index_version = 1
WHERE project_id = $3 AND id = $4 AND revoked_at IS NULL
`

type SetDeliveryKeyScopeParams struct {
	Environments []string
	Branches     bool
	ProjectID    uuid.UUID
	ID           uuid.UUID
}

// Replaces what an active key reads (RFC 0004 §4.3). index_version
// drops to 1 (before scopes), so the key index task rewrites the object
// if the write that follows the change doesn't reach storage.
func (q *Queries) SetDeliveryKeyScope(ctx context.Context, arg SetDeliveryKeyScopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDeliveryKeyScope,
		arg.Environments,
		arg.Branches,
		arg.ProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEnvironment = `-- name: UpdateEnvironment :execrows
UPDATE release_environments
SET policy = $1, current_release_id = $2, version = $3,
    updated_at = $4
WHERE project_id = $5 AND name = $6 AND version = $7
`

type UpdateEnvironmentParams struct {
	Policy           json.RawMessage
	CurrentReleaseID uuid.NullUUID
	Version          int32
	UpdatedAt        time.Time
	ProjectID        uuid.UUID
	Name             string
	ExpectedVersion  int32
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEnvironment,
		arg.Policy,
		arg.CurrentReleaseID,
		arg.Version,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.Name,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
