// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package releasesql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePublishRequest = `-- name: DeletePublishRequest :execrows
DELETE FROM release_publish_requests
WHERE project_id = $1 AND environment = $2 AND request_id = $3
`

type DeletePublishRequestParams struct {
	ProjectID   uuid.UUID
	Environment string
	RequestID   uuid.UUID
}

// Only the request that was published: a newer one keeps waiting.
func (q *Queries) DeletePublishRequest(ctx context.Context, arg DeletePublishRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishRequest, arg.ProjectID, arg.Environment, arg.RequestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockPublishRequest = `-- name: LockPublishRequest :one

SELECT tenant_id, project_id, environment, request_id, first_requested_at, not_before, requested_by FROM release_publish_requests
WHERE project_id = $1 AND environment = $2
FOR UPDATE
`

type LockPublishRequestParams struct {
	ProjectID   uuid.UUID
	Environment string
}

// Tenant scope (db.TenantTx): debounced publish requests of branch
// environments (RFC 0004 §4.2).
func (q *Queries) LockPublishRequest(ctx context.Context, arg LockPublishRequestParams) (ReleasePublishRequest, error) {
	row := q.db.QueryRow(ctx, lockPublishRequest, arg.ProjectID, arg.Environment)
	var i ReleasePublishRequest
	err := row.Scan(
		&i.TenantID,
		&i.ProjectID,
		&i.Environment,
		&i.RequestID,
		&i.FirstRequestedAt,
		&i.NotBefore,
		&i.RequestedBy,
	)
	return i, err
}

const savePublishRequest = `-- name: SavePublishRequest :exec
INSERT INTO release_publish_requests (tenant_id, project_id, environment, request_id, first_requested_at, not_before,
                                      requested_by)
VALUES (app_current_tenant(), $1, $2, $3,
        $4, $5, $6)
ON CONFLICT (project_id, environment) DO UPDATE
SET request_id = excluded.request_id, first_requested_at = excluded.first_requested_at,
    not_before = excluded.not_before, requested_by = excluded.requested_by
`

type SavePublishRequestParams struct {
	ProjectID        uuid.UUID
	Environment      string
	RequestID        uuid.UUID
	FirstRequestedAt time.Time
	NotBefore        time.Time
	RequestedBy      string
}

func (q *Queries) SavePublishRequest(ctx context.Context, arg SavePublishRequestParams) error {
	_, err := q.db.Exec(ctx, savePublishRequest,
		arg.ProjectID,
		arg.Environment,
		arg.RequestID,
		arg.FirstRequestedAt,
		arg.NotBefore,
		arg.RequestedBy,
	)
	return err
}
