// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package releasesql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listDuePublishRequests = `-- name: ListDuePublishRequests :many

SELECT tenant_id, project_id, environment FROM release_publish_requests
WHERE not_before <= $1
ORDER BY not_before, project_id, environment
LIMIT $2::int
`

type ListDuePublishRequestsParams struct {
	Now     time.Time
	MaxRows int32
}

type ListDuePublishRequestsRow struct {
	TenantID    uuid.UUID
	ProjectID   uuid.UUID
	Environment string
}

// System scope (db.SystemTx as glossa_system): migration 0015 opens
// these columns to it, read-only, and nothing else. Each query finds
// work across tenants; the work itself runs in each tenant's scope.
// System scope release.publisher.
func (q *Queries) ListDuePublishRequests(ctx context.Context, arg ListDuePublishRequestsParams) ([]ListDuePublishRequestsRow, error) {
	rows, err := q.db.Query(ctx, listDuePublishRequests, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDuePublishRequestsRow
	for rows.Next() {
		var i ListDuePublishRequestsRow
		if err := rows.Scan(&i.TenantID, &i.ProjectID, &i.Environment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleKeyIndexes = `-- name: ListStaleKeyIndexes :many
SELECT tenant_id, project_id, id FROM release_delivery_keys
WHERE revoked_at IS NULL AND index_version < $1
ORDER BY tenant_id, id
LIMIT $2::int
`

type ListStaleKeyIndexesParams struct {
	IndexVersion int16
	MaxRows      int32
}

type ListStaleKeyIndexesRow struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
	ID        uuid.UUID
}

// System scope release.key_index: active keys whose index object
// predates the current format.
func (q *Queries) ListStaleKeyIndexes(ctx context.Context, arg ListStaleKeyIndexesParams) ([]ListStaleKeyIndexesRow, error) {
	rows, err := q.db.Query(ctx, listStaleKeyIndexes, arg.IndexVersion, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleKeyIndexesRow
	for rows.Next() {
		var i ListStaleKeyIndexesRow
		if err := rows.Scan(&i.TenantID, &i.ProjectID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
