#!/usr/bin/env bash
# Prints the chart values that pin glossa-server, glossa-edge and
# glossa-studio to the digests a released tag resolves to in GHCR —
# the same file .github/workflows/release-platform.yml uploads as its
# `values-images` artifact, regenerated from the registry.
#
# Use it when that artifact has expired, when pinning an older release,
# or to check that a deployment's pins still match the tag.
#
#   ci/image-digests.sh v0.4.0 > values-images.yaml
#   helm upgrade --install glossa-platform deploy/charts/glossa-platform \
#     --namespace glossa-platform -f my-values.yaml -f values-images.yaml
#
# The tag written into the file is the one that exists in the registry:
# Kiln's `v0.4.0` (which is also the chart's default, `v<appVersion>`),
# or the bare `0.4.0` the manual GitHub workflow pushes.
#
# Needs `crane` or `docker buildx`, and `curl`. The packages must be
# public: the script verifies an anonymous pull of each image (the way a
# cluster pulls) and fails, with the fix, when the registry refuses it.
set -euo pipefail

OWNER="${GLOSSA_IMAGE_OWNER:-klarlabs-studio}"
REGISTRY="${GLOSSA_IMAGE_REGISTRY:-ghcr.io}"

usage() {
  echo "usage: $(basename "$0") <tag>    e.g. $(basename "$0") v0.4.0" >&2
  exit 2
}

[ $# -eq 1 ] || usage
tag="$1"
case "$tag" in
  v*) semver="${tag#v}" ;;
  *) semver="$tag" ;;
esac
printf '%s' "$semver" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || usage

# The digest of the pushed artifact — the OCI index when the image
# carries provenance and SBOM attestations, which is exactly what a
# `repository@sha256:…` reference must name.
_digest() {
  local ref="$1"
  if command -v crane > /dev/null 2>&1; then
    crane digest "$ref"
  elif docker buildx version > /dev/null 2>&1; then
    docker buildx imagetools inspect "$ref" --format '{{.Manifest.Digest}}'
  else
    echo "need crane or docker buildx to read $ref" >&2
    exit 1
  fi
}

# Sets resolved_tag to the tag that exists: Kiln's `v0.5.0` first (the
# chart's default), then the bare `0.5.0`.
resolved_tag=""
resolve_tag() {
  local repo="$1" t
  for t in "v${semver}" "${semver}"; do
    if _digest "${repo}:${t}" > /dev/null 2>&1; then
      resolved_tag="$t"
      return 0
    fi
  done
  echo "neither ${repo}:v${semver} nor ${repo}:${semver} is readable; was the release published?" >&2
  exit 1
}

# A cluster pulls anonymously, and the first push to a new GHCR owner
# creates the package private/internal. Ask the registry the way a
# cluster would, with no credentials (crane and docker may be logged in,
# so they cannot answer this): an anonymous token and a manifest HEAD.
assert_anonymous_pull() {
  local component="$1" digest="$2" path token="" code
  path="${OWNER}/glossa-${component}"
  command -v curl > /dev/null 2>&1 || { echo "need curl to verify anonymous pulls" >&2; exit 1; }
  if [ "$REGISTRY" = "ghcr.io" ]; then
    token=$(curl -fsS "https://ghcr.io/token?service=ghcr.io&scope=repository:${path}:pull" \
      | sed -n 's/.*"token":"\([^"]*\)".*/\1/p') || token=""
  fi
  code=$(curl -s -o /dev/null -I -w '%{http_code}' \
    ${token:+-H "Authorization: Bearer ${token}"} \
    -H 'Accept: application/vnd.oci.image.index.v1+json, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json' \
    "https://${REGISTRY}/v2/${path}/manifests/${digest}" || true)
  if [ "$code" != "200" ]; then
    cat >&2 <<MSG
${REGISTRY}/${path}@${digest} cannot be pulled anonymously (HTTP ${code:-none}).
The package is probably private or internal: the first push to a new
registry owner creates it that way. In GitHub, open the package settings
(https://github.com/orgs/${OWNER}/packages/container/glossa-${component}/settings),
set "Change package visibility" to Public, and under "Manage Actions
access" add the repository with Write role (the workflow_dispatch
fallback needs it). There is no API for the visibility change. Then
re-run this script. For a private registry that clusters pull from with
image.pullSecrets, set GLOSSA_SKIP_ANONYMOUS_CHECK=1.
MSG
    exit 1
  fi
}

echo "# Generated by deploy/charts/glossa-platform/ci/image-digests.sh for ${tag}."
echo "# What ${REGISTRY}/${OWNER}/glossa-*:v${semver} (or :${semver}) resolve to today."
echo "image:"
echo "  requireDigest: true"

for component in server edge studio site; do
  repo="${REGISTRY}/${OWNER}/glossa-${component}"
  resolve_tag "$repo"
  ref="${repo}:${resolved_tag}"
  digest=$(_digest "$ref")
  printf '%s' "$digest" | grep -Eq '^sha256:[0-9a-f]{64}$' || {
    echo "unexpected digest for ${ref}: ${digest}" >&2
    exit 1
  }
  [ "${GLOSSA_SKIP_ANONYMOUS_CHECK:-}" = "1" ] || assert_anonymous_pull "$component" "$digest"
  printf '%s:\n  image:\n    tag: "%s"\n    digest: %s\n' \
    "$component" "$resolved_tag" "$digest"
done
