#!/usr/bin/env bash
# Prints the chart values that pin glossa-server, glossa-edge and
# glossa-studio to the digests a released tag resolves to in GHCR —
# the same file .github/workflows/release-platform.yml uploads as its
# `values-images` artifact, regenerated from the registry.
#
# Use it when that artifact has expired, when pinning an older release,
# or to check that a deployment's pins still match the tag.
#
#   ci/image-digests.sh v0.4.0 > values-images.yaml
#   helm upgrade --install glossa-platform deploy/charts/glossa-platform \
#     --namespace glossa-platform -f my-values.yaml -f values-images.yaml
#
# Needs `crane` or `docker buildx`, and read access to the packages
# (they are public for this repository, so usually no login).
set -euo pipefail

OWNER="${GLOSSA_IMAGE_OWNER:-felixgeelhaar}"
REGISTRY="${GLOSSA_IMAGE_REGISTRY:-ghcr.io}"

usage() {
  echo "usage: $(basename "$0") <tag>    e.g. $(basename "$0") v0.4.0" >&2
  exit 2
}

[ $# -eq 1 ] || usage
tag="$1"
case "$tag" in
  v*) semver="${tag#v}" ;;
  *) semver="$tag" ;;
esac
printf '%s' "$semver" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || usage

# The digest of the pushed artifact — the OCI index when the image
# carries provenance and SBOM attestations, which is exactly what a
# `repository@sha256:…` reference must name.
digest_of() {
  local ref="$1"
  if command -v crane > /dev/null 2>&1; then
    crane digest "$ref"
  elif docker buildx version > /dev/null 2>&1; then
    docker buildx imagetools inspect "$ref" --format '{{.Manifest.Digest}}'
  else
    echo "need crane or docker buildx to read $ref" >&2
    exit 1
  fi
}

echo "# Generated by deploy/charts/glossa-platform/ci/image-digests.sh for ${tag}."
echo "# What ${REGISTRY}/${OWNER}/glossa-*:${semver} resolve to today."
echo "image:"
echo "  requireDigest: true"

for component in server edge studio; do
  ref="${REGISTRY}/${OWNER}/glossa-${component}:${semver}"
  digest=$(digest_of "$ref")
  printf '%s' "$digest" | grep -Eq '^sha256:[0-9a-f]{64}$' || {
    echo "unexpected digest for ${ref}: ${digest}" >&2
    exit 1
  }
  printf '%s:\n  image:\n    tag: "%s"\n    digest: %s\n' \
    "$component" "$semver" "$digest"
done
