// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package tenancysql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getCurrentTenant = `-- name: GetCurrentTenant :one
SELECT id, kind, slug, name, created_at
FROM tenants
WHERE id = app_current_tenant()
`

func (q *Queries) GetCurrentTenant(ctx context.Context) (Tenant, error) {
	row := q.db.QueryRow(ctx, getCurrentTenant)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :one

INSERT INTO tenants (id, kind, slug, name)
VALUES ($1, $2, $3, $4)
RETURNING created_at
`

type InsertTenantParams struct {
	ID   uuid.UUID
	Kind string
	Slug string
	Name string
}

// Queries run inside a tenant-scoped transaction (db.TenantTx), so RLS
// limits them to the current tenant; app_current_tenant() makes that
// explicit rather than trusting a caller-supplied id.
func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertTenant,
		arg.ID,
		arg.Kind,
		arg.Slug,
		arg.Name,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}
