// Code generated by glossa generate. DO NOT EDIT.
/* eslint-disable */
import { useMemo } from "react";
import { useMessages } from "@glossa/react";
import { createMessages } from "./messages.js";
import type { Messages } from "./messages.js";

declare module "@glossa/react" {
  interface GlossaRegister {
    messages: Messages;
  }
}

/**
 * Typed accessors on the provider's Glossa runtime. A hook: it re-renders
 * like useGlossa(). const m = useTypedMessages(); m.checkout.pay({ amount }).
 */
export function useTypedMessages() {
  const { t } = useMessages<Messages>();
  return useMemo(() => {
    const render = t as unknown as (id: string, values: Record<string, unknown>) => string;
    return createMessages((id, values) => render(id, values));
  }, [t]);
}
