// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package intelligencesql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelFillJobs = `-- name: CancelFillJobs :execrows
UPDATE intelligence_jobs
SET state = 'cancelled', finished_at = $1, updated_at = $1,
    last_error = 'cancelled by ' || $2::text
WHERE fill_id = $3 AND state = 'queued'
`

type CancelFillJobsParams struct {
	Now    pgtype.Timestamptz
	By     string
	FillID uuid.NullUUID
}

func (q *Queries) CancelFillJobs(ctx context.Context, arg CancelFillJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelFillJobs, arg.Now, arg.By, arg.FillID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelJob = `-- name: CancelJob :execrows
UPDATE intelligence_jobs
SET state = 'cancelled', finished_at = $1, updated_at = $1, failure_code = NULL,
    last_error = 'cancelled by ' || $2::text
WHERE id = $3 AND state = 'queued'
`

type CancelJobParams struct {
	Now pgtype.Timestamptz
	By  string
	ID  uuid.UUID
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelJob, arg.Now, arg.By, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimJob = `-- name: ClaimJob :one

WITH running AS (
    SELECT r.tenant_id, count(*) AS n
    FROM intelligence_jobs r
    WHERE r.state = 'running' AND r.available_at > now()
    GROUP BY r.tenant_id
), due AS (
    SELECT j.id
    FROM intelligence_jobs j
    LEFT JOIN running ON running.tenant_id = j.tenant_id
    LEFT JOIN intelligence_settings s ON s.tenant_id = j.tenant_id
    WHERE j.state IN ('queued', 'running') AND j.available_at <= now()
      AND coalesce(running.n, 0) < coalesce(s.max_concurrent_jobs, 4)
    ORDER BY j.available_at, j.id
    LIMIT 1
    FOR UPDATE OF j SKIP LOCKED
)
UPDATE intelligence_jobs e
SET state        = 'running',
    attempts     = e.attempts + 1,
    available_at = now() + make_interval(secs => $1::float8),
    claim_token  = gen_random_uuid(),
    started_at   = coalesce(e.started_at, now()),
    updated_at   = now()
FROM due
WHERE e.id = due.id
RETURNING e.id, e.tenant_id, e.claim_token, e.attempts, e.max_attempts
`

type ClaimJobRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ClaimToken  uuid.NullUUID
	Attempts    int32
	MaxAttempts int32
}

// ── claiming (system scope "intelligence.jobs") ────────────────────
// ClaimJob leases the next due job whose tenant is under its concurrency
// cap: queued and due, or running with an expired lease (its worker
// died). The caller serializes claims with an advisory lock, so the
// per-tenant count is exact across replicas; SKIP LOCKED keeps workers
// off each other's rows.
func (q *Queries) ClaimJob(ctx context.Context, leaseSeconds float64) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob, leaseSeconds)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClaimToken,
		&i.Attempts,
		&i.MaxAttempts,
	)
	return i, err
}

const deleteProjectDisclosures = `-- name: DeleteProjectDisclosures :exec
DELETE FROM intelligence_disclosures WHERE project_id = $1
`

func (q *Queries) DeleteProjectDisclosures(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectDisclosures, projectID)
	return err
}

const deleteProjectFills = `-- name: DeleteProjectFills :exec
DELETE FROM intelligence_fills WHERE project_id = $1
`

func (q *Queries) DeleteProjectFills(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectFills, projectID)
	return err
}

const deleteProjectJobs = `-- name: DeleteProjectJobs :exec
DELETE FROM intelligence_jobs WHERE project_id = $1
`

func (q *Queries) DeleteProjectJobs(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectJobs, projectID)
	return err
}

const deleteProjectRouting = `-- name: DeleteProjectRouting :exec
DELETE FROM intelligence_routing_policies WHERE project_id = $1
`

func (q *Queries) DeleteProjectRouting(ctx context.Context, projectID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteProjectRouting, projectID)
	return err
}

const deleteProjectSettings = `-- name: DeleteProjectSettings :exec
DELETE FROM intelligence_project_settings WHERE project_id = $1
`

func (q *Queries) DeleteProjectSettings(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectSettings, projectID)
	return err
}

const deleteProjectSuggestions = `-- name: DeleteProjectSuggestions :exec
DELETE FROM intelligence_suggestions WHERE project_id = $1
`

func (q *Queries) DeleteProjectSuggestions(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectSuggestions, projectID)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO intelligence_jobs (
    id, tenant_id, project_id, message_id, message_key, namespace, locale, source_revision,
    knowledge_fingerprint, trigger, fill_id, state, attempts, max_attempts, available_at,
    created_by, created_at, updated_at
) VALUES (
    $1, app_current_tenant(), $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, 'queued', 0, $11, now(),
    $12, $13, $13
)
ON CONFLICT (tenant_id, message_id, locale, source_revision, knowledge_fingerprint) DO UPDATE
SET state = 'queued', attempts = 0, available_at = now(), failure_code = NULL,
    last_error = NULL, claim_token = NULL, fill_id = excluded.fill_id, trigger = excluded.trigger,
    finished_at = NULL, updated_at = excluded.updated_at
WHERE $14::boolean AND intelligence_jobs.state IN ('failed', 'dead', 'cancelled')
RETURNING id
`

type EnqueueJobParams struct {
	ID                   uuid.UUID
	ProjectID            uuid.UUID
	MessageID            uuid.UUID
	MessageKey           string
	Namespace            string
	Locale               string
	SourceRevision       int32
	KnowledgeFingerprint string
	Trigger              string
	FillID               uuid.NullUUID
	MaxAttempts          int32
	CreatedBy            string
	CreatedAt            time.Time
	Requeue              bool
}

// ── jobs (tenant scope) ────────────────────────────────────────────
// EnqueueJob inserts a job unless one exists for the same message,
// locale, source revision and knowledge fingerprint. An explicit fill
// (requeue) brings back such a job that failed, died or was cancelled;
// anything else finds the existing job unchanged and returns no row.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.ID,
		arg.ProjectID,
		arg.MessageID,
		arg.MessageKey,
		arg.Namespace,
		arg.Locale,
		arg.SourceRevision,
		arg.KnowledgeFingerprint,
		arg.Trigger,
		arg.FillID,
		arg.MaxAttempts,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.Requeue,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const fillJobCounts = `-- name: FillJobCounts :many
SELECT state, count(*)::int AS n FROM intelligence_jobs WHERE fill_id = $1 GROUP BY state
`

type FillJobCountsRow struct {
	State string
	N     int32
}

func (q *Queries) FillJobCounts(ctx context.Context, fillID uuid.NullUUID) ([]FillJobCountsRow, error) {
	rows, err := q.db.Query(ctx, fillJobCounts, fillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FillJobCountsRow
	for rows.Next() {
		var i FillJobCountsRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishFill = `-- name: FinishFill :exec
UPDATE intelligence_fills
SET jobs_created = $1, jobs_existing = $2, skipped = $3
WHERE id = $4
`

type FinishFillParams struct {
	JobsCreated  int32
	JobsExisting int32
	Skipped      json.RawMessage
	ID           uuid.UUID
}

func (q *Queries) FinishFill(ctx context.Context, arg FinishFillParams) error {
	_, err := q.db.Exec(ctx, finishFill,
		arg.JobsCreated,
		arg.JobsExisting,
		arg.Skipped,
		arg.ID,
	)
	return err
}

const finishJob = `-- name: FinishJob :exec
UPDATE intelligence_jobs
SET state = $1, failure_code = $2, last_error = $3,
    suggestion_id = $4, audit = $5, claim_token = NULL,
    finished_at = $6, updated_at = $6
WHERE id = $7
`

type FinishJobParams struct {
	State        string
	FailureCode  pgtype.Text
	LastError    pgtype.Text
	SuggestionID uuid.NullUUID
	Audit        []byte
	Now          pgtype.Timestamptz
	ID           uuid.UUID
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob,
		arg.State,
		arg.FailureCode,
		arg.LastError,
		arg.SuggestionID,
		arg.Audit,
		arg.Now,
		arg.ID,
	)
	return err
}

const getFill = `-- name: GetFill :one
SELECT id, tenant_id, project_id, trigger, locales, filter, jobs_created, jobs_existing, skipped, requested_by, created_at FROM intelligence_fills WHERE id = $1
`

func (q *Queries) GetFill(ctx context.Context, id uuid.UUID) (IntelligenceFill, error) {
	row := q.db.QueryRow(ctx, getFill, id)
	var i IntelligenceFill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Trigger,
		&i.Locales,
		&i.Filter,
		&i.JobsCreated,
		&i.JobsExisting,
		&i.Skipped,
		&i.RequestedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, tenant_id, project_id, message_id, message_key, namespace, locale, source_revision, knowledge_fingerprint, trigger, fill_id, state, attempts, max_attempts, available_at, claim_token, failure_code, last_error, suggestion_id, audit, created_by, created_at, started_at, finished_at, updated_at FROM intelligence_jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (IntelligenceJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i IntelligenceJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.MessageID,
		&i.MessageKey,
		&i.Namespace,
		&i.Locale,
		&i.SourceRevision,
		&i.KnowledgeFingerprint,
		&i.Trigger,
		&i.FillID,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimToken,
		&i.FailureCode,
		&i.LastError,
		&i.SuggestionID,
		&i.Audit,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByKey = `-- name: GetJobByKey :one
SELECT id, tenant_id, project_id, message_id, message_key, namespace, locale, source_revision, knowledge_fingerprint, trigger, fill_id, state, attempts, max_attempts, available_at, claim_token, failure_code, last_error, suggestion_id, audit, created_by, created_at, started_at, finished_at, updated_at FROM intelligence_jobs
WHERE message_id = $1 AND locale = $2
  AND source_revision = $3 AND knowledge_fingerprint = $4
`

type GetJobByKeyParams struct {
	MessageID            uuid.UUID
	Locale               string
	SourceRevision       int32
	KnowledgeFingerprint string
}

func (q *Queries) GetJobByKey(ctx context.Context, arg GetJobByKeyParams) (IntelligenceJob, error) {
	row := q.db.QueryRow(ctx, getJobByKey,
		arg.MessageID,
		arg.Locale,
		arg.SourceRevision,
		arg.KnowledgeFingerprint,
	)
	var i IntelligenceJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.MessageID,
		&i.MessageKey,
		&i.Namespace,
		&i.Locale,
		&i.SourceRevision,
		&i.KnowledgeFingerprint,
		&i.Trigger,
		&i.FillID,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimToken,
		&i.FailureCode,
		&i.LastError,
		&i.SuggestionID,
		&i.Audit,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFill = `-- name: InsertFill :exec

INSERT INTO intelligence_fills (id, tenant_id, project_id, trigger, locales, filter, requested_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4::text[],
        $5, $6, $7)
`

type InsertFillParams struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Trigger     string
	Locales     []string
	Filter      json.RawMessage
	RequestedBy string
	CreatedAt   time.Time
}

// ── fills ──────────────────────────────────────────────────────────
func (q *Queries) InsertFill(ctx context.Context, arg InsertFillParams) error {
	_, err := q.db.Exec(ctx, insertFill,
		arg.ID,
		arg.ProjectID,
		arg.Trigger,
		arg.Locales,
		arg.Filter,
		arg.RequestedBy,
		arg.CreatedAt,
	)
	return err
}

const listJobs = `-- name: ListJobs :many
SELECT id, tenant_id, project_id, message_id, message_key, namespace, locale, source_revision, knowledge_fingerprint, trigger, fill_id, state, attempts, max_attempts, available_at, claim_token, failure_code, last_error, suggestion_id, audit, created_by, created_at, started_at, finished_at, updated_at FROM intelligence_jobs
WHERE ($1::uuid IS NULL OR project_id = $1::uuid)
  AND ($2::text IS NULL OR state = $2::text)
  AND ($3::text IS NULL OR locale = $3::text)
  AND ($4::uuid IS NULL OR fill_id = $4::uuid)
  AND ($5::uuid IS NULL OR message_id = $5::uuid)
  AND ($6::timestamptz IS NULL OR (created_at, id) < ($6::timestamptz, $7::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $8::int
`

type ListJobsParams struct {
	ProjectID uuid.NullUUID
	State     pgtype.Text
	Locale    pgtype.Text
	FillID    uuid.NullUUID
	MessageID uuid.NullUUID
	BeforeAt  pgtype.Timestamptz
	BeforeID  uuid.UUID
	MaxRows   int32
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]IntelligenceJob, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.ProjectID,
		arg.State,
		arg.Locale,
		arg.FillID,
		arg.MessageID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntelligenceJob
	for rows.Next() {
		var i IntelligenceJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.MessageID,
			&i.MessageKey,
			&i.Namespace,
			&i.Locale,
			&i.SourceRevision,
			&i.KnowledgeFingerprint,
			&i.Trigger,
			&i.FillID,
			&i.State,
			&i.Attempts,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.ClaimToken,
			&i.FailureCode,
			&i.LastError,
			&i.SuggestionID,
			&i.Audit,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClaimedJob = `-- name: LockClaimedJob :one
SELECT id, tenant_id, project_id, message_id, message_key, namespace, locale, source_revision, knowledge_fingerprint, trigger, fill_id, state, attempts, max_attempts, available_at, claim_token, failure_code, last_error, suggestion_id, audit, created_by, created_at, started_at, finished_at, updated_at FROM intelligence_jobs
WHERE id = $1 AND claim_token = $2::uuid AND state = 'running'
FOR UPDATE
`

type LockClaimedJobParams struct {
	ID         uuid.UUID
	ClaimToken uuid.UUID
}

// LockClaimedJob locks a job the caller still holds (its claim token):
// settlement is fenced, so a worker whose lease expired changes nothing.
func (q *Queries) LockClaimedJob(ctx context.Context, arg LockClaimedJobParams) (IntelligenceJob, error) {
	row := q.db.QueryRow(ctx, lockClaimedJob, arg.ID, arg.ClaimToken)
	var i IntelligenceJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.MessageID,
		&i.MessageKey,
		&i.Namespace,
		&i.Locale,
		&i.SourceRevision,
		&i.KnowledgeFingerprint,
		&i.Trigger,
		&i.FillID,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimToken,
		&i.FailureCode,
		&i.LastError,
		&i.SuggestionID,
		&i.Audit,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockClaims = `-- name: LockClaims :exec
SELECT pg_advisory_xact_lock(hashtext('glossa.intelligence.claim'))
`

func (q *Queries) LockClaims(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockClaims)
	return err
}

const queueDepth = `-- name: QueueDepth :many
SELECT state, count(*)::bigint AS n FROM intelligence_jobs WHERE state IN ('queued', 'running') GROUP BY state
`

type QueueDepthRow struct {
	State string
	N     int64
}

func (q *Queries) QueueDepth(ctx context.Context) ([]QueueDepthRow, error) {
	rows, err := q.db.Query(ctx, queueDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueDepthRow
	for rows.Next() {
		var i QueueDepthRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :exec
UPDATE intelligence_jobs
SET state = 'queued', available_at = now() + make_interval(secs => $1::float8), failure_code = $2,
    last_error = $3, audit = $4, claim_token = NULL, updated_at = $5
WHERE id = $6
`

type RetryJobParams struct {
	DelaySeconds float64
	FailureCode  pgtype.Text
	LastError    pgtype.Text
	Audit        []byte
	Now          time.Time
	ID           uuid.UUID
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.Exec(ctx, retryJob,
		arg.DelaySeconds,
		arg.FailureCode,
		arg.LastError,
		arg.Audit,
		arg.Now,
		arg.ID,
	)
	return err
}
