// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suggestions.sql

package intelligencesql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decideSuggestion = `-- name: DecideSuggestion :execrows
UPDATE intelligence_suggestions
SET status = $1, translation_revision = $2,
    decided_by = $3, decided_at = $4, decision = $5,
    action_note = $6, version = version + 1
WHERE id = $7 AND version = $8
`

type DecideSuggestionParams struct {
	Status              string
	TranslationRevision pgtype.Int4
	DecidedBy           pgtype.Text
	DecidedAt           pgtype.Timestamptz
	Decision            []byte
	ActionNote          pgtype.Text
	ID                  uuid.UUID
	ExpectedVersion     int32
}

func (q *Queries) DecideSuggestion(ctx context.Context, arg DecideSuggestionParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideSuggestion,
		arg.Status,
		arg.TranslationRevision,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.Decision,
		arg.ActionNote,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decisionStats = `-- name: DecisionStats :many
SELECT locale,
       count(*) FILTER (WHERE status = 'accepted')::bigint AS accepted,
       count(*) FILTER (WHERE status = 'accepted' AND decision ? 'edit')::bigint AS edited,
       count(*) FILTER (WHERE status = 'rejected')::bigint AS rejected,
       coalesce(avg(coalesce((decision -> 'edit' ->> 'distance')::float8, 0)) FILTER (WHERE status = 'accepted'), 0)::float8 AS mean_edit_distance,
       coalesce(avg(coalesce((decision -> 'edit' ->> 'ratio')::float8, 0)) FILTER (WHERE status = 'accepted'), 0)::float8 AS mean_edit_ratio
FROM intelligence_suggestions
WHERE project_id = $1 AND decided_at >= $2 AND status IN ('accepted', 'rejected')
GROUP BY locale
ORDER BY locale
`

type DecisionStatsParams struct {
	ProjectID uuid.UUID
	Since     pgtype.Timestamptz
}

type DecisionStatsRow struct {
	Locale           string
	Accepted         int64
	Edited           int64
	Rejected         int64
	MeanEditDistance float64
	MeanEditRatio    float64
}

// DecisionStats summarizes people's decisions on a project's
// suggestions per locale since a time: the acceptance rate and edit
// distance metrics.
func (q *Queries) DecisionStats(ctx context.Context, arg DecisionStatsParams) ([]DecisionStatsRow, error) {
	rows, err := q.db.Query(ctx, decisionStats, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecisionStatsRow
	for rows.Next() {
		var i DecisionStatsRow
		if err := rows.Scan(
			&i.Locale,
			&i.Accepted,
			&i.Edited,
			&i.Rejected,
			&i.MeanEditDistance,
			&i.MeanEditRatio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuggestion = `-- name: GetSuggestion :one
SELECT id, tenant_id, job_id, project_id, message_id, message_key, namespace, locale, source_revision, message_mf2, model, findings, term_findings, provenance, origin, score, explanation, action, action_note, risk_tags, calls, usage, cost_micro_usd, status, translation_revision, decided_by, decided_at, decision, version, created_at FROM intelligence_suggestions WHERE id = $1
`

func (q *Queries) GetSuggestion(ctx context.Context, id uuid.UUID) (IntelligenceSuggestion, error) {
	row := q.db.QueryRow(ctx, getSuggestion, id)
	var i IntelligenceSuggestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.ProjectID,
		&i.MessageID,
		&i.MessageKey,
		&i.Namespace,
		&i.Locale,
		&i.SourceRevision,
		&i.MessageMf2,
		&i.Model,
		&i.Findings,
		&i.TermFindings,
		&i.Provenance,
		&i.Origin,
		&i.Score,
		&i.Explanation,
		&i.Action,
		&i.ActionNote,
		&i.RiskTags,
		&i.Calls,
		&i.Usage,
		&i.CostMicroUsd,
		&i.Status,
		&i.TranslationRevision,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Decision,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const insertDisclosure = `-- name: InsertDisclosure :exec

INSERT INTO intelligence_disclosures (
    id, tenant_id, job_id, project_id, message_id, locale, task, provider, model, system_sha256, sent, occurred_at
) VALUES (
    $1, app_current_tenant(), $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
ON CONFLICT (id) DO NOTHING
`

type InsertDisclosureParams struct {
	ID           uuid.UUID
	JobID        uuid.UUID
	ProjectID    uuid.UUID
	MessageID    uuid.UUID
	Locale       string
	Task         string
	Provider     string
	Model        string
	SystemSha256 string
	Sent         json.RawMessage
	OccurredAt   time.Time
}

// ── disclosures ────────────────────────────────────────────────────
func (q *Queries) InsertDisclosure(ctx context.Context, arg InsertDisclosureParams) error {
	_, err := q.db.Exec(ctx, insertDisclosure,
		arg.ID,
		arg.JobID,
		arg.ProjectID,
		arg.MessageID,
		arg.Locale,
		arg.Task,
		arg.Provider,
		arg.Model,
		arg.SystemSha256,
		arg.Sent,
		arg.OccurredAt,
	)
	return err
}

const insertSuggestion = `-- name: InsertSuggestion :exec
INSERT INTO intelligence_suggestions (
    id, tenant_id, job_id, project_id, message_id, message_key, namespace, locale, source_revision,
    message_mf2, model, findings, term_findings, provenance, origin, score, explanation, action, action_note,
    risk_tags, calls, usage, cost_micro_usd, status, version, created_at
) VALUES (
    $1, app_current_tenant(), $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18,
    $19::text[], $20, $21, $22, $23, 1,
    $24
)
`

type InsertSuggestionParams struct {
	ID             uuid.UUID
	JobID          uuid.UUID
	ProjectID      uuid.UUID
	MessageID      uuid.UUID
	MessageKey     string
	Namespace      string
	Locale         string
	SourceRevision int32
	MessageMf2     string
	Model          json.RawMessage
	Findings       json.RawMessage
	TermFindings   json.RawMessage
	Provenance     json.RawMessage
	Origin         string
	Score          float64
	Explanation    json.RawMessage
	Action         string
	ActionNote     pgtype.Text
	RiskTags       []string
	Calls          json.RawMessage
	Usage          json.RawMessage
	CostMicroUsd   int64
	Status         string
	CreatedAt      time.Time
}

func (q *Queries) InsertSuggestion(ctx context.Context, arg InsertSuggestionParams) error {
	_, err := q.db.Exec(ctx, insertSuggestion,
		arg.ID,
		arg.JobID,
		arg.ProjectID,
		arg.MessageID,
		arg.MessageKey,
		arg.Namespace,
		arg.Locale,
		arg.SourceRevision,
		arg.MessageMf2,
		arg.Model,
		arg.Findings,
		arg.TermFindings,
		arg.Provenance,
		arg.Origin,
		arg.Score,
		arg.Explanation,
		arg.Action,
		arg.ActionNote,
		arg.RiskTags,
		arg.Calls,
		arg.Usage,
		arg.CostMicroUsd,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const listDisclosures = `-- name: ListDisclosures :many
SELECT id, tenant_id, job_id, project_id, message_id, locale, task, provider, model, system_sha256, sent, occurred_at FROM intelligence_disclosures
WHERE ($1::uuid IS NULL OR job_id = $1::uuid)
  AND ($2::uuid IS NULL OR message_id = $2::uuid)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::text IS NULL OR provider = $4::text)
  AND ($5::timestamptz IS NULL OR (occurred_at, id) < ($5::timestamptz, $6::uuid))
ORDER BY occurred_at DESC, id DESC
LIMIT $7::int
`

type ListDisclosuresParams struct {
	JobID     uuid.NullUUID
	MessageID uuid.NullUUID
	ProjectID uuid.NullUUID
	Provider  pgtype.Text
	BeforeAt  pgtype.Timestamptz
	BeforeID  uuid.UUID
	MaxRows   int32
}

func (q *Queries) ListDisclosures(ctx context.Context, arg ListDisclosuresParams) ([]IntelligenceDisclosure, error) {
	rows, err := q.db.Query(ctx, listDisclosures,
		arg.JobID,
		arg.MessageID,
		arg.ProjectID,
		arg.Provider,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntelligenceDisclosure
	for rows.Next() {
		var i IntelligenceDisclosure
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.ProjectID,
			&i.MessageID,
			&i.Locale,
			&i.Task,
			&i.Provider,
			&i.Model,
			&i.SystemSha256,
			&i.Sent,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuggestions = `-- name: ListSuggestions :many
SELECT id, tenant_id, job_id, project_id, message_id, message_key, namespace, locale, source_revision, message_mf2, model, findings, term_findings, provenance, origin, score, explanation, action, action_note, risk_tags, calls, usage, cost_micro_usd, status, translation_revision, decided_by, decided_at, decision, version, created_at FROM intelligence_suggestions
WHERE ($1::uuid IS NULL OR project_id = $1::uuid)
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR locale = $3::text)
  AND ($4::uuid IS NULL OR message_id = $4::uuid)
  AND ($5::uuid IS NULL OR job_id = $5::uuid)
  AND ($6::timestamptz IS NULL OR (created_at, id) < ($6::timestamptz, $7::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $8::int
`

type ListSuggestionsParams struct {
	ProjectID uuid.NullUUID
	Status    pgtype.Text
	Locale    pgtype.Text
	MessageID uuid.NullUUID
	JobID     uuid.NullUUID
	BeforeAt  pgtype.Timestamptz
	BeforeID  uuid.UUID
	MaxRows   int32
}

func (q *Queries) ListSuggestions(ctx context.Context, arg ListSuggestionsParams) ([]IntelligenceSuggestion, error) {
	rows, err := q.db.Query(ctx, listSuggestions,
		arg.ProjectID,
		arg.Status,
		arg.Locale,
		arg.MessageID,
		arg.JobID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntelligenceSuggestion
	for rows.Next() {
		var i IntelligenceSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.ProjectID,
			&i.MessageID,
			&i.MessageKey,
			&i.Namespace,
			&i.Locale,
			&i.SourceRevision,
			&i.MessageMf2,
			&i.Model,
			&i.Findings,
			&i.TermFindings,
			&i.Provenance,
			&i.Origin,
			&i.Score,
			&i.Explanation,
			&i.Action,
			&i.ActionNote,
			&i.RiskTags,
			&i.Calls,
			&i.Usage,
			&i.CostMicroUsd,
			&i.Status,
			&i.TranslationRevision,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Decision,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSuggestion = `-- name: LockSuggestion :one
SELECT id, tenant_id, job_id, project_id, message_id, message_key, namespace, locale, source_revision, message_mf2, model, findings, term_findings, provenance, origin, score, explanation, action, action_note, risk_tags, calls, usage, cost_micro_usd, status, translation_revision, decided_by, decided_at, decision, version, created_at FROM intelligence_suggestions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSuggestion(ctx context.Context, id uuid.UUID) (IntelligenceSuggestion, error) {
	row := q.db.QueryRow(ctx, lockSuggestion, id)
	var i IntelligenceSuggestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.ProjectID,
		&i.MessageID,
		&i.MessageKey,
		&i.Namespace,
		&i.Locale,
		&i.SourceRevision,
		&i.MessageMf2,
		&i.Model,
		&i.Findings,
		&i.TermFindings,
		&i.Provenance,
		&i.Origin,
		&i.Score,
		&i.Explanation,
		&i.Action,
		&i.ActionNote,
		&i.RiskTags,
		&i.Calls,
		&i.Usage,
		&i.CostMicroUsd,
		&i.Status,
		&i.TranslationRevision,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Decision,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const reviewQueue = `-- name: ReviewQueue :many
SELECT id, tenant_id, job_id, project_id, message_id, message_key, namespace, locale, source_revision, message_mf2, model, findings, term_findings, provenance, origin, score, explanation, action, action_note, risk_tags, calls, usage, cost_micro_usd, status, translation_revision, decided_by, decided_at, decision, version, created_at FROM intelligence_suggestions
WHERE project_id = $1 AND status = 'pending'
  AND (cardinality($2::text[]) = 0 OR locale = ANY ($2::text[]))
  AND (NOT $3::boolean
       OR (score, -cardinality(risk_tags), id) > ($4::float8, $5::int, $6::uuid))
ORDER BY score, cardinality(risk_tags) DESC, id
LIMIT $7::int
`

type ReviewQueueParams struct {
	ProjectID  uuid.UUID
	Locales    []string
	HasAfter   bool
	AfterScore float64
	AfterRisk  int32
	AfterID    uuid.UUID
	MaxRows    int32
}

// ReviewQueue lists a project's pending suggestions by risk: lowest
// score first, then the most risk tags, then id (keyset).
func (q *Queries) ReviewQueue(ctx context.Context, arg ReviewQueueParams) ([]IntelligenceSuggestion, error) {
	rows, err := q.db.Query(ctx, reviewQueue,
		arg.ProjectID,
		arg.Locales,
		arg.HasAfter,
		arg.AfterScore,
		arg.AfterRisk,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntelligenceSuggestion
	for rows.Next() {
		var i IntelligenceSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.ProjectID,
			&i.MessageID,
			&i.MessageKey,
			&i.Namespace,
			&i.Locale,
			&i.SourceRevision,
			&i.MessageMf2,
			&i.Model,
			&i.Findings,
			&i.TermFindings,
			&i.Provenance,
			&i.Origin,
			&i.Score,
			&i.Explanation,
			&i.Action,
			&i.ActionNote,
			&i.RiskTags,
			&i.Calls,
			&i.Usage,
			&i.CostMicroUsd,
			&i.Status,
			&i.TranslationRevision,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Decision,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestionCounts = `-- name: SuggestionCounts :many
SELECT locale, status, count(*)::bigint AS n
FROM intelligence_suggestions
WHERE project_id = $1 AND created_at >= $2
GROUP BY locale, status
`

type SuggestionCountsParams struct {
	ProjectID uuid.UUID
	Since     time.Time
}

type SuggestionCountsRow struct {
	Locale string
	Status string
	N      int64
}

func (q *Queries) SuggestionCounts(ctx context.Context, arg SuggestionCountsParams) ([]SuggestionCountsRow, error) {
	rows, err := q.db.Query(ctx, suggestionCounts, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestionCountsRow
	for rows.Next() {
		var i SuggestionCountsRow
		if err := rows.Scan(&i.Locale, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedePending = `-- name: SupersedePending :exec
UPDATE intelligence_suggestions
SET status = 'superseded', version = version + 1
WHERE message_id = $1 AND locale = $2 AND status = 'pending' AND id <> $3
`

type SupersedePendingParams struct {
	MessageID uuid.UUID
	Locale    string
	Keep      uuid.UUID
}

// SupersedePending retires the pending suggestions of a message and
// locale other than keep: only the newest waits for review.
func (q *Queries) SupersedePending(ctx context.Context, arg SupersedePendingParams) error {
	_, err := q.db.Exec(ctx, supersedePending, arg.MessageID, arg.Locale, arg.Keep)
	return err
}
