// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package knowledgesql

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type KnowledgeConcept struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ProjectID  uuid.NullUUID
	Definition string
	Domain     string
	Note       string
	ProductRef string
	Version    int32
	CreatedBy  string
	CreatedAt  time.Time
	UpdatedBy  string
	UpdatedAt  time.Time
}

type KnowledgeConceptRevision struct {
	TenantID  uuid.UUID
	ConceptID uuid.UUID
	ProjectID uuid.NullUUID
	Version   int32
	Action    string
	Snapshot  json.RawMessage
	Author    string
	CreatedAt time.Time
}

type KnowledgeStyleGuide struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ProjectID uuid.NullUUID
	Locale    pgtype.Text
	Namespace pgtype.Text
	Name      string
	Fields    json.RawMessage
	Rules     json.RawMessage
	Version   int32
	CreatedBy string
	CreatedAt time.Time
	UpdatedBy string
	UpdatedAt time.Time
}

type KnowledgeStyleGuideVersion struct {
	TenantID     uuid.UUID
	StyleGuideID uuid.UUID
	Version      int32
	Action       string
	ProjectID    uuid.NullUUID
	Locale       pgtype.Text
	Namespace    pgtype.Text
	Name         string
	Fields       json.RawMessage
	Rules        json.RawMessage
	Author       string
	CreatedAt    time.Time
}

type KnowledgeTerm struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	ConceptID     uuid.UUID
	Position      int32
	Locale        string
	Text          string
	Status        string
	PartOfSpeech  string
	CaseSensitive bool
	Note          string
}

type KnowledgeTmUnit struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	ProjectID           uuid.NullUUID
	Origin              string
	TranslationID       uuid.NullUUID
	TranslationRevision pgtype.Int4
	MessageID           uuid.NullUUID
	MessageKey          string
	Namespace           string
	SourceLocale        string
	TargetLocale        string
	SourceMf2           string
	TargetMf2           string
	TargetModel         json.RawMessage
	SourceNormalized    string
	TargetNormalized    string
	SourceHash          string
	Signature           string
	SourceVars          json.RawMessage
	HitCount            int32
	LastHitAt           pgtype.Timestamptz
	CreatedBy           string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	RetiredAt           pgtype.Timestamptz
	RetiredReason       pgtype.Text
	RetiredBy           pgtype.Text
}
