// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: style.sql

package knowledgesql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectStyleGuideVersions = `-- name: DeleteProjectStyleGuideVersions :exec
DELETE FROM knowledge_style_guide_versions WHERE project_id = $1
`

func (q *Queries) DeleteProjectStyleGuideVersions(ctx context.Context, projectID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteProjectStyleGuideVersions, projectID)
	return err
}

const deleteProjectStyleGuides = `-- name: DeleteProjectStyleGuides :exec
DELETE FROM knowledge_style_guides WHERE project_id = $1
`

func (q *Queries) DeleteProjectStyleGuides(ctx context.Context, projectID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteProjectStyleGuides, projectID)
	return err
}

const deleteStyleGuide = `-- name: DeleteStyleGuide :exec
DELETE FROM knowledge_style_guides WHERE id = $1
`

func (q *Queries) DeleteStyleGuide(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStyleGuide, id)
	return err
}

const getStyleGuide = `-- name: GetStyleGuide :one
SELECT id, tenant_id, project_id, locale, namespace, name, fields, rules, version, created_by, created_at, updated_by, updated_at FROM knowledge_style_guides WHERE id = $1
`

func (q *Queries) GetStyleGuide(ctx context.Context, id uuid.UUID) (KnowledgeStyleGuide, error) {
	row := q.db.QueryRow(ctx, getStyleGuide, id)
	var i KnowledgeStyleGuide
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Locale,
		&i.Namespace,
		&i.Name,
		&i.Fields,
		&i.Rules,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStyleGuide = `-- name: InsertStyleGuide :execrows

INSERT INTO knowledge_style_guides (id, tenant_id, project_id, locale, namespace, name, fields, rules, version,
                                    created_by, created_at, updated_by, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $9,
        $10, $11, $12)
ON CONFLICT (id) DO NOTHING
`

type InsertStyleGuideParams struct {
	ID        uuid.UUID
	ProjectID uuid.NullUUID
	Locale    pgtype.Text
	Namespace pgtype.Text
	Name      string
	Fields    json.RawMessage
	Rules     json.RawMessage
	Version   int32
	CreatedBy string
	CreatedAt time.Time
	UpdatedBy string
	UpdatedAt time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
// ON CONFLICT (id): a retried create with the same Idempotency-Key.
// Another guide at the same scope violates knowledge_style_guides_scope.
func (q *Queries) InsertStyleGuide(ctx context.Context, arg InsertStyleGuideParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertStyleGuide,
		arg.ID,
		arg.ProjectID,
		arg.Locale,
		arg.Namespace,
		arg.Name,
		arg.Fields,
		arg.Rules,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertStyleGuideVersion = `-- name: InsertStyleGuideVersion :exec
INSERT INTO knowledge_style_guide_versions (tenant_id, style_guide_id, version, action, project_id, locale,
                                            namespace, name, fields, rules, author, created_at)
VALUES (app_current_tenant(), $1, $2, $3, $4,
        $5, $6, $7, $8, $9,
        $10, $11)
`

type InsertStyleGuideVersionParams struct {
	StyleGuideID uuid.UUID
	Version      int32
	Action       string
	ProjectID    uuid.NullUUID
	Locale       pgtype.Text
	Namespace    pgtype.Text
	Name         string
	Fields       json.RawMessage
	Rules        json.RawMessage
	Author       string
	CreatedAt    time.Time
}

func (q *Queries) InsertStyleGuideVersion(ctx context.Context, arg InsertStyleGuideVersionParams) error {
	_, err := q.db.Exec(ctx, insertStyleGuideVersion,
		arg.StyleGuideID,
		arg.Version,
		arg.Action,
		arg.ProjectID,
		arg.Locale,
		arg.Namespace,
		arg.Name,
		arg.Fields,
		arg.Rules,
		arg.Author,
		arg.CreatedAt,
	)
	return err
}

const listStyleGuideVersions = `-- name: ListStyleGuideVersions :many
SELECT tenant_id, style_guide_id, version, action, project_id, locale, namespace, name, fields, rules, author, created_at FROM knowledge_style_guide_versions
WHERE style_guide_id = $1 AND version < $2
ORDER BY version DESC
LIMIT $3
`

type ListStyleGuideVersionsParams struct {
	StyleGuideID uuid.UUID
	Before       int32
	MaxRows      int32
}

func (q *Queries) ListStyleGuideVersions(ctx context.Context, arg ListStyleGuideVersionsParams) ([]KnowledgeStyleGuideVersion, error) {
	rows, err := q.db.Query(ctx, listStyleGuideVersions, arg.StyleGuideID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeStyleGuideVersion
	for rows.Next() {
		var i KnowledgeStyleGuideVersion
		if err := rows.Scan(
			&i.TenantID,
			&i.StyleGuideID,
			&i.Version,
			&i.Action,
			&i.ProjectID,
			&i.Locale,
			&i.Namespace,
			&i.Name,
			&i.Fields,
			&i.Rules,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStyleGuides = `-- name: ListStyleGuides :many
SELECT id, tenant_id, project_id, locale, namespace, name, fields, rules, version, created_by, created_at, updated_by, updated_at FROM knowledge_style_guides
WHERE id > $1
  AND (NOT $2::boolean OR project_id IS NULL)
  AND ($3::uuid IS NULL OR project_id = $3)
  AND ($4::text IS NULL OR locale = $4)
ORDER BY id
LIMIT $5
`

type ListStyleGuidesParams struct {
	After      uuid.UUID
	TenantOnly bool
	ProjectID  uuid.NullUUID
	Locale     pgtype.Text
	MaxRows    int32
}

// Guides in id order after the cursor, optionally of one project or
// tenant-level only, and of one locale.
func (q *Queries) ListStyleGuides(ctx context.Context, arg ListStyleGuidesParams) ([]KnowledgeStyleGuide, error) {
	rows, err := q.db.Query(ctx, listStyleGuides,
		arg.After,
		arg.TenantOnly,
		arg.ProjectID,
		arg.Locale,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeStyleGuide
	for rows.Next() {
		var i KnowledgeStyleGuide
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Locale,
			&i.Namespace,
			&i.Name,
			&i.Fields,
			&i.Rules,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStyleGuide = `-- name: LockStyleGuide :one
SELECT id, tenant_id, project_id, locale, namespace, name, fields, rules, version, created_by, created_at, updated_by, updated_at FROM knowledge_style_guides WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockStyleGuide(ctx context.Context, id uuid.UUID) (KnowledgeStyleGuide, error) {
	row := q.db.QueryRow(ctx, lockStyleGuide, id)
	var i KnowledgeStyleGuide
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Locale,
		&i.Namespace,
		&i.Name,
		&i.Fields,
		&i.Rules,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const styleGuidesInScope = `-- name: StyleGuidesInScope :many
SELECT id, tenant_id, project_id, locale, namespace, name, fields, rules, version, created_by, created_at, updated_by, updated_at FROM knowledge_style_guides
WHERE project_id IS NULL OR project_id = $1
ORDER BY id
`

// Every guide that may apply to a project (or to tenant-level text):
// the domain picks the applicable ones and merges them.
func (q *Queries) StyleGuidesInScope(ctx context.Context, projectID uuid.NullUUID) ([]KnowledgeStyleGuide, error) {
	rows, err := q.db.Query(ctx, styleGuidesInScope, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeStyleGuide
	for rows.Next() {
		var i KnowledgeStyleGuide
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Locale,
			&i.Namespace,
			&i.Name,
			&i.Fields,
			&i.Rules,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStyleGuide = `-- name: UpdateStyleGuide :execrows
UPDATE knowledge_style_guides
SET name = $1, fields = $2, rules = $3, version = $4,
    updated_by = $5, updated_at = $6
WHERE id = $7 AND version = $8
`

type UpdateStyleGuideParams struct {
	Name            string
	Fields          json.RawMessage
	Rules           json.RawMessage
	Version         int32
	UpdatedBy       string
	UpdatedAt       time.Time
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateStyleGuide(ctx context.Context, arg UpdateStyleGuideParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStyleGuide,
		arg.Name,
		arg.Fields,
		arg.Rules,
		arg.Version,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
