// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terms.sql

package knowledgesql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const conceptsWithTermsIn = `-- name: ConceptsWithTermsIn :many
SELECT c.id, c.tenant_id, c.project_id, c.definition, c.domain, c.note, c.product_ref, c.version, c.created_by, c.created_at, c.updated_by, c.updated_at FROM knowledge_concepts c
WHERE (c.project_id IS NULL OR c.project_id = $1)
  AND EXISTS (SELECT FROM knowledge_terms t WHERE t.concept_id = c.id AND t.locale = ANY ($2::text[]))
ORDER BY c.id
`

type ConceptsWithTermsInParams struct {
	ProjectID uuid.NullUUID
	Locales   []string
}

// The concepts in scope with a term in any of the locales: what
// recognition and terminology QA need for a locale pair.
func (q *Queries) ConceptsWithTermsIn(ctx context.Context, arg ConceptsWithTermsInParams) ([]KnowledgeConcept, error) {
	rows, err := q.db.Query(ctx, conceptsWithTermsIn, arg.ProjectID, arg.Locales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeConcept
	for rows.Next() {
		var i KnowledgeConcept
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Definition,
			&i.Domain,
			&i.Note,
			&i.ProductRef,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteConcept = `-- name: DeleteConcept :exec
DELETE FROM knowledge_concepts WHERE id = $1
`

func (q *Queries) DeleteConcept(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConcept, id)
	return err
}

const deleteProjectConceptRevisions = `-- name: DeleteProjectConceptRevisions :exec
DELETE FROM knowledge_concept_revisions WHERE project_id = $1
`

func (q *Queries) DeleteProjectConceptRevisions(ctx context.Context, projectID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteProjectConceptRevisions, projectID)
	return err
}

const deleteProjectConcepts = `-- name: DeleteProjectConcepts :exec
DELETE FROM knowledge_concepts WHERE project_id = $1
`

func (q *Queries) DeleteProjectConcepts(ctx context.Context, projectID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteProjectConcepts, projectID)
	return err
}

const deleteTermsOfConcept = `-- name: DeleteTermsOfConcept :exec
DELETE FROM knowledge_terms WHERE concept_id = $1
`

func (q *Queries) DeleteTermsOfConcept(ctx context.Context, conceptID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTermsOfConcept, conceptID)
	return err
}

const getConcept = `-- name: GetConcept :one
SELECT id, tenant_id, project_id, definition, domain, note, product_ref, version, created_by, created_at, updated_by, updated_at FROM knowledge_concepts WHERE id = $1
`

func (q *Queries) GetConcept(ctx context.Context, id uuid.UUID) (KnowledgeConcept, error) {
	row := q.db.QueryRow(ctx, getConcept, id)
	var i KnowledgeConcept
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Definition,
		&i.Domain,
		&i.Note,
		&i.ProductRef,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConcept = `-- name: InsertConcept :execrows

INSERT INTO knowledge_concepts (id, tenant_id, project_id, definition, domain, note, product_ref, version,
                                created_by, created_at, updated_by, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $9,
        $10, $11)
ON CONFLICT (id) DO NOTHING
`

type InsertConceptParams struct {
	ID         uuid.UUID
	ProjectID  uuid.NullUUID
	Definition string
	Domain     string
	Note       string
	ProductRef string
	Version    int32
	CreatedBy  string
	CreatedAt  time.Time
	UpdatedBy  string
	UpdatedAt  time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
// ON CONFLICT: an Idempotency-Key derives the ID, so a retried create
// inserts nothing and the caller replays the first.
func (q *Queries) InsertConcept(ctx context.Context, arg InsertConceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertConcept,
		arg.ID,
		arg.ProjectID,
		arg.Definition,
		arg.Domain,
		arg.Note,
		arg.ProductRef,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertConceptRevision = `-- name: InsertConceptRevision :exec
INSERT INTO knowledge_concept_revisions (tenant_id, concept_id, project_id, version, action, snapshot, author,
                                         created_at)
VALUES (app_current_tenant(), $1, $2, $3, $4,
        $5, $6, $7)
`

type InsertConceptRevisionParams struct {
	ConceptID uuid.UUID
	ProjectID uuid.NullUUID
	Version   int32
	Action    string
	Snapshot  json.RawMessage
	Author    string
	CreatedAt time.Time
}

func (q *Queries) InsertConceptRevision(ctx context.Context, arg InsertConceptRevisionParams) error {
	_, err := q.db.Exec(ctx, insertConceptRevision,
		arg.ConceptID,
		arg.ProjectID,
		arg.Version,
		arg.Action,
		arg.Snapshot,
		arg.Author,
		arg.CreatedAt,
	)
	return err
}

const insertTerm = `-- name: InsertTerm :exec
INSERT INTO knowledge_terms (id, tenant_id, concept_id, position, locale, text, status, part_of_speech,
                             case_sensitive, note)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $9)
`

type InsertTermParams struct {
	ID            uuid.UUID
	ConceptID     uuid.UUID
	Position      int32
	Locale        string
	Text          string
	Status        string
	PartOfSpeech  string
	CaseSensitive bool
	Note          string
}

func (q *Queries) InsertTerm(ctx context.Context, arg InsertTermParams) error {
	_, err := q.db.Exec(ctx, insertTerm,
		arg.ID,
		arg.ConceptID,
		arg.Position,
		arg.Locale,
		arg.Text,
		arg.Status,
		arg.PartOfSpeech,
		arg.CaseSensitive,
		arg.Note,
	)
	return err
}

const listConceptRevisions = `-- name: ListConceptRevisions :many
SELECT tenant_id, concept_id, project_id, version, action, snapshot, author, created_at FROM knowledge_concept_revisions
WHERE concept_id = $1 AND version < $2
ORDER BY version DESC
LIMIT $3
`

type ListConceptRevisionsParams struct {
	ConceptID uuid.UUID
	Before    int32
	MaxRows   int32
}

func (q *Queries) ListConceptRevisions(ctx context.Context, arg ListConceptRevisionsParams) ([]KnowledgeConceptRevision, error) {
	rows, err := q.db.Query(ctx, listConceptRevisions, arg.ConceptID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeConceptRevision
	for rows.Next() {
		var i KnowledgeConceptRevision
		if err := rows.Scan(
			&i.TenantID,
			&i.ConceptID,
			&i.ProjectID,
			&i.Version,
			&i.Action,
			&i.Snapshot,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConcepts = `-- name: ListConcepts :many
SELECT c.id, c.tenant_id, c.project_id, c.definition, c.domain, c.note, c.product_ref, c.version, c.created_by, c.created_at, c.updated_by, c.updated_at FROM knowledge_concepts c
WHERE c.id > $1
  AND ($2::uuid IS NULL OR c.project_id IS NULL OR c.project_id = $2)
  AND ($3::text IS NULL OR c.domain = $3)
  AND ($4::text IS NULL
       OR EXISTS (SELECT FROM knowledge_terms t WHERE t.concept_id = c.id AND t.locale = $4))
  AND ($5::text IS NULL
       OR c.definition ILIKE $5
       OR EXISTS (SELECT FROM knowledge_terms t
                  WHERE t.concept_id = c.id AND t.text ILIKE $5
                    AND ($4::text IS NULL OR t.locale = $4)))
ORDER BY c.id
LIMIT $6
`

type ListConceptsParams struct {
	After     uuid.UUID
	ProjectID uuid.NullUUID
	Domain    pgtype.Text
	Locale    pgtype.Text
	Pattern   pgtype.Text
	MaxRows   int32
}

// Concepts in id order after the cursor. project: that project's and
// the tenant-wide ones (the termbase that applies to it). pattern
// (ILIKE) searches term texts (in locale, when given) and definitions.
func (q *Queries) ListConcepts(ctx context.Context, arg ListConceptsParams) ([]KnowledgeConcept, error) {
	rows, err := q.db.Query(ctx, listConcepts,
		arg.After,
		arg.ProjectID,
		arg.Domain,
		arg.Locale,
		arg.Pattern,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeConcept
	for rows.Next() {
		var i KnowledgeConcept
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Definition,
			&i.Domain,
			&i.Note,
			&i.ProductRef,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConcept = `-- name: LockConcept :one
SELECT id, tenant_id, project_id, definition, domain, note, product_ref, version, created_by, created_at, updated_by, updated_at FROM knowledge_concepts WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockConcept(ctx context.Context, id uuid.UUID) (KnowledgeConcept, error) {
	row := q.db.QueryRow(ctx, lockConcept, id)
	var i KnowledgeConcept
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Definition,
		&i.Domain,
		&i.Note,
		&i.ProductRef,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const termsOfConcepts = `-- name: TermsOfConcepts :many
SELECT id, tenant_id, concept_id, position, locale, text, status, part_of_speech, case_sensitive, note FROM knowledge_terms WHERE concept_id = ANY ($1::uuid[])
ORDER BY concept_id, position
`

func (q *Queries) TermsOfConcepts(ctx context.Context, conceptIds []uuid.UUID) ([]KnowledgeTerm, error) {
	rows, err := q.db.Query(ctx, termsOfConcepts, conceptIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeTerm
	for rows.Next() {
		var i KnowledgeTerm
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConceptID,
			&i.Position,
			&i.Locale,
			&i.Text,
			&i.Status,
			&i.PartOfSpeech,
			&i.CaseSensitive,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConcept = `-- name: UpdateConcept :execrows
UPDATE knowledge_concepts
SET definition = $1, domain = $2, note = $3,
    product_ref = $4, version = $5, updated_by = $6,
    updated_at = $7
WHERE id = $8 AND version = $9
`

type UpdateConceptParams struct {
	Definition      string
	Domain          string
	Note            string
	ProductRef      string
	Version         int32
	UpdatedBy       string
	UpdatedAt       time.Time
	ID              uuid.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateConcept(ctx context.Context, arg UpdateConceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConcept,
		arg.Definition,
		arg.Domain,
		arg.Note,
		arg.ProductRef,
		arg.Version,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
