// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tm.sql

package knowledgesql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const concordanceSource = `-- name: ConcordanceSource :many
SELECT knowledge_tm_units.id, knowledge_tm_units.tenant_id, knowledge_tm_units.project_id, knowledge_tm_units.origin, knowledge_tm_units.translation_id, knowledge_tm_units.translation_revision, knowledge_tm_units.message_id, knowledge_tm_units.message_key, knowledge_tm_units.namespace, knowledge_tm_units.source_locale, knowledge_tm_units.target_locale, knowledge_tm_units.source_mf2, knowledge_tm_units.target_mf2, knowledge_tm_units.target_model, knowledge_tm_units.source_normalized, knowledge_tm_units.target_normalized, knowledge_tm_units.source_hash, knowledge_tm_units.signature, knowledge_tm_units.source_vars, knowledge_tm_units.hit_count, knowledge_tm_units.last_hit_at, knowledge_tm_units.created_by, knowledge_tm_units.created_at, knowledge_tm_units.updated_at, knowledge_tm_units.retired_at, knowledge_tm_units.retired_reason, knowledge_tm_units.retired_by,
       word_similarity($1::text, knowledge_tm_units.source_normalized)::float8 AS similarity
FROM knowledge_tm_units
WHERE retired_at IS NULL
  AND ($2::text IS NULL OR source_locale = $2)
  AND ($3::text IS NULL OR target_locale = $3)
  AND ($4::boolean OR project_id IS NULL OR project_id = $5)
  AND source_normalized ILIKE $6::text
ORDER BY similarity DESC, updated_at DESC, id
LIMIT $7
`

type ConcordanceSourceParams struct {
	Query        string
	SourceLocale pgtype.Text
	TargetLocale pgtype.Text
	AllProjects  bool
	ProjectID    uuid.NullUUID
	Pattern      string
	MaxRows      int32
}

type ConcordanceSourceRow struct {
	KnowledgeTmUnit KnowledgeTmUnit
	Similarity      float64
}

// Active units whose source contains the pattern (ILIKE, trigram
// indexed), closest first.
func (q *Queries) ConcordanceSource(ctx context.Context, arg ConcordanceSourceParams) ([]ConcordanceSourceRow, error) {
	rows, err := q.db.Query(ctx, concordanceSource,
		arg.Query,
		arg.SourceLocale,
		arg.TargetLocale,
		arg.AllProjects,
		arg.ProjectID,
		arg.Pattern,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConcordanceSourceRow
	for rows.Next() {
		var i ConcordanceSourceRow
		if err := rows.Scan(
			&i.KnowledgeTmUnit.ID,
			&i.KnowledgeTmUnit.TenantID,
			&i.KnowledgeTmUnit.ProjectID,
			&i.KnowledgeTmUnit.Origin,
			&i.KnowledgeTmUnit.TranslationID,
			&i.KnowledgeTmUnit.TranslationRevision,
			&i.KnowledgeTmUnit.MessageID,
			&i.KnowledgeTmUnit.MessageKey,
			&i.KnowledgeTmUnit.Namespace,
			&i.KnowledgeTmUnit.SourceLocale,
			&i.KnowledgeTmUnit.TargetLocale,
			&i.KnowledgeTmUnit.SourceMf2,
			&i.KnowledgeTmUnit.TargetMf2,
			&i.KnowledgeTmUnit.TargetModel,
			&i.KnowledgeTmUnit.SourceNormalized,
			&i.KnowledgeTmUnit.TargetNormalized,
			&i.KnowledgeTmUnit.SourceHash,
			&i.KnowledgeTmUnit.Signature,
			&i.KnowledgeTmUnit.SourceVars,
			&i.KnowledgeTmUnit.HitCount,
			&i.KnowledgeTmUnit.LastHitAt,
			&i.KnowledgeTmUnit.CreatedBy,
			&i.KnowledgeTmUnit.CreatedAt,
			&i.KnowledgeTmUnit.UpdatedAt,
			&i.KnowledgeTmUnit.RetiredAt,
			&i.KnowledgeTmUnit.RetiredReason,
			&i.KnowledgeTmUnit.RetiredBy,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const concordanceTarget = `-- name: ConcordanceTarget :many
SELECT knowledge_tm_units.id, knowledge_tm_units.tenant_id, knowledge_tm_units.project_id, knowledge_tm_units.origin, knowledge_tm_units.translation_id, knowledge_tm_units.translation_revision, knowledge_tm_units.message_id, knowledge_tm_units.message_key, knowledge_tm_units.namespace, knowledge_tm_units.source_locale, knowledge_tm_units.target_locale, knowledge_tm_units.source_mf2, knowledge_tm_units.target_mf2, knowledge_tm_units.target_model, knowledge_tm_units.source_normalized, knowledge_tm_units.target_normalized, knowledge_tm_units.source_hash, knowledge_tm_units.signature, knowledge_tm_units.source_vars, knowledge_tm_units.hit_count, knowledge_tm_units.last_hit_at, knowledge_tm_units.created_by, knowledge_tm_units.created_at, knowledge_tm_units.updated_at, knowledge_tm_units.retired_at, knowledge_tm_units.retired_reason, knowledge_tm_units.retired_by,
       word_similarity($1::text, knowledge_tm_units.target_normalized)::float8 AS similarity
FROM knowledge_tm_units
WHERE retired_at IS NULL
  AND ($2::text IS NULL OR source_locale = $2)
  AND ($3::text IS NULL OR target_locale = $3)
  AND ($4::boolean OR project_id IS NULL OR project_id = $5)
  AND target_normalized ILIKE $6::text
ORDER BY similarity DESC, updated_at DESC, id
LIMIT $7
`

type ConcordanceTargetParams struct {
	Query        string
	SourceLocale pgtype.Text
	TargetLocale pgtype.Text
	AllProjects  bool
	ProjectID    uuid.NullUUID
	Pattern      string
	MaxRows      int32
}

type ConcordanceTargetRow struct {
	KnowledgeTmUnit KnowledgeTmUnit
	Similarity      float64
}

func (q *Queries) ConcordanceTarget(ctx context.Context, arg ConcordanceTargetParams) ([]ConcordanceTargetRow, error) {
	rows, err := q.db.Query(ctx, concordanceTarget,
		arg.Query,
		arg.SourceLocale,
		arg.TargetLocale,
		arg.AllProjects,
		arg.ProjectID,
		arg.Pattern,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConcordanceTargetRow
	for rows.Next() {
		var i ConcordanceTargetRow
		if err := rows.Scan(
			&i.KnowledgeTmUnit.ID,
			&i.KnowledgeTmUnit.TenantID,
			&i.KnowledgeTmUnit.ProjectID,
			&i.KnowledgeTmUnit.Origin,
			&i.KnowledgeTmUnit.TranslationID,
			&i.KnowledgeTmUnit.TranslationRevision,
			&i.KnowledgeTmUnit.MessageID,
			&i.KnowledgeTmUnit.MessageKey,
			&i.KnowledgeTmUnit.Namespace,
			&i.KnowledgeTmUnit.SourceLocale,
			&i.KnowledgeTmUnit.TargetLocale,
			&i.KnowledgeTmUnit.SourceMf2,
			&i.KnowledgeTmUnit.TargetMf2,
			&i.KnowledgeTmUnit.TargetModel,
			&i.KnowledgeTmUnit.SourceNormalized,
			&i.KnowledgeTmUnit.TargetNormalized,
			&i.KnowledgeTmUnit.SourceHash,
			&i.KnowledgeTmUnit.Signature,
			&i.KnowledgeTmUnit.SourceVars,
			&i.KnowledgeTmUnit.HitCount,
			&i.KnowledgeTmUnit.LastHitAt,
			&i.KnowledgeTmUnit.CreatedBy,
			&i.KnowledgeTmUnit.CreatedAt,
			&i.KnowledgeTmUnit.UpdatedAt,
			&i.KnowledgeTmUnit.RetiredAt,
			&i.KnowledgeTmUnit.RetiredReason,
			&i.KnowledgeTmUnit.RetiredBy,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTMHits = `-- name: CountTMHits :exec
UPDATE knowledge_tm_units SET hit_count = hit_count + 1, last_hit_at = $1
WHERE id = ANY ($2::uuid[])
`

type CountTMHitsParams struct {
	HitAt pgtype.Timestamptz
	Ids   []uuid.UUID
}

func (q *Queries) CountTMHits(ctx context.Context, arg CountTMHitsParams) error {
	_, err := q.db.Exec(ctx, countTMHits, arg.HitAt, arg.Ids)
	return err
}

const deleteProjectDerivations = `-- name: DeleteProjectDerivations :exec
DELETE FROM knowledge_tm_derivations WHERE project_id = $1
`

func (q *Queries) DeleteProjectDerivations(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectDerivations, projectID)
	return err
}

const deleteProjectTM = `-- name: DeleteProjectTM :exec
DELETE FROM knowledge_tm_units WHERE project_id = $1
`

func (q *Queries) DeleteProjectTM(ctx context.Context, projectID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteProjectTM, projectID)
	return err
}

const ensureDerivation = `-- name: EnsureDerivation :exec


INSERT INTO knowledge_tm_derivations (translation_id, tenant_id, project_id, revision, updated_at)
VALUES ($1, app_current_tenant(), $2, 0, $3)
ON CONFLICT (translation_id) DO NOTHING
`

type EnsureDerivationParams struct {
	TranslationID uuid.UUID
	ProjectID     uuid.UUID
	UpdatedAt     time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
//
// Scope filter used by the lookups: all_projects reaches every unit of
// the tenant; otherwise tenant-wide units and the given project's.
// ── derivation ─────────────────────────────────────────────────────
// Creates the translation's bookkeeping row so LockDerivation always
// has a row to lock; a concurrent insert waits for the first to commit.
func (q *Queries) EnsureDerivation(ctx context.Context, arg EnsureDerivationParams) error {
	_, err := q.db.Exec(ctx, ensureDerivation, arg.TranslationID, arg.ProjectID, arg.UpdatedAt)
	return err
}

const exactTMMatches = `-- name: ExactTMMatches :many

SELECT id, tenant_id, project_id, origin, translation_id, translation_revision, message_id, message_key, namespace, source_locale, target_locale, source_mf2, target_mf2, target_model, source_normalized, target_normalized, source_hash, signature, source_vars, hit_count, last_hit_at, created_by, created_at, updated_at, retired_at, retired_reason, retired_by FROM knowledge_tm_units
WHERE retired_at IS NULL
  AND source_locale = $1 AND target_locale = $2
  AND source_hash = $3 AND signature = $4
  AND ($5::boolean OR project_id IS NULL OR project_id = $6)
ORDER BY (project_id IS NOT DISTINCT FROM $6) DESC, updated_at DESC, id
LIMIT $7
`

type ExactTMMatchesParams struct {
	SourceLocale string
	TargetLocale string
	SourceHash   string
	Signature    string
	AllProjects  bool
	ProjectID    uuid.NullUUID
	MaxRows      int32
}

// ── lookups ────────────────────────────────────────────────────────
// Same normalized text and placeholder signature in the locale pair,
// the query's project first, then the most recently confirmed.
func (q *Queries) ExactTMMatches(ctx context.Context, arg ExactTMMatchesParams) ([]KnowledgeTmUnit, error) {
	rows, err := q.db.Query(ctx, exactTMMatches,
		arg.SourceLocale,
		arg.TargetLocale,
		arg.SourceHash,
		arg.Signature,
		arg.AllProjects,
		arg.ProjectID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeTmUnit
	for rows.Next() {
		var i KnowledgeTmUnit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Origin,
			&i.TranslationID,
			&i.TranslationRevision,
			&i.MessageID,
			&i.MessageKey,
			&i.Namespace,
			&i.SourceLocale,
			&i.TargetLocale,
			&i.SourceMf2,
			&i.TargetMf2,
			&i.TargetModel,
			&i.SourceNormalized,
			&i.TargetNormalized,
			&i.SourceHash,
			&i.Signature,
			&i.SourceVars,
			&i.HitCount,
			&i.LastHitAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetiredAt,
			&i.RetiredReason,
			&i.RetiredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveTMUnit = `-- name: FindActiveTMUnit :one
SELECT id FROM knowledge_tm_units
WHERE retired_at IS NULL
  AND project_id IS NOT DISTINCT FROM $1
  AND source_locale = $2 AND target_locale = $3
  AND source_hash = $4
  AND source_mf2 = $5 AND target_mf2 = $6
LIMIT 1
`

type FindActiveTMUnitParams struct {
	ProjectID    uuid.NullUUID
	SourceLocale string
	TargetLocale string
	SourceHash   string
	SourceMf2    string
	TargetMf2    string
}

// An active unit with exactly this text in the locale pair and scope
// (project, or tenant-wide when NULL): what makes a TMX import
// idempotent.
func (q *Queries) FindActiveTMUnit(ctx context.Context, arg FindActiveTMUnitParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findActiveTMUnit,
		arg.ProjectID,
		arg.SourceLocale,
		arg.TargetLocale,
		arg.SourceHash,
		arg.SourceMf2,
		arg.TargetMf2,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const fuzzyTMMatches = `-- name: FuzzyTMMatches :many
SELECT knowledge_tm_units.id, knowledge_tm_units.tenant_id, knowledge_tm_units.project_id, knowledge_tm_units.origin, knowledge_tm_units.translation_id, knowledge_tm_units.translation_revision, knowledge_tm_units.message_id, knowledge_tm_units.message_key, knowledge_tm_units.namespace, knowledge_tm_units.source_locale, knowledge_tm_units.target_locale, knowledge_tm_units.source_mf2, knowledge_tm_units.target_mf2, knowledge_tm_units.target_model, knowledge_tm_units.source_normalized, knowledge_tm_units.target_normalized, knowledge_tm_units.source_hash, knowledge_tm_units.signature, knowledge_tm_units.source_vars, knowledge_tm_units.hit_count, knowledge_tm_units.last_hit_at, knowledge_tm_units.created_by, knowledge_tm_units.created_at, knowledge_tm_units.updated_at, knowledge_tm_units.retired_at, knowledge_tm_units.retired_reason, knowledge_tm_units.retired_by,
       similarity(knowledge_tm_units.source_normalized, $1::text)::float8 AS similarity
FROM knowledge_tm_units
WHERE retired_at IS NULL
  AND source_locale = $2 AND target_locale = $3
  AND ($4::boolean OR project_id IS NULL OR project_id = $5)
  AND source_normalized % $1::text
ORDER BY similarity DESC, (project_id IS NOT DISTINCT FROM $5) DESC, updated_at DESC, id
LIMIT $6
`

type FuzzyTMMatchesParams struct {
	Query        string
	SourceLocale string
	TargetLocale string
	AllProjects  bool
	ProjectID    uuid.NullUUID
	MaxRows      int32
}

type FuzzyTMMatchesRow struct {
	KnowledgeTmUnit KnowledgeTmUnit
	Similarity      float64
}

// Trigram-similar normalized text in the locale pair, most similar
// first.
func (q *Queries) FuzzyTMMatches(ctx context.Context, arg FuzzyTMMatchesParams) ([]FuzzyTMMatchesRow, error) {
	rows, err := q.db.Query(ctx, fuzzyTMMatches,
		arg.Query,
		arg.SourceLocale,
		arg.TargetLocale,
		arg.AllProjects,
		arg.ProjectID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FuzzyTMMatchesRow
	for rows.Next() {
		var i FuzzyTMMatchesRow
		if err := rows.Scan(
			&i.KnowledgeTmUnit.ID,
			&i.KnowledgeTmUnit.TenantID,
			&i.KnowledgeTmUnit.ProjectID,
			&i.KnowledgeTmUnit.Origin,
			&i.KnowledgeTmUnit.TranslationID,
			&i.KnowledgeTmUnit.TranslationRevision,
			&i.KnowledgeTmUnit.MessageID,
			&i.KnowledgeTmUnit.MessageKey,
			&i.KnowledgeTmUnit.Namespace,
			&i.KnowledgeTmUnit.SourceLocale,
			&i.KnowledgeTmUnit.TargetLocale,
			&i.KnowledgeTmUnit.SourceMf2,
			&i.KnowledgeTmUnit.TargetMf2,
			&i.KnowledgeTmUnit.TargetModel,
			&i.KnowledgeTmUnit.SourceNormalized,
			&i.KnowledgeTmUnit.TargetNormalized,
			&i.KnowledgeTmUnit.SourceHash,
			&i.KnowledgeTmUnit.Signature,
			&i.KnowledgeTmUnit.SourceVars,
			&i.KnowledgeTmUnit.HitCount,
			&i.KnowledgeTmUnit.LastHitAt,
			&i.KnowledgeTmUnit.CreatedBy,
			&i.KnowledgeTmUnit.CreatedAt,
			&i.KnowledgeTmUnit.UpdatedAt,
			&i.KnowledgeTmUnit.RetiredAt,
			&i.KnowledgeTmUnit.RetiredReason,
			&i.KnowledgeTmUnit.RetiredBy,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTMUnit = `-- name: GetTMUnit :one
SELECT id, tenant_id, project_id, origin, translation_id, translation_revision, message_id, message_key, namespace, source_locale, target_locale, source_mf2, target_mf2, target_model, source_normalized, target_normalized, source_hash, signature, source_vars, hit_count, last_hit_at, created_by, created_at, updated_at, retired_at, retired_reason, retired_by FROM knowledge_tm_units WHERE id = $1
`

func (q *Queries) GetTMUnit(ctx context.Context, id uuid.UUID) (KnowledgeTmUnit, error) {
	row := q.db.QueryRow(ctx, getTMUnit, id)
	var i KnowledgeTmUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Origin,
		&i.TranslationID,
		&i.TranslationRevision,
		&i.MessageID,
		&i.MessageKey,
		&i.Namespace,
		&i.SourceLocale,
		&i.TargetLocale,
		&i.SourceMf2,
		&i.TargetMf2,
		&i.TargetModel,
		&i.SourceNormalized,
		&i.TargetNormalized,
		&i.SourceHash,
		&i.Signature,
		&i.SourceVars,
		&i.HitCount,
		&i.LastHitAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.RetiredBy,
	)
	return i, err
}

const insertTMUnit = `-- name: InsertTMUnit :exec

INSERT INTO knowledge_tm_units (id, tenant_id, project_id, origin, translation_id, translation_revision, message_id,
                                message_key, namespace, source_locale, target_locale, source_mf2, target_mf2,
                                target_model, source_normalized, target_normalized, source_hash, signature,
                                source_vars, hit_count, last_hit_at, created_by, created_at, updated_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12,
        $13, $14, $15, $16,
        $17, $18, 0, NULL, $19, $20,
        $21)
`

type InsertTMUnitParams struct {
	ID                  uuid.UUID
	ProjectID           uuid.NullUUID
	Origin              string
	TranslationID       uuid.NullUUID
	TranslationRevision pgtype.Int4
	MessageID           uuid.NullUUID
	MessageKey          string
	Namespace           string
	SourceLocale        string
	TargetLocale        string
	SourceMf2           string
	TargetMf2           string
	TargetModel         json.RawMessage
	SourceNormalized    string
	TargetNormalized    string
	SourceHash          string
	Signature           string
	SourceVars          json.RawMessage
	CreatedBy           string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// ── units ──────────────────────────────────────────────────────────
func (q *Queries) InsertTMUnit(ctx context.Context, arg InsertTMUnitParams) error {
	_, err := q.db.Exec(ctx, insertTMUnit,
		arg.ID,
		arg.ProjectID,
		arg.Origin,
		arg.TranslationID,
		arg.TranslationRevision,
		arg.MessageID,
		arg.MessageKey,
		arg.Namespace,
		arg.SourceLocale,
		arg.TargetLocale,
		arg.SourceMf2,
		arg.TargetMf2,
		arg.TargetModel,
		arg.SourceNormalized,
		arg.TargetNormalized,
		arg.SourceHash,
		arg.Signature,
		arg.SourceVars,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listTMUnits = `-- name: ListTMUnits :many
SELECT id, tenant_id, project_id, origin, translation_id, translation_revision, message_id, message_key, namespace, source_locale, target_locale, source_mf2, target_mf2, target_model, source_normalized, target_normalized, source_hash, signature, source_vars, hit_count, last_hit_at, created_by, created_at, updated_at, retired_at, retired_reason, retired_by FROM knowledge_tm_units
WHERE id > $1
  AND ($2::text IS NULL OR source_locale = $2)
  AND ($3::text IS NULL OR target_locale = $3)
  AND ($4::uuid IS NULL OR project_id = $4)
  AND ($5::uuid IS NULL OR translation_id = $5)
  AND ($6::text = 'all'
       OR ($6::text = 'active' AND retired_at IS NULL)
       OR ($6::text = 'retired' AND retired_at IS NOT NULL))
ORDER BY id
LIMIT $7
`

type ListTMUnitsParams struct {
	After         uuid.UUID
	SourceLocale  pgtype.Text
	TargetLocale  pgtype.Text
	ProjectID     uuid.NullUUID
	TranslationID uuid.NullUUID
	State         string
	MaxRows       int32
}

// Units in id order after the cursor. state: active, retired or all.
func (q *Queries) ListTMUnits(ctx context.Context, arg ListTMUnitsParams) ([]KnowledgeTmUnit, error) {
	rows, err := q.db.Query(ctx, listTMUnits,
		arg.After,
		arg.SourceLocale,
		arg.TargetLocale,
		arg.ProjectID,
		arg.TranslationID,
		arg.State,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeTmUnit
	for rows.Next() {
		var i KnowledgeTmUnit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Origin,
			&i.TranslationID,
			&i.TranslationRevision,
			&i.MessageID,
			&i.MessageKey,
			&i.Namespace,
			&i.SourceLocale,
			&i.TargetLocale,
			&i.SourceMf2,
			&i.TargetMf2,
			&i.TargetModel,
			&i.SourceNormalized,
			&i.TargetNormalized,
			&i.SourceHash,
			&i.Signature,
			&i.SourceVars,
			&i.HitCount,
			&i.LastHitAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetiredAt,
			&i.RetiredReason,
			&i.RetiredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveUnitOfTranslation = `-- name: LockActiveUnitOfTranslation :one
SELECT id, tenant_id, project_id, origin, translation_id, translation_revision, message_id, message_key, namespace, source_locale, target_locale, source_mf2, target_mf2, target_model, source_normalized, target_normalized, source_hash, signature, source_vars, hit_count, last_hit_at, created_by, created_at, updated_at, retired_at, retired_reason, retired_by FROM knowledge_tm_units
WHERE translation_id = $1 AND retired_at IS NULL
FOR UPDATE
`

func (q *Queries) LockActiveUnitOfTranslation(ctx context.Context, translationID uuid.NullUUID) (KnowledgeTmUnit, error) {
	row := q.db.QueryRow(ctx, lockActiveUnitOfTranslation, translationID)
	var i KnowledgeTmUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Origin,
		&i.TranslationID,
		&i.TranslationRevision,
		&i.MessageID,
		&i.MessageKey,
		&i.Namespace,
		&i.SourceLocale,
		&i.TargetLocale,
		&i.SourceMf2,
		&i.TargetMf2,
		&i.TargetModel,
		&i.SourceNormalized,
		&i.TargetNormalized,
		&i.SourceHash,
		&i.Signature,
		&i.SourceVars,
		&i.HitCount,
		&i.LastHitAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.RetiredBy,
	)
	return i, err
}

const lockDerivation = `-- name: LockDerivation :one
SELECT revision FROM knowledge_tm_derivations WHERE translation_id = $1 FOR UPDATE
`

func (q *Queries) LockDerivation(ctx context.Context, translationID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lockDerivation, translationID)
	var revision int32
	err := row.Scan(&revision)
	return revision, err
}

const lockTMUnit = `-- name: LockTMUnit :one
SELECT id, tenant_id, project_id, origin, translation_id, translation_revision, message_id, message_key, namespace, source_locale, target_locale, source_mf2, target_mf2, target_model, source_normalized, target_normalized, source_hash, signature, source_vars, hit_count, last_hit_at, created_by, created_at, updated_at, retired_at, retired_reason, retired_by FROM knowledge_tm_units WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTMUnit(ctx context.Context, id uuid.UUID) (KnowledgeTmUnit, error) {
	row := q.db.QueryRow(ctx, lockTMUnit, id)
	var i KnowledgeTmUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Origin,
		&i.TranslationID,
		&i.TranslationRevision,
		&i.MessageID,
		&i.MessageKey,
		&i.Namespace,
		&i.SourceLocale,
		&i.TargetLocale,
		&i.SourceMf2,
		&i.TargetMf2,
		&i.TargetModel,
		&i.SourceNormalized,
		&i.TargetNormalized,
		&i.SourceHash,
		&i.Signature,
		&i.SourceVars,
		&i.HitCount,
		&i.LastHitAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetiredAt,
		&i.RetiredReason,
		&i.RetiredBy,
	)
	return i, err
}

const retireTMUnit = `-- name: RetireTMUnit :execrows
UPDATE knowledge_tm_units
SET retired_at = $1, retired_reason = $2, retired_by = $3,
    updated_at = $1
WHERE id = $4 AND retired_at IS NULL
`

type RetireTMUnitParams struct {
	RetiredAt     pgtype.Timestamptz
	RetiredReason pgtype.Text
	RetiredBy     pgtype.Text
	ID            uuid.UUID
}

func (q *Queries) RetireTMUnit(ctx context.Context, arg RetireTMUnitParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireTMUnit,
		arg.RetiredAt,
		arg.RetiredReason,
		arg.RetiredBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDerivation = `-- name: SetDerivation :exec
UPDATE knowledge_tm_derivations SET revision = $1, updated_at = $2
WHERE translation_id = $3
`

type SetDerivationParams struct {
	Revision      int32
	UpdatedAt     time.Time
	TranslationID uuid.UUID
}

func (q *Queries) SetDerivation(ctx context.Context, arg SetDerivationParams) error {
	_, err := q.db.Exec(ctx, setDerivation, arg.Revision, arg.UpdatedAt, arg.TranslationID)
	return err
}

const setSimilarityThreshold = `-- name: SetSimilarityThreshold :exec
SELECT set_config('pg_trgm.similarity_threshold', $1::text, true)
`

// The % operator (and so the trigram index) filters by this, for the
// rest of the transaction.
func (q *Queries) SetSimilarityThreshold(ctx context.Context, threshold string) error {
	_, err := q.db.Exec(ctx, setSimilarityThreshold, threshold)
	return err
}

const touchTMUnit = `-- name: TouchTMUnit :exec
UPDATE knowledge_tm_units
SET translation_revision = $1, updated_at = $2
WHERE id = $3
`

type TouchTMUnitParams struct {
	TranslationRevision pgtype.Int4
	UpdatedAt           time.Time
	ID                  uuid.UUID
}

func (q *Queries) TouchTMUnit(ctx context.Context, arg TouchTMUnitParams) error {
	_, err := q.db.Exec(ctx, touchTMUnit, arg.TranslationRevision, arg.UpdatedAt, arg.ID)
	return err
}
