// Package fixture is the M2 exit test's catalog (RFC 0003 §1): about 600
// messages of a SaaS product in German with complete English and
// deliberately partial Spanish, French and Japanese, a termbase, style
// guides, a legacy translation memory, and the script the fake provider
// answers from — reference translations plus deliberate, labelled slips.
//
// Everything is generated by Generate from a seed (DefaultSeed) and
// committed under ../testdata: fixture.json (the catalog, expectations
// and provider script) and the interchange files the test imports
// (XLIFF catalogs, TMX memory, TBX termbase). Regenerate with
//
//	go generate ./internal/systemtest/m2/...
//
// TestFixtureIsCurrent fails when the committed files differ from what
// the generator writes.
package fixture

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// DefaultSeed is the seed the committed fixture was generated with.
const DefaultSeed = 20260919

// Routes a missing translation is expected to take through a fill.
const (
	// RouteExisting: translated (approved) before the fill; not filled.
	RouteExisting = "existing"
	// RouteSensitive: the namespace is tagged sensitive; never queued.
	RouteSensitive = "sensitive"
	// RouteTM: an exact translation-memory match is reused, no model call.
	RouteTM = "tm"
	// RouteAI: the provider drafts it. TMBlocked marks the ones whose only
	// exact TM match is legacy text with a forbidden term.
	RouteAI = "ai"
)

// Slip kinds: what the fake provider gets wrong, on purpose.
const (
	// SlipForbiddenTerm: the draft uses the concept's forbidden term.
	SlipForbiddenTerm = "forbidden_term"
	// SlipFormality: the draft addresses the user informally although
	// the style guide is formal; the fake reviewer (assess) notices.
	SlipFormality = "formality"
	// SlipPluralMissing: a plural draft lacks the target locale's `many`
	// category, in every repair too.
	SlipPluralMissing = "plural_missing"
	// SlipTooLong: the draft exceeds the message's max_length.
	SlipTooLong = "too_long"
	// SlipPlaceholderRepaired: the first draft drops a placeholder; the
	// repair turn fixes it.
	SlipPlaceholderRepaired = "placeholder_repaired"
	// SlipPlaceholderPersistent: every draft drops a placeholder; the job
	// ends invalid_output.
	SlipPlaceholderPersistent = "placeholder_persistent"
)

// SurvivingSlips are the slips that reach a suggestion unrepaired: the
// review routing has to catch every one of them.
var SurvivingSlips = []string{SlipForbiddenTerm, SlipFormality, SlipPluralMissing, SlipTooLong}

// AllSlips lists every slip kind in report order.
var AllSlips = []string{SlipForbiddenTerm, SlipFormality, SlipPluralMissing, SlipTooLong, SlipPlaceholderRepaired, SlipPlaceholderPersistent}

// Fixture is the generated catalog and everything around it.
type Fixture struct {
	Seed         int64    `json:"seed"`
	SourceLocale string   `json:"source_locale"`
	Locales      []string `json:"locales"`
	FillLocales  []string `json:"fill_locales"`
	// SensitiveNamespaces are tagged sensitive (and legal) in the project.
	SensitiveNamespaces []string                     `json:"sensitive_namespaces"`
	Messages            []Message                    `json:"messages"`
	Concepts            []Concept                    `json:"concepts"`
	StyleGuides         []StyleGuide                 `json:"style_guides"`
	LegacyTM            []LegacyUnit                 `json:"legacy_tm"`
	Expect              map[string]LocaleExpectation `json:"expect"`
}

// Message is one catalog message with its reference translations.
type Message struct {
	Key         string `json:"key"`
	Namespace   string `json:"namespace"`
	Pattern     string `json:"pattern"`
	Description string `json:"description"`
	MaxLength   int    `json:"max_length,omitempty"`
	Source      Text   `json:"source"`
	// Translations are by locale; ja has none for the sensitive namespace
	// (humans translate it later).
	Translations map[string]*Translation `json:"translations"`
}

// Text is authored message text and its canonical MF2.
type Text struct {
	Syntax string `json:"syntax"`
	Text   string `json:"text"`
	MF2    string `json:"mf2"`
}

// Translation is a reference translation and what the fill should do
// with it.
type Translation struct {
	Text
	// Existing translations are imported (approved) before the fill.
	Existing bool `json:"existing,omitempty"`
	// Route is the expected route of a missing translation (fill locales).
	Route string `json:"route,omitempty"`
	// TMBlocked: the only exact TM match is legacy text with a forbidden
	// term, so the agent drafts instead of reusing it.
	TMBlocked bool `json:"tm_blocked,omitempty"`
	// Slip is the deliberate mistake the fake provider makes (RouteAI).
	Slip string `json:"slip,omitempty"`
	// LengthFlagged: the default scoring's length heuristic flags the
	// (clean) reference, which lowers its confidence below
	// approve_recommended unless translation memory supports the draft.
	LengthFlagged bool `json:"length_flagged,omitempty"`
	// Drafts are the provider's answers by attempt (the last repeats);
	// empty means the reference MF2.
	Drafts []Draft `json:"drafts,omitempty"`
}

// Draft is one scripted provider answer and how the fake reviewer
// assesses it.
type Draft struct {
	MF2        string      `json:"mf2"`
	Assessment *Assessment `json:"assessment,omitempty"`
}

// Assessment is the fake reviewer's answer to the assess prompt.
type Assessment struct {
	Score       float64  `json:"score"`
	FormalityOK bool     `json:"formality_ok"`
	Issues      []string `json:"issues"`
}

// DefaultAssessment is what the fake reviewer says about every draft
// without a scripted assessment: fluent, on style.
var DefaultAssessment = Assessment{Score: 0.93, FormalityOK: true, Issues: []string{}}

// ProviderDrafts returns the scripted answers for t: its drafts, or the
// reference.
func (t *Translation) ProviderDrafts() []Draft {
	if len(t.Drafts) > 0 {
		return t.Drafts
	}
	return []Draft{{MF2: t.MF2}}
}

// Concept is a termbase concept.
type Concept struct {
	ID         string `json:"id"`
	Domain     string `json:"domain"`
	Definition string `json:"definition"`
	Terms      []Term `json:"terms"`
}

// Term is one term of a concept.
type Term struct {
	Locale string `json:"locale"`
	Text   string `json:"text"`
	Status string `json:"status"`
}

// StyleGuide is a project style guide, in the API's shape (POST
// /v1/tenants/{tenant}/style-guides, plus project_id).
type StyleGuide struct {
	Name      string      `json:"name"`
	Locale    string      `json:"locale,omitempty"`
	Namespace string      `json:"namespace,omitempty"`
	Fields    StyleFields `json:"fields"`
	Rules     []StyleRule `json:"rules,omitempty"`
}

// StyleFields are the structured style fields.
type StyleFields struct {
	Formality   *Formality        `json:"formality,omitempty"`
	Tone        []string          `json:"tone,omitempty"`
	Punctuation *StylePunctuation `json:"punctuation,omitempty"`
}

// Formality is the register and pronoun.
type Formality struct {
	Register string `json:"register"`
	Pronoun  string `json:"pronoun,omitempty"`
}

// StylePunctuation are punctuation preferences.
type StylePunctuation struct {
	Quotes                 string `json:"quotes,omitempty"`
	SpaceBeforePunctuation *bool  `json:"space_before_punctuation,omitempty"`
}

// StyleRule is a style rule with rationale and examples.
type StyleRule struct {
	ID        string   `json:"id"`
	Title     string   `json:"title"`
	Rationale string   `json:"rationale,omitempty"`
	Good      []string `json:"good,omitempty"`
	Bad       []string `json:"bad,omitempty"`
}

// LegacyUnit is a translation-memory unit of the tenant's previous
// product, imported through TMX.
type LegacyUnit struct {
	ID           string `json:"id"`
	SourceLocale string `json:"source_locale"`
	TargetLocale string `json:"target_locale"`
	Source       string `json:"source"`
	Target       string `json:"target"`
	// Kind is exact (a message's source), fuzzy (a near variant) or
	// forbidden_term (exact, but with terminology the termbase forbids).
	Kind string `json:"kind"`
}

// LocaleExpectation is what a fill of one locale should do.
type LocaleExpectation struct {
	Messages int `json:"messages"`
	Existing int `json:"existing"`
	Missing  int `json:"missing"`
	// Sensitive are missing messages in sensitive namespaces.
	Sensitive int `json:"sensitive"`
	// PreviewTMExact counts missing messages with an exact TM match (the
	// preview doesn't validate them); TMReused are those reused; TMBlocked
	// those whose match has a forbidden term.
	PreviewTMExact int `json:"preview_tm_exact"`
	TMReused       int `json:"tm_reused"`
	TMBlocked      int `json:"tm_blocked"`
	// AIDrafted are the messages the provider translates.
	AIDrafted int            `json:"ai_drafted"`
	Slips     map[string]int `json:"slips"`
	// LengthFlagged counts the clean AI drafts the length heuristic flags.
	LengthFlagged int `json:"length_flagged"`
}

// Surviving counts the slips that reach a suggestion unrepaired.
func (e LocaleExpectation) Surviving() int {
	n := 0
	for _, k := range SurvivingSlips {
		n += e.Slips[k]
	}
	return n
}

// Files the generator writes into the testdata directory.
const (
	FileFixture  = "fixture.json"
	FileTMX      = "legacy-memory.tmx"
	FileTBX      = "termbase.tbx"
	xliffPattern = "catalog.%s-%s.xlf"
)

// XLIFFFile is the name of the catalog file for a target locale.
func XLIFFFile(source, target string) string { return fmt.Sprintf(xliffPattern, source, target) }

// Load reads fixture.json from dir.
func Load(dir string) (*Fixture, error) {
	raw, err := os.ReadFile(filepath.Join(dir, FileFixture))
	if err != nil {
		return nil, err
	}
	var f Fixture
	if err := json.Unmarshal(raw, &f); err != nil {
		return nil, fmt.Errorf("fixture: %w", err)
	}
	return &f, nil
}

// Message returns the message with key.
func (f *Fixture) Message(key string) (*Message, bool) {
	for i := range f.Messages {
		if f.Messages[i].Key == key {
			return &f.Messages[i], true
		}
	}
	return nil, false
}

// Sensitive reports whether ns is tagged sensitive.
func (f *Fixture) Sensitive(ns string) bool {
	for _, s := range f.SensitiveNamespaces {
		if s == ns {
			return true
		}
	}
	return false
}
