apiVersion: rollops.klarlabs.de/v1
kind: RolloutConfig
metadata: { name: gl-svc-postgres }
spec:
  target:
    kind: kubernetes
    ref: glossa/prod/svc-postgres
    criticality: medium
    spec:
      namespace: glossa
      resource: service/postgres
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          annotations:
            meta.helm.sh/release-name: glossa
            meta.helm.sh/release-namespace: glossa
          labels:
            app.kubernetes.io/instance: glossa
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: glossa
            app.kubernetes.io/version: 0.1.0
            helm.sh/chart: glossa-0.1.1
          name: postgres
          namespace: glossa
        spec:
          internalTrafficPolicy: Cluster
          ports:
          - name: postgres
            port: 5432
            protocol: TCP
            targetPort: 5432
          selector:
            app: postgres
          sessionAffinity: None
          type: ClusterIP
  strategy: { type: rolling }
