apiVersion: rollops.klarlabs.de/v1
kind: RolloutConfig
metadata: { name: gl-svc-admin }
spec:
  target:
    kind: kubernetes
    ref: glossa/prod/svc-admin
    criticality: medium
    spec:
      namespace: glossa
      resource: service/admin
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          annotations:
            meta.helm.sh/release-name: glossa
            meta.helm.sh/release-namespace: glossa
            obvia.io/depends-on: api
          labels:
            app.kubernetes.io/instance: glossa
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: glossa
            app.kubernetes.io/version: 0.1.0
            helm.sh/chart: glossa-0.1.1
          name: admin
          namespace: glossa
        spec:
          internalTrafficPolicy: Cluster
          ports:
          - port: 80
            protocol: TCP
            targetPort: 8080
          selector:
            app: admin
          sessionAffinity: None
          type: ClusterIP
  strategy: { type: rolling }
