// Code generated by glossa generate from locales/en.json. DO NOT EDIT.

// Package msg has typed accessors for the project's messages.
package msg

import (
	"context"

	glossa "github.com/felixgeelhaar/glossa/runtimes/go"
)

// Localizer renders a message by ID; *glossa.Localizer implements it.
type Localizer interface {
	T(id string, args glossa.Args, opts ...glossa.Option) string
}

// Contextual finds the locale on a request's context; *glossa.Client
// implements it.
type Contextual interface {
	Localizer(ctx context.Context) *glossa.Localizer
}

// Messages are the project's messages with typed arguments.
type Messages struct{ l Localizer }

// For binds the accessors to a localizer.
func For(l Localizer) Messages { return Messages{l: l} }

// FromContext binds the accessors to the locale on ctx (set by
// glossa's middleware).
func FromContext(ctx context.Context, c Contextual) Messages { return For(c.Localizer(ctx)) }

// CartItems renders cart.items: {count, plural, one {# item} other {# items}}
func (m Messages) CartItems(count float64, opts ...glossa.Option) string {
	return m.l.T("cart.items", glossa.Args{"count": count}, opts...)
}

// CheckoutPay renders checkout.pay: Pay {amount, number, ::currency/EUR}
func (m Messages) CheckoutPay(amount float64, opts ...glossa.Option) string {
	return m.l.T("checkout.pay", glossa.Args{"amount": amount}, opts...)
}

// Title renders title: Shop
func (m Messages) Title(opts ...glossa.Option) string {
	return m.l.T("title", nil, opts...)
}
