{{- if .Values.metrics.serviceMonitor.enabled }}
{{- $sm := .Values.metrics.serviceMonitor -}}
{{- range $component := list "server" "edge" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gp.componentName" (dict "root" $ "component" $component) }}
  labels:
    {{- include "gp.componentLabels" (dict "root" $ "component" $component) | nindent 4 }}
    {{- with $sm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gp.selectorLabels" (dict "root" $ "component" $component) | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $sm.interval }}
      scrapeTimeout: {{ $sm.scrapeTimeout }}
{{- end }}
{{- end }}
