/**
 * Every string Studio shows, in one place (English for now). Keeping
 * copy out of components makes localizing Studio with Glossa itself a
 * mechanical change later: these keys become messages.
 */
import { ApiError } from "./api/errors";

export const strings = {
  app: {
    name: "Glossa Studio",
    beta: "Public Beta",
    skip: "Skip to content",
    loading: "Loading…",
    retry: "Try again",
    cancel: "Cancel",
    close: "Close",
    save: "Save",
    saving: "Saving…",
    remove: "Remove",
    notFound: "This page doesn't exist.",
    backHome: "Back to projects",
  },
  nav: {
    projects: "Projects",
    translate: "Translate",
    locales: "Locales",
    settings: "Settings",
    releases: "Releases",
    shortcuts: "Keyboard shortcuts",
    account: "Account & security",
    signOut: "Sign out",
    signOutEverywhere: "Sign out everywhere",
    tenant: "Workspace",
    individual: "Personal",
    organization: "Organization",
    newOrganization: "New organization…",
    breadcrumb: "Breadcrumb",
    projectSections: "Project sections",
  },
  auth: {
    signInTitle: "Sign in to Glossa",
    signInLead: "We'll email you a link. No password needed.",
    email: "Email address",
    sendLink: "Email me a sign-in link",
    sending: "Sending…",
    linkSentTitle: "Check your inbox",
    linkSent: (email: string) => `If ${email} can receive mail, a sign-in link is on its way. It works once, for 15 minutes.`,
    useDifferentEmail: "Use a different address",
    redeeming: "Signing you in…",
    linkInvalid: "This sign-in link is invalid, expired or already used. Request a new one.",
    passkey: "Sign in with a passkey",
    passkeyPrimary: (email: string) => `Continue as ${email} with your passkey`,
    otherMethods: "Other ways to sign in",
    password: "Password",
    totp: "Authentication code",
    totpHint: "Six digits from your authenticator app.",
    signInWithPassword: "Sign in with password",
    forgotPassword: "Forgot your password?",
    noAccount: "New to Glossa?",
    register: "Create an account",
    registerTitle: "Create your Glossa account",
    registerLead: "You'll get a personal workspace; invite a team later.",
    displayName: "Your name (optional)",
    newPassword: "Password (at least 12 characters)",
    registerSubmit: "Create account",
    registered: (email: string) => `Almost there: we sent a verification link to ${email}. Open it to sign in.`,
    haveAccount: "Already have an account?",
    resetTitle: "Reset your password",
    resetLead: "We'll email you a link to set a new password.",
    resetSend: "Email me a reset link",
    resetSent: (email: string) => `If ${email} has an account, a reset link is on its way.`,
    setPasswordTitle: "Choose a new password",
    setPassword: "Set password",
    passwordChanged: "Your password is changed and every session was signed out. Sign in again.",
    backToSignIn: "Back to sign in",
  },
  passkeyPromo: {
    title: "Sign in faster with a passkey",
    body: "Use Touch ID, Windows Hello or your phone instead of waiting for an email.",
    action: "Add a passkey",
    dismiss: "Not now",
  },
  account: {
    title: "Account & security",
    profile: "Profile",
    emailVerified: "verified",
    emailUnverified: "not verified",
    passkeys: "Passkeys",
    passkeysLead: "A passkey signs you in with your device's screen lock. It can't be phished or reused elsewhere.",
    passkeyName: "Passkey name",
    passkeyNameDefault: "This device",
    addPasskey: "Add a passkey",
    passkeyAdded: (name: string) => `Passkey "${name}" added.`,
    passkeysUnsupported: "This browser doesn't support passkeys.",
    totp: "Authenticator app (TOTP)",
    totpLead: "A second step for password sign-in.",
    totpOn: "On",
    totpOff: "Off",
    totpStart: "Set up authenticator app",
    totpSecret: "Enter this key in your authenticator app, or open the link on your phone:",
    totpOpen: "Open in authenticator app",
    totpConfirm: "Confirm",
    totpEnabled: "Authenticator app is on. Password sign-in now asks for a code.",
    totpDisable: "Turn off",
    totpDisabled: "Authenticator app is off.",
    sessions: "Sessions",
    sessionsLead: "Sign out on every device, including this one.",
  },
  tenants: {
    createTitle: "New organization",
    createLead: "Organizations share projects with a team. You'll be the owner.",
    name: "Name",
    slug: "Slug",
    slugHint: "Lowercase letters, digits and hyphens; used in URLs.",
    create: "Create organization",
  },
  projects: {
    title: "Projects",
    empty: "No projects yet. A project holds one product's messages, locales and releases.",
    create: "New project",
    createTitle: "New project",
    name: "Name",
    slug: "Slug",
    sourceLocale: "Source locale",
    sourceLocaleHint: "The language messages are written in. It can't change later.",
    defaultSyntax: "Authoring syntax",
    syntaxMf1: "ICU MessageFormat 1",
    syntaxMf2: "MessageFormat 2",
    reviewRequired: "Translations need review before release",
    reviewRequiredHint: "New text waits in “needs review” until a reviewer approves it.",
    submit: "Create project",
    source: (tag: string) => `Source: ${tag}`,
  },
  settings: {
    title: "Project settings",
    general: "General",
    saved: "Settings saved.",
    changedElsewhere: "Someone else changed this project. Reload to see their changes, then apply yours.",
    applications: "Applications",
    applicationsLead: "Runtime surfaces that load this project's messages.",
    platform: "Platform",
    addApplication: "Add application",
    noApplications: "No applications yet.",
    danger: "Delete project",
    dangerLead: "Deletes every message, locale, translation and their history. This can't be undone.",
    deleteConfirm: (slug: string) => `Type ${slug} to confirm`,
    deleteProject: "Delete this project",
  },
  locales: {
    title: "Locales",
    lead: "Every locale this project is translated into. Codes are BCP 47 and stored canonically.",
    add: "Add locale",
    code: "Locale code",
    codeHint: "BCP 47, e.g. de, pt-BR, zh-Hant-TW.",
    preview: (tag: string, name: string, dir: string) => `Adds ${tag} — ${name}, written ${dir === "rtl" ? "right to left" : "left to right"}.`,
    invalid: "That isn't a valid BCP 47 locale code.",
    extension: "Extensions (-u-, -t-) and private use (-x-) aren't allowed.",
    tooLong: "Locale codes can be at most 35 characters.",
    source: "source",
    direction: "Direction",
    ltr: "Left to right",
    rtl: "Right to left",
    name: "Language",
    removeLabel: (tag: string) => `Remove ${tag}`,
    removeConfirm: (tag: string) => `Remove ${tag}? Its translations are kept and come back if you add it again.`,
    fallbackTitle: "Fallback graph",
    fallbackLead:
      "When a translation is missing, runtimes try these locales in order. Rows apply to one locale; “*” applies to every locale without its own row. Without a row, a locale falls back to its parent (de-AT → de), then to the source.",
    from: "When missing in",
    chain: "try, in order",
    everyLocale: "* (every other locale)",
    addRow: "Add rule",
    addToChain: "Add fallback locale",
    moveUp: (tag: string) => `Move ${tag} earlier`,
    moveDown: (tag: string) => `Move ${tag} later`,
    removeFromChain: (tag: string) => `Remove ${tag} from this chain`,
    removeRow: (from: string) => `Remove the rule for ${from}`,
    saveFallback: "Save fallback graph",
    fallbackSaved: "Fallback graph saved.",
    choose: "Choose…",
    issues: {
      fallback_unknown_locale: (l: string) => `${l} isn't a locale of this project.`,
      fallback_self_reference: (l: string) => `${l} can't fall back to itself.`,
      fallback_duplicate: (l: string) => `${l} is listed twice.`,
      fallback_duplicate_row: (l: string) => `There is already a rule for ${l}.`,
      fallback_empty_chain: (l: string) => `Add at least one fallback locale for ${l}.`,
      fallback_cycle: (_l: string, path: string[]) => `This creates a loop: ${path.join(" → ")}.`,
    },
  },
  workspace: {
    title: "Translate",
    targetLocale: "Target locale",
    noTargets: "Add a locale to start translating.",
    addLocales: "Add locales",
    filters: "Filters",
    search: "Search keys and text",
    namespace: "Namespace",
    allNamespaces: "All namespaces",
    coverage: "Show",
    coverageAll: "All messages",
    coverageMissing: (l: string) => `Missing in ${l}`,
    coverageOutdated: (l: string) => `Outdated in ${l}`,
    state: "Message state",
    stateActive: "Active",
    stateObsolete: "Obsolete",
    stateAll: "All",
    messages: "Messages",
    count: (shown: number, loaded: number, done: boolean) =>
      `${shown.toLocaleString()} of ${loaded.toLocaleString()}${done ? "" : "+"} messages`,
    loadingMore: "Loading more…",
    empty: "No messages match these filters.",
    noMessages: "This project has no messages yet. Push them with the CLI or the API.",
    selectMessage: "Select a message to translate it.",
    status: { missing: "Missing", outdated: "Outdated", translated: "Translated", unknown: "" },
    key: "Key",
    description: "Context",
    noDescription: "No context from the developers yet.",
    maxLength: (n: number) => `Max ${n} characters`,
    source: "Source",
    arguments: "Arguments",
    noArguments: "No arguments",
    markup: "Markup",
    target: "Translation",
    syntax: "Syntax",
    stateLabel: {
      draft: "Draft",
      needs_review: "Needs review",
      approved: "Approved",
      rejected: "Rejected",
    } as Record<string, string>,
    origin: "Origin",
    outdated: "Outdated",
    outdatedLead: (from: number, to: number) => `Translated against source revision ${from}; the source is now at revision ${to}.`,
    showSourceChanges: "Show source changes",
    hideSourceChanges: "Hide source changes",
    sourceChanges: "Changes to the source since this translation",
    notTranslated: "Not translated yet.",
    save: "Save",
    saveApprove: "Save & approve",
    approve: "Approve",
    reject: "Reject",
    requestReview: "Request review",
    saved: "Saved.",
    approved: "Approved.",
    rejected: "Rejected.",
    unchanged: "No changes to save.",
    unsaved: "Unsaved changes",
    noWrite: (l: string) => `You can't write ${l} translations in this workspace.`,
    noReview: (l: string) => `Only reviewers for ${l} can approve or reject.`,
    conflict: "Someone else saved this translation meanwhile. Their version is loaded; your text is kept in the editor.",
    qaTitle: "Structural QA",
    qaFailed: "The translation doesn't match the source's structure. Fix these and save again:",
    qaWarnings: "Warnings",
    invalidText: "The text doesn't parse:",
    preview: "Live preview",
    previewSource: "Source",
    previewTarget: "Translation",
    previewMf1Stale: "MF1 is parsed on the server: the preview shows the last saved text and updates when you save.",
    previewEmpty: "Nothing to preview yet.",
    samples: "Sample values",
    sampleFor: (name: string) => `Sample value for ${name}`,
    pluralForms: (l: string) => `Plural forms in ${l}`,
    formatErrors: "Formatting problems",
    tabs: { editor: "Editor", history: "History" },
    history: "Revisions, newest first",
    historyEmpty: "No revisions yet.",
    revision: (n: number) => `Revision ${n}`,
    kind: { content: "Text", review: "Review" } as Record<string, string>,
    madeAgainst: (n: number) => `against source revision ${n}`,
    by: (who: string) => `by ${who}`,
    canonical: "Canonical MF2",
  },
  releases: {
    title: "Releases",
    comingSoonTitle: "Releases are coming soon",
    comingSoonLead:
      "A release will snapshot this project's eligible translations into signed, immutable artifacts that runtimes load from the edge. You'll publish, promote and roll back here.",
    planned: ["Publish a release from approved translations", "Environments (production, preview) pointing at releases", "Promote and roll back without rebuilding", "Per-locale, per-namespace artifacts with a signed manifest"],
    meanwhile: "Until then, everything you translate here is kept with full history and will be included in the first release.",
    comingSoon: "Coming soon",
    publish: "Publish release",
    columns: { release: "Release", created: "Created", environments: "Environments", locales: "Locales", messages: "Messages" },
  },
  shortcuts: {
    title: "Keyboard shortcuts",
    lead: "Studio is built for the keyboard. Chords use ⌘ on macOS and Ctrl elsewhere.",
  },
  problems: {
    network_error: "The server could not be reached. Check your connection and try again.",
    unexpected_response: "The server sent an unexpected response.",
    invalid_response: "The server's response didn't match what Studio expects.",
    unauthenticated: "Your session has ended. Sign in again.",
    invalid_credentials: "That email and password don't match.",
    totp_required: "Enter the code from your authenticator app.",
    totp_invalid: "That code isn't valid. Codes change every 30 seconds.",
    email_unverified: "Verify your email first: open the link we sent you.",
    account_locked: "Too many attempts. Password sign-in is locked for 15 minutes; a sign-in link still works.",
    link_invalid: "This link is invalid, expired or already used.",
    weak_password: "Choose a longer password (at least 12 characters).",
    passkeys_disabled: "Passkeys aren't enabled on this server.",
    no_passkeys: "There's no passkey for this address. Use a sign-in link instead.",
    passkey_invalid: "The passkey couldn't be verified.",
    rate_limited: "Too many requests. Wait a moment and try again.",
    slug_taken: "That slug is taken.",
    forbidden: "You don't have permission to do that here.",
    review_forbidden: "Approving and rejecting needs the reviewer role for this locale.",
    source_locale: "That's the source locale.",
    locale_in_fallback: "Remove it from the fallback graph first.",
    invalid_locale: "That isn't a valid locale code.",
    invalid_transition: "That review step isn't possible from the current state.",
    precondition_failed: "Someone else changed this meanwhile. Reload and try again.",
    translation_conflict: "Someone else created this translation first. Reload and try again.",
    structural_qa_failed: "The translation doesn't match the source's structure.",
    invalid_message: "The text doesn't parse.",
  } as Record<string, string>,
};

/** A person-readable message for any error, preferring our copy for known codes. */
export function problemText(e: unknown): string {
  if (e instanceof ApiError) {
    const known = strings.problems[e.code];
    if (known && e.code !== "invalid_message") return known;
    return e.message || strings.problems.unexpected_response!;
  }
  return e instanceof Error ? e.message : String(e);
}

/** "person:abc" → a short label; the API names principals, not people, in history. */
export function principalLabel(principal: string, selfId?: string): string {
  const [kind, id] = principal.split(":");
  if (kind === "person" && id && id === selfId) return "you";
  if (kind === "token") return `API token ${id?.slice(0, 8) ?? ""}`;
  if (kind === "person") return `member ${id?.slice(0, 8) ?? ""}`;
  return principal;
}
