/**
 * Every string Studio shows, in one place (English for now). Keeping
 * copy out of components makes localizing Studio with Glossa itself a
 * mechanical change later: these keys become messages.
 */
import { ApiError } from "./api/errors";

export const strings = {
  app: {
    name: "Glossa Studio",
    beta: "Public Beta",
    skip: "Skip to content",
    loading: "Loading…",
    retry: "Try again",
    cancel: "Cancel",
    close: "Close",
    save: "Save",
    saving: "Saving…",
    remove: "Remove",
    edit: "Edit",
    delete: "Delete",
    notFound: "This page doesn't exist.",
    backHome: "Back to projects",
  },
  nav: {
    projects: "Projects",
    translate: "Translate",
    locales: "Locales",
    settings: "Settings",
    releases: "Releases",
    review: "Review",
    termbase: "Termbase",
    style: "Style",
    ai: "AI",
    shortcuts: "Keyboard shortcuts",
    account: "Account & security",
    signOut: "Sign out",
    signOutEverywhere: "Sign out everywhere",
    tenant: "Workspace",
    individual: "Personal",
    organization: "Organization",
    newOrganization: "New organization…",
    breadcrumb: "Breadcrumb",
    projectSections: "Project sections",
  },
  auth: {
    signInTitle: "Sign in to Glossa",
    signInLead: "We'll email you a link. No password needed.",
    signInLeadNoEmail: "Sign in with your password or a passkey.",
    noEmailHint: "This server doesn't send email, so there are no sign-in links or password resets by email.",
    email: "Email address",
    sendLink: "Email me a sign-in link",
    sending: "Sending…",
    linkSentTitle: "Check your inbox",
    linkSent: (email: string) => `If ${email} can receive mail, a sign-in link is on its way. It works once, for 15 minutes.`,
    useDifferentEmail: "Use a different address",
    redeeming: "Signing you in…",
    linkInvalid: "This sign-in link is invalid, expired or already used. Request a new one.",
    passkey: "Sign in with a passkey",
    passkeyPrimary: (email: string) => `Continue as ${email} with your passkey`,
    otherMethods: "Other ways to sign in",
    password: "Password",
    totp: "Authentication code",
    totpHint: "Six digits from your authenticator app.",
    signInWithPassword: "Sign in with password",
    forgotPassword: "Forgot your password?",
    noAccount: "New to Glossa?",
    register: "Create an account",
    registerTitle: "Create your Glossa account",
    registerLead: "You'll get a personal workspace; invite a team later.",
    registerLeadNoEmail: "You'll get a personal workspace and be signed in right away. This server doesn't send email, so keep your password safe; you can add a passkey afterwards.",
    displayName: "Your name (optional)",
    newPassword: "Password (at least 12 characters)",
    registerSubmit: "Create account",
    registered: (email: string) => `Almost there: we sent a verification link to ${email}. Open it to sign in.`,
    haveAccount: "Already have an account?",
    resetTitle: "Reset your password",
    resetLead: "We'll email you a link to set a new password.",
    resetUnavailable: "This server doesn't send email, so a password can't be reset by email. Sign in with a passkey if you added one, or ask the server's operator.",
    resetSend: "Email me a reset link",
    resetSent: (email: string) => `If ${email} has an account, a reset link is on its way.`,
    setPasswordTitle: "Choose a new password",
    setPassword: "Set password",
    passwordChanged: "Your password is changed and every session was signed out. Sign in again.",
    backToSignIn: "Back to sign in",
  },
  passkeyPromo: {
    title: "Sign in faster with a passkey",
    body: "Use Touch ID, Windows Hello or your phone instead of waiting for an email.",
    action: "Add a passkey",
    dismiss: "Not now",
  },
  account: {
    title: "Account & security",
    profile: "Profile",
    emailVerified: "verified",
    emailUnverified: "not verified",
    passkeys: "Passkeys",
    passkeysLead: "A passkey signs you in with your device's screen lock. It can't be phished or reused elsewhere.",
    passkeyName: "Passkey name",
    passkeyNameDefault: "This device",
    addPasskey: "Add a passkey",
    passkeyAdded: (name: string) => `Passkey "${name}" added.`,
    passkeysUnsupported: "This browser doesn't support passkeys.",
    passkeysOff: "Passkeys aren't configured on this server, so new ones can't be added. Existing ones stay listed and can be removed.",
    noPasskeys: "No passkeys yet.",
    passkeyColumns: { name: "Name", added: "Added", lastUsed: "Last used", actions: "Actions" },
    neverUsed: "never",
    removePasskey: "Remove",
    removePasskeyLabel: (name: string) => `Remove passkey ${name}`,
    removeTitle: (name: string) => `Remove passkey “${name}”?`,
    removeLead: "It won't sign you in any more, on any device. Sessions it started stay signed in; sign out everywhere to end them.",
    removeConfirm: "Remove passkey",
    passkeyRemoved: (name: string) => `Passkey "${name}" removed.`,
    totp: "Authenticator app (TOTP)",
    totpLead: "A second step for password sign-in.",
    totpOn: "On",
    totpOff: "Off",
    totpStart: "Set up authenticator app",
    totpSecret: "Enter this key in your authenticator app, or open the link on your phone:",
    totpOpen: "Open in authenticator app",
    totpConfirm: "Confirm",
    totpEnabled: "Authenticator app is on. Password sign-in now asks for a code.",
    totpDisable: "Turn off",
    totpDisabled: "Authenticator app is off.",
    sessions: "Sessions",
    sessionsLead: "Sign out on every device, including this one.",
  },
  tenants: {
    createTitle: "New organization",
    createLead: "Organizations share projects with a team. You'll be the owner.",
    name: "Name",
    slug: "Slug",
    slugHint: "Lowercase letters, digits and hyphens; used in URLs.",
    create: "Create organization",
  },
  projects: {
    title: "Projects",
    empty: "No projects yet. A project holds one product's messages, locales and releases.",
    create: "New project",
    createTitle: "New project",
    name: "Name",
    slug: "Slug",
    sourceLocale: "Source locale",
    sourceLocaleHint: "The language messages are written in. It can't change later.",
    defaultSyntax: "Authoring syntax",
    syntaxMf1: "ICU MessageFormat 1",
    syntaxMf2: "MessageFormat 2",
    reviewRequired: "Translations need review before release",
    reviewRequiredHint: "New text waits in “needs review” until a reviewer approves it.",
    submit: "Create project",
    source: (tag: string) => `Source: ${tag}`,
  },
  settings: {
    title: "Project settings",
    general: "General",
    saved: "Settings saved.",
    changedElsewhere: "Someone else changed this project. Reload to see their changes, then apply yours.",
    applications: "Applications",
    applicationsLead: "Runtime surfaces that load this project's messages.",
    platform: "Platform",
    addApplication: "Add application",
    noApplications: "No applications yet.",
    danger: "Delete project",
    dangerLead: "Deletes every message, locale, translation and their history. This can't be undone.",
    deleteConfirm: (slug: string) => `Type ${slug} to confirm`,
    deleteProject: "Delete this project",
  },
  locales: {
    title: "Locales",
    lead: "Every locale this project is translated into. Codes are BCP 47 and stored canonically.",
    add: "Add locale",
    code: "Locale code",
    codeHint: "BCP 47, e.g. de, pt-BR, zh-Hant-TW.",
    preview: (tag: string, name: string, dir: string) => `Adds ${tag} — ${name}, written ${dir === "rtl" ? "right to left" : "left to right"}.`,
    invalid: "That isn't a valid BCP 47 locale code.",
    extension: "Extensions (-u-, -t-) and private use (-x-) aren't allowed.",
    tooLong: "Locale codes can be at most 35 characters.",
    source: "source",
    direction: "Direction",
    ltr: "Left to right",
    rtl: "Right to left",
    name: "Language",
    removeLabel: (tag: string) => `Remove ${tag}`,
    removeConfirm: (tag: string) => `Remove ${tag}? Its translations are kept and come back if you add it again.`,
    fallbackTitle: "Fallback graph",
    fallbackLead:
      "When a translation is missing, runtimes try these locales in order. Rows apply to one locale; “*” applies to every locale without its own row. Without a row, a locale falls back to its parent (de-AT → de), then to the source.",
    from: "When missing in",
    chain: "try, in order",
    everyLocale: "* (every other locale)",
    addRow: "Add rule",
    addToChain: "Add fallback locale",
    moveUp: (tag: string) => `Move ${tag} earlier`,
    moveDown: (tag: string) => `Move ${tag} later`,
    removeFromChain: (tag: string) => `Remove ${tag} from this chain`,
    removeRow: (from: string) => `Remove the rule for ${from}`,
    saveFallback: "Save fallback graph",
    fallbackSaved: "Fallback graph saved.",
    choose: "Choose…",
    issues: {
      fallback_unknown_locale: (l: string) => `${l} isn't a locale of this project.`,
      fallback_self_reference: (l: string) => `${l} can't fall back to itself.`,
      fallback_duplicate: (l: string) => `${l} is listed twice.`,
      fallback_duplicate_row: (l: string) => `There is already a rule for ${l}.`,
      fallback_empty_chain: (l: string) => `Add at least one fallback locale for ${l}.`,
      fallback_cycle: (_l: string, path: string[]) => `This creates a loop: ${path.join(" → ")}.`,
    },
  },
  workspace: {
    title: "Translate",
    targetLocale: "Target locale",
    noTargets: "Add a locale to start translating.",
    addLocales: "Add locales",
    filters: "Filters",
    search: "Search keys and text",
    namespace: "Namespace",
    allNamespaces: "All namespaces",
    coverage: "Show",
    coverageAll: "All messages",
    coverageMissing: (l: string) => `Missing in ${l}`,
    coverageOutdated: (l: string) => `Outdated in ${l}`,
    state: "Message state",
    stateActive: "Active",
    stateObsolete: "Obsolete",
    stateAll: "All",
    messages: "Messages",
    count: (shown: number, loaded: number, done: boolean) =>
      `${shown.toLocaleString()} of ${loaded.toLocaleString()}${done ? "" : "+"} messages`,
    loadingMore: "Loading more…",
    localeStats: (code: string, translated: number, total: number, outdated: number, review: number) =>
      [`${code}: ${translated.toLocaleString()} of ${total.toLocaleString()} translated`, outdated ? `${outdated.toLocaleString()} outdated` : "", review ? `${review.toLocaleString()} need review` : ""]
        .filter(Boolean)
        .join(" · "),
    empty: "No messages match these filters.",
    noMessages: "This project has no messages yet. Push them with the CLI or the API.",
    selectMessage: "Select a message to translate it.",
    status: { missing: "Missing", outdated: "Outdated", translated: "Translated", unknown: "" },
    key: "Key",
    description: "Context",
    noDescription: "No context from the developers yet.",
    maxLength: (n: number) => `Max ${n} characters`,
    source: "Source",
    arguments: "Arguments",
    noArguments: "No arguments",
    markup: "Markup",
    target: "Translation",
    syntax: "Syntax",
    stateLabel: {
      draft: "Draft",
      needs_review: "Needs review",
      approved: "Approved",
      rejected: "Rejected",
    } as Record<string, string>,
    origin: "Origin",
    outdated: "Outdated",
    outdatedLead: (from: number, to: number) => `Translated against source revision ${from}; the source is now at revision ${to}.`,
    showSourceChanges: "Show source changes",
    hideSourceChanges: "Hide source changes",
    sourceChanges: "Changes to the source since this translation",
    notTranslated: "Not translated yet.",
    save: "Save",
    saveApprove: "Save & approve",
    approve: "Approve",
    reject: "Reject",
    requestReview: "Request review",
    saved: "Saved.",
    approved: "Approved.",
    rejected: "Rejected.",
    unchanged: "No changes to save.",
    unsaved: "Unsaved changes",
    noWrite: (l: string) => `You can't write ${l} translations in this workspace.`,
    noReview: (l: string) => `Only reviewers for ${l} can approve or reject.`,
    conflict: "Someone else saved this translation meanwhile. Their version is loaded; your text is kept in the editor.",
    qaTitle: "Structural QA",
    qaFailed: "The translation doesn't match the source's structure. Fix these and save again:",
    qaWarnings: "Warnings",
    invalidText: "The text doesn't parse:",
    preview: "Live preview",
    previewSource: "Source",
    previewTarget: "Translation",
    previewMf1Stale: "The live preview is unavailable right now: it shows the last saved text and updates when you save.",
    previewPaused: "Preview paused: too many previews in a short time. It resumes in a moment.",
    previewInvalid: "This text doesn't parse yet:",
    previewEmpty: "Nothing to preview yet.",
    samples: "Sample values",
    sampleFor: (name: string) => `Sample value for ${name}`,
    pluralForms: (l: string) => `Plural forms in ${l}`,
    formatErrors: "Formatting problems",
    tabs: { editor: "Editor", history: "History" },
    history: "Revisions, newest first",
    historyEmpty: "No revisions yet.",
    revision: (n: number) => `Revision ${n}`,
    kind: { content: "Text", review: "Review" } as Record<string, string>,
    madeAgainst: (n: number) => `against source revision ${n}`,
    by: (who: string) => `by ${who}`,
    canonical: "Canonical MF2",
  },
  releases: {
    title: "Releases",
    lead: "A release is an immutable, signed snapshot of this project's eligible translations. Environments point at releases; promoting and rolling back move the pointer without rebuilding.",
    readOnly: "You can see releases here. Publishing, promoting and rolling back need the developer, admin or owner role.",
    publish: "Publish release",
    environments: "Environments",
    releases: "Releases",
    noReleases: "Nothing published yet. Publish a release to make this project's text available to runtimes.",
    loadMore: "Load more releases",
    version: (v: number) => `v${v}`,
    nothingServed: "Nothing published here yet",
    serving: (v: string) => `Serving ${v}`,
    lastChange: { publish: "Published", promote: "Promoted", rollback: "Rolled back" } as Record<string, string>,
    byWhen: (what: string, who: string) => `${what} by ${who}`,
    ships: "Ships",
    state: { draft: "Draft", needs_review: "Needs review", approved: "Approved" } as Record<string, string>,
    outdatedIncluded: "outdated included",
    outdatedExcluded: "outdated excluded",
    policyText: (states: string, outdated: string) => `${states}; ${outdated}`,
    // Visible label + a visually hidden suffix, so the accessible name starts with what's shown.
    promote: "Promote",
    toEnv: (env: string) => ` to ${env}`,
    rollback: "Roll back",
    history: "History",
    editPolicy: "Policy",
    ofEnv: (env: string) => ` of ${env}`,
    ofRelease: (v: string) => ` ${v}`,
    columns: {
      release: "Release",
      builtFor: "Built for",
      serving: "Serving",
      locales: "Locales",
      messages: "Messages",
      note: "Note",
      published: "Published",
      actions: "Actions",
    },
    // publish
    publishTitle: "Publish a release",
    environment: "Environment",
    note: "Note (optional)",
    noteHint: "What this release is for, e.g. “Checkout copy for the spring sale”.",
    willShip: "What will ship",
    policyLead: (env: string, policy: string) => `${env} ships translations that are: ${policy}.`,
    firstRelease: (env: string) => `Nothing is published to ${env} yet: every eligible translation ships.`,
    dryRunChecking: "Checking what would ship…",
    dryRunSummary: (messages: number, locales: number, fresh: number, bytes: string) =>
      `${messages.toLocaleString()} ${messages === 1 ? "message" : "messages"} in ${locales} ${locales === 1 ? "locale" : "locales"} · ${fresh} new ${fresh === 1 ? "artifact" : "artifacts"} to upload · ${bytes}`,
    dryRunAgainst: (env: string, v: string) => `Compared with ${v}, which ${env} serves now:`,
    dryRunUnchanged: (env: string) => `Nothing would change: ${env} already ships this text.`,
    dryRunNote: "A dry run: nothing is stored until you publish. A translation saved meanwhile ships too.",
    dryRunFailed: "Glossa couldn't check what would ship. You can still publish; the changes are shown once it's built.",
    notReleasable: (n: number) => `This can't be published yet: ${n} ${n === 1 ? "problem" : "problems"} to fix first.`,
    publishTo: (env: string) => `Publish to ${env}`,
    publishing: "Publishing…",
    published: (v: string, env: string) => `Published ${v} to ${env}.`,
    changesSince: (v: string) => `Changes since ${v}, per locale`,
    everythingNew: "Everything is new in this environment.",
    noChanges: "Nothing changed: it ships the same text as before.",
    done: "Done",
    // promote
    promoteTitle: "Promote a release",
    release: "Release",
    target: "To environment",
    choose: "Choose…",
    pointerMove: (env: string, from: string, to: string) => `${env}: ${from} → ${to}`,
    noneYet: "nothing",
    alreadyServing: (env: string, v: string) => `${env} already serves ${v}. Nothing would change.`,
    ineligible: (env: string, v: string, states: string) =>
      `${v} can't go to ${env}: it was built with ${states} translations, which ${env} doesn't ship. ` +
      (env === "production" ? "Publish to staging (approved text, like production) and promote that release, or publish to production directly." : `Publish to ${env} instead, or change its policy.`),
    ineligibleOutdated: (env: string, v: string) => `${v} can't go to ${env}: it ships outdated translations, which ${env} excludes.`,
    promoteConfirm: (v: string, env: string) => `Promote ${v} to ${env}`,
    promoted: (v: string, env: string) => `${env} now serves ${v}.`,
    pointerOnly: "Only the pointer moves: nothing is rebuilt, and runtimes pick it up within a minute.",
    // rollback
    rollbackTitle: (env: string) => `Roll back ${env}`,
    rollbackTo: "Back to",
    noRollback: (env: string) => `${env} hasn't served an earlier release, so there's nothing to roll back to.`,
    rollbackConfirm: (env: string, v: string) => `Roll ${env} back to ${v}`,
    rolledBack: (env: string, v: string) => `${env} is back on ${v}.`,
    // policy
    policyTitle: (env: string) => `What ships to ${env}`,
    policyStates: "Review states that ship",
    policyStatesHint: "Rejected translations never ship. Promotions into this environment must fit this policy too.",
    includeOutdated: "Ship outdated translations",
    includeOutdatedHint: "Translations made against an older version of the source text.",
    policyNeedsState: "Choose at least one review state.",
    policySaved: (env: string) => `${env}'s policy is saved. It applies from the next publish; the current release keeps serving.`,
    savePolicy: "Save policy",
    // history
    historyTitle: (env: string) => `Deployments to ${env}`,
    historyEmpty: "No deployments yet.",
    historyColumns: { number: "#", action: "Change", release: "Release", by: "By", when: "When" },
    from: (v: string) => `from ${v}`,
    // detail
    detailTitle: (v: string) => `Release ${v}`,
    backToReleases: "All releases",
    builtFor: "Built for",
    policy: "Policy",
    publishedBy: "Published",
    parent: "Previous release here",
    noParent: "None: the first release of its environment",
    digest: "Manifest digest",
    artifacts: "Artifacts",
    artifactsText: (n: number, fresh: number, bytes: string) => `${n} (${fresh} new), ${bytes}`,
    perLocale: "Per locale",
    diffTo: (v: string) => `Compared with ${v}`,
    diffToNothing: "Compared with nothing: the first release of its environment",
    localeColumns: { locale: "Locale", messages: "Messages", outdated: "Outdated", added: "Added", changed: "Changed", removed: "Removed" },
    showIds: (n: number) => `Show ${n} message ${n === 1 ? "ID" : "IDs"}`,
    sourceLocale: "source",
    notInRelease: "not in this release",
  },
  deliveryKeys: {
    title: "Delivery keys",
    lead: "Runtimes load releases from glossa-edge with a publishable delivery key. It is public by design (it ships in browser bundles), read-only, scoped to this project, and grants nothing on the API.",
    name: "Name",
    nameHint: "What uses it, e.g. “web” or “go-emails”.",
    create: "Create delivery key",
    creating: "Creating…",
    empty: "No delivery keys yet.",
    columns: { name: "Name", key: "Key", created: "Created", status: "Status", actions: "Actions" },
    active: "Active",
    revoked: "Revoked",
    revoke: "Revoke",
    revokeLabel: (name: string) => `Revoke ${name}`,
    revokeTitle: (name: string) => `Revoke “${name}”?`,
    revokeBody: (key: string) =>
      `Runtimes using ${key} stop receiving new releases from the edge within about 30 seconds, plus any CDN caching; they keep the release they already loaded. A revoked key can't be restored.`,
    revokeConfirm: "Revoke key",
    revokedDone: (name: string) => `${name} is revoked.`,
    createdTitle: (name: string) => `Delivery key “${name}”`,
    createdLead: "Copy the key now: later Studio shows only its beginning. Paste one of these snippets into your app to load this project's releases.",
    key: "Delivery key",
    copy: "Copy",
    copyLabel: (what: string) => `Copy ${what}`,
    copied: "Copied.",
    copyFailed: "Couldn't copy: select the text and copy it yourself.",
    snippetEnv: "Environment",
    snippets: "Integration snippets",
    snippetOf: (runtime: string) => `${runtime} snippet`,
    install: "Install",
    edgePlaceholder: (edge: string) => `Replace ${edge} with your glossa-edge origin. Set GLOSSA_STUDIO_EDGE_URL on the Studio container to fill it in.`,
    signed: "The snippets pin this project's signing keys, so a manifest without a valid signature is rejected.",
  },
  assist: {
    label: "What Glossa knows about this message",
  },
  tm: {
    title: "Translation memory",
    none: "No similar approved translations yet.",
    kind: { context: "Same key, exact", exact: "Exact match", fuzzy: "Fuzzy match" } as Record<string, string>,
    insert: "Insert",
    sourceDiff: "Its source, compared with this one:",
    from: (key: string) => `From ${key}`,
    imported: "Imported",
    scopeProject: "this project",
    scopeTenant: "workspace-wide",
    variablesKept: "a variable kept its name — check it",
  },
  concordance: {
    title: "Concordance",
    phrase: "Phrase to look up",
    placeholder: "How was … translated?",
    side: "Search in",
    inSource: (l: string) => `in source (${l})`,
    inTarget: (l: string) => `in translation (${l})`,
    search: "Search",
    results: "Earlier translations containing the phrase",
    none: "Nothing in the translation memory contains that phrase.",
    similarity: (x: number) => `similarity ${x.toFixed(2)}`,
  },
  terms: {
    title: "Terminology",
    none: "No termbase terms in this source.",
    status: { preferred: "Preferred", admitted: "Admitted", deprecated: "Deprecated", forbidden: "Forbidden" } as Record<string, string>,
    avoid: (status: string) => `${status} — avoid`,
    targetTerms: (l: string) => `Terms in ${l}`,
    noTarget: (l: string) => `No ${l} term for this concept yet.`,
    findingsTitle: "Terminology",
    severity: { error: "error", warning: "warning" },
    forbiddenUsed: (t: string) => `“${t}” is a term to avoid here.`,
    missingTerm: (t: string) => `“${t}” is in the source, but the translation uses none of its approved terms.`,
    useInstead: (s: string[]) => `Use: ${s.join(", ")}`,
    checkStale: "The terminology check is paused until the text parses.",
    checkClean: "The translation uses the termbase's terms.",
  },
  style: {
    paneTitle: (locale: string, ns: string) => `Style for ${locale} · ${ns}`,
    none: "No style guide applies here yet.",
    rules: "Style rules",
    good: "Do",
    bad: "Don't",
    sources: (n: number) => (n === 1 ? "From 1 guide." : `Merged from ${n} guides, the narrowest winning.`),
    summary: {
      address: "Address",
      tone: "Tone",
      quotes: "Quotes",
      nested: (q: string) => `(nested ${q})`,
      dash: "Dash",
      dashes: { hyphen: "hyphen (-)", en: "en dash (–)", em: "em dash (—)" },
      ellipsis: "Ellipsis",
      spaceBeforeUnit: "Space before units",
      spaceBeforePunctuation: "Space before punctuation",
      serialComma: "Serial comma",
      yes: "yes",
      no: "no",
      numbers: "Numbers",
      decimal: (s: string) => `decimal “${s}”`,
      grouping: (s: string) => `grouping “${s}”`,
      numberNotes: "Number notes",
      dates: "Dates",
      dateNotes: "Date notes",
    },
    title: "Style guides",
    lead: "Style is structured, not prose, so the AI and QA can follow it. Guides stack from the workspace to this project, a locale and a namespace; the narrowest wins field by field.",
    readOnly: "You can read the style guides. Changing them needs the developer, admin or owner role.",
    newGuide: "New style guide",
    empty: "No style guides yet.",
    scope: "Applies to",
    scopeLevel: { tenant: "The whole workspace", project: "This project", locale: "This project, one locale", namespace: "This project, one locale and namespace" } as Record<string, string>,
    tenantScope: "Workspace",
    locale: "Locale",
    namespace: "Namespace",
    name: "Name",
    version: (n: number) => `v${n}`,
    updated: (who: string, when: string) => `Updated by ${who}, ${when}`,
    edit: (name: string) => `Edit ${name}`,
    history: (name: string) => `History of ${name}`,
    remove: (name: string) => `Delete ${name}`,
    dialogNew: "New style guide",
    dialogEdit: (name: string) => `Edit “${name}”`,
    fields: "Fields",
    inherit: "Inherit",
    register: "Formality",
    registers: { formal: "Formal", informal: "Informal", neutral: "Neutral" } as Record<string, string>,
    pronoun: "Pronoun",
    pronounHint: "How the reader is addressed, e.g. du, Sie, vous.",
    tone: "Tone",
    toneHint: "Tags, separated by commas: concise, friendly, …",
    quotes: "Quotes",
    nestedQuotes: "Nested quotes",
    dash: "Dash",
    ellipsis: "Ellipsis",
    spaceBeforeUnit: "Space before units",
    spaceBeforePunctuation: "Space before punctuation",
    serialComma: "Serial comma",
    yes: "Yes",
    no: "No",
    decimal: "Decimal separator",
    grouping: "Grouping separator",
    numberNotes: "Number notes",
    dateFormat: "Date pattern (CLDR)",
    dateNotes: "Date notes",
    rulesTitle: "Rules",
    addRule: "Add rule",
    ruleTitle: "Rule",
    ruleId: "ID",
    ruleIdHint: "Lowercase letters, digits, - and _. A narrower guide's rule with the same ID replaces this one.",
    rationale: "Why",
    goodExamples: "Good examples (one per line)",
    badExamples: "Bad examples (one per line)",
    disableRule: "Switch off the broader rule with this ID",
    removeRule: (n: number) => `Remove rule ${n}`,
    invalidRuleId: (id: string) => `“${id}” isn't a valid rule ID.`,
    saveGuide: "Save guide",
    created: "Style guide created.",
    saved: "Style guide saved.",
    deleted: "Style guide deleted.",
    confirmDelete: (name: string) => `Delete “${name}”?`,
    confirmDeleteLead: "Its versions stay readable; broader guides apply again where it did.",
    versions: (name: string) => `Versions of “${name}”`,
    versionAction: { created: "Created", updated: "Updated", deleted: "Deleted" } as Record<string, string>,
    preview: "What applies",
    previewLead: "The effective style for a locale and namespace of this project.",
    previewNamespace: "Namespace",
    changedElsewhere: "Someone else changed this guide meanwhile. Reload it and try again.",
  },
  termbase: {
    title: "Termbase",
    lead: "Concepts and their terms per locale: the words to use, and the ones to avoid. Terms are highlighted in the editor and checked as translators type.",
    readOnly: "You can read the termbase. Changing it needs the developer, admin or owner role.",
    search: "Search terms and definitions",
    locale: "Locale",
    allLocales: "All locales",
    newConcept: "New concept",
    empty: "No concepts yet.",
    noMatch: "No concepts match.",
    scopeProject: "This project",
    scopeTenant: "Workspace",
    scope: "Scope",
    scopeHint: "A workspace concept applies to every project; the scope can't change later.",
    definition: "Definition",
    domain: "Domain",
    note: "Note",
    terms: "Terms",
    term: "Term",
    status: "Status",
    partOfSpeech: "Part of speech",
    pos: { "": "—", noun: "Noun", verb: "Verb", adjective: "Adjective", adverb: "Adverb", proper_noun: "Proper noun", phrase: "Phrase", other: "Other" } as Record<string, string>,
    caseSensitive: "Case-sensitive",
    termNote: "Usage note",
    addTerm: "Add term",
    removeTerm: (n: number) => `Remove term ${n}`,
    dialogNew: "New concept",
    dialogEdit: "Edit concept",
    saveConcept: "Save concept",
    created: "Concept added.",
    saved: "Concept saved.",
    deleted: "Concept deleted.",
    edit: (label: string) => `Edit ${label}`,
    history: (label: string) => `History of ${label}`,
    remove: (label: string) => `Delete ${label}`,
    confirmDelete: (label: string) => `Delete “${label}”?`,
    confirmDeleteLead: "Its history stays readable. Its terms stop being highlighted and checked.",
    revisions: (label: string) => `History of “${label}”`,
    revisionAction: { created: "Created", updated: "Updated", deleted: "Deleted" } as Record<string, string>,
    version: (n: number) => `v${n}`,
    needsTerm: "Add at least one term.",
    changedElsewhere: "Someone else changed this concept meanwhile. Reload it and try again.",
  },
  ai: {
    title: "AI suggestion",
    none: "No AI suggestion for this message yet. “Fill with AI” asks for one.",
    status: { pending: "Pending", accepted: "Accepted", rejected: "Rejected", auto_applied: "Auto-applied", superseded: "Superseded" } as Record<string, string>,
    band: { very_high: "Very high confidence", high: "High confidence", medium: "Medium confidence", low: "Low confidence" } as Record<string, string>,
    score: (x: string) => `score ${x}`,
    notCertainty: "Confidence orders review; it isn't a promise that the text is right.",
    action: { auto_approve: "Auto-approve", approve_recommended: "Approval recommended", review_required: "Review required" } as Record<string, string>,
    risks: "Risks",
    riskTag: (t: string) => ({ legal: "Legal text", marketing: "Marketing text", term_forbidden: "Forbidden term", max_length: "Too long", missing_plural_categories: "Missing plural forms", markup: "Markup" })[t] ?? t.replaceAll("_", " "),
    findings: "Findings",
    why: "Why?",
    factorsCaption: "What moved the confidence score",
    factor: "Factor",
    effect: "Effect",
    reason: "Why",
    factorName: (f: string) =>
      ({
        origin: "Origin",
        tm_match: "Translation-memory match",
        term_forbidden: "Forbidden term",
        term_missing: "Missing term",
        repairs: "Repairs",
        qa_warnings: "QA warnings",
        self_assessment: "Model's self-assessment",
        formality: "Formality",
        max_length: "Max length",
        length_ratio: "Length ratio",
        risk_tag: "Risk tag",
        markup_density: "Markup density",
        missing_plural_categories: "Missing plural forms",
      })[f] ?? f.replaceAll("_", " "),
    provenance: "Provenance",
    origin: "Made by",
    originName: { ai: "AI model", translation_memory: "Translation memory (no model call)" } as Record<string, string>,
    model: "Provider / model",
    promptVersion: "Prompt version",
    tmUnits: "TM units used",
    terms: "Terms used",
    styleVersion: "Style guide version",
    repairs: "Structural repairs",
    cost: "Cost",
    tokens: (n: number) => `${n.toLocaleString()} tokens`,
    count: (n: number) => n.toLocaleString(),
    noneUsed: "none",
    accept: "Accept",
    edit: "Edit…",
    rejectEllipsis: "Reject…",
    reject: "Reject",
    acceptEdit: "Accept edit",
    editLabel: "Your edit (MessageFormat 2)",
    editHint: (chord: string) => `${chord} accepts, Esc cancels. Your changes are recorded to improve future suggestions.`,
    reasonLabel: "Reason (optional)",
    acceptedNotice: "Accepted: it's now the translation.",
    acceptedEditNotice: "Your edit is accepted as the translation.",
    rejectedNotice: "Rejected. Nothing was written.",
    editedBy: (d: number) => `Accepted after an edit of ${d} character${d === 1 ? "" : "s"}.`,
    noDecide: (l: string) => `Accepting and rejecting ${l} suggestions needs permission to translate ${l}.`,
  },
  fill: {
    button: "Fill with AI…",
    queueLink: "Review queue",
    title: (l: string) => `Fill ${l} with AI`,
    scope: (l: string, ns: string | undefined, keys: number | undefined) =>
      keys !== undefined
        ? `Of the ${keys.toLocaleString()} message${keys === 1 ? "" : "s"} your search shows${ns ? ` in ${ns}` : ""}, each one missing in ${l} gets an AI suggestion.`
        : `Every message${ns ? ` in ${ns}` : ""} missing in ${l} gets an AI suggestion.`,
    includeOutdated: "Also redo outdated translations",
    lead: "Suggestions use the translation memory, termbase and style guides, and wait in the review queue unless the project's policy auto-approves them. Messages in sensitive namespaces are never sent to a provider.",
    start: "Fill with AI",
    queued: (created: number, existing: number) =>
      `${created.toLocaleString()} job${created === 1 ? "" : "s"} queued${existing ? `, ${existing.toLocaleString()} already there` : ""}.`,
    skipped: (entries: Array<[string, number]>) =>
      `Skipped: ${entries.map(([why, n]) => `${n} ${({ sensitive: "in sensitive namespaces", up_to_date: "up to date", limit: "over the limit" } as Record<string, string>)[why] ?? why}`).join(", ")}.`,
    progressLabel: "Progress",
    progress: (p: { total: number; active: number; succeeded: number; skipped: number; failed: number }) =>
      p.active
        ? `${(p.total - p.active).toLocaleString()} of ${p.total.toLocaleString()} done…`
        : `Done: ${p.succeeded} suggested, ${p.skipped} skipped, ${p.failed} failed.`,
    nothing: "Nothing to fill: every message in scope has a translation.",
    failure: (code: string, n: number) =>
      `${n} × ${({ provider_consent: "consent to use AI providers is off", sensitive: "sensitive namespace", invalid_output: "the model's answer wasn't valid", budget_exceeded: "over the monthly budget", no_route: "no provider for this task", provider_error: "the provider failed", invalid_source: "the source doesn't parse", dead: "gave up after retries", cancelled: "cancelled" } as Record<string, string>)[code] ?? code}`,
    warning: (w: string) =>
      ({
        provider_consent_off: "Sending text to AI providers is off for this workspace, so only exact translation-memory matches are reused. An admin can turn it on in AI settings.",
        no_budget: "The monthly AI budget is 0, so no provider is called. An admin can set a budget in AI settings.",
        no_provider: "No AI provider is configured for this workspace. An admin can add one in AI settings.",
      })[w] ?? w,
    cancelQueued: "Cancel queued jobs",
    openQueue: "Open the review queue",
    keepRunning: "Close (keeps running)",
  },
  review: {
    title: "Review queue",
    lead: "AI suggestions waiting for a person, riskiest first: the lowest confidence, then the most risk tags. The routing policy decides what lands here.",
    locale: "Locale",
    allLocales: "All your locales",
    list: "Suggestions to review",
    empty: "Nothing to review. New suggestions appear here as AI jobs finish.",
    loadMore: "Load more",
    count: (n: number, more: boolean) => `${n.toLocaleString()}${more ? "+" : ""} waiting`,
    source: "Source",
    openInEditor: "Open in the editor",
    accept: "Accept",
    edit: "Edit",
    reject: "Reject",
    acceptEdit: "Accept edit",
    editLabel: "Your edit (MessageFormat 2)",
    batch: (n: number) => `Accept ${n} recommended`,
    batchTitle: "Accept every recommended suggestion?",
    batchLead: (n: number) =>
      `${n} suggestion${n === 1 ? " is" : "s are"} routed “approval recommended” by the project's policy. Each becomes the translation. Suggestions that need review are left for you.`,
    batchConfirm: (n: number) => `Accept ${n}`,
    batchDone: (ok: number, failed: number) => `Accepted ${ok}${failed ? `; ${failed} couldn't be accepted` : ""}.`,
    accepted: (key: string, l: string) => `Accepted ${key} (${l}).`,
    acceptedEdit: (key: string, l: string) => `Accepted your edit of ${key} (${l}).`,
    rejected: (key: string, l: string) => `Rejected ${key} (${l}).`,
    noDecide: (l: string) => `You can't decide ${l} suggestions.`,
    keys: "a accept · e edit · r reject · j/k move",
  },
  aiSettings: {
    title: "AI",
    lead: "Which models translate for this workspace, what they may see and spend, and how their suggestions are routed. Settings above the line apply to the whole workspace; below it, to this project.",
    readOnly: "You can see the AI settings. Changing them needs the admin or owner role.",
    workspace: "Workspace",
    project: "This project",
    consentTitle: "Data handling",
    consentLead: "Messages can hold unreleased product copy, customer templates or legal text. Nothing is sent to an AI provider unless you allow it here.",
    consentPoints: [
      "When on, a provider receives exactly what the translation agent looked up for one message: its source and context, matching terms, style rules and translation-memory matches. Every call is logged below (“Disclosures”).",
      "Namespaces tagged sensitive are never sent, whatever this says.",
      "When off, exact translation-memory matches are still reused; nothing else is translated by AI.",
    ],
    consentOn: "Sending text to AI providers is allowed.",
    consentOff: "Sending text to AI providers is off.",
    consentChanged: (who: string, when: string) => `Changed by ${who}, ${when}.`,
    allow: "Allow sending text…",
    disallow: "Stop sending text",
    confirmAllow: "Allow sending text to AI providers?",
    confirmAllowLead: "From now on, AI jobs in every project of this workspace send message text to the configured providers under their terms. You can turn this off at any time; what was already sent stays logged.",
    confirmAllowButton: "Allow",
    providers: "Providers",
    providersLead: "Bring your own keys. A key is sealed (encrypted) when stored and never shown again, not even to admins.",
    noProviders: "No providers yet. Routing uses a provider named “anthropic” by default.",
    name: "Name",
    nameHint: "What routing refers to, e.g. anthropic or mistral-eu.",
    kind: "API",
    kinds: { anthropic: "Anthropic", openai_compatible: "OpenAI-compatible", gemini: "Gemini" } as Record<string, string>,
    baseUrl: "Endpoint (base URL)",
    baseUrlHint: "https only. Required for OpenAI-compatible servers; empty uses the API's default.",
    models: "Allowed models",
    modelsHint: "Comma-separated; empty allows any model.",
    anyModel: "any model",
    enabled: "Enabled",
    disabled: "Disabled",
    apiKey: "API key",
    apiKeyHint: "Stored sealed, never shown again. Leave empty to keep the current key.",
    apiKeyNewHint: "Stored sealed, never shown again — keep your own copy if you need it.",
    keySet: "Key stored (sealed)",
    keyMissing: "No key",
    clearKey: "Remove the stored key",
    addProvider: "Add provider",
    editProvider: (n: string) => `Edit ${n}`,
    removeProvider: (n: string) => `Remove ${n}`,
    confirmRemove: (n: string) => `Remove provider “${n}”?`,
    confirmRemoveLead: "Its key is deleted. A routing policy that uses it has to change first.",
    providerSaved: "Provider saved.",
    budgetTitle: "Budget and spend",
    budget: "Monthly budget (USD)",
    budgetHint: "Provider spend per calendar month (UTC). 0 stops all provider calls.",
    invalidBudget: "Enter an amount in dollars, like 25 or 12.50.",
    concurrency: "Jobs running at once",
    saveBudget: "Save budget",
    budgetSaved: "Budget saved.",
    spent: (spent: string, budget: string) => `${spent} of ${budget} spent this month`,
    remaining: (r: string) => `${r} left`,
    calls: (n: number) => `${n.toLocaleString()} call${n === 1 ? "" : "s"}`,
    spendChart: "Spend per day this month",
    spendChartEmpty: "No provider calls this month.",
    spendTable: "Show as a table",
    byModel: "By provider and model",
    provider: "Provider",
    model: "Model",
    cost: "Cost",
    tokens: "Tokens (in / out)",
    prices: "Prices",
    pricesLead: "USD per million tokens. Your overrides replace the deployment's defaults; an unpriced model costs 0 and is flagged.",
    priceKey: "Provider/model",
    priceIn: "Input",
    priceOut: "Output",
    override: "Override",
    removeOverride: (k: string) => `Remove override for ${k}`,
    addOverride: "Add override",
    pricesSaved: "Prices saved.",
    routingTitle: "Routing policy",
    routingLead: "Which provider and model each task uses, per target locale, with fallbacks in order.",
    routingSource: { default: "The default policy applies (Anthropic).", tenant: "The workspace's policy applies.", project: "This project has its own policy." } as Record<string, string>,
    routingScope: "Edit the policy of",
    routingScopes: { project: "this project", tenant: "the workspace" } as Record<string, string>,
    task: "Task",
    tasks: { translate: "Translate", review: "Review", explain: "Explain", assess: "Self-assessment" } as Record<string, string>,
    ruleLocales: "Locales",
    ruleLocalesHint: "Comma-separated; empty applies to all.",
    routes: "Routes (first preferred)",
    maxTokens: "Max tokens",
    temperature: "Temperature",
    effort: "Effort",
    effortDefault: "Default",
    addRoute: "Add fallback",
    removeRoute: (n: number) => `Remove route ${n}`,
    addRule: "Add rule",
    removeRule: (n: number) => `Remove rule ${n}`,
    saveRouting: "Save policy",
    routingSaved: "Routing policy saved.",
    resetProject: "Use the workspace's policy",
    projectPolicy: "Project policy",
    namespaceTags: "Namespace tags",
    namespaceTagsLead: "Sensitive: never sent to a provider, always translated by people. Legal and marketing: riskier, reviewed first.",
    namespace: "Namespace",
    tagNames: { sensitive: "Sensitive", legal: "Legal", marketing: "Marketing" } as Record<string, string>,
    addNamespace: "Add namespace",
    removeNamespace: (ns: string) => `Remove ${ns}`,
    noTags: "No namespace is tagged.",
    autoTranslate: "Auto-translate",
    autoTranslateLead: "New and outdated messages in these locales get an AI suggestion automatically.",
    reviewRouting: "Review routing",
    reviewRoutingLead: "Suggestions scoring at or above the first line are recommended for approval; below it, they need review.",
    recommendMin: "Approval recommended from score",
    autoApprove: "Auto-approve high-confidence suggestions",
    autoApproveWarning: "Auto-approved text becomes an approved translation without anyone reading it, and ships to the environments below. Keep this off unless your evals and edit rates say it's safe.",
    autoApproveMin: "Auto-approve from score",
    autoApproveEnvironments: "Environments auto-approved text ships to",
    autoApproveEnvironmentsHint: "Comma-separated; each must ship approved translations only.",
    forceReview: "Always review when these factors apply",
    forceReviewHint: "Comma-separated factor names, e.g. term_forbidden, max_length.",
    saveProject: "Save project policy",
    projectSaved: "Project policy saved.",
    insights: "Insights",
    metrics: "Acceptance per locale (last 30 days)",
    metricsEmpty: "No decisions on suggestions yet.",
    locale: "Locale",
    acceptance: "Accepted",
    acceptanceRate: "Acceptance rate",
    editDistance: "Mean edit distance",
    rejected: "Rejected",
    edited: "Edited",
    disclosures: "Disclosures",
    disclosuresLead: "Every provider call, with exactly what the provider received, newest first.",
    disclosuresEmpty: "No provider has seen any text from this project.",
    when: "When",
    message: "Message",
    whatWasSent: "What was sent",
    baseline: "Eval baseline",
    baselineLead: "The golden-set metrics committed with this server. A prompt or model change may not regress them.",
    pair: "Pair",
    cases: "Cases",
    structural: "Structural",
    terminology: "Terminology",
    formality: "Formality",
    editRatio: "Edit ratio",
    changedElsewhere: "Someone else changed these settings meanwhile. They're reloaded; make your change again.",
    percent: (x: number) => `${Math.round(x * 100)}%`,
  },
  shortcuts: {
    title: "Keyboard shortcuts",
    lead: "Studio is built for the keyboard. Chords use ⌘ on macOS and Ctrl elsewhere.",
  },
  problems: {
    network_error: "The server could not be reached. Check your connection and try again.",
    unexpected_response: "The server sent an unexpected response.",
    invalid_response: "The server's response didn't match what Studio expects.",
    unauthenticated: "Your session has ended. Sign in again.",
    invalid_credentials: "That email and password don't match.",
    totp_required: "Enter the code from your authenticator app.",
    totp_invalid: "That code isn't valid. Codes change every 30 seconds.",
    email_unverified: "Verify your email first: open the link we sent you.",
    account_locked: "Too many attempts. Password sign-in is locked for 15 minutes; a sign-in link still works.",
    link_invalid: "This link is invalid, expired or already used.",
    weak_password: "Choose a longer password (at least 12 characters).",
    passkeys_disabled: "Passkeys aren't enabled on this server.",
    no_passkeys: "There's no passkey for this address. Use a sign-in link instead.",
    passkey_invalid: "The passkey couldn't be verified.",
    rate_limited: "Too many requests. Wait a moment and try again.",
    slug_taken: "That slug is taken.",
    forbidden: "You don't have permission to do that here.",
    review_forbidden: "Approving and rejecting needs the reviewer role for this locale.",
    source_locale: "That's the source locale.",
    locale_in_fallback: "Remove it from the fallback graph first.",
    invalid_locale: "That isn't a valid locale code.",
    invalid_transition: "That review step isn't possible from the current state.",
    precondition_failed: "Someone else changed this meanwhile. Reload and try again.",
    translation_conflict: "Someone else created this translation first. Reload and try again.",
    structural_qa_failed: "The translation doesn't match the source's structure.",
    invalid_message: "The text doesn't parse.",
    release_ineligible: "That release has translations this environment's policy doesn't ship.",
    release_not_found: "That release doesn't exist in this project.",
    no_rollback_target: "This environment hasn't served an earlier release.",
    not_in_history: "This environment never served that release.",
    not_releasable: "There's nothing to release yet: add messages first.",
    storage_unavailable: "Object storage is unavailable right now. Nothing changed; try again in a moment.",
    invalid_policy: "That policy isn't valid: choose at least one review state.",
    invalid_note: "The note is too long (at most 1000 characters).",
    invalid_key_name: "Give the key a name of 1 to 200 characters.",
    key_revoked: "That key is already revoked.",
    environment_exists: "An environment with that name exists already.",
    suggestion_decided: "Someone decided on this suggestion meanwhile.",
    suggestion_outdated: "The source changed since this suggestion was made; it can't be accepted any more.",
    translation_rejected: "The translation was refused; check its QA findings.",
    duplicate_term: "That term is listed twice for the same locale.",
    invalid_term_status: "That term status isn't valid.",
    style_guide_exists: "This scope has a style guide already: edit that one.",
    namespace_needs_project: "A namespace guide needs a project.",
    invalid_style_rule: "A rule needs an ID and a title (unless it switches a broader rule off).",
    provider_name_taken: "A provider with that name exists already.",
    provider_in_use: "A routing policy uses this provider. Change the policy first.",
    invalid_provider: "That provider configuration isn't valid.",
    invalid_routing_policy: "Every route needs a configured provider that allows its model.",
    invalid_settings: "Those settings aren't valid.",
    invalid_review_policy: "Scores must be between 0 and 1, the auto-approve line at or above the recommend line.",
    invalid_namespace_tags: "Those namespace tags aren't valid.",
    auto_approve_ineligible: "Auto-approve needs environments that exist and ship approved translations only.",
    job_not_cancellable: "Only queued jobs can be cancelled.",
    too_many_keys: "Too many messages for one fill (at most 500 keys); narrow the search.",
    locale_not_found: "That locale isn't in this project.",
  } as Record<string, string>,
};

/** A person-readable message for any error, preferring our copy for known codes. */
export function problemText(e: unknown): string {
  if (e instanceof ApiError) {
    const known = strings.problems[e.code];
    if (known && e.code !== "invalid_message") return known;
    return e.message || strings.problems.unexpected_response!;
  }
  return e instanceof Error ? e.message : String(e);
}

/** "person:abc" → a short label; the API names principals, not people, in history. */
export function principalLabel(principal: string, selfId?: string): string {
  const [kind, id] = principal.split(":");
  if (kind === "person" && id && id === selfId) return "you";
  if (kind === "token") return `API token ${id?.slice(0, 8) ?? ""}`;
  if (kind === "person") return `member ${id?.slice(0, 8) ?? ""}`;
  return principal;
}
