// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIProvider = `-- name: CreateAIProvider :one
INSERT INTO ai_translation_providers (
  tenant_id, kind, label, base_url, model, api_key_ct, api_key_nonce, enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, kind, label, base_url, model, enabled, created_at, updated_at
`

type CreateAIProviderParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Kind        string      `json:"kind"`
	Label       string      `json:"label"`
	BaseUrl     string      `json:"base_url"`
	Model       string      `json:"model"`
	ApiKeyCt    []byte      `json:"api_key_ct"`
	ApiKeyNonce []byte      `json:"api_key_nonce"`
	Enabled     bool        `json:"enabled"`
}

type CreateAIProviderRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Kind      string             `json:"kind"`
	Label     string             `json:"label"`
	BaseUrl   string             `json:"base_url"`
	Model     string             `json:"model"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAIProvider(ctx context.Context, arg CreateAIProviderParams) (CreateAIProviderRow, error) {
	row := q.db.QueryRow(ctx, createAIProvider,
		arg.TenantID,
		arg.Kind,
		arg.Label,
		arg.BaseUrl,
		arg.Model,
		arg.ApiKeyCt,
		arg.ApiKeyNonce,
		arg.Enabled,
	)
	var i CreateAIProviderRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Label,
		&i.BaseUrl,
		&i.Model,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAIProvider = `-- name: DeleteAIProvider :exec
DELETE FROM ai_translation_providers WHERE id = $1
`

func (q *Queries) DeleteAIProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAIProvider, id)
	return err
}

const getAIProvider = `-- name: GetAIProvider :one
SELECT id, tenant_id, kind, label, base_url, model, api_key_ct, api_key_nonce, enabled, created_at, updated_at
FROM ai_translation_providers
WHERE id = $1
`

func (q *Queries) GetAIProvider(ctx context.Context, id pgtype.UUID) (AiTranslationProvider, error) {
	row := q.db.QueryRow(ctx, getAIProvider, id)
	var i AiTranslationProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Label,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKeyCt,
		&i.ApiKeyNonce,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIProviders = `-- name: ListAIProviders :many
SELECT id, tenant_id, kind, label, base_url, model, enabled, created_at, updated_at
FROM ai_translation_providers
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListAIProvidersRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Kind      string             `json:"kind"`
	Label     string             `json:"label"`
	BaseUrl   string             `json:"base_url"`
	Model     string             `json:"model"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAIProviders(ctx context.Context, tenantID pgtype.UUID) ([]ListAIProvidersRow, error) {
	rows, err := q.db.Query(ctx, listAIProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIProvidersRow
	for rows.Next() {
		var i ListAIProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Label,
			&i.BaseUrl,
			&i.Model,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAIProvidersForTenant = `-- name: ListEnabledAIProvidersForTenant :many
SELECT id, tenant_id, kind, label, base_url, model, api_key_ct, api_key_nonce
FROM ai_translation_providers
WHERE tenant_id = $1 AND enabled = TRUE
ORDER BY created_at ASC
`

type ListEnabledAIProvidersForTenantRow struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Kind        string      `json:"kind"`
	Label       string      `json:"label"`
	BaseUrl     string      `json:"base_url"`
	Model       string      `json:"model"`
	ApiKeyCt    []byte      `json:"api_key_ct"`
	ApiKeyNonce []byte      `json:"api_key_nonce"`
}

func (q *Queries) ListEnabledAIProvidersForTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListEnabledAIProvidersForTenantRow, error) {
	rows, err := q.db.Query(ctx, listEnabledAIProvidersForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledAIProvidersForTenantRow
	for rows.Next() {
		var i ListEnabledAIProvidersForTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Label,
			&i.BaseUrl,
			&i.Model,
			&i.ApiKeyCt,
			&i.ApiKeyNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIProvider = `-- name: UpdateAIProvider :exec
UPDATE ai_translation_providers
SET label = $2,
    base_url = $3,
    model = $4,
    enabled = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAIProviderParams struct {
	ID      pgtype.UUID `json:"id"`
	Label   string      `json:"label"`
	BaseUrl string      `json:"base_url"`
	Model   string      `json:"model"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpdateAIProvider(ctx context.Context, arg UpdateAIProviderParams) error {
	_, err := q.db.Exec(ctx, updateAIProvider,
		arg.ID,
		arg.Label,
		arg.BaseUrl,
		arg.Model,
		arg.Enabled,
	)
	return err
}

const updateAIProviderKey = `-- name: UpdateAIProviderKey :exec
UPDATE ai_translation_providers
SET api_key_ct = $2,
    api_key_nonce = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAIProviderKeyParams struct {
	ID          pgtype.UUID `json:"id"`
	ApiKeyCt    []byte      `json:"api_key_ct"`
	ApiKeyNonce []byte      `json:"api_key_nonce"`
}

func (q *Queries) UpdateAIProviderKey(ctx context.Context, arg UpdateAIProviderKeyParams) error {
	_, err := q.db.Exec(ctx, updateAIProviderKey, arg.ID, arg.ApiKeyCt, arg.ApiKeyNonce)
	return err
}
