// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const projectFunnel = `-- name: ProjectFunnel :many
SELECT kind, MIN(occurred_at) AS first_at, COUNT(*) AS total
FROM analytics_events
WHERE tenant_id = $1 AND project_id = $2
GROUP BY kind
ORDER BY kind
`

type ProjectFunnelParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type ProjectFunnelRow struct {
	Kind    string      `json:"kind"`
	FirstAt interface{} `json:"first_at"`
	Total   int64       `json:"total"`
}

// Returns first-occurrence timestamps per kind for a single project.
// Drives the cohort funnel display in the admin metrics view.
func (q *Queries) ProjectFunnel(ctx context.Context, arg ProjectFunnelParams) ([]ProjectFunnelRow, error) {
	rows, err := q.db.Query(ctx, projectFunnel, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectFunnelRow
	for rows.Next() {
		var i ProjectFunnelRow
		if err := rows.Scan(&i.Kind, &i.FirstAt, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAnalyticsEvent = `-- name: RecordAnalyticsEvent :exec
INSERT INTO analytics_events (tenant_id, project_id, kind, metadata)
VALUES ($1, $2, $3, $4)
`

type RecordAnalyticsEventParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Kind      string      `json:"kind"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) RecordAnalyticsEvent(ctx context.Context, arg RecordAnalyticsEventParams) error {
	_, err := q.db.Exec(ctx, recordAnalyticsEvent,
		arg.TenantID,
		arg.ProjectID,
		arg.Kind,
		arg.Metadata,
	)
	return err
}

const tenantProjectsFirstEvents = `-- name: TenantProjectsFirstEvents :many
SELECT project_id, kind, MIN(occurred_at) AS first_at
FROM analytics_events
WHERE tenant_id = $1 AND project_id IS NOT NULL
GROUP BY project_id, kind
ORDER BY project_id, kind
`

type TenantProjectsFirstEventsRow struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Kind      string      `json:"kind"`
	FirstAt   interface{} `json:"first_at"`
}

// One row per (project, kind) carrying the first-occurrence timestamp
// across every project in the tenant. Used by the cohort dashboard
// to compute time-to-first-X distributions.
func (q *Queries) TenantProjectsFirstEvents(ctx context.Context, tenantID pgtype.UUID) ([]TenantProjectsFirstEventsRow, error) {
	rows, err := q.db.Query(ctx, tenantProjectsFirstEvents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantProjectsFirstEventsRow
	for rows.Next() {
		var i TenantProjectsFirstEventsRow
		if err := rows.Scan(&i.ProjectID, &i.Kind, &i.FirstAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
