// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEntry = `-- name: AppendAuditEntry :exec

INSERT INTO audit_log (tenant_id, translation_id, before_value, after_value, changed_by, actor_kind, actor_label)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type AppendAuditEntryParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	TranslationID pgtype.UUID `json:"translation_id"`
	BeforeValue   *string     `json:"before_value"`
	AfterValue    *string     `json:"after_value"`
	ChangedBy     pgtype.UUID `json:"changed_by"`
	ActorKind     string      `json:"actor_kind"`
	ActorLabel    string      `json:"actor_label"`
}

// Audit log — records every translation mutation. Append-only;
// reads are tenant-scoped via RLS just like the rest of the schema.
func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) error {
	_, err := q.db.Exec(ctx, appendAuditEntry,
		arg.TenantID,
		arg.TranslationID,
		arg.BeforeValue,
		arg.AfterValue,
		arg.ChangedBy,
		arg.ActorKind,
		arg.ActorLabel,
	)
	return err
}

const listAuditForTenant = `-- name: ListAuditForTenant :many
SELECT id, tenant_id, translation_id, before_value, after_value, changed_by, actor_kind, actor_label, changed_at
FROM audit_log
WHERE tenant_id = $1
ORDER BY changed_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditForTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListAuditForTenantRow struct {
	ID            int64              `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	TranslationID pgtype.UUID        `json:"translation_id"`
	BeforeValue   *string            `json:"before_value"`
	AfterValue    *string            `json:"after_value"`
	ChangedBy     pgtype.UUID        `json:"changed_by"`
	ActorKind     string             `json:"actor_kind"`
	ActorLabel    string             `json:"actor_label"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
}

func (q *Queries) ListAuditForTenant(ctx context.Context, arg ListAuditForTenantParams) ([]ListAuditForTenantRow, error) {
	rows, err := q.db.Query(ctx, listAuditForTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditForTenantRow
	for rows.Next() {
		var i ListAuditForTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TranslationID,
			&i.BeforeValue,
			&i.AfterValue,
			&i.ChangedBy,
			&i.ActorKind,
			&i.ActorLabel,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
