// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID            int64              `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	TranslationID pgtype.UUID        `json:"translation_id"`
	BeforeValue   *string            `json:"before_value"`
	AfterValue    *string            `json:"after_value"`
	ChangedBy     pgtype.UUID        `json:"changed_by"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
}

type Key struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Key         string             `json:"key"`
	Description *string            `json:"description"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
}

type Locale struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Code      string             `json:"code"`
	Label     string             `json:"label"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	DefaultLocale string             `json:"default_locale"`
	ApiKeyHash    []byte             `json:"api_key_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Translation struct {
	ID        pgtype.UUID        `json:"id"`
	KeyID     pgtype.UUID        `json:"key_id"`
	LocaleID  pgtype.UUID        `json:"locale_id"`
	Value     string             `json:"value"`
	Status    string             `json:"status"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Role         string             `json:"role"`
	Locales      []string           `json:"locales"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
