// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectAPIKey = `-- name: CreateProjectAPIKey :one
INSERT INTO project_api_keys (project_id, hash, scope, label)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, scope, label, created_at, last_used_at, revoked_at
`

type CreateProjectAPIKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Hash      []byte      `json:"hash"`
	Scope     string      `json:"scope"`
	Label     string      `json:"label"`
}

type CreateProjectAPIKeyRow struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Scope      string             `json:"scope"`
	Label      string             `json:"label"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) CreateProjectAPIKey(ctx context.Context, arg CreateProjectAPIKeyParams) (CreateProjectAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createProjectAPIKey,
		arg.ProjectID,
		arg.Hash,
		arg.Scope,
		arg.Label,
	)
	var i CreateProjectAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Scope,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getProjectAPIKeyByHash = `-- name: GetProjectAPIKeyByHash :one
SELECT k.id, k.project_id, k.scope, k.label, k.created_at, k.last_used_at,
       p.tenant_id, p.slug AS project_slug, p.name AS project_name,
       p.default_locale
FROM project_api_keys k
JOIN projects p ON p.id = k.project_id
WHERE k.hash = $1 AND k.revoked_at IS NULL
`

type GetProjectAPIKeyByHashRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Scope         string             `json:"scope"`
	Label         string             `json:"label"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ProjectSlug   string             `json:"project_slug"`
	ProjectName   string             `json:"project_name"`
	DefaultLocale string             `json:"default_locale"`
}

// Hot path. Hits every API-key authed request. The partial unique
// index on hash (WHERE revoked_at IS NULL) makes this O(1).
func (q *Queries) GetProjectAPIKeyByHash(ctx context.Context, hash []byte) (GetProjectAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getProjectAPIKeyByHash, hash)
	var i GetProjectAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Scope,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.TenantID,
		&i.ProjectSlug,
		&i.ProjectName,
		&i.DefaultLocale,
	)
	return i, err
}

const listProjectAPIKeys = `-- name: ListProjectAPIKeys :many
SELECT id, project_id, scope, label, created_at, last_used_at, revoked_at
FROM project_api_keys
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListProjectAPIKeysRow struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Scope      string             `json:"scope"`
	Label      string             `json:"label"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListProjectAPIKeys(ctx context.Context, projectID pgtype.UUID) ([]ListProjectAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listProjectAPIKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectAPIKeysRow
	for rows.Next() {
		var i ListProjectAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Scope,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeProjectAPIKey = `-- name: RevokeProjectAPIKey :exec
UPDATE project_api_keys
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeProjectAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeProjectAPIKey, id)
	return err
}

const touchProjectAPIKey = `-- name: TouchProjectAPIKey :exec
UPDATE project_api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchProjectAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchProjectAPIKey, id)
	return err
}
