// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTranslation = `-- name: GetTranslation :one
SELECT id, key_id, locale_id, value, status, updated_by, updated_at
FROM translations
WHERE key_id = $1 AND locale_id = $2
`

type GetTranslationParams struct {
	KeyID    pgtype.UUID `json:"key_id"`
	LocaleID pgtype.UUID `json:"locale_id"`
}

// Pre-edit lookup for the audit log: read the current value at
// (key, locale) so AuditEntry.BeforeValue isn't always empty.
func (q *Queries) GetTranslation(ctx context.Context, arg GetTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, getTranslation, arg.KeyID, arg.LocaleID)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.LocaleID,
		&i.Value,
		&i.Status,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listBundle = `-- name: ListBundle :many
SELECT k.key, t.value, t.status
FROM keys k
LEFT JOIN translations t
  ON t.key_id = k.id AND t.locale_id = $2
WHERE k.project_id = $1
ORDER BY k.key ASC
`

type ListBundleParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	LocaleID  pgtype.UUID `json:"locale_id"`
}

type ListBundleRow struct {
	Key    string  `json:"key"`
	Value  *string `json:"value"`
	Status *string `json:"status"`
}

// Full message bundle for a (project, locale) — used by both the
// runtime SDK and the CLI's pull command. Filters by approved when
// the caller is a consumer; admin reads include all statuses.
func (q *Queries) ListBundle(ctx context.Context, arg ListBundleParams) ([]ListBundleRow, error) {
	rows, err := q.db.Query(ctx, listBundle, arg.ProjectID, arg.LocaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBundleRow
	for rows.Next() {
		var i ListBundleRow
		if err := rows.Scan(&i.Key, &i.Value, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTranslation = `-- name: UpsertTranslation :one
INSERT INTO translations (key_id, locale_id, value, status, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key_id, locale_id) DO UPDATE
  SET value = EXCLUDED.value,
      status = EXCLUDED.status,
      updated_by = EXCLUDED.updated_by,
      updated_at = NOW()
RETURNING id, key_id, locale_id, value, status, updated_by, updated_at
`

type UpsertTranslationParams struct {
	KeyID     pgtype.UUID `json:"key_id"`
	LocaleID  pgtype.UUID `json:"locale_id"`
	Value     string      `json:"value"`
	Status    string      `json:"status"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertTranslation(ctx context.Context, arg UpsertTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, upsertTranslation,
		arg.KeyID,
		arg.LocaleID,
		arg.Value,
		arg.Status,
		arg.UpdatedBy,
	)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.LocaleID,
		&i.Value,
		&i.Status,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
