/// Access to the shared fixtures in `runtimes/testdata` and
/// `messageformat/testdata`.
///
/// The fixtures are read from the repository, never copied into this
/// package: they are generated by `runtimes/testdata/gen/generate.py` and CI
/// already fails on drift (SPEC §7). A missing directory is a hard failure,
/// not an empty test run.
library;

import 'dart:convert';
import 'dart:io';

/// `runtimes/`. `dart test` runs with the package root as the working
/// directory, so the repository is always one level up from `runtimes/dart`.
final Directory runtimesDir = Directory.current.parent;

/// The repository root.
final Directory repoRoot = runtimesDir.parent;

/// The directory holding a shared fixture suite, e.g. `scenarios`.
Directory fixtureDir(String kind) {
  final dir = Directory('${runtimesDir.path}/testdata/$kind');
  if (!dir.existsSync()) {
    throw StateError(
      'shared fixtures missing: ${dir.path}.\n'
      'The Dart runtime is a driver over runtimes/testdata; run the tests '
      'from runtimes/dart inside a checkout of the repository.',
    );
  }
  return dir;
}

/// Every `*.json` fixture of [kind], keyed by file name, in name order.
Map<String, Map<String, Object?>> loadFixtures(String kind) {
  final dir = fixtureDir(kind);
  final files =
      dir
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.json'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  if (files.isEmpty) {
    throw StateError('no $kind fixtures in ${dir.path}');
  }
  return {
    for (final f in files)
      f.uri.pathSegments.last:
          jsonDecode(f.readAsStringSync()) as Map<String, Object?>,
  };
}

/// One JSON fixture file below `runtimes/testdata`, e.g. `markup.json`.
Map<String, Object?> loadRuntimeFixture(String relativePath) {
  final file = File('${runtimesDir.path}/testdata/$relativePath');
  if (!file.existsSync()) {
    throw StateError(
      'shared fixture missing: ${file.path}.\n'
      'The Dart runtime is a driver over runtimes/testdata; run the tests '
      'from runtimes/dart inside a checkout of the repository.',
    );
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
}

/// One JSON fixture file below `messageformat/testdata`.
Map<String, Object?> loadMessageFormatFixture(String relativePath) {
  final file = File('${repoRoot.path}/messageformat/testdata/$relativePath');
  if (!file.existsSync()) {
    throw StateError(
      'shared fixture missing: ${file.path}.\n'
      'Run the tests from runtimes/dart inside a checkout of the repository.',
    );
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
}
