// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package contextsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteApplicationBuilds = `-- name: DeleteApplicationBuilds :exec
DELETE FROM context_builds WHERE project_id = $1 AND application_id = $2
`

type DeleteApplicationBuildsParams struct {
	ProjectID     uuid.UUID
	ApplicationID uuid.UUID
}

func (q *Queries) DeleteApplicationBuilds(ctx context.Context, arg DeleteApplicationBuildsParams) error {
	_, err := q.db.Exec(ctx, deleteApplicationBuilds, arg.ProjectID, arg.ApplicationID)
	return err
}

const deleteBuilds = `-- name: DeleteBuilds :execrows
DELETE FROM context_builds WHERE id = ANY($1::uuid[])
`

// Usages, captures and regions go with their builds (ON DELETE CASCADE).
func (q *Queries) DeleteBuilds(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBuilds, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectBuilds = `-- name: DeleteProjectBuilds :exec
DELETE FROM context_builds WHERE project_id = $1
`

func (q *Queries) DeleteProjectBuilds(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectBuilds, projectID)
	return err
}

const getBuild = `-- name: GetBuild :one
SELECT id, tenant_id, project_id, application_id, commit_sha, branch, on_default_branch, source, tool_name, tool_version, digest, usage_count, created_by, created_at FROM context_builds WHERE id = $1
`

func (q *Queries) GetBuild(ctx context.Context, id uuid.UUID) (ContextBuild, error) {
	row := q.db.QueryRow(ctx, getBuild, id)
	var i ContextBuild
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ApplicationID,
		&i.CommitSha,
		&i.Branch,
		&i.OnDefaultBranch,
		&i.Source,
		&i.ToolName,
		&i.ToolVersion,
		&i.Digest,
		&i.UsageCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getBuildByUpload = `-- name: GetBuildByUpload :one
SELECT id, tenant_id, project_id, application_id, commit_sha, branch, on_default_branch, source, tool_name, tool_version, digest, usage_count, created_by, created_at FROM context_builds
WHERE tenant_id = app_current_tenant() AND application_id = $1
  AND commit_sha = $2 AND source = $3 AND digest = $4
`

type GetBuildByUploadParams struct {
	ApplicationID uuid.UUID
	CommitSha     string
	Source        string
	Digest        string
}

func (q *Queries) GetBuildByUpload(ctx context.Context, arg GetBuildByUploadParams) (ContextBuild, error) {
	row := q.db.QueryRow(ctx, getBuildByUpload,
		arg.ApplicationID,
		arg.CommitSha,
		arg.Source,
		arg.Digest,
	)
	var i ContextBuild
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ApplicationID,
		&i.CommitSha,
		&i.Branch,
		&i.OnDefaultBranch,
		&i.Source,
		&i.ToolName,
		&i.ToolVersion,
		&i.Digest,
		&i.UsageCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertBuild = `-- name: InsertBuild :execrows

INSERT INTO context_builds (id, tenant_id, project_id, application_id, commit_sha, branch, on_default_branch, source,
                            tool_name, tool_version, digest, usage_count, created_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8, $9,
        $10, $11, $12, $13)
ON CONFLICT (tenant_id, application_id, commit_sha, source, digest) DO NOTHING
`

type InsertBuildParams struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	ApplicationID   uuid.UUID
	CommitSha       string
	Branch          string
	OnDefaultBranch bool
	Source          string
	ToolName        string
	ToolVersion     string
	Digest          string
	UsageCount      int32
	CreatedBy       string
	CreatedAt       time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
// An upload is idempotent by (application, commit, source, digest): a
// repeat inserts nothing and the caller reads the first.
func (q *Queries) InsertBuild(ctx context.Context, arg InsertBuildParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBuild,
		arg.ID,
		arg.ProjectID,
		arg.ApplicationID,
		arg.CommitSha,
		arg.Branch,
		arg.OnDefaultBranch,
		arg.Source,
		arg.ToolName,
		arg.ToolVersion,
		arg.Digest,
		arg.UsageCount,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBuildsByIDs = `-- name: ListBuildsByIDs :many
SELECT id, tenant_id, project_id, application_id, commit_sha, branch, on_default_branch, source, tool_name, tool_version, digest, usage_count, created_by, created_at FROM context_builds WHERE id = ANY($1::uuid[]) ORDER BY application_id, source
`

func (q *Queries) ListBuildsByIDs(ctx context.Context, ids []uuid.UUID) ([]ContextBuild, error) {
	rows, err := q.db.Query(ctx, listBuildsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextBuild
	for rows.Next() {
		var i ContextBuild
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.ApplicationID,
			&i.CommitSha,
			&i.Branch,
			&i.OnDefaultBranch,
			&i.Source,
			&i.ToolName,
			&i.ToolVersion,
			&i.Digest,
			&i.UsageCount,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectBuildSummaries = `-- name: ListProjectBuildSummaries :many
SELECT id, application_id, source, branch, on_default_branch, created_at
FROM context_builds
WHERE project_id = $1
ORDER BY application_id, source, created_at DESC, id DESC
`

type ListProjectBuildSummariesRow struct {
	ID              uuid.UUID
	ApplicationID   uuid.UUID
	Source          string
	Branch          string
	OnDefaultBranch bool
	CreatedAt       time.Time
}

// Every build of a project, which retention bounds: what the current
// views and retention are computed from.
func (q *Queries) ListProjectBuildSummaries(ctx context.Context, projectID uuid.UUID) ([]ListProjectBuildSummariesRow, error) {
	rows, err := q.db.Query(ctx, listProjectBuildSummaries, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectBuildSummariesRow
	for rows.Next() {
		var i ListProjectBuildSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Source,
			&i.Branch,
			&i.OnDefaultBranch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBuildCaptures = `-- name: LockBuildCaptures :exec
SELECT pg_advisory_xact_lock(hashtextextended('context.build:' || $1::text, 0))
`

// Serializes the captures added to one build, so the per-build limit
// holds under concurrent uploads (builds are immutable: no row lock).
func (q *Queries) LockBuildCaptures(ctx context.Context, buildID string) error {
	_, err := q.db.Exec(ctx, lockBuildCaptures, buildID)
	return err
}
