// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: captures.sql

package contextsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countBuildCaptures = `-- name: CountBuildCaptures :one
SELECT count(*) FROM context_captures WHERE build_id = $1
`

func (q *Queries) CountBuildCaptures(ctx context.Context, buildID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBuildCaptures, buildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCaptureByShot = `-- name: GetCaptureByShot :one
SELECT id, tenant_id, build_id, project_id, route, viewport_width, viewport_height, locale, image_digest, image_width, image_height, created_by, created_at FROM context_captures
WHERE build_id = $1 AND route = $2 AND viewport_width = $3
  AND viewport_height = $4 AND locale = $5
`

type GetCaptureByShotParams struct {
	BuildID        uuid.UUID
	Route          string
	ViewportWidth  int32
	ViewportHeight int32
	Locale         string
}

func (q *Queries) GetCaptureByShot(ctx context.Context, arg GetCaptureByShotParams) (ContextCapture, error) {
	row := q.db.QueryRow(ctx, getCaptureByShot,
		arg.BuildID,
		arg.Route,
		arg.ViewportWidth,
		arg.ViewportHeight,
		arg.Locale,
	)
	var i ContextCapture
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuildID,
		&i.ProjectID,
		&i.Route,
		&i.ViewportWidth,
		&i.ViewportHeight,
		&i.Locale,
		&i.ImageDigest,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertCapture = `-- name: InsertCapture :execrows

INSERT INTO context_captures (id, tenant_id, build_id, project_id, route, viewport_width, viewport_height, locale,
                              image_digest, image_width, image_height, created_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12)
ON CONFLICT (build_id, route, viewport_width, viewport_height, locale) DO NOTHING
`

type InsertCaptureParams struct {
	ID             uuid.UUID
	BuildID        uuid.UUID
	ProjectID      uuid.UUID
	Route          string
	ViewportWidth  int32
	ViewportHeight int32
	Locale         string
	ImageDigest    string
	ImageWidth     int32
	ImageHeight    int32
	CreatedBy      string
	CreatedAt      time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
// One capture per (route, viewport, locale) of a build: a repeat
// inserts nothing and the caller compares it with the first.
func (q *Queries) InsertCapture(ctx context.Context, arg InsertCaptureParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCapture,
		arg.ID,
		arg.BuildID,
		arg.ProjectID,
		arg.Route,
		arg.ViewportWidth,
		arg.ViewportHeight,
		arg.Locale,
		arg.ImageDigest,
		arg.ImageWidth,
		arg.ImageHeight,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRegions = `-- name: InsertRegions :exec
INSERT INTO context_regions (capture_id, position, tenant_id, message_key, message_id, kind, x, y, width, height, visible)
SELECT $1, r.position, app_current_tenant(), r.message_key,
       NULLIF(r.message_id, '00000000-0000-0000-0000-000000000000'::uuid), r.kind, r.x, r.y, r.width, r.height,
       r.visible
FROM (SELECT unnest($2::int[]) AS position, unnest($3::text[]) AS message_key,
             unnest($4::uuid[]) AS message_id, unnest($5::text[]) AS kind,
             unnest($6::int[]) AS x, unnest($7::int[]) AS y,
             unnest($8::int[]) AS width, unnest($9::int[]) AS height,
             unnest($10::boolean[]) AS visible) AS r
`

type InsertRegionsParams struct {
	CaptureID  uuid.UUID
	Positions  []int32
	Keys       []string
	MessageIds []uuid.UUID
	Kinds      []string
	Xs         []int32
	Ys         []int32
	Widths     []int32
	Heights    []int32
	Visibles   []bool
}

func (q *Queries) InsertRegions(ctx context.Context, arg InsertRegionsParams) error {
	_, err := q.db.Exec(ctx, insertRegions,
		arg.CaptureID,
		arg.Positions,
		arg.Keys,
		arg.MessageIds,
		arg.Kinds,
		arg.Xs,
		arg.Ys,
		arg.Widths,
		arg.Heights,
		arg.Visibles,
	)
	return err
}

const listBuildImages = `-- name: ListBuildImages :many
SELECT DISTINCT image_digest FROM context_captures WHERE build_id = ANY($1::uuid[])
`

// The images the given builds' captures reference.
func (q *Queries) ListBuildImages(ctx context.Context, buildIds []uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listBuildImages, buildIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_digest string
		if err := rows.Scan(&image_digest); err != nil {
			return nil, err
		}
		items = append(items, image_digest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencedImages = `-- name: ListReferencedImages :many
SELECT DISTINCT image_digest FROM context_captures
WHERE project_id = $1 AND image_digest = ANY($2::text[])
`

type ListReferencedImagesParams struct {
	ProjectID uuid.UUID
	Digests   []string
}

// Which of digests a capture of the project still references.
func (q *Queries) ListReferencedImages(ctx context.Context, arg ListReferencedImagesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listReferencedImages, arg.ProjectID, arg.Digests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_digest string
		if err := rows.Scan(&image_digest); err != nil {
			return nil, err
		}
		items = append(items, image_digest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many
SELECT capture_id, position, tenant_id, message_key, message_id, kind, x, y, width, height, visible FROM context_regions WHERE capture_id = $1 ORDER BY position
`

func (q *Queries) ListRegions(ctx context.Context, captureID uuid.UUID) ([]ContextRegion, error) {
	rows, err := q.db.Query(ctx, listRegions, captureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextRegion
	for rows.Next() {
		var i ContextRegion
		if err := rows.Scan(
			&i.CaptureID,
			&i.Position,
			&i.TenantID,
			&i.MessageKey,
			&i.MessageID,
			&i.Kind,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
