// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: captures.sql

package contextsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countBuildCaptures = `-- name: CountBuildCaptures :one
SELECT count(*) FROM context_captures WHERE build_id = $1
`

func (q *Queries) CountBuildCaptures(ctx context.Context, buildID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBuildCaptures, buildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCapturesOfBuilds = `-- name: CountCapturesOfBuilds :one
SELECT count(*)::int FROM context_captures WHERE build_id = ANY($1::uuid[])
`

// How many captures the given builds hold: what a purge deletes with
// them (RFC 0004 §11 counts deletions by kind).
func (q *Queries) CountCapturesOfBuilds(ctx context.Context, buildIds []uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCapturesOfBuilds, buildIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getCapture = `-- name: GetCapture :one
SELECT id, tenant_id, build_id, project_id, route, viewport_width, viewport_height, locale, image_digest, image_width, image_height, created_by, created_at FROM context_captures WHERE id = $1
`

func (q *Queries) GetCapture(ctx context.Context, id uuid.UUID) (ContextCapture, error) {
	row := q.db.QueryRow(ctx, getCapture, id)
	var i ContextCapture
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuildID,
		&i.ProjectID,
		&i.Route,
		&i.ViewportWidth,
		&i.ViewportHeight,
		&i.Locale,
		&i.ImageDigest,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCaptureByShot = `-- name: GetCaptureByShot :one
SELECT id, tenant_id, build_id, project_id, route, viewport_width, viewport_height, locale, image_digest, image_width, image_height, created_by, created_at FROM context_captures
WHERE build_id = $1 AND route = $2 AND viewport_width = $3
  AND viewport_height = $4 AND locale = $5
`

type GetCaptureByShotParams struct {
	BuildID        uuid.UUID
	Route          string
	ViewportWidth  int32
	ViewportHeight int32
	Locale         string
}

func (q *Queries) GetCaptureByShot(ctx context.Context, arg GetCaptureByShotParams) (ContextCapture, error) {
	row := q.db.QueryRow(ctx, getCaptureByShot,
		arg.BuildID,
		arg.Route,
		arg.ViewportWidth,
		arg.ViewportHeight,
		arg.Locale,
	)
	var i ContextCapture
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuildID,
		&i.ProjectID,
		&i.Route,
		&i.ViewportWidth,
		&i.ViewportHeight,
		&i.Locale,
		&i.ImageDigest,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertCapture = `-- name: InsertCapture :execrows

INSERT INTO context_captures (id, tenant_id, build_id, project_id, route, viewport_width, viewport_height, locale,
                              image_digest, image_width, image_height, created_by, created_at)
VALUES ($1, app_current_tenant(), $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10, $11, $12)
ON CONFLICT (build_id, route, viewport_width, viewport_height, locale) DO NOTHING
`

type InsertCaptureParams struct {
	ID             uuid.UUID
	BuildID        uuid.UUID
	ProjectID      uuid.UUID
	Route          string
	ViewportWidth  int32
	ViewportHeight int32
	Locale         string
	ImageDigest    string
	ImageWidth     int32
	ImageHeight    int32
	CreatedBy      string
	CreatedAt      time.Time
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
// One capture per (route, viewport, locale) of a build: a repeat
// inserts nothing and the caller compares it with the first.
func (q *Queries) InsertCapture(ctx context.Context, arg InsertCaptureParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCapture,
		arg.ID,
		arg.BuildID,
		arg.ProjectID,
		arg.Route,
		arg.ViewportWidth,
		arg.ViewportHeight,
		arg.Locale,
		arg.ImageDigest,
		arg.ImageWidth,
		arg.ImageHeight,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRegions = `-- name: InsertRegions :exec
INSERT INTO context_regions (capture_id, position, tenant_id, message_key, message_id, kind, x, y, width, height, visible)
SELECT $1, r.position, app_current_tenant(), r.message_key,
       NULLIF(r.message_id, '00000000-0000-0000-0000-000000000000'::uuid), r.kind, r.x, r.y, r.width, r.height,
       r.visible
FROM (SELECT unnest($2::int[]) AS position, unnest($3::text[]) AS message_key,
             unnest($4::uuid[]) AS message_id, unnest($5::text[]) AS kind,
             unnest($6::int[]) AS x, unnest($7::int[]) AS y,
             unnest($8::int[]) AS width, unnest($9::int[]) AS height,
             unnest($10::boolean[]) AS visible) AS r
`

type InsertRegionsParams struct {
	CaptureID  uuid.UUID
	Positions  []int32
	Keys       []string
	MessageIds []uuid.UUID
	Kinds      []string
	Xs         []int32
	Ys         []int32
	Widths     []int32
	Heights    []int32
	Visibles   []bool
}

func (q *Queries) InsertRegions(ctx context.Context, arg InsertRegionsParams) error {
	_, err := q.db.Exec(ctx, insertRegions,
		arg.CaptureID,
		arg.Positions,
		arg.Keys,
		arg.MessageIds,
		arg.Kinds,
		arg.Xs,
		arg.Ys,
		arg.Widths,
		arg.Heights,
		arg.Visibles,
	)
	return err
}

const listBuildImages = `-- name: ListBuildImages :many
SELECT DISTINCT image_digest FROM context_captures WHERE build_id = ANY($1::uuid[])
`

// The images the given builds' captures reference.
func (q *Queries) ListBuildImages(ctx context.Context, buildIds []uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listBuildImages, buildIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_digest string
		if err := rows.Scan(&image_digest); err != nil {
			return nil, err
		}
		items = append(items, image_digest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildUnknownRegionKeys = `-- name: ListBuildUnknownRegionKeys :many
SELECT DISTINCT r.message_key
FROM context_regions r
JOIN context_captures c ON c.id = r.capture_id
WHERE c.build_id = $1 AND r.message_id IS NULL
ORDER BY r.message_key
`

// The keys of a build's regions the catalog didn't know at ingest.
func (q *Queries) ListBuildUnknownRegionKeys(ctx context.Context, buildID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listBuildUnknownRegionKeys, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message_key string
		if err := rows.Scan(&message_key); err != nil {
			return nil, err
		}
		items = append(items, message_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapturedMessageIDs = `-- name: ListCapturedMessageIDs :many
SELECT DISTINCT r.message_id::uuid AS message_id
FROM context_regions r
JOIN context_captures c ON c.id = r.capture_id
WHERE c.build_id = ANY($1::uuid[]) AND r.message_id IS NOT NULL AND r.visible
`

// The messages with a visible region on the given (current) builds'
// captures.
func (q *Queries) ListCapturedMessageIDs(ctx context.Context, buildIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCapturedMessageIDs, buildIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var message_id uuid.UUID
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageCaptures = `-- name: ListMessageCaptures :many
SELECT c.id, c.build_id, c.project_id, c.route, c.viewport_width, c.viewport_height, c.locale, c.image_digest,
       c.image_width, c.image_height, c.created_by, c.created_at,
       b.application_id, b.commit_sha, b.branch, b.on_default_branch
FROM context_captures c
JOIN context_builds b ON b.id = c.build_id
WHERE c.build_id = ANY($1::uuid[])
  AND EXISTS (SELECT 1 FROM context_regions r WHERE r.capture_id = c.id AND r.message_id = $2::uuid)
ORDER BY b.on_default_branch DESC, b.application_id, c.route, c.locale, c.viewport_width DESC, c.viewport_height DESC, c.id
LIMIT $3
`

type ListMessageCapturesParams struct {
	BuildIds  []uuid.UUID
	MessageID uuid.UUID
	MaxRows   int32
}

type ListMessageCapturesRow struct {
	ID              uuid.UUID
	BuildID         uuid.UUID
	ProjectID       uuid.UUID
	Route           string
	ViewportWidth   int32
	ViewportHeight  int32
	Locale          string
	ImageDigest     string
	ImageWidth      int32
	ImageHeight     int32
	CreatedBy       string
	CreatedAt       time.Time
	ApplicationID   uuid.UUID
	CommitSha       string
	Branch          string
	OnDefaultBranch bool
}

// The captures in the given (current) builds that show a message: the
// default branch first, then by application, route, locale and the
// widest viewport.
func (q *Queries) ListMessageCaptures(ctx context.Context, arg ListMessageCapturesParams) ([]ListMessageCapturesRow, error) {
	rows, err := q.db.Query(ctx, listMessageCaptures, arg.BuildIds, arg.MessageID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageCapturesRow
	for rows.Next() {
		var i ListMessageCapturesRow
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.ProjectID,
			&i.Route,
			&i.ViewportWidth,
			&i.ViewportHeight,
			&i.Locale,
			&i.ImageDigest,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ApplicationID,
			&i.CommitSha,
			&i.Branch,
			&i.OnDefaultBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageRegions = `-- name: ListMessageRegions :many
SELECT capture_id, position, tenant_id, message_key, message_id, kind, x, y, width, height, visible FROM context_regions
WHERE capture_id = ANY($1::uuid[]) AND message_id = $2::uuid
ORDER BY capture_id, position
`

type ListMessageRegionsParams struct {
	CaptureIds []uuid.UUID
	MessageID  uuid.UUID
}

// A message's regions on the given captures, by capture and position.
func (q *Queries) ListMessageRegions(ctx context.Context, arg ListMessageRegionsParams) ([]ContextRegion, error) {
	rows, err := q.db.Query(ctx, listMessageRegions, arg.CaptureIds, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextRegion
	for rows.Next() {
		var i ContextRegion
		if err := rows.Scan(
			&i.CaptureID,
			&i.Position,
			&i.TenantID,
			&i.MessageKey,
			&i.MessageID,
			&i.Kind,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectImages = `-- name: ListProjectImages :many
SELECT DISTINCT image_digest FROM context_captures WHERE project_id = $1
`

// Every image a capture of the project references.
func (q *Queries) ListProjectImages(ctx context.Context, projectID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listProjectImages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_digest string
		if err := rows.Scan(&image_digest); err != nil {
			return nil, err
		}
		items = append(items, image_digest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencedImages = `-- name: ListReferencedImages :many
SELECT DISTINCT image_digest FROM context_captures
WHERE project_id = $1 AND image_digest = ANY($2::text[])
`

type ListReferencedImagesParams struct {
	ProjectID uuid.UUID
	Digests   []string
}

// Which of digests a capture of the project still references.
func (q *Queries) ListReferencedImages(ctx context.Context, arg ListReferencedImagesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listReferencedImages, arg.ProjectID, arg.Digests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_digest string
		if err := rows.Scan(&image_digest); err != nil {
			return nil, err
		}
		items = append(items, image_digest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many
SELECT capture_id, position, tenant_id, message_key, message_id, kind, x, y, width, height, visible FROM context_regions WHERE capture_id = $1 ORDER BY position
`

func (q *Queries) ListRegions(ctx context.Context, captureID uuid.UUID) ([]ContextRegion, error) {
	rows, err := q.db.Query(ctx, listRegions, captureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextRegion
	for rows.Next() {
		var i ContextRegion
		if err := rows.Scan(
			&i.CaptureID,
			&i.Position,
			&i.TenantID,
			&i.MessageKey,
			&i.MessageID,
			&i.Kind,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
