// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package contextsql

import (
	"time"

	"github.com/google/uuid"
)

type ContextBuild struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	ProjectID       uuid.UUID
	ApplicationID   uuid.UUID
	CommitSha       string
	Branch          string
	OnDefaultBranch bool
	Source          string
	ToolName        string
	ToolVersion     string
	Digest          string
	UsageCount      int32
	CreatedBy       string
	CreatedAt       time.Time
}

type ContextCapture struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	BuildID        uuid.UUID
	ProjectID      uuid.UUID
	Route          string
	ViewportWidth  int32
	ViewportHeight int32
	Locale         string
	ImageDigest    string
	ImageWidth     int32
	ImageHeight    int32
	CreatedBy      string
	CreatedAt      time.Time
	ImageBytes     int64
}

type ContextRegion struct {
	CaptureID  uuid.UUID
	Position   int32
	TenantID   uuid.UUID
	MessageKey string
	MessageID  uuid.NullUUID
	Kind       string
	X          int32
	Y          int32
	Width      int32
	Height     int32
	Visible    bool
}
