// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package contextsql

import (
	"context"

	"github.com/google/uuid"
)

const listProjectsWithBuilds = `-- name: ListProjectsWithBuilds :many

SELECT DISTINCT tenant_id, project_id FROM context_builds ORDER BY tenant_id, project_id
`

type ListProjectsWithBuildsRow struct {
	TenantID  uuid.UUID
	ProjectID uuid.UUID
}

// System scope context.retention (db.SystemTx as glossa_system):
// migration 0012 opens context_builds' tenant_id and project_id to it,
// read-only, and nothing else.
func (q *Queries) ListProjectsWithBuilds(ctx context.Context) ([]ListProjectsWithBuildsRow, error) {
	rows, err := q.db.Query(ctx, listProjectsWithBuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsWithBuildsRow
	for rows.Next() {
		var i ListProjectsWithBuildsRow
		if err := rows.Scan(&i.TenantID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
