// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usages.sql

package contextsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnknownKeys = `-- name: CountUnknownKeys :one
SELECT count(*) FROM context_usages WHERE build_id = $1 AND message_id IS NULL
`

func (q *Queries) CountUnknownKeys(ctx context.Context, buildID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnknownKeys, buildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertUsages = `-- name: InsertUsages :exec

INSERT INTO context_usages (build_id, position, tenant_id, message_key, message_id, file, line, col, component, route, kind)
SELECT $1, u.position, app_current_tenant(), u.message_key,
       NULLIF(u.message_id, '00000000-0000-0000-0000-000000000000'::uuid), u.file, u.line, NULLIF(u.col, 0),
       u.component, u.route, u.kind
FROM (SELECT unnest($2::int[]) AS position, unnest($3::text[]) AS message_key,
             unnest($4::uuid[]) AS message_id, unnest($5::text[]) AS file,
             unnest($6::int[]) AS line, unnest($7::int[]) AS col,
             unnest($8::text[]) AS component, unnest($9::text[]) AS route,
             unnest($10::text[]) AS kind) AS u
`

type InsertUsagesParams struct {
	BuildID    uuid.UUID
	Positions  []int32
	Keys       []string
	MessageIds []uuid.UUID
	Files      []string
	Lines      []int32
	Cols       []int32
	Components []string
	Routes     []string
	Kinds      []string
}

// Tenant scope (db.TenantTx): RLS limits every statement to the current
// tenant.
// A batch of a build's usages, by position in the document. uuid.Nil
// is an unknown key's message ID, 0 an unknown column.
func (q *Queries) InsertUsages(ctx context.Context, arg InsertUsagesParams) error {
	_, err := q.db.Exec(ctx, insertUsages,
		arg.BuildID,
		arg.Positions,
		arg.Keys,
		arg.MessageIds,
		arg.Files,
		arg.Lines,
		arg.Cols,
		arg.Components,
		arg.Routes,
		arg.Kinds,
	)
	return err
}

const listCoLocatedMessages = `-- name: ListCoLocatedMessages :many
WITH own_routes AS (
    SELECT DISTINCT route FROM context_usages
    WHERE message_id = $2::uuid AND build_id = ANY($3::uuid[]) AND route <> ''
), own_captures AS (
    SELECT DISTINCT r.capture_id
    FROM context_regions r
    JOIN context_captures c ON c.id = r.capture_id
    WHERE r.message_id = $2::uuid AND c.build_id = ANY($3::uuid[])
), shared AS (
    SELECT u.message_id FROM context_usages u
    WHERE u.build_id = ANY($3::uuid[]) AND u.route <> '' AND u.route IN (SELECT route FROM own_routes)
      AND u.message_id IS NOT NULL AND u.message_id <> $2::uuid
    UNION ALL
    SELECT r.message_id FROM context_regions r
    WHERE r.capture_id IN (SELECT capture_id FROM own_captures)
      AND r.message_id IS NOT NULL AND r.message_id <> $2::uuid
)
SELECT message_id::uuid AS message_id, count(*)::int AS shared
FROM shared
GROUP BY message_id
ORDER BY count(*) DESC, message_id
LIMIT $1
`

type ListCoLocatedMessagesParams struct {
	MaxRows   int32
	MessageID uuid.UUID
	BuildIds  []uuid.UUID
}

type ListCoLocatedMessagesRow struct {
	MessageID uuid.UUID
	Shared    int32
}

// The messages shown together with a message in the given (current)
// builds (RFC 0004 §8): used on one of its routes, or rendered on one
// of its captures. Most shared first.
func (q *Queries) ListCoLocatedMessages(ctx context.Context, arg ListCoLocatedMessagesParams) ([]ListCoLocatedMessagesRow, error) {
	rows, err := q.db.Query(ctx, listCoLocatedMessages, arg.MaxRows, arg.MessageID, arg.BuildIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoLocatedMessagesRow
	for rows.Next() {
		var i ListCoLocatedMessagesRow
		if err := rows.Scan(&i.MessageID, &i.Shared); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageUsages = `-- name: ListMessageUsages :many
SELECT u.build_id, u.position, u.message_key, u.message_id, u.file, u.line, u.col, u.component, u.route, u.kind,
       b.application_id, b.commit_sha, b.branch, b.on_default_branch, b.source
FROM context_usages u
JOIN context_builds b ON b.id = u.build_id
WHERE u.message_id = $1 AND u.build_id = ANY($2::uuid[])
ORDER BY b.on_default_branch DESC, b.application_id, u.file, u.line, u.col NULLS FIRST, u.build_id, u.position
LIMIT $3
`

type ListMessageUsagesParams struct {
	MessageID uuid.NullUUID
	BuildIds  []uuid.UUID
	MaxRows   int32
}

type ListMessageUsagesRow struct {
	BuildID         uuid.UUID
	Position        int32
	MessageKey      string
	MessageID       uuid.NullUUID
	File            string
	Line            int32
	Col             pgtype.Int4
	Component       string
	Route           string
	Kind            string
	ApplicationID   uuid.UUID
	CommitSha       string
	Branch          string
	OnDefaultBranch bool
	Source          string
}

// A message's usages in the given (current) builds: the default branch
// first, then by application, file and position in the file.
func (q *Queries) ListMessageUsages(ctx context.Context, arg ListMessageUsagesParams) ([]ListMessageUsagesRow, error) {
	rows, err := q.db.Query(ctx, listMessageUsages, arg.MessageID, arg.BuildIds, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageUsagesRow
	for rows.Next() {
		var i ListMessageUsagesRow
		if err := rows.Scan(
			&i.BuildID,
			&i.Position,
			&i.MessageKey,
			&i.MessageID,
			&i.File,
			&i.Line,
			&i.Col,
			&i.Component,
			&i.Route,
			&i.Kind,
			&i.ApplicationID,
			&i.CommitSha,
			&i.Branch,
			&i.OnDefaultBranch,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsagesInBuilds = `-- name: ListUsagesInBuilds :many
SELECT u.build_id, u.position, u.message_key, u.message_id, u.file, u.line, u.col, u.component, u.route, u.kind,
       b.application_id, b.commit_sha, b.branch, b.on_default_branch, b.source
FROM context_usages u
JOIN context_builds b ON b.id = u.build_id
WHERE u.build_id = ANY($1::uuid[])
  AND ($2::text IS NULL OR u.route = $2::text)
  AND ($3::text IS NULL OR u.component = $3::text)
  AND ($4::text IS NULL OR u.file = $4::text)
  AND (u.build_id, u.position) > ($5::uuid, $6::int)
ORDER BY u.build_id, u.position
LIMIT $7
`

type ListUsagesInBuildsParams struct {
	BuildIds      []uuid.UUID
	Route         pgtype.Text
	Component     pgtype.Text
	File          pgtype.Text
	AfterBuild    uuid.UUID
	AfterPosition int32
	MaxRows       int32
}

type ListUsagesInBuildsRow struct {
	BuildID         uuid.UUID
	Position        int32
	MessageKey      string
	MessageID       uuid.NullUUID
	File            string
	Line            int32
	Col             pgtype.Int4
	Component       string
	Route           string
	Kind            string
	ApplicationID   uuid.UUID
	CommitSha       string
	Branch          string
	OnDefaultBranch bool
	Source          string
}

// A page of the usages in the given (current) builds on a route, in a
// component or in a file (each filter optional), by build and position.
func (q *Queries) ListUsagesInBuilds(ctx context.Context, arg ListUsagesInBuildsParams) ([]ListUsagesInBuildsRow, error) {
	rows, err := q.db.Query(ctx, listUsagesInBuilds,
		arg.BuildIds,
		arg.Route,
		arg.Component,
		arg.File,
		arg.AfterBuild,
		arg.AfterPosition,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsagesInBuildsRow
	for rows.Next() {
		var i ListUsagesInBuildsRow
		if err := rows.Scan(
			&i.BuildID,
			&i.Position,
			&i.MessageKey,
			&i.MessageID,
			&i.File,
			&i.Line,
			&i.Col,
			&i.Component,
			&i.Route,
			&i.Kind,
			&i.ApplicationID,
			&i.CommitSha,
			&i.Branch,
			&i.OnDefaultBranch,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedMessageIDs = `-- name: ListUsedMessageIDs :many
SELECT DISTINCT message_id::uuid AS message_id
FROM context_usages
WHERE build_id = ANY($1::uuid[]) AND message_id IS NOT NULL
`

// The messages with a usage in the given (current) builds.
func (q *Queries) ListUsedMessageIDs(ctx context.Context, buildIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUsedMessageIDs, buildIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var message_id uuid.UUID
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
