// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package auditsql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const auditEntriesAfter = `-- name: AuditEntriesAfter :many
SELECT tenant_id, sequence, event_id, source, action, actor, occurred_at,
       aggregate_type, aggregate_id, project_id, locale, summary,
       request_id, trace_id, prev_hash, hash
FROM audit_entries
WHERE tenant_id = $1 AND sequence > $2
ORDER BY sequence
LIMIT $3::int
`

type AuditEntriesAfterParams struct {
	TenantID      uuid.UUID
	AfterSequence int64
	PageSize      int32
}

type AuditEntriesAfterRow struct {
	TenantID      uuid.UUID
	Sequence      int64
	EventID       uuid.UUID
	Source        string
	Action        string
	Actor         string
	OccurredAt    time.Time
	AggregateType string
	AggregateID   string
	ProjectID     uuid.NullUUID
	Locale        pgtype.Text
	Summary       json.RawMessage
	RequestID     pgtype.Text
	TraceID       pgtype.Text
	PrevHash      []byte
	Hash          []byte
}

// AuditEntriesAfter reads the chain in order from after a sequence.
func (q *Queries) AuditEntriesAfter(ctx context.Context, arg AuditEntriesAfterParams) ([]AuditEntriesAfterRow, error) {
	rows, err := q.db.Query(ctx, auditEntriesAfter, arg.TenantID, arg.AfterSequence, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEntriesAfterRow
	for rows.Next() {
		var i AuditEntriesAfterRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Sequence,
			&i.EventID,
			&i.Source,
			&i.Action,
			&i.Actor,
			&i.OccurredAt,
			&i.AggregateType,
			&i.AggregateID,
			&i.ProjectID,
			&i.Locale,
			&i.Summary,
			&i.RequestID,
			&i.TraceID,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const auditHead = `-- name: AuditHead :one
SELECT sequence, hash
FROM audit_entries
WHERE tenant_id = $1
ORDER BY sequence DESC
LIMIT 1
`

type AuditHeadRow struct {
	Sequence int64
	Hash     []byte
}

func (q *Queries) AuditHead(ctx context.Context, tenantID uuid.UUID) (AuditHeadRow, error) {
	row := q.db.QueryRow(ctx, auditHead, tenantID)
	var i AuditHeadRow
	err := row.Scan(&i.Sequence, &i.Hash)
	return i, err
}

const auditOutboxCount = `-- name: AuditOutboxCount :one
SELECT count(*) FROM audit_entries WHERE tenant_id = $1 AND source = 'outbox'
`

// AuditOutboxCount counts the tenant's entries projected from the
// outbox: when it equals the outbox's own count, the backfill has
// nothing to do for the tenant.
func (q *Queries) AuditOutboxCount(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, auditOutboxCount, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const auditRecorded = `-- name: AuditRecorded :many
SELECT event_id
FROM audit_entries
WHERE tenant_id = $1 AND event_id = ANY($2::uuid[])
`

type AuditRecordedParams struct {
	TenantID uuid.UUID
	EventIds []uuid.UUID
}

// AuditRecorded returns which of the given event ids already have an
// entry: the idempotency check, made under the chain lock.
func (q *Queries) AuditRecorded(ctx context.Context, arg AuditRecordedParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, auditRecorded, arg.TenantID, arg.EventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var event_id uuid.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_entries (
    tenant_id, sequence, event_id, source, action, actor, occurred_at,
    aggregate_type, aggregate_id, project_id, locale, summary,
    request_id, trace_id, prev_hash, hash
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16
)
`

type InsertAuditEntryParams struct {
	TenantID      uuid.UUID
	Sequence      int64
	EventID       uuid.UUID
	Source        string
	Action        string
	Actor         string
	OccurredAt    time.Time
	AggregateType string
	AggregateID   string
	ProjectID     uuid.NullUUID
	Locale        pgtype.Text
	Summary       json.RawMessage
	RequestID     pgtype.Text
	TraceID       pgtype.Text
	PrevHash      []byte
	Hash          []byte
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.TenantID,
		arg.Sequence,
		arg.EventID,
		arg.Source,
		arg.Action,
		arg.Actor,
		arg.OccurredAt,
		arg.AggregateType,
		arg.AggregateID,
		arg.ProjectID,
		arg.Locale,
		arg.Summary,
		arg.RequestID,
		arg.TraceID,
		arg.PrevHash,
		arg.Hash,
	)
	return err
}

const lockAuditChain = `-- name: LockAuditChain :exec

SELECT pg_advisory_xact_lock(hashtextextended('glossa.audit_entries:' || $1::uuid::text, 0))
`

// The Audit context's queries over audit_entries (migration 0045). All
// run in the tenant's own scope; the table is INSERT and SELECT only.
// LockAuditChain serializes appends to one tenant's chain for the rest
// of the transaction. Two tenants never wait on each other (unless
// their keys collide, which only costs a wait).
func (q *Queries) LockAuditChain(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockAuditChain, tenantID)
	return err
}
