// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package auditsql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const auditExportJob = `-- name: AuditExportJob :one
SELECT id, tenant_id, state, occurred_from, occurred_to, first_sequence, last_sequence, entry_count, first_prev_hash, last_hash, key_id, entries_key, entries_sha256, entries_bytes, manifest_key, manifest_sha256, manifest_bytes, failure_code, failure_message, attempts, max_attempts, available_at, claim_token, created_by, created_at, started_at, finished_at, updated_at, expires_at, files_deleted_at FROM audit_export_jobs WHERE tenant_id = $1 AND id = $2
`

type AuditExportJobParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) AuditExportJob(ctx context.Context, arg AuditExportJobParams) (AuditExportJob, error) {
	row := q.db.QueryRow(ctx, auditExportJob, arg.TenantID, arg.ID)
	var i AuditExportJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.State,
		&i.OccurredFrom,
		&i.OccurredTo,
		&i.FirstSequence,
		&i.LastSequence,
		&i.EntryCount,
		&i.FirstPrevHash,
		&i.LastHash,
		&i.KeyID,
		&i.EntriesKey,
		&i.EntriesSha256,
		&i.EntriesBytes,
		&i.ManifestKey,
		&i.ManifestSha256,
		&i.ManifestBytes,
		&i.FailureCode,
		&i.FailureMessage,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimToken,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.FilesDeletedAt,
	)
	return i, err
}

const auditExportJobs = `-- name: AuditExportJobs :many
SELECT id, tenant_id, state, occurred_from, occurred_to, first_sequence, last_sequence, entry_count, first_prev_hash, last_hash, key_id, entries_key, entries_sha256, entries_bytes, manifest_key, manifest_sha256, manifest_bytes, failure_code, failure_message, attempts, max_attempts, available_at, claim_token, created_by, created_at, started_at, finished_at, updated_at, expires_at, files_deleted_at FROM audit_export_jobs
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type AuditExportJobsParams struct {
	TenantID        uuid.UUID
	BeforeCreatedAt pgtype.Timestamptz
	BeforeID        uuid.NullUUID
	PageSize        int32
}

func (q *Queries) AuditExportJobs(ctx context.Context, arg AuditExportJobsParams) ([]AuditExportJob, error) {
	rows, err := q.db.Query(ctx, auditExportJobs,
		arg.TenantID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditExportJob
	for rows.Next() {
		var i AuditExportJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.State,
			&i.OccurredFrom,
			&i.OccurredTo,
			&i.FirstSequence,
			&i.LastSequence,
			&i.EntryCount,
			&i.FirstPrevHash,
			&i.LastHash,
			&i.KeyID,
			&i.EntriesKey,
			&i.EntriesSha256,
			&i.EntriesBytes,
			&i.ManifestKey,
			&i.ManifestSha256,
			&i.ManifestBytes,
			&i.FailureCode,
			&i.FailureMessage,
			&i.Attempts,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.ClaimToken,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.FilesDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimAuditExportJob = `-- name: ClaimAuditExportJob :one
WITH due AS (
    SELECT j.id
    FROM audit_export_jobs j
    WHERE j.state IN ('queued', 'running') AND j.available_at <= now()
    ORDER BY j.available_at, j.id
    LIMIT 1
    FOR UPDATE OF j SKIP LOCKED
)
UPDATE audit_export_jobs e
SET state        = 'running',
    attempts     = e.attempts + 1,
    available_at = now() + make_interval(secs => $1::float8),
    claim_token  = gen_random_uuid(),
    updated_at   = now()
FROM due
WHERE e.id = due.id
RETURNING e.id, e.tenant_id, e.claim_token, e.attempts
`

type ClaimAuditExportJobRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ClaimToken uuid.NullUUID
	Attempts   int32
}

// ClaimAuditExportJob leases the next due job: queued and due, or
// running with an expired lease (its worker died).
func (q *Queries) ClaimAuditExportJob(ctx context.Context, leaseSeconds float64) (ClaimAuditExportJobRow, error) {
	row := q.db.QueryRow(ctx, claimAuditExportJob, leaseSeconds)
	var i ClaimAuditExportJobRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClaimToken,
		&i.Attempts,
	)
	return i, err
}

const expiredAuditExports = `-- name: ExpiredAuditExports :many
SELECT id, tenant_id, coalesce(entries_key, '')::text AS entries_key, coalesce(manifest_key, '')::text AS manifest_key
FROM audit_export_jobs
WHERE files_deleted_at IS NULL AND expires_at <= now() AND state NOT IN ('queued', 'running')
ORDER BY expires_at
LIMIT $1::int
FOR UPDATE SKIP LOCKED
`

type ExpiredAuditExportsRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	EntriesKey  string
	ManifestKey string
}

func (q *Queries) ExpiredAuditExports(ctx context.Context, maxRows int32) ([]ExpiredAuditExportsRow, error) {
	rows, err := q.db.Query(ctx, expiredAuditExports, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpiredAuditExportsRow
	for rows.Next() {
		var i ExpiredAuditExportsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntriesKey,
			&i.ManifestKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishAuditExportJob = `-- name: FinishAuditExportJob :exec
UPDATE audit_export_jobs
SET state = $1, first_sequence = $2, last_sequence = $3,
    entry_count = $4, first_prev_hash = $5, last_hash = $6,
    key_id = $7, entries_key = $8, entries_sha256 = $9,
    entries_bytes = $10, manifest_key = $11,
    manifest_sha256 = $12, manifest_bytes = $13,
    failure_code = $14, failure_message = $15,
    started_at = $16, finished_at = $17, updated_at = $18,
    claim_token = NULL
WHERE tenant_id = $19 AND id = $20
`

type FinishAuditExportJobParams struct {
	State          string
	FirstSequence  pgtype.Int8
	LastSequence   pgtype.Int8
	EntryCount     int64
	FirstPrevHash  pgtype.Text
	LastHash       pgtype.Text
	KeyID          pgtype.Text
	EntriesKey     pgtype.Text
	EntriesSha256  pgtype.Text
	EntriesBytes   pgtype.Int8
	ManifestKey    pgtype.Text
	ManifestSha256 pgtype.Text
	ManifestBytes  pgtype.Int8
	FailureCode    pgtype.Text
	FailureMessage pgtype.Text
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	UpdatedAt      time.Time
	TenantID       uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) FinishAuditExportJob(ctx context.Context, arg FinishAuditExportJobParams) error {
	_, err := q.db.Exec(ctx, finishAuditExportJob,
		arg.State,
		arg.FirstSequence,
		arg.LastSequence,
		arg.EntryCount,
		arg.FirstPrevHash,
		arg.LastHash,
		arg.KeyID,
		arg.EntriesKey,
		arg.EntriesSha256,
		arg.EntriesBytes,
		arg.ManifestKey,
		arg.ManifestSha256,
		arg.ManifestBytes,
		arg.FailureCode,
		arg.FailureMessage,
		arg.StartedAt,
		arg.FinishedAt,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const insertAuditExportJob = `-- name: InsertAuditExportJob :execrows

INSERT INTO audit_export_jobs (
    id, tenant_id, state, occurred_from, occurred_to, first_sequence, last_sequence,
    max_attempts, available_at, created_by, created_at, updated_at, expires_at
) VALUES (
    $1, $2, 'queued', $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12
)
ON CONFLICT (id) DO NOTHING
`

type InsertAuditExportJobParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	OccurredFrom  pgtype.Timestamptz
	OccurredTo    pgtype.Timestamptz
	FirstSequence pgtype.Int8
	LastSequence  pgtype.Int8
	MaxAttempts   int32
	AvailableAt   time.Time
	CreatedBy     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ExpiresAt     time.Time
}

// The Audit context's export jobs (migration 0053).
func (q *Queries) InsertAuditExportJob(ctx context.Context, arg InsertAuditExportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuditExportJob,
		arg.ID,
		arg.TenantID,
		arg.OccurredFrom,
		arg.OccurredTo,
		arg.FirstSequence,
		arg.LastSequence,
		arg.MaxAttempts,
		arg.AvailableAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockAuditExportClaims = `-- name: LockAuditExportClaims :exec

SELECT pg_advisory_xact_lock(hashtext('glossa.audit.export_claim'))
`

// ── system scope (audit.export_jobs) ───────────────────────────────
func (q *Queries) LockAuditExportClaims(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAuditExportClaims)
	return err
}

const lockClaimedAuditExportJob = `-- name: LockClaimedAuditExportJob :one
SELECT id, tenant_id, state, occurred_from, occurred_to, first_sequence, last_sequence, entry_count, first_prev_hash, last_hash, key_id, entries_key, entries_sha256, entries_bytes, manifest_key, manifest_sha256, manifest_bytes, failure_code, failure_message, attempts, max_attempts, available_at, claim_token, created_by, created_at, started_at, finished_at, updated_at, expires_at, files_deleted_at FROM audit_export_jobs
WHERE tenant_id = $1 AND id = $2 AND claim_token = $3
  AND state = 'running'
FOR UPDATE
`

type LockClaimedAuditExportJobParams struct {
	TenantID   uuid.UUID
	ID         uuid.UUID
	ClaimToken uuid.NullUUID
}

// LockClaimedAuditExportJob locks a running job its worker still holds.
func (q *Queries) LockClaimedAuditExportJob(ctx context.Context, arg LockClaimedAuditExportJobParams) (AuditExportJob, error) {
	row := q.db.QueryRow(ctx, lockClaimedAuditExportJob, arg.TenantID, arg.ID, arg.ClaimToken)
	var i AuditExportJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.State,
		&i.OccurredFrom,
		&i.OccurredTo,
		&i.FirstSequence,
		&i.LastSequence,
		&i.EntryCount,
		&i.FirstPrevHash,
		&i.LastHash,
		&i.KeyID,
		&i.EntriesKey,
		&i.EntriesSha256,
		&i.EntriesBytes,
		&i.ManifestKey,
		&i.ManifestSha256,
		&i.ManifestBytes,
		&i.FailureCode,
		&i.FailureMessage,
		&i.Attempts,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.ClaimToken,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.FilesDeletedAt,
	)
	return i, err
}

const markAuditExportsDeleted = `-- name: MarkAuditExportsDeleted :exec
UPDATE audit_export_jobs SET files_deleted_at = now(), updated_at = now()
WHERE id = ANY ($1::uuid[]) AND files_deleted_at IS NULL
`

func (q *Queries) MarkAuditExportsDeleted(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAuditExportsDeleted, ids)
	return err
}

const retryAuditExportJob = `-- name: RetryAuditExportJob :execrows
UPDATE audit_export_jobs
SET state = 'queued', available_at = now() + make_interval(secs => $1::float8),
    failure_message = $2, started_at = $3, claim_token = NULL,
    updated_at = now()
WHERE tenant_id = $4 AND id = $5 AND claim_token = $6
`

type RetryAuditExportJobParams struct {
	DelaySeconds   float64
	FailureMessage pgtype.Text
	StartedAt      pgtype.Timestamptz
	TenantID       uuid.UUID
	ID             uuid.UUID
	ClaimToken     uuid.NullUUID
}

// RetryAuditExportJob queues a job again after a failed attempt.
func (q *Queries) RetryAuditExportJob(ctx context.Context, arg RetryAuditExportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryAuditExportJob,
		arg.DelaySeconds,
		arg.FailureMessage,
		arg.StartedAt,
		arg.TenantID,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
