// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditsql

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditExportJob struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	State          string
	OccurredFrom   pgtype.Timestamptz
	OccurredTo     pgtype.Timestamptz
	FirstSequence  pgtype.Int8
	LastSequence   pgtype.Int8
	EntryCount     int64
	FirstPrevHash  pgtype.Text
	LastHash       pgtype.Text
	KeyID          pgtype.Text
	EntriesKey     pgtype.Text
	EntriesSha256  pgtype.Text
	EntriesBytes   pgtype.Int8
	ManifestKey    pgtype.Text
	ManifestSha256 pgtype.Text
	ManifestBytes  pgtype.Int8
	FailureCode    pgtype.Text
	FailureMessage pgtype.Text
	Attempts       int32
	MaxAttempts    int32
	AvailableAt    time.Time
	ClaimToken     uuid.NullUUID
	CreatedBy      string
	CreatedAt      time.Time
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	UpdatedAt      time.Time
	ExpiresAt      time.Time
	FilesDeletedAt pgtype.Timestamptz
}
